"use client";

import {AbsoluteFill,Img,Easing,interpolate,useCurrentFrame,useVideoConfig} from "remotion";
import type {AdProduct,ThingsIFoundProps} from "./ThingsIFoundAd";

export type TemplateProps=ThingsIFoundProps;

const font="Inter,Arial,sans-serif";
function money(p:AdProduct){if(p.price==null)return"";try{return new Intl.NumberFormat("en",{style:"currency",currency:p.currency||"EUR",maximumFractionDigits:0}).format(Number(p.price))}catch{return `${p.currency||"EUR"} ${Number(p.price).toFixed(0)}`}}
function safe(products:AdProduct[]){return (products||[]).filter(p=>p?.image).slice(0,8)}

export function SingleProductPremiumAd({products,hook,headline,cta="Discover on YNOT"}:TemplateProps){
 const frame=useCurrentFrame();const {fps,width,height}=useVideoConfig();const p=safe(products)[0];const intro=interpolate(frame,[0,16],[0,1],{extrapolateRight:"clamp",extrapolateLeft:"clamp",easing:Easing.bezier(.16,1,.3,1)});const scale=interpolate(frame,[0,10*fps],[1.02,1.13],{extrapolateRight:"clamp"});const outro=interpolate(frame,[9.5*fps,10.2*fps],[0,1],{extrapolateRight:"clamp",extrapolateLeft:"clamp"});
 return <AbsoluteFill style={{backgroundColor:"#070808",color:"white",fontFamily:font,overflow:"hidden"}}><AbsoluteFill style={{background:"radial-gradient(circle at 50% 18%,rgba(255,255,255,.10),transparent 42%)"}}/>{p&&<><div style={{position:"absolute",left:width*.07,right:width*.07,top:height*.08,bottom:height*.18,borderRadius:width*.045,overflow:"hidden",opacity:intro}}><Img src={p.image||""} style={{width:"100%",height:"100%",objectFit:"cover",scale}}/><div style={{position:"absolute",inset:0,background:"linear-gradient(180deg,transparent 52%,rgba(0,0,0,.84) 100%)"}}/></div><div style={{position:"absolute",left:width*.105,right:width*.105,bottom:height*.08,opacity:intro}}><div style={{fontSize:width*.03,color:"rgba(255,255,255,.58)",marginBottom:12}}>{hook}</div><div style={{fontSize:width*.065,fontWeight:860,letterSpacing:"-.045em",lineHeight:.95}}>{p.title}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:18,fontSize:width*.031}}><span style={{color:"rgba(255,255,255,.58)"}}>{p.brand||"YNOT edit"}</span><b>{money(p)}</b></div></div></>}<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",padding:width*.1,textAlign:"center",background:"rgba(7,8,8,.94)",opacity:outro}}><div><div style={{fontSize:width*.075,fontWeight:860,letterSpacing:"-.055em",lineHeight:.94}}>{headline}</div><div style={{marginTop:30,color:"#9BEA92",fontSize:width*.029,fontWeight:800}}>{cta}</div></div></div></AbsoluteFill>
}

export function UgcDiscoveryAd({products,hook,headline,cta="See what I saved"}:TemplateProps){
 const frame=useCurrentFrame();const {fps,width,height}=useVideoConfig();const list=safe(products);const index=Math.min(Math.max(0,list.length-1),Math.floor(frame/(2.2*fps)));const p=list[index]||list[0];const local=frame-index*2.2*fps;const opacity=interpolate(local,[0,7,2*fps,2.2*fps],[0,1,1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const y=interpolate(local,[0,12],["0px 54px","0px 0px"],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)});
 return <AbsoluteFill style={{backgroundColor:"#efefea",color:"#111",fontFamily:font,padding:width*.055}}><div style={{fontSize:width*.055,lineHeight:1,fontWeight:900,letterSpacing:"-.055em",maxWidth:"88%"}}>{hook}</div><div style={{fontSize:width*.021,marginTop:14,opacity:.58}}>YNOT discovery • {list.length||0} finds</div>{p&&<div style={{position:"absolute",left:width*.055,right:width*.055,top:height*.2,bottom:height*.13,opacity,translate:y}}><div style={{height:"78%",borderRadius:width*.04,overflow:"hidden",backgroundColor:"#ddd"}}><Img src={p.image||""} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginTop:18}}><div><div style={{fontSize:width*.038,fontWeight:850,lineHeight:1.02}}>{p.title}</div><div style={{fontSize:width*.021,opacity:.5,marginTop:7}}>{p.brand||`find ${index+1}`}</div></div><div style={{fontSize:width*.035,fontWeight:900}}>{money(p)}</div></div></div>}<div style={{position:"absolute",left:width*.055,right:width*.055,bottom:height*.035,display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:width*.022,fontWeight:800}}><span>{headline}</span><span style={{backgroundColor:"#111",color:"white",padding:"12px 18px",borderRadius:999}}>{cta}</span></div></AbsoluteFill>
}

export function CollectionEditAd({products,hook,headline,cta="Open the collection"}:TemplateProps){
 const frame=useCurrentFrame();const {fps,width,height}=useVideoConfig();const list=safe(products).slice(0,6);const reveal=(i:number)=>interpolate(frame,[8+i*5,18+i*5],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:Easing.bezier(.16,1,.3,1)});return <AbsoluteFill style={{backgroundColor:"#0c0f0f",color:"white",fontFamily:font,padding:width*.052}}><div style={{fontSize:width*.025,color:"#99e891",fontWeight:850,letterSpacing:".12em"}}>YNOT COLLECTION</div><div style={{fontSize:width*.062,lineHeight:.94,fontWeight:900,letterSpacing:"-.055em",marginTop:18,maxWidth:"90%"}}>{hook}</div><div style={{position:"absolute",left:width*.052,right:width*.052,top:height*.25,bottom:height*.17,display:"grid",gridTemplateColumns:"1fr 1fr",gridTemplateRows:"1fr 1fr 1fr",gap:width*.022}}>{list.map((p,i)=><div key={p.id} style={{position:"relative",borderRadius:width*.025,overflow:"hidden",backgroundColor:"#161a1a",opacity:reveal(i),translate:interpolate(frame,[8+i*5,18+i*5],[`0px ${40+i*2}px`,`0px 0px`],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}><Img src={p.image||""} style={{width:"100%",height:"100%",objectFit:"cover"}}/><div style={{position:"absolute",left:12,right:12,bottom:10,display:"flex",justifyContent:"space-between",gap:10,fontSize:width*.018,fontWeight:850,textShadow:"0 2px 12px rgba(0,0,0,.8)"}}><span>{p.title}</span><span>{money(p)}</span></div></div>)}</div><div style={{position:"absolute",left:width*.052,right:width*.052,bottom:height*.055,display:"flex",justifyContent:"space-between",alignItems:"end",gap:28}}><div style={{fontSize:width*.035,fontWeight:850,maxWidth:"60%"}}>{headline}</div><div style={{fontSize:width*.021,fontWeight:850,color:"#9BEA92"}}>{cta}</div></div></AbsoluteFill>}

export function DigitalAiCourseAd({products,hook,headline,cta="Explore on YNOT"}:TemplateProps){
 const frame=useCurrentFrame();const {fps,width,height}=useVideoConfig();const p=safe(products)[0];const pulse=interpolate(frame,[0,2*fps,4*fps],[.65,1,.65],{extrapolateRight:"extend"});const cardY=interpolate(frame,[0,22],["0px 70px","0px 0px"],{extrapolateRight:"clamp",extrapolateLeft:"clamp",easing:Easing.bezier(.16,1,.3,1)});return <AbsoluteFill style={{backgroundColor:"#080a0e",color:"white",fontFamily:font,padding:width*.06,overflow:"hidden"}}><div style={{position:"absolute",width:width*.8,height:width*.8,left:width*.1,top:height*.2,borderRadius:"50%",background:"radial-gradient(circle,rgba(77,116,255,.24),transparent 62%)",opacity:pulse}}/><div style={{fontSize:width*.023,letterSpacing:".12em",fontWeight:850,color:"#9BEA92"}}>YNOT DIGITAL</div><div style={{fontSize:width*.071,fontWeight:900,letterSpacing:"-.06em",lineHeight:.92,marginTop:22,maxWidth:"92%"}}>{hook}</div><div style={{position:"absolute",left:width*.06,right:width*.06,top:height*.39,translate:cardY}}><div style={{border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.055)",borderRadius:width*.04,padding:width*.035,boxShadow:"0 28px 80px rgba(0,0,0,.35)"}}><div style={{display:"flex",gap:width*.03,alignItems:"center"}}>{p?.image&&<div style={{width:width*.2,aspectRatio:"1/1",borderRadius:width*.025,overflow:"hidden",backgroundColor:"#16191d"}}><Img src={p.image} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div>}<div style={{flex:1}}><div style={{fontSize:width*.036,fontWeight:850,lineHeight:1.05}}>{p?.title||headline}</div><div style={{fontSize:width*.022,opacity:.55,marginTop:10}}>{p?.brand||"AI • course • template • coaching"}</div></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:width*.035}}>{["Fast to start","Practical workflow","Built for results","Save & revisit"].map((x,i)=><div key={x} style={{padding:"14px 15px",borderRadius:16,background:"rgba(255,255,255,.05)",fontSize:width*.02,opacity:interpolate(frame,[24+i*5,34+i*5],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}>{x}</div>)}</div></div></div><div style={{position:"absolute",left:width*.06,right:width*.06,bottom:height*.055,display:"flex",justifyContent:"space-between",alignItems:"end",gap:20}}><div style={{fontSize:width*.034,fontWeight:850,maxWidth:"62%"}}>{headline}</div><div style={{padding:"14px 18px",borderRadius:999,backgroundColor:"#9BEA92",color:"#071007",fontSize:width*.019,fontWeight:900}}>{cta}</div></div></AbsoluteFill>}
