alter table public.ynot_users
  add column if not exists account_name text,
  add column if not exists pin_hash text,
  add column if not exists avatar_data text,
  add column if not exists saved_items jsonb not null default '[]'::jsonb,
  add column if not exists profile_updated_at timestamptz not null default now();

create unique index if not exists ynot_users_account_name_unique
  on public.ynot_users (lower(account_name))
  where account_name is not null;

create table if not exists public.ynot_profile_attempts (
  id bigint generated by default as identity primary key,
  account_name text not null,
  ip_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists ynot_profile_attempts_lookup
  on public.ynot_profile_attempts (account_name, ip_key, created_at desc);

alter table public.ynot_profile_attempts enable row level security;
revoke all on table public.ynot_profile_attempts from anon, authenticated;
grant select, insert, delete on table public.ynot_profile_attempts to service_role;
grant usage, select on sequence public.ynot_profile_attempts_id_seq to service_role;
grant select, insert, update, delete on table public.ynot_users to service_role;