"use client";

import {useEffect,useMemo,useState} from "react";
import {ArrowRight,Check,CircleUserRound,Clapperboard,Copy,ExternalLink,Image as ImageIcon,Play,Search,Send,Upload,UserRound,Video,WandSparkles} from "lucide-react";
import {authedFetch} from "@/lib/ynot/supabase-browser";

type CreatorProduct={id?:string;product_id:string;title:string;brand?:string;image_url?:string;price?:number|null;currency:string;commission_rate?:number;commission_cents?:number|null;description?:string;url?:string};
type CatalogProduct={id:string;title:string;brand?:string;image?:string;price?:number|null;currency?:string;description?:string;url?:string};
type Inspiration={id:string;title:string;description?:string;image:string;source_url?:string;creator?:string};
type Mode="video-self"|"video-avatar"|"image-self"|"ai-avatar"|"product-only";
type Step="product"|"source"|"avatar"|"creative"|"review";

const creativeAngles=[
 {id:"testimonial",title:"UGC testimonial",desc:"Natural creator-led review with a strong first-person hook."},
 {id:"problem",title:"Problem → solution",desc:"Open with a relatable problem, then reveal the product."},
 {id:"routine",title:"Routine / lifestyle",desc:"Blend the product into a daily routine so it feels native."},
 {id:"demo",title:"Product demo",desc:"Show the product being used with clear visual proof."},
];

const FLOW_URL="https://labs.google/fx/tools/flow";
const FLOW_NEGATIVE="No text, captions, subtitles, interface graphics, buttons, timestamps, watermarks, invented logos, duplicate products, extra people, extra fingers, deformed hands, distorted anatomy, warped packaging, floating objects, CGI look, cartoon styling, oversaturated colors, impossible product interaction or altered product branding.";
function flowPack(product:CreatorProduct|undefined,mode:Mode,angle:string,hasBackground:boolean){
 if(!product)return{full:"",short:"",negative:FLOW_NEGATIVE};
 const title=product.title||"the selected product",brand=product.brand?" by "+product.brand:"",description=(product.description||"").slice(0,700);
 const modeNote=mode==="video-avatar"?"Compose the selected creator/avatar as the visible identity while keeping the frame suitable for later motion transfer.":mode==="video-self"?"Keep a natural creator-led UGC composition that can be animated from a source performance.":mode==="image-self"||mode==="ai-avatar"?"Create a believable creator-led frame with natural body positioning and realistic product interaction.":"Make the exact product the visual hero in a realistic use context.";
 const angleNote=angle==="problem"?"Frame a relatable problem-to-solution moment.":angle==="routine"?"Frame the product naturally inside a daily lifestyle routine.":angle==="demo"?"Frame a clear hands-on product demonstration.":"Frame a believable first-person UGC testimonial moment.";
 const bg=hasBackground?"Use the supplied background reference as the environment/composition guide.":"Choose the most believable real-world environment for this product.";
 const full=["OBJECTIVE","Create one highly photorealistic vertical 9:16 smartphone UGC keyframe for later video animation.","","PRODUCT","Use the supplied product reference as authoritative: "+title+brand+". Preserve exact design, color, branding, proportions, materials and recognizable details."+(description?" Product context: "+description:""),"","CREATOR / COMPOSITION",modeNote+" "+angleNote,"The product must be worn, used, held or interacted with exactly as a real person would use it; do not merely place it in frame unless that is natural for the product.","","ENVIRONMENT",bg,"","CAMERA","Modern smartphone look, vertical 9:16, natural perspective, believable social-media framing, realistic skin and materials, subtle HDR, premium but not overproduced.","","LIGHTING","Soft believable lighting appropriate to the environment with realistic contact shadows and product reflections.","","REFERENCE FIDELITY","Prioritize identity consistency, exact product fidelity, realistic hands/body interaction, scene geometry, scale, perspective and physical contact.","","OUTPUT","One clean 2K photorealistic image. No UI or added typography.","","NEGATIVE",FLOW_NEGATIVE].join("\n");
 const short="Photorealistic 9:16 smartphone UGC keyframe featuring the exact product "+title+brand+". "+modeNote+" "+angleNote+" "+bg+" Preserve exact product design/branding and realistic human use, scale, hands, anatomy, shadows and perspective. Authentic social-media look, clean 2K image, no text/UI/watermarks.";
 return{full,short,negative:FLOW_NEGATIVE};
}

export default function CreatorStudio({products}:{products:CreatorProduct[]}){
 const[step,setStep]=useState<Step>("product"),[productId,setProductId]=useState(products[0]?.product_id||""),[mode,setMode]=useState<Mode>("video-avatar"),[angle,setAngle]=useState("testimonial"),[avatar,setAvatar]=useState("new-avatar"),[sourceName,setSourceName]=useState(""),[notice,setNotice]=useState("");
 const[query,setQuery]=useState(""),[catalog,setCatalog]=useState<CatalogProduct[]>([]),[sourcePath,setSourcePath]=useState(""),[avatarPath,setAvatarPath]=useState(""),[avatarName,setAvatarName]=useState(""),[working,setWorking]=useState(""),[result,setResult]=useState<any>(null),[caption,setCaption]=useState(""),[platforms,setPlatforms]=useState<string[]>(["instagram","tiktok","youtube","threads"]),[scheduledFor,setScheduledFor]=useState("");
 const[readiness,setReadiness]=useState<{higgsfield?:{configured:boolean};viggle?:{configured:boolean};trypost?:{configured:boolean};gemini_image?:{configured:boolean;standard_model?:string;premium_model?:string};generation_ready?:boolean;standard_motion_ready?:boolean;premium_motion_ready?:boolean}|null>(null);
 const[qualityTier,setQualityTier]=useState<"standard"|"premium">("standard");
 const[imageSource,setImageSource]=useState<"ynot_standard"|"ynot_premium"|"google_flow">("ynot_standard"),[flowImagePath,setFlowImagePath]=useState(""),[flowImageName,setFlowImageName]=useState("");
 const[inspirationQuery,setInspirationQuery]=useState(""),[inspirationKind,setInspirationKind]=useState<"avatar"|"background">("avatar"),[inspiration,setInspiration]=useState<Inspiration[]>([]);
 const[avatarImageUrl,setAvatarImageUrl]=useState(""),[backgroundImageUrl,setBackgroundImageUrl]=useState("");
 const allProducts=useMemo(()=>{const map=new Map<string,CreatorProduct>();for(const p of products)map.set(p.product_id,p);for(const p of catalog)map.set(String(p.id),{product_id:String(p.id),title:p.title,brand:p.brand||"YNOT",image_url:p.image||"",price:p.price??null,currency:p.currency||"EUR",commission_rate:.05,description:p.description,url:p.url});return [...map.values()]},[products,catalog]);
 const product=useMemo(()=>allProducts.find(p=>p.product_id===productId)||allProducts[0],[allProducts,productId]);
 const flow=useMemo(()=>flowPack(product,mode,angle,Boolean(backgroundImageUrl)),[product,mode,angle,backgroundImageUrl]);
 useEffect(()=>{let live=true;void authedFetch("/api/earn/studio/status").then(async r=>{const j=await r.json().catch(()=>null);if(live&&r.ok)setReadiness(j)}).catch(()=>{});return()=>{live=false}},[]);
 const steps:Step[]=["product","source","avatar","creative","review"],current=steps.indexOf(step);
 function next(){setStep(steps[Math.min(current+1,steps.length-1)])}
 function back(){setStep(steps[Math.max(current-1,0)])}
 async function searchCatalog(){const q=query.trim();if(q.length<2)return;setWorking("search");setNotice("");try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(q)}&source=shopify&country=FR`),j=await r.json();if(!r.ok)throw new Error(j.error||"Search failed");setCatalog((j.products||[]).slice(0,40));if(!(j.products||[]).length)setNotice("No products found.")}catch(e){setNotice(e instanceof Error?e.message:"Search failed")}finally{setWorking("")}}
 async function chooseProduct(p:CreatorProduct){setProductId(p.product_id);try{await authedFetch("/api/earn/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:p.product_id,title:p.title,brand:p.brand,image:p.image_url,price:p.price,currency:p.currency,description:p.description,url:p.url})});setNotice("Product selected and added to your promotion catalogue.")}catch{}}
 async function upload(file:File,kind:"video"|"avatar"|"flow"){setWorking(kind);setNotice("");try{const ext=(file.name.split(".").pop()||(kind==="video"?"mp4":"jpg")).toLowerCase(),r=await authedFetch("/api/earn/studio/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,extension:ext})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Upload setup failed");const up=await fetch(j.signed_url,{method:"PUT",headers:{"Content-Type":file.type||"application/octet-stream"},body:file});if(!up.ok)throw new Error("Upload failed");if(kind==="video"){setSourcePath(j.path);setSourceName(file.name)}else if(kind==="flow"){setFlowImagePath(j.path);setFlowImageName(file.name)}else{setAvatarPath(j.path);setAvatarImageUrl("");setAvatarName(file.name)}setNotice("Reference uploaded.")}catch(e){setNotice(e instanceof Error?e.message:"Upload failed")}finally{setWorking("")}}
 async function searchInspiration(kind:"avatar"|"background"=inspirationKind){const q=inspirationQuery.trim();if(q.length<2)return;setWorking("inspiration");setNotice("");setInspirationKind(kind);try{const r=await authedFetch(`/api/earn/studio/inspiration?q=${encodeURIComponent(q)}&kind=${kind}`),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Inspiration search failed");setInspiration(j.items||[]);if(!(j.items||[]).length)setNotice("No inspiration found. Try another search.")}catch(e){setNotice(e instanceof Error?e.message:"Inspiration search failed")}finally{setWorking("")}}
 function chooseInspiration(item:Inspiration){if(inspirationKind==="avatar"){setAvatarImageUrl(item.image);setAvatarPath("");setAvatarName(item.title||"Pinterest avatar");setAvatar("new-avatar")}else{setBackgroundImageUrl(item.image)}setNotice(inspirationKind==="avatar"?"Avatar reference selected.":"Background reference selected.")}
 async function generate(){if(!product)return;setWorking("generate");setNotice(imageSource==="google_flow"?"Using your Google Flow image as the video base…":(imageSource==="ynot_premium"?"Nano Banana Pro":"Nano Banana 2")+" is composing the video base…");try{const r=await authedFetch("/api/earn/studio/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product,mode,angle,quality_tier:qualityTier,image_source:imageSource,flow_image_path:flowImagePath,flow_prompt:imageSource==="google_flow"?flow.full:"",source_path:sourcePath,avatar_path:avatarPath,avatar_image_url:avatarImageUrl,background_image_url:backgroundImageUrl})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Generation failed");setResult(j.job);setCaption(`I found ${product.title} on YNOT — shop it from my creator link.`);setNotice("Video ready.")}catch(e){setNotice(e instanceof Error?e.message:"Generation failed")}finally{setWorking("")}}
 async function autopost(){if(!result?.result_url||!product)return;setWorking("post");setNotice("");try{const r=await authedFetch("/api/earn/autopost",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studio_job_id:result.id,product_id:product.product_id,media_url:result.result_url,caption,platforms,scheduled_for:scheduledFor||null,destination:"trypost"})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Post failed");setNotice(scheduledFor?"Scheduled in TryPost.":"Submitted to TryPost.")}catch(e){setNotice(e instanceof Error?e.message:"Post failed")}finally{setWorking("")}}
 function togglePlatform(p:string){setPlatforms(s=>s.includes(p)?s.filter(x=>x!==p):[...s,p])}
 return <section className="studioShell">
  <div className="studioIntro"><div><span>YNOT CREATOR STUDIO</span><h2>Turn yourself — or an avatar — into the product creative.</h2><p>Use your own performance as the source motion, keep yourself in the final video, or replace yourself with another avatar while preserving the movement and delivery. Then swap in the product and finish the ad around it.</p><div className="studioReadiness"><b className={readiness?.gemini_image?.configured?"ready":"setup"}>{readiness?.gemini_image?.configured?"Nano Banana ready":"Nano Banana setup required"}</b><b className={readiness?.higgsfield?.configured?"ready":"setup"}>{readiness?.viggle?.configured&&readiness?.higgsfield?.configured?"Viggle + Premium ready":readiness?.viggle?.configured?"Viggle Standard ready":readiness?.higgsfield?.configured?"Premium video ready":"Video provider setup required"}</b><b className={readiness?.trypost?.configured?"ready":"setup"}>{readiness?.trypost?.configured?"TryPost ready":"TryPost setup required"}</b></div></div><div className="studioFlow"><span>PRODUCT</span><i>→</i><span>SOURCE VIDEO</span><i>→</i><span>AVATAR</span><i>→</i><span>V2V</span><i>→</i><span>POST</span></div></div>
  <div className="studioProgress">{steps.map((s,i)=><button key={s} className={i===current?"active":i<current?"done":""} onClick={()=>i<=current&&setStep(s)}><b>{i<current?<Check/>:i+1}</b><span>{s==="product"?"Product":s==="source"?"Source":s==="avatar"?"Avatar":s==="creative"?"Creative":"Review"}</span></button>)}</div>
  {notice&&<div className="creatorNotice">{notice}</div>}

  {step==="product"&&<div className="studioStage"><div className="studioStageHead"><span>STEP 1 · LIVE YNOT CATALOGUE</span><h3>Choose any product to promote.</h3><p>Search the live catalogue directly. Selecting a product also adds it to your promotion catalogue automatically.</p></div><form className="creatorSearch studioCatalogSearch" onSubmit={e=>{e.preventDefault();void searchCatalog()}}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search YNOT — dress, lamp, skincare, headphones…"/><button disabled={working==="search"}>{working==="search"?"Searching…":"Search catalogue"}</button></form><div className="studioProductChoice">{allProducts.map(p=><button key={p.product_id} className={productId===p.product_id?"active":""} onClick={()=>void chooseProduct(p)}>{p.image_url?<img src={p.image_url} alt=""/>:<span>Y</span>}<div><strong>{p.title}</strong><small>{p.brand||"YNOT"}{p.price?" · "+p.currency+" "+Number(p.price).toFixed(0)+" · ~"+(Number(p.price)*Number(p.commission_rate||.05)).toFixed(2)+" commission":" · "+Math.round(Number(p.commission_rate||.05)*100)+"% commission"}</small></div>{productId===p.product_id?<Check/>:null}</button>)}</div><div className="studioFooter"><span>{product?"Selected: "+product.title:"Search and choose a product"}</span><button className="creatorAction" disabled={!product} onClick={next}>Choose source <ArrowRight/></button></div></div>}

  {step==="source"&&<div className="studioStage"><div className="studioStageHead"><span>STEP 2 · VIDEO-TO-VIDEO FIRST</span><h3>Give YNOT the performance.</h3><p>This is the motion source. You can record yourself talking, demonstrating, walking, holding a placeholder object, or performing the exact actions you want in the finished ad.</p></div><div className="studioModeGrid">
    <button className={mode==="video-self"?"active":""} onClick={()=>setMode("video-self")}><Video/><strong>Keep me in the video</strong><p>Your motion and identity stay. YNOT/Higgsfield changes the product, styling or environment around you.</p></button>
    <button className={mode==="video-avatar"?"active":""} onClick={()=>setMode("video-avatar")}><CircleUserRound/><strong>Replace me with an avatar</strong><p><b>Your original performance stays.</b> The final person can be a different avatar/persona while preserving the motion, framing and delivery of your source clip.</p></button>
    <button className={mode==="image-self"?"active":""} onClick={()=>setMode("image-self")}><ImageIcon/><strong>Start from my image</strong><p>Use your portrait/full-body reference when you do not have a source clip.</p></button>
    <button className={mode==="ai-avatar"?"active":""} onClick={()=>setMode("ai-avatar")}><UserRound/><strong>AI creator</strong><p>Create the entire presenter without showing yourself.</p></button>
    <button className={mode==="product-only"?"active":""} onClick={()=>setMode("product-only")}><Clapperboard/><strong>Product only</strong><p>No presenter. Build a cinematic or demo-led product ad.</p></button>
   </div>
   {(mode==="video-self"||mode==="video-avatar")&&<label className="studioUpload"><Upload/><strong>{sourceName||"Upload your source performance video"}</strong><span>Vertical 9:16 is ideal. Your movement becomes the motion blueprint for the final video.</span><input type="file" accept="video/mp4,video/quicktime" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,"video")}}/></label>}
   <div className="studioFooter"><button className="studioBack" onClick={back}>Back</button><button className="creatorAction" onClick={next}>Choose avatar <ArrowRight/></button></div></div>}

  {step==="avatar"&&<div className="studioStage"><div className="studioStageHead"><span>STEP 3</span><h3>{mode==="video-avatar"?"Who should replace you?":"Choose the presenter identity."}</h3><p>{mode==="video-avatar"?"The source clip still supplies the performance. This step only changes who appears in that performance.":"Save reusable creator identities so the same face/look can be used across products."}</p></div>
   <div className="studioAvatarGrid"><button className={avatar==="me"?"active":""} onClick={()=>setAvatar("me")}><UserRound/><strong>Me</strong><span>Keep my identity</span></button><button className={avatar==="new-avatar"?"active":""} onClick={()=>setAvatar("new-avatar")}><CircleUserRound/><strong>Different avatar</strong><span>Replace the person while keeping source motion</span></button><button className={avatar==="saved"?"active":""} onClick={()=>setAvatar("saved")}><WandSparkles/><strong>Saved persona</strong><span>Reuse one of my Studio identities</span></button></div>
   {(mode==="video-avatar"||mode==="image-self"||mode==="ai-avatar")&&avatar!=="me"&&<label className="studioUpload"><Upload/><strong>{avatarName||"Upload avatar / creator reference image"}</strong><span>This image becomes the visible identity while the source video can still control the motion.</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,"avatar")}}/></label>}{(mode==="video-avatar"||mode==="image-self"||mode==="ai-avatar")&&avatar!=="me"&&<div className="studioInspiration"><div className="studioInspirationHead"><div><small>PINTEREST INSPIRATION</small><strong>Search for a creator look</strong></div><div className="studioInspirationSearch"><Search/><input value={inspirationQuery} onChange={e=>setInspirationQuery(e.target.value)} placeholder="streetwear male creator, luxury female model…"/><button onClick={()=>void searchInspiration("avatar")} disabled={working==="inspiration"}>{working==="inspiration"?"Searching…":"Search"}</button></div></div>{avatarImageUrl&&<div className="studioSelectedReference"><img src={avatarImageUrl} alt="Selected avatar"/><span>Selected avatar reference</span></div>}{inspirationKind==="avatar"&&inspiration.length?<div className="studioInspirationGrid">{inspiration.map(item=><button key={item.id} className={avatarImageUrl===item.image?"active":""} onClick={()=>chooseInspiration(item)}><img src={item.image} alt={item.title}/><span>{item.title||"Creator reference"}</span></button>)}</div>:null}</div>}\n   {mode==="video-avatar"&&<div className="studioExplain"><Play/><div><b>Video-to-video avatar replacement</b><span>Example: you record the motions and dialogue timing yourself → YNOT sends that source performance into the video-to-video workflow → the final video can show a different model/avatar performing those same actions with the selected product.</span></div></div>}
   <div className="studioFooter"><button className="studioBack" onClick={back}>Back</button><button className="creatorAction" onClick={next}>Choose creative <ArrowRight/></button></div></div>}

  {step==="creative"&&<div className="studioStage"><div className="studioStageHead"><span>STEP 4</span><h3>Choose the selling angle.</h3><p>YNOT builds the hook, scene instructions, product fidelity notes, caption and CTA around this choice.</p></div><div className="studioInspiration studioBackgroundFinder"><div className="studioInspirationHead"><div><small>PINTEREST BACKGROUNDS</small><strong>Choose the world around the creative</strong></div><div className="studioInspirationSearch"><Search/><input value={inspirationQuery} onChange={e=>setInspirationQuery(e.target.value)} placeholder="minimal apartment, gym studio, beach sunset…"/><button onClick={()=>void searchInspiration("background")} disabled={working==="inspiration"}>{working==="inspiration"?"Searching…":"Search"}</button></div></div>{backgroundImageUrl&&<div className="studioSelectedReference"><img src={backgroundImageUrl} alt="Selected background"/><span>Selected background reference</span></div>}{inspirationKind==="background"&&inspiration.length?<div className="studioInspirationGrid background">{inspiration.map(item=><button key={item.id} className={backgroundImageUrl===item.image?"active":""} onClick={()=>chooseInspiration(item)}><img src={item.image} alt={item.title}/><span>{item.title||"Background reference"}</span></button>)}</div>:null}</div><div className="studioAngleGrid">{creativeAngles.map(x=><button key={x.id} className={angle===x.id?"active":""} onClick={()=>setAngle(x.id)}><strong>{x.title}</strong><span>{x.desc}</span></button>)}</div><div className="studioFooter"><button className="studioBack" onClick={back}>Back</button><button className="creatorAction" onClick={next}>Review workflow <ArrowRight/></button></div></div>}

  {step==="review"&&<div className="studioStage"><div className="studioStageHead"><span>READY TO BUILD</span><h3>Your Studio job</h3><p>This review page is intentionally explicit so the creator always knows what will be changed before generation.</p></div>
   <div className="studioChoiceLabel"><span>BASE IMAGE SOURCE</span><p>Choose where the starting frame comes from. Image quality and video quality are independent.</p></div>
   <div className="studioImageSourceGrid">
    <button className={imageSource==="ynot_standard"?"active":""} onClick={()=>setImageSource("ynot_standard")}><span>YNOT STANDARD</span><strong>Nano Banana 2</strong><small>Automatic 2K composition inside YNOT. Good default image quality.</small></button>
    <button className={imageSource==="ynot_premium"?"active":""} onClick={()=>setImageSource("ynot_premium")}><span>YNOT PREMIUM</span><strong>Nano Banana Pro</strong><small>Higher-fidelity 2K composition for harder products, people and scenes.</small></button>
    <button className={imageSource==="google_flow"?"active":""} onClick={()=>setImageSource("google_flow")}><span>USE YOUR OWN CREDITS</span><strong>Google Flow</strong><small>YNOT prepares the prompt and references. Generate in Flow, then upload the result.</small></button>
   </div>
   {imageSource==="google_flow"&&<div className="studioFlowPack">
    <div className="studioFlowPackHead"><div><span>GOOGLE FLOW EXPORT PACK</span><strong>Generate the base image with your own Flow credits.</strong><small>Use the full prompt for maximum fidelity, or the short prompt for a faster manual workflow.</small></div><a href={FLOW_URL} target="_blank" rel="noreferrer"><ExternalLink/> Open Google Flow</a></div>
    <div className="studioFlowPrompt"><div><span>FULL PROMPT</span><button onClick={()=>void navigator.clipboard.writeText(flow.full)}><Copy/> Copy prompt</button></div><textarea readOnly value={flow.full}/></div>
    <div className="studioFlowPrompt compact"><div><span>SHORT PROMPT</span><button onClick={()=>void navigator.clipboard.writeText(flow.short)}><Copy/> Copy short prompt</button></div><textarea readOnly value={flow.short}/></div>
    <div className="studioFlowPrompt compact"><div><span>NEGATIVE PROMPT</span><button onClick={()=>void navigator.clipboard.writeText(flow.negative)}><Copy/> Copy negative</button></div><textarea readOnly value={flow.negative}/></div>
    <div className="studioFlowRefs">
     <div><span>PRODUCT</span>{product?.image_url?<img src={product.image_url} alt="Product reference"/>:<b>No image</b>}{product?.image_url&&<a href={product.image_url} target="_blank" rel="noreferrer">Open reference</a>}</div>
     <div><span>AVATAR</span>{avatarImageUrl?<img src={avatarImageUrl} alt="Avatar reference"/>:<b>{avatarPath?"Uploaded reference ready":"Optional / not selected"}</b>}{avatarImageUrl&&<a href={avatarImageUrl} target="_blank" rel="noreferrer">Open reference</a>}</div>
     <div><span>BACKGROUND</span>{backgroundImageUrl?<img src={backgroundImageUrl} alt="Background reference"/>:<b>Optional / not selected</b>}{backgroundImageUrl&&<a href={backgroundImageUrl} target="_blank" rel="noreferrer">Open reference</a>}</div>
    </div>
    <div className="studioFlowSettings"><span>FLOW SETTINGS</span><b>9:16 portrait</b><b>2K image</b><b>Photorealistic</b><b>Reference fidelity first</b></div>
    <label className="studioUpload flowReturn"><Upload/><strong>{flowImageName||"Upload the image you generated in Google Flow"}</strong><span>This image becomes the base frame. YNOT will not run Nano Banana again.</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,"flow")}}/></label>
   </div>}
   <div className="studioChoiceLabel videoTier"><span>VIDEO QUALITY</span><p>Pick the video route separately so you can mix a strong image with a cheaper video, or vice versa.</p></div>
   <div className="studioTierPicker">
    <button className={qualityTier==="standard"?"active":""} onClick={()=>setQualityTier("standard")}><span>STANDARD VIDEO</span><strong>{mode==="video-avatar"||mode==="video-self"?"Viggle motion route":"Efficient route"}</strong><small>{mode==="video-avatar"||mode==="video-self"?"JST-2 uses the source performance with your composed character frame; Genjutsu remains fallback.":"Best cost/quality balance for most creator content."}</small></button>
    <button className={qualityTier==="premium"?"active":""} onClick={()=>setQualityTier("premium")}><span>PREMIUM VIDEO</span><strong>Higher-fidelity route</strong><small>Use when motion, identity or product fidelity matters more than generation cost.</small></button>
   </div>
   <div className="studioReview">
    <div><small>PRODUCT</small><strong>{product?.title}</strong><span>{product?.brand||"YNOT"}</span></div>
    <div><small>METHOD</small><strong>{mode==="video-avatar"?"Video-to-video + avatar replacement":mode==="video-self"?"Video-to-video · keep creator":mode==="image-self"?"Creator image → video":mode==="ai-avatar"?"AI avatar generation":"Product-only generation"}</strong><span>{mode==="video-avatar"?"Preserve motion/performance; replace the visible person.":"Creator-selected workflow."}</span></div>
    <div><small>CREATIVE ANGLE</small><strong>{creativeAngles.find(x=>x.id===angle)?.title}</strong><span>{backgroundImageUrl?"Pinterest background reference selected. ":""}YNOT will generate hook, script, CTA and platform variants.</span></div>
    <div><small>IMAGE + VIDEO</small><strong>{imageSource==="google_flow"?"Google Flow":imageSource==="ynot_premium"?"YNOT Premium image":"YNOT Standard image"} + {qualityTier==="premium"?"Premium":"Standard"} video</strong><span>{imageSource==="google_flow"?"Your uploaded Flow image will be used directly.":"YNOT will compose the base image automatically."}</span></div>
   </div>
   <div className="studioPipeline"><span><b>1</b> Analyse source</span><i>→</i><span><b>2</b> Replace/avatar</span><i>→</i><span><b>3</b> Product swap</span><i>→</i><span><b>4</b> Final video</span><i>→</i><span><b>5</b> Caption + link</span></div>
   <div className="studioProviderNote"><WandSparkles/><div><b>Image-first routing</b><span>{imageSource==="google_flow"?"Your Flow image is used directly as the base frame. No YNOT image-generation charge is added.":"YNOT first composes the selected image tier, then routes that base frame into the selected video tier."}</span></div></div>
   <div className="studioFooter"><button className="studioBack" onClick={back}>Back</button><button className="creatorAction" disabled={working==="generate"||((qualityTier==="premium"?readiness?.premium_motion_ready===false:readiness?.standard_motion_ready===false))||(imageSource!=="google_flow"&&readiness?.gemini_image?.configured===false)||!product||(imageSource==="google_flow"&&!flowImagePath)||((mode==="video-self"||mode==="video-avatar")&&!sourcePath)||((mode==="video-avatar"||mode==="image-self"||mode==="ai-avatar")&&avatar!=="me"&&!avatarPath&&!avatarImageUrl)} onClick={()=>void generate()}><Clapperboard/> {working==="generate"?"Building creative…":imageSource==="google_flow"?(qualityTier==="premium"?"Use Flow Image · Premium Video":"Use Flow Image · Standard Video"):(qualityTier==="premium"?"Generate Premium":"Generate Standard")}</button></div>
  </div>}
  {result?.result_url&&<div className="studioStage"><div className="studioStageHead"><span>VIDEO READY · AUTOPOST</span><h3>Approve and distribute.</h3><p>The Higgsfield output can go straight into TryPost for multi-platform publishing or scheduling.</p></div><div className="studioResult"><video src={result.result_url} controls playsInline/><div><small>HIGGSFIELD OUTPUT</small><strong>{product?.title}</strong><span>{result.provider_model||"Higgsfield"}</span></div></div><label className="studioCaption"><span>Caption + CTA</span><textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Write the post caption…"/></label><div className="studioSocials"><span>POST TO</span><div>{["instagram","tiktok","youtube","threads","x","pinterest","facebook"].map(p=><button key={p} className={platforms.includes(p)?"active":""} onClick={()=>togglePlatform(p)}>{platforms.includes(p)?<Check/>:null}{p}</button>)}</div></div><label className="studioSchedule"><span>Optional schedule</span><input type="datetime-local" value={scheduledFor} onChange={e=>setScheduledFor(e.target.value)}/></label><div className="studioFooter"><span/><button className="creatorAction" disabled={working==="post"||!platforms.length} onClick={()=>void autopost()}><Send/> {working==="post"?"Sending…":scheduledFor?"Schedule via TryPost":"Publish via TryPost"}</button></div></div>}
 </section>;
}
