"use client";

import {useMemo,useState} from "react";

type Prospect={username:string;displayName:string;avatar?:string;profileUrl?:string;bio?:string;followers?:number;verified?:boolean;videoCount:number;totalViews:number;avgViews:number;avgEngagement:number;prospectScore:number;sampleVideos:any[]};

const MODES=[["creator","Creators"],["brand","Brands"],["property","Airbnb / Property"],["product","Products"],["content","Content angles"]] as const;
function compact(n:any){const x=Number(n||0);return new Intl.NumberFormat(undefined,{notation:"compact",maximumFractionDigits:1}).format(x)}

export default function GrowthSocialIntel(){
 const[section,setSection]=useState<"prospects"|"ads"|"instagram">("prospects");
 const[mode,setMode]=useState("creator"),[query,setQuery]=useState("home decor"),[country,setCountry]=useState("FR");
 const[prospects,setProspects]=useState<Prospect[]>([]),[selectedUser,setSelectedUser]=useState(""),[profile,setProfile]=useState<any>(null);
 const[ads,setAds]=useState<any[]>([]),[advertisers,setAdvertisers]=useState<any[]>([]),[igHandle,setIgHandle]=useState(""),[ig,setIg]=useState<any>(null);
 const[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 const selected=useMemo(()=>prospects.find(x=>x.username===selectedUser)||prospects[0]||null,[prospects,selectedUser]);

 async function runProspects(){setBusy("prospects");setNotice("");setProfile(null);try{const r=await fetch("/api/admin/growth/social/tiktok/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query,mode,pages:2,limit:60})});const j=await r.json();if(!r.ok)throw new Error(j.error||"TikTok search failed");setProspects(j.prospects||[]);setSelectedUser(j.prospects?.[0]?.username||"");if(!j.prospects?.length)setNotice("No public TikTok prospects found for this search.");}catch(e){setNotice(e instanceof Error?e.message:"TikTok search failed")}finally{setBusy("")}}
 async function enrichTikTok(){if(!selected)return;setBusy("enrich");setNotice("");try{const r=await fetch("/api/admin/growth/social/tiktok/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:selected.username})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Enrichment failed");setProfile(j);}catch(e){setNotice(e instanceof Error?e.message:"Enrichment failed")}finally{setBusy("")}}
 async function runAds(){setBusy("ads");setNotice("");try{const r=await fetch("/api/admin/growth/social/tiktok/ads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query,country,limit:50})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Ad search failed");setAds(j.ads||[]);setAdvertisers(j.advertisers||[]);if(!j.ads?.length)setNotice("No active public TikTok ads found for this search.");}catch(e){setNotice(e instanceof Error?e.message:"Ad search failed")}finally{setBusy("")}}
 async function runInstagram(){if(!igHandle.trim())return;setBusy("instagram");setNotice("");try{const r=await fetch("/api/admin/growth/social/instagram/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:igHandle})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Instagram enrichment failed");setIg(j);}catch(e){setNotice(e instanceof Error?e.message:"Instagram enrichment failed")}finally{setBusy("")}}
 async function saveLead(payload:any){setBusy("save");setNotice("");try{const r=await fetch("/api/admin/growth/social/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Save failed");setNotice("Saved to Growth Outreach Inbox.");}catch(e){setNotice(e instanceof Error?e.message:"Save failed")}finally{setBusy("")}}

 function saveTikTok(){if(!selected)return;const p=profile?.profile||{};const contact=profile?.contact?.bestContact||null;saveLead({platform:"tiktok",kind:mode==="creator"?"creator":mode==="brand"?"brand":mode==="property"?"airbnb_host":mode==="product"?"product_opportunity":"content_opportunity",handle:selected.username,display_name:p.displayName||selected.displayName,profile_url:p.profileUrl||selected.profileUrl,source_post_url:selected.sampleVideos?.[0]?.url,niche:query,followers:p.followers||selected.followers,engagement:profile?.metrics?.avgEngagement||selected.avgEngagement,score:selected.prospectScore,bio:p.bio||selected.bio,known_targets:p.bioLinks||[],contact,metrics:profile?.metrics||{avgViews:selected.avgViews,totalViews:selected.totalViews},summary:"TikTok "+mode+" prospect discovered from “"+query+"”.",reason:"Relevant TikTok content, activity and commercial-fit signals.",tags:["tiktok",mode,query]});}
 function saveAdvertiser(a:any){saveLead({platform:"tiktok_ads",kind:"advertiser",display_name:a.advertiser,niche:query,country,score:a.signalScore,known_targets:a.landingPages||[],summary:a.adCount+" active/recent ads found for this advertiser around “"+query+"”.",reason:"Repeated paid-ad activity is a strong research and outreach signal, though not proof of sales.",source:a.sampleAds,tags:["tiktok-ads","advertiser",query]});}
 function saveInstagram(){if(!ig?.profile)return;const p=ig.profile;saveLead({platform:"instagram",kind:"social_prospect",handle:p.username,display_name:p.displayName,profile_url:p.profileUrl,niche:"instagram enrichment",followers:p.followers,engagement:ig.metrics?.avgEngagement,score:Math.min(100,30+(p.followers>=10000?20:10)+(ig.metrics?.avgViews>=10000?20:5)+(p.bioLinks?.length?15:0)),bio:p.bio,known_targets:p.bioLinks||[],contact:ig.contact?.bestContact||null,metrics:ig.metrics,summary:"Instagram profile enriched with public profile and reels data.",reason:"Active public Instagram presence with measurable reel engagement and contact paths.",tags:["instagram","enriched"]});}

 return <section className="socialIntel" id="social-intelligence">
  <div className="socialHead"><div><span>SOCIAL PROSPECTING</span><h2>TikTok discovery + Instagram enrichment</h2><p>Find creators, brands, property prospects, product opportunities and content angles, then push qualified results into one outreach inbox.</p></div><div className="socialBadge">FETCHLAYER LIVE</div></div>
  <div className="socialTabs"><button className={section==="prospects"?"active":""} onClick={()=>setSection("prospects")}>TikTok Prospects</button><button className={section==="ads"?"active":""} onClick={()=>setSection("ads")}>TikTok Ad Intel</button><button className={section==="instagram"?"active":""} onClick={()=>setSection("instagram")}>Instagram Enrichment</button></div>
  {notice&&<div className="socialNotice">{notice}</div>}

  {section==="prospects"&&<>
   <div className="socialModes">{MODES.map(([id,label])=><button key={id} className={mode===id?"active":""} onClick={()=>setMode(id)}>{label}</button>)}</div>
   <div className="socialSearch"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. luxury villa, activewear brand, smart mirror"/><button onClick={runProspects} disabled={busy==="prospects"||query.trim().length<2}>{busy==="prospects"?"Searching TikTok…":"Search TikTok"}</button></div>
   <div className="socialLayout"><aside className="socialList">{prospects.length?prospects.map(x=><button key={x.username} className={"socialLead "+(selected?.username===x.username?"selected":"")} onClick={()=>{setSelectedUser(x.username);setProfile(null)}}>{x.avatar?<img src={x.avatar} alt=""/>:<span>{x.displayName.slice(0,1)}</span>}<div><div><strong>{x.displayName}</strong><b>{x.prospectScore}</b></div><small>@{x.username} · {compact(x.followers)} followers</small><p>{compact(x.avgViews)} avg views · {x.videoCount} search matches</p></div></button>):<div className="empty">Search TikTok to discover prospects.</div>}</aside>
    <section className="socialDetail">{selected?<><div className="socialProfileHero">{selected.avatar?<img src={selected.avatar} alt=""/>:<div>{selected.displayName.slice(0,1)}</div>}<div><span>{mode.toUpperCase()} PROSPECT</span><h3>{selected.displayName}</h3><p>@{selected.username}</p></div><b>{selected.prospectScore}/100</b></div><p className="socialBio">{profile?.profile?.bio||selected.bio||selected.sampleVideos?.[0]?.description||"No public bio loaded yet."}</p><div className="socialStats"><span><b>{compact(profile?.profile?.followers||selected.followers)}</b>followers</span><span><b>{compact(profile?.metrics?.avgViews||selected.avgViews)}</b>avg views</span><span><b>{compact(profile?.metrics?.avgEngagement||selected.avgEngagement)}</b>avg engagement</span></div><div className="socialActions"><a href={profile?.profile?.profileUrl||selected.profileUrl} target="_blank" rel="noreferrer">Open TikTok ↗</a><button onClick={enrichTikTok} disabled={busy==="enrich"}>{busy==="enrich"?"Enriching…":"Enrich profile + contact"}</button><button className="save" onClick={saveTikTok} disabled={busy==="save"}>Save to Outreach</button></div>
     {profile&&<><article className="socialContact"><span>PUBLIC CONTACT</span><strong>{profile.contact?.bestContact?.email||"No published email found"}</strong><small>{profile.contact?.bestContact?.sourceUrl||"Bio links and public web were checked."}</small></article><div className="socialVideos">{(profile.recentVideos||selected.sampleVideos||[]).slice(0,6).map((v:any,i:number)=><a key={v.id||i} href={v.url} target="_blank" rel="noreferrer">{v.coverUrl?<img src={v.coverUrl} alt=""/>:<div/>}<strong>{String(v.description||"TikTok video").slice(0,80)}</strong></a>)}</div></>}
    </>:<div className="empty">Select a result.</div>}</section></div>
  </>}

  {section==="ads"&&<>
   <div className="socialSearch ad"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, problem, or niche"/><input className="country" value={country} onChange={e=>setCountry(e.target.value.toUpperCase().slice(0,3))}/><button onClick={runAds} disabled={busy==="ads"||query.trim().length<2}>{busy==="ads"?"Searching ads…":"Search active ads"}</button></div>
   <div className="advertiserGrid">{advertisers.length?advertisers.map((a:any)=><article className="advertiserCard" key={a.advertiser}><div><span>ADVERTISER</span><b>{a.signalScore}/100</b></div><h3>{a.advertiser}</h3><p>{a.adCount} ads found · {a.landingPages?.length||0} landing page{a.landingPages?.length===1?"":"s"}</p><div className="adSamples">{(a.sampleAds||[]).slice(0,3).map((ad:any)=><div key={ad.id}><strong>{ad.title||ad.body||"TikTok ad"}</strong><small>{ad.cta||"No CTA"} · {ad.estimatedAudience||"reach not published"}</small></div>)}</div><button onClick={()=>saveAdvertiser(a)} disabled={busy==="save"}>Save advertiser</button></article>):<div className="empty">Search the TikTok Ad Library to identify active advertisers and creative patterns.</div>}</div>
  </>}

  {section==="instagram"&&<>
   <div className="socialSearch"><input value={igHandle} onChange={e=>setIgHandle(e.target.value)} placeholder="@handle or Instagram profile URL"/><button onClick={runInstagram} disabled={busy==="instagram"||igHandle.trim().length<2}>{busy==="instagram"?"Reading Instagram…":"Enrich Instagram"}</button></div>
   {ig?.profile?<div className="instagramResult"><div className="socialProfileHero">{ig.profile.avatar?<img src={ig.profile.avatar} alt=""/>:<div>{ig.profile.displayName.slice(0,1)}</div>}<div><span>INSTAGRAM PROFILE</span><h3>{ig.profile.displayName}</h3><p>@{ig.profile.username}</p></div><b>{compact(ig.profile.followers)}</b></div><p className="socialBio">{ig.profile.bio||"No public bio."}</p><div className="socialStats"><span><b>{compact(ig.profile.followers)}</b>followers</span><span><b>{compact(ig.metrics?.avgViews)}</b>avg reel plays</span><span><b>{ig.profile.bioLinks?.length||0}</b>bio links</span></div><article className="socialContact"><span>PUBLIC CONTACT</span><strong>{ig.contact?.bestContact?.email||"No published email found"}</strong><small>{ig.contact?.bestContact?.sourceUrl||"Public bio links were checked."}</small></article><div className="socialActions"><a href={ig.profile.profileUrl} target="_blank" rel="noreferrer">Open Instagram ↗</a><button className="save" onClick={saveInstagram} disabled={busy==="save"}>Save to Outreach</button></div><div className="socialVideos">{(ig.reels||[]).slice(0,6).map((v:any,i:number)=><a href={v.url} target="_blank" rel="noreferrer" key={v.id||i}>{v.assets?.[0]?.url?<img src={v.assets[0].url} alt=""/>:<div/>}<strong>{String(v.caption||"Instagram reel").slice(0,80)}</strong><small>{compact(v.playCount)} plays</small></a>)}</div></div>:<div className="empty instagramEmpty">Paste a known Instagram handle found through TikTok, Airbnb, a website, or another source.</div>}
  </>}
 </section>;
}