"use client";

import "./research-library.css";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Item={id:string;kind:string;source?:string;title:string;summary?:string;url?:string;image_url?:string;score?:number;payload?:any;created_at?:string};
type Folder={id:string;name:string;niche?:string;description?:string;cover_image_url?:string;created_at?:string;updated_at?:string;ynot_growth_research_items?:Item[]};
type Props={products?:any[]};

function words(v:string){return String(v||"").toLowerCase().replace(/[^a-z0-9€$£ ]+/g," ").split(/\s+/).filter(x=>x.length>3)}
function topValues(values:string[],limit=6){const m=new Map<string,number>();values.filter(Boolean).forEach(v=>m.set(v,(m.get(v)||0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit)}
function normalizeList(j:any){const options=[j?.products,j?.results,j?.items,j?.data?.products,j?.data?.results,j?.data?.items,j?.data];return options.find(Array.isArray)||[]}
function pImage(p:any){return String(p?.image_url||p?.image||"")}
function pId(p:any,i=0){return String(p?.product_id||p?.id||`${p?.title||"product"}-${i}`)}
function adObject(item:Item){const p=item.payload||{};return{...p,id:p.id||item.id,title:p.title||item.title,headline:p.headline||item.title,body:p.body||item.summary||"",imageUrl:p.imageUrl||p.image_url||item.image_url||"",videoUrl:p.videoUrl||p.video_url||"",previewUrl:p.previewUrl||p.preview_url||item.image_url||"",platform:p.platform||item.source||"",advertiser:p.advertiser||p.pageName||""}}
function analyse(folder:Folder,products:any[]){
 const items=(folder.ynot_growth_research_items||[]).filter(x=>x.kind==="ad"||String(x.source||"").toLowerCase().includes("ads"));
 const payloads=items.map(x=>x.payload||{}),ctas=topValues(payloads.map(x=>String(x.cta||"")).filter(Boolean)),formats=topValues(payloads.map(x=>String(x.format||"")).filter(Boolean)),advertisers=topValues(payloads.map(x=>String(x.advertiser||"")).filter(Boolean));
 const corpus=payloads.map(x=>[x.headline,x.body,x.cta].filter(Boolean).join(" ")).join(" "),freq=new Map<string,number>();words(corpus).forEach(w=>freq.set(w,(freq.get(w)||0)+1));const keywords=[...freq.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10);
 const queryWords=new Set(words(`${folder.name} ${folder.niche||""} ${corpus}`));const matched=[...products].map(p=>({...p,_match:words(String(p.title||"")).filter(w=>queryWords.has(w)).length*20+Number(p.advertability_score||0)})).sort((a,b)=>b._match-a._match).slice(0,6);
 return{items,ctas,formats,advertisers,keywords,matched};
}

export default function ResearchLibrary({products=[]}:Props){
 const[folders,setFolders]=useState<Folder[]>([]),[selected,setSelected]=useState<Folder|null>(null),[busy,setBusy]=useState(true),[notice,setNotice]=useState(""),[showAnalysis,setShowAnalysis]=useState(false);
 const[sourceAd,setSourceAd]=useState<Item|null>(null),[sourceAnalysis,setSourceAnalysis]=useState<any>(null),[sourceBusy,setSourceBusy]=useState(false);
 const[productQuery,setProductQuery]=useState(""),[productCountry,setProductCountry]=useState("FR"),[productBusy,setProductBusy]=useState(false),[productResults,setProductResults]=useState<any[]>([]),[chosenProduct,setChosenProduct]=useState<any>(null);
 const[createBusy,setCreateBusy]=useState(false),[createProgress,setCreateProgress]=useState(""),[createResults,setCreateResults]=useState<any[]>([]),[creativePlan,setCreativePlan]=useState<any>(null);
 async function load(){setBusy(true);try{const r=await fetch("/api/admin/growth/research",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load research library");setFolders(j.folders||[])}catch(e){setNotice(e instanceof Error?e.message:"Could not load research library")}finally{setBusy(false)}}
 useEffect(()=>{load();const refresh=()=>load();window.addEventListener("ynot:research-saved",refresh);return()=>window.removeEventListener("ynot:research-saved",refresh)},[]);
 const count=useMemo(()=>folders.reduce((n,f)=>n+(f.ynot_growth_research_items?.length||0),0),[folders]);
 const analysis=useMemo(()=>selected?analyse(selected,products):null,[selected,products]);

 async function searchProducts(query?:string){const q=String(query??productQuery).trim();if(q.length<2)return;setProductBusy(true);setNotice("");setProductQuery(q);try{const params=new URLSearchParams({query:q,q,country:productCountry,source:"all",limit:"60"});const r=await fetch(`/api/catalog?${params.toString()}`,{cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||"Catalogue search failed");const list=normalizeList(j);setProductResults(list);if(!list.length)setNotice("No catalogue products matched this ad yet. Try a broader product search.")}catch(e){setNotice(e instanceof Error?e.message:"Catalogue search failed")}finally{setProductBusy(false)}}
 async function beginFromAd(item:Item){if(!selected||!analysis||sourceBusy)return;setSourceAd(item);setSourceBusy(true);setShowAnalysis(true);setSourceAnalysis(null);setCreativePlan(null);setCreateResults([]);setChosenProduct(null);setProductResults([]);setNotice("");setCreateProgress("Gemini is watching the ad media and reading its title/copy…");try{const ad=adObject(item);const r=await fetch("/api/admin/growth/create-from-ad",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"analyse-source",ad,contextAds:analysis.items.slice(0,10).map(adObject)})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gemini source analysis failed");setSourceAnalysis(j.sourceAnalysis);const seed=String(j.sourceAnalysis?.product_search_queries?.[0]||j.sourceAnalysis?.analysis?.product_type||j.sourceAnalysis?.analysis?.product_category||selected.niche||selected.name);setProductQuery(seed);setCreateProgress("Gemini finished the source analysis. Searching the live YNOT catalogue for matching products…");await searchProducts(seed);setCreateProgress("")}catch(e){setCreateProgress("");setNotice(e instanceof Error?e.message:"Could not analyse this ad")}finally{setSourceBusy(false)}}
 async function chooseProduct(product:any){if(!selected||!analysis||!sourceAd||!sourceAnalysis||createBusy)return;setChosenProduct(product);setCreateBusy(true);setCreateResults([]);setCreativePlan(null);setNotice("");setCreateProgress("Gemini is adapting the analysed ad strategy to this exact product…");try{const ad=adObject(sourceAd);const r=await fetch("/api/admin/growth/create-from-ad",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"analyse",ad,product,sourceAnalysis,contextAds:analysis.items.slice(0,12).map(adObject),folderId:selected.id})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Product adaptation failed");setCreativePlan(j.analysis);setCreateProgress("Gemini created 5 original directions. Ready to generate 20 image variants on Modal.")}catch(e){setCreateProgress("");setNotice(e instanceof Error?e.message:"Could not adapt the ad to this product")}finally{setCreateBusy(false)}}
 async function generateAll(){if(!selected||!sourceAd||!chosenProduct||!creativePlan||createBusy)return;setCreateBusy(true);setCreateResults([]);setNotice("");const directions=(creativePlan.directions||[]).slice(0,5),all:any[]=[];try{for(let i=0;i<directions.length;i++){setCreateProgress(`Modal GPU · direction ${i+1}/${directions.length} · generating 4 variants…`);const r=await fetch("/api/admin/growth/create-from-ad",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"generate",ad:adObject(sourceAd),product:chosenProduct,analysis:creativePlan,direction:directions[i],folderId:selected.id})}),j=await r.json();if(!r.ok)throw new Error(j.error||`Generation failed on direction ${i+1}`);all.push(...(j.variants||[]).map((v:any)=>({...v,direction:directions[i],creativeId:j.creative?.id||null})));setCreateResults([...all])}setCreateProgress(`Finished · ${all.length} variants generated and scored.`);setNotice(`Created ${all.length} original YNOT ad variants for ${chosenProduct.title}.`);window.dispatchEvent(new Event("ynot:research-saved"))}catch(e){setCreateProgress("");setNotice(e instanceof Error?e.message:"Could not generate variants")}finally{setCreateBusy(false)}}

 return <section className="researchLibrary" id="research-library">
  <div className="researchLibraryTop"><div><span>RESEARCH LIBRARY</span><h2>Saved intelligence folders</h2><p>Choose a saved ad. Gemini analyses its actual image/video and copy first, then YNOT searches the live catalogue for products to adapt the strategy to.</p></div><div className="researchLibraryStats"><b>{folders.length} folders</b><b>{count} saved items</b></div></div>
  {notice&&<div className="researchLibraryNotice">{notice}</div>}
  <div className="researchFolderGrid">{busy?<div className="researchEmpty">Loading folders…</div>:folders.length?folders.map(f=>{const items=f.ynot_growth_research_items||[],imgs=[f.cover_image_url,...items.map(x=>x.image_url)].filter(Boolean).slice(0,4) as string[];return <button className="researchFolder" key={f.id} onClick={()=>{setSelected(f);setShowAnalysis(false);setSourceAd(null);setSourceAnalysis(null);setCreativePlan(null);setCreateResults([]);setProductResults([]);setChosenProduct(null);setCreateProgress("")}}><div className="folderPreview">{imgs.length?imgs.map((src,i)=><img src={src} alt="" key={src+i}/>):<div className="folderGlyph">Y</div>}</div><div className="folderMeta"><span>{f.niche||"Research"}</span><h3>{f.name}</h3><p>{f.description||"Saved Growth intelligence and examples."}</p><footer><b>{items.length} items</b><em>Open folder →</em></footer></div></button>}):<div className="researchEmpty">Nothing saved yet. Run an ad search and save it to a folder.</div>}</div>
  {selected&&<div className="researchModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="researchModal"><button className="researchClose" onClick={()=>setSelected(null)}>×</button><header><span>RESEARCH FOLDER</span><h2>{selected.name}</h2><p>{selected.description||selected.niche||"Saved YNOT Growth intelligence."}</p><div><b>{selected.ynot_growth_research_items?.length||0} items</b>{analysis?.items.length?<button className="researchAnalyse" onClick={()=>setShowAnalysis(v=>!v)}>{showAnalysis?"Hide workflow":"Analyse folder"}</button>:null}</div></header>
   {showAnalysis&&analysis&&<section className="researchAnalysis">
    <div className="researchAnalysisHead"><div><span>CREATE FROM AD</span><h3>{sourceAd?sourceAd.title:"Select an ad below to start with Gemini"}</h3></div><b>{analysis.items.length} ads available</b></div>
    {sourceBusy&&<div className="creativeJobProgress"><i/><span>{createProgress}</span></div>}
    {sourceAnalysis&&<div className="sourceAnalysisCard"><div><span>STEP 1 · GEMINI SOURCE ANALYSIS</span><strong>{sourceAnalysis.summary||sourceAnalysis.analysis?.marketing_structure?.hook||"Ad analysed"}</strong><p>{sourceAnalysis.analysis?.niche} {sourceAnalysis.analysis?.product_type?`· ${sourceAnalysis.analysis.product_type}`:""}</p></div><div className="creativeDirectionPills">{(sourceAnalysis.product_search_queries||[]).map((q:string)=><button key={q} onClick={()=>void searchProducts(q)}>{q}</button>)}</div></div>}
    {sourceAnalysis&&<div className="productSearchStage"><div className="researchAnalysisHead"><div><span>STEP 2 · LIVE PRODUCT SEARCH</span><h3>Choose what YNOT should create the ad for</h3></div><small>Searches the full live catalogue, not only pre-scored products</small></div><form onSubmit={(e:FormEvent)=>{e.preventDefault();void searchProducts()}}><input value={productQuery} onChange={e=>setProductQuery(e.target.value)} placeholder="Search YNOT catalogue…"/><input className="country" value={productCountry} onChange={e=>setProductCountry(e.target.value.toUpperCase().slice(0,3))}/><button disabled={productBusy}>{productBusy?"Searching…":"Search products"}</button></form><div className="createProductGrid">{productResults.slice(0,18).map((p:any,i:number)=><article key={pId(p,i)} className={chosenProduct&&pId(chosenProduct)===pId(p)?"chosen":""}>{pImage(p)?<img src={pImage(p)} alt=""/>:<div className="researchItemPlaceholder">Y</div>}<div><strong>{p.title||"Untitled product"}</strong><small>{p.brand||p.source||"YNOT catalogue"} · {p.currency||""} {p.price??p.supplierPrice??"—"}</small></div><button disabled={createBusy} onClick={()=>void chooseProduct(p)}>{chosenProduct&&pId(chosenProduct)===pId(p)?"Selected":"Use product"}</button></article>)}</div></div>}
    {creativePlan&&<div className="creativePlan"><div><span>STEP 3 · GEMINI PRODUCT ADAPTATION</span><strong>{creativePlan.adaptation?.adapted_angle||"Original YNOT adaptation"}</strong><p>{creativePlan.adaptation?.reason_for_match}</p></div><div className="creativeDirectionPills">{(creativePlan.directions||[]).map((d:any)=><b key={d.direction_id}>{d.name}</b>)}</div><button className="generateAllBtn" disabled={createBusy} onClick={()=>void generateAll()}>{createBusy?"Generating…":"Generate 20 variants"}</button></div>}
    {createProgress&&!sourceBusy&&<div className="creativeJobProgress"><i/><span>{createProgress}</span></div>}
    {createResults.length>0&&<div className="generatedVariantGrid">{[...createResults].sort((a,b)=>Number(b.score?.overall||0)-Number(a.score?.overall||0)).map((v:any,i)=><article key={`${v.directionId}-${v.variantIndex}-${i}`}><img src={v.url} alt="Generated YNOT ad variant"/><div><strong>{v.direction?.name||v.directionId}</strong><span>Variant {v.variantIndex}{v.score?.overall!=null?` · ${Math.round(Number(v.score.overall))}/100`:""}</span>{v.score?.summary&&<small>{v.score.summary}</small>}</div></article>)}</div>}
   </section>}
   <div className="researchItemGrid">{(selected.ynot_growth_research_items||[]).map(item=><article key={item.id} className={sourceAd?.id===item.id?"sourceAdSelected":""}>{item.image_url?<img src={item.image_url} alt=""/>:<div className="researchItemPlaceholder">Y</div>}<div><span>{item.source||item.kind}</span><h3>{item.title}</h3>{item.summary&&<p>{item.summary}</p>}<footer>{item.score!=null&&<b>Score {Math.round(Number(item.score))}</b>}{item.kind==="ad"?<button className="createFromAd" disabled={sourceBusy} onClick={()=>void beginFromAd(item)}>{sourceAd?.id===item.id&&sourceBusy?"Gemini analysing…":sourceAd?.id===item.id?"Analysed source":"Create from this ad"}</button>:item.url?<a href={item.url} target="_blank" rel="noreferrer">Source ↗</a>:<em>{item.kind}</em>}</footer></div></article>)}</div>
  </section></div>}
 </section>
}
