"use client";

import "./research-library.css";
import "./research-product-source.css";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Item={id:string;kind:string;source?:string;title:string;summary?:string;url?:string;image_url?:string;score?:number;payload?:any;created_at?:string};
type Folder={id:string;name:string;niche?:string;description?:string;cover_image_url?:string;ynot_growth_research_items?:Item[]};
type Props={products?:any[]};
type ProductSource="supplier"|"etsy";

const MAJOR_BRANDS=["la roche-posay","la roche posay","cerave","avene","avène","vichy","bioderma","eucerin","l'oreal","l’oréal","loreal","maybelline","garnier","clinique","estee lauder","estée lauder","the ordinary","kiehl","neutrogena","olaplex","nike","adidas","puma","new balance","under armour","apple","samsung","sony","dyson"];
function normalizeList(j:any){const xs=[j?.products,j?.results,j?.items,j?.data?.products,j?.data?.results,j?.data?.items,j?.data];return xs.find(Array.isArray)||[]}
function pImage(p:any){return String(p?.image_url||p?.image||"")}
function pId(p:any,i=0){return String(p?.product_id||p?.id||`${p?.title||"product"}-${i}`)}
function mediaPlatform(v:string){const p=String(v||"").toLowerCase();return p.includes("meta")||p.includes("facebook")||p.includes("instagram")?"meta":p.includes("tiktok")?"tiktok":p.includes("google")?"google":p.includes("linkedin")?"linkedin":""}
function assetUrl(x:any){return String(x?.url||x?.downloadUrl||x?.download_url||"")}
function assetKind(x:any){const k=String(x?.kind||"").toLowerCase(),ct=String(x?.contentType||x?.content_type||"").toLowerCase();if(k.includes("video")||ct.startsWith("video/"))return"video";return"image"}
function proxied(platform:string,url:string){if(!url)return"";const p=mediaPlatform(platform);return p?`/api/admin/growth/ad-media?platform=${encodeURIComponent(p)}&url=${encodeURIComponent(url)}`:url}
function displayAssetUrl(platform:string,a:any){const u=assetUrl(a);return a?.passthrough?u:proxied(platform,u)}
function fallbackAssets(ad:any){const a:any[]=[];if(ad?.videoUrl)a.push({kind:"video",url:ad.videoUrl,passthrough:true,label:"saved video"});if(ad?.imageUrl)a.push({kind:"image",url:ad.imageUrl,passthrough:true,label:"saved image"});if(ad?.previewUrl&&ad.previewUrl!==ad.imageUrl)a.push({kind:"image",url:ad.previewUrl,passthrough:true,label:"saved preview"});const seen=new Set<string>();return a.filter(x=>{const u=assetUrl(x);if(!u||seen.has(u))return false;seen.add(u);return true})}
function adObject(item:Item){const p=item.payload||{};return{...p,id:p.id||item.id,title:p.title||item.title,headline:p.headline||item.title,body:p.body||item.summary||"",imageUrl:p.imageUrl||p.image_url||item.image_url||"",videoUrl:p.videoUrl||p.video_url||"",previewUrl:p.previewUrl||p.preview_url||item.image_url||"",platform:p.platform||item.source||"",advertiser:p.advertiser||p.pageName||"",assets:Array.isArray(p.assets)?p.assets:[]}}
function isMajorBrand(p:any){const s=`${p?.brand||""} ${p?.title||""}`.toLowerCase();return MAJOR_BRANDS.some(x=>s.includes(x))}
function supplierScore(p:any){let s=0;const src=String(p?.source||p?.marketplace||"").toLowerCase();if(p?.supplierPrice!=null)s+=30;if(Number(p?.supplierOfferCount||0)>0)s+=25;if(Array.isArray(p?.supplierOffers)&&p.supplierOffers.length)s+=20;if(/aliexpress|cj|dsers|supplier|dropship|temu|wholesale|1688/.test(src))s+=35;if(p?.url)s+=5;if(pImage(p))s+=5;if(isMajorBrand(p))s-=100;return s}
function supplierReady(list:any[]){const filtered=list.filter(p=>!isMajorBrand(p));return filtered.sort((a,b)=>supplierScore(b)-supplierScore(a))}

export default function ResearchLibrary({products=[]}:Props){
 const[folders,setFolders]=useState<Folder[]>([]),[selected,setSelected]=useState<Folder|null>(null),[busy,setBusy]=useState(true),[notice,setNotice]=useState("");
 const[sourceAd,setSourceAd]=useState<Item|null>(null),[resolvedAd,setResolvedAd]=useState<any>(null),[activeAsset,setActiveAsset]=useState<any>(null),[sourceBusy,setSourceBusy]=useState(false),[sourceAnalysis,setSourceAnalysis]=useState<any>(null),[mediaResolveError,setMediaResolveError]=useState("");
 const[productQuery,setProductQuery]=useState(""),[productCountry,setProductCountry]=useState("FR"),[productBusy,setProductBusy]=useState(false),[productResults,setProductResults]=useState<any[]>([]),[chosenProduct,setChosenProduct]=useState<any>(null),[productPage,setProductPage]=useState(1),[productSource,setProductSource]=useState<ProductSource>("supplier"),[etsyHasNext,setEtsyHasNext]=useState(false);
 const[createBusy,setCreateBusy]=useState(false),[createProgress,setCreateProgress]=useState(""),[creativePlan,setCreativePlan]=useState<any>(null),[createResults,setCreateResults]=useState<any[]>([]);

 async function load(){setBusy(true);try{const r=await fetch("/api/admin/growth/research",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load research library");setFolders(j.folders||[])}catch(e){setNotice(e instanceof Error?e.message:"Could not load research library")}finally{setBusy(false)}}
 useEffect(()=>{load();const f=()=>load();window.addEventListener("ynot:research-saved",f);return()=>window.removeEventListener("ynot:research-saved",f)},[]);
 const count=useMemo(()=>folders.reduce((n,f)=>n+(f.ynot_growth_research_items?.length||0),0),[folders]);
 const ads=useMemo(()=>selected?(selected.ynot_growth_research_items||[]).filter(x=>x.kind==="ad"||String(x.source||"").toLowerCase().includes("ads")):[],[selected]);
 const pageSize=18;
 const supplierPageCount=Math.max(1,Math.ceil(productResults.length/pageSize));
 const displayedProducts=productSource==="etsy"?productResults:productResults.slice((productPage-1)*pageSize,productPage*pageSize);

 async function resolveAd(item:Item){
  const ad=adObject(item),platform=mediaPlatform(ad.platform);let assets=[...(Array.isArray(ad.assets)?ad.assets:[]),...fallbackAssets(ad)];setMediaResolveError("");
  if(platform){try{const r=await fetch("/api/admin/growth/intelligence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"ad_media",platform,ad:ad.mediaRef||ad.adLibraryUrl||ad.rawId||ad.id,advertiser:ad.advertiserId||ad.advertiser||"",country:productCountry})}),j=await r.json().catch(()=>({}));if(r.ok&&Array.isArray(j.assets)&&j.assets.length)assets=[...j.assets,...fallbackAssets(ad)];else setMediaResolveError(String(j?.error||j?.message||"Full media resolver failed; using saved media fallback."))}catch(e){setMediaResolveError(e instanceof Error?e.message:"Full media resolver failed; using saved media fallback.")}}
  const seen=new Set<string>();assets=assets.filter(a=>{const u=assetUrl(a);if(!u||seen.has(u))return false;seen.add(u);return true});
  const merged={...ad,assets};setResolvedAd(merged);const first=assets[0]||null;setActiveAsset(first);return merged;
 }
 async function selectAd(item:Item){setSourceAd(item);setResolvedAd(null);setSourceAnalysis(null);setChosenProduct(null);setCreativePlan(null);setCreateResults([]);setProductResults([]);setProductQuery("");setNotice("");setCreateProgress("");setProductPage(1);setMediaResolveError("");setSourceBusy(true);try{await resolveAd(item)}finally{setSourceBusy(false)}}

 async function searchProducts(q0?:string,source:ProductSource=productSource,page=1){const q=String(q0??productQuery).trim();if(q.length<2)return;setProductBusy(true);setProductQuery(q);setProductSource(source);setProductPage(page);setNotice("");try{if(source==="etsy"){const r=await fetch(`/api/admin/growth/etsy-search?q=${encodeURIComponent(q)}&page=${page}`,{cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||"Etsy search failed");const list=normalizeList(j);setProductResults(list);setEtsyHasNext(Boolean(j?.hasNextPage));if(!list.length)setNotice("Etsy returned no products for this search.")}else{const params=new URLSearchParams({query:q,q,country:productCountry,source:"all",limit:"120"});const r=await fetch(`/api/catalog?${params}`,{cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||"Catalogue search failed");const list=supplierReady(normalizeList(j));setProductResults(list);setEtsyHasNext(false);if(!list.length)setNotice("No supplier-ready catalogue products matched. Try another Gemini suggestion or Etsy.")}}catch(e){setNotice(e instanceof Error?e.message:"Product discovery failed")}finally{setProductBusy(false)}}

 async function analyseSource(){if(!sourceAd||sourceBusy)return;setSourceBusy(true);setSourceAnalysis(null);setCreativePlan(null);setCreateResults([]);setNotice("");setCreateProgress("Resolving every available image/video before Gemini analysis…");try{const ad=resolvedAd||await resolveAd(sourceAd);if(!(ad.assets||[]).length)throw new Error("No ad media could be loaded from this saved item. Re-save the ad after opening its media, or choose another ad.");setCreateProgress("Gemini is analysing the full ad media, title, copy, CTA and context…");const r=await fetch("/api/admin/growth/create-from-ad",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"analyse-source",ad,contextAds:ads.slice(0,10).map(adObject)})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gemini source analysis failed");setSourceAnalysis(j.sourceAnalysis);const queries=(j.sourceAnalysis?.product_search_queries||[]).filter(Boolean);const seed=String(queries[0]||j.sourceAnalysis?.analysis?.product_type||j.sourceAnalysis?.analysis?.product_category||selected?.niche||selected?.name||"");setCreateProgress(`Gemini analysed ${j.sourceAnalysis?.media_inputs||0} media asset(s). Searching supplier-ready catalogue products…`);if(seed)await searchProducts(seed,"supplier",1);setCreateProgress("")}catch(e){setCreateProgress("");setNotice(e instanceof Error?e.message:"Could not analyse this ad")}finally{setSourceBusy(false)}}

 async function chooseProduct(product:any){if(!sourceAd||!sourceAnalysis||createBusy)return;setChosenProduct(product);setCreateBusy(true);setCreativePlan(null);setCreateResults([]);setNotice("");setCreateProgress("Gemini is adapting the analysed strategy to this exact product…");try{const r=await fetch("/api/admin/growth/create-from-ad",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"analyse",ad:resolvedAd||adObject(sourceAd),product,sourceAnalysis,contextAds:ads.slice(0,12).map(adObject),folderId:selected?.id})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Product adaptation failed");setCreativePlan(j.analysis);setCreateProgress("5 original directions are ready. Generate 10 variants when you want.")}catch(e){setCreateProgress("");setNotice(e instanceof Error?e.message:"Could not adapt this ad")}finally{setCreateBusy(false)}}
 async function generateAll(){if(!sourceAd||!chosenProduct||!creativePlan||createBusy)return;setCreateBusy(true);setCreateResults([]);setNotice("");const directions=(creativePlan.directions||[]).slice(0,5),all:any[]=[];try{for(let i=0;i<directions.length;i++){setCreateProgress(`Nano Banana 2 Lite · direction ${i+1}/${directions.length} · 2 variants…`);const r=await fetch("/api/admin/growth/create-from-ad",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"generate",ad:resolvedAd||adObject(sourceAd),product:chosenProduct,analysis:creativePlan,direction:directions[i],folderId:selected?.id})}),j=await r.json();if(!r.ok)throw new Error(j.error||`Generation failed on direction ${i+1}`);all.push(...(j.variants||[]).map((v:any)=>({...v,direction:directions[i]})));setCreateResults([...all])}setCreateProgress(`Finished · ${all.length} generated and scored.`);window.dispatchEvent(new Event("ynot:research-saved"))}catch(e){setCreateProgress("");setNotice(e instanceof Error?e.message:"Generation failed")}finally{setCreateBusy(false)}}

 const fullAssets=resolvedAd?.assets||[];
 const activeUrl=activeAsset?displayAssetUrl(resolvedAd?.platform,activeAsset):resolvedAd?.videoUrl||resolvedAd?.imageUrl||resolvedAd?.previewUrl||"";
 const activeKind=activeAsset?assetKind(activeAsset):(resolvedAd?.videoUrl?"video":"image");

 return <section className="researchLibrary" id="research-library">
  <div className="researchLibraryTop"><div><span>RESEARCH LIBRARY</span><h2>Saved intelligence folders</h2><p>Select an ad, inspect the complete creative, analyse all media with Gemini, match supplier-ready products or Etsy listings, then generate original variants.</p></div><div className="researchLibraryStats"><b>{folders.length} folders</b><b>{count} saved items</b></div></div>
  {notice&&<div className="researchLibraryNotice">{notice}</div>}
  <div className="researchFolderGrid">{busy?<div className="researchEmpty">Loading folders…</div>:folders.length?folders.map(f=>{const items=f.ynot_growth_research_items||[],imgs=[f.cover_image_url,...items.map(x=>x.image_url)].filter(Boolean).slice(0,4) as string[];return <button className="researchFolder" key={f.id} onClick={()=>{setSelected(f);setSourceAd(null);setResolvedAd(null);setSourceAnalysis(null);setProductResults([]);setChosenProduct(null);setCreativePlan(null);setCreateResults([]);setNotice("");setProductPage(1);setMediaResolveError("")}}><div className="folderPreview">{imgs.length?imgs.map((src,i)=><img src={src} alt="" key={src+i}/>):<div className="folderGlyph">Y</div>}</div><div className="folderMeta"><span>{f.niche||"Research"}</span><h3>{f.name}</h3><p>{f.description||"Saved Growth intelligence."}</p><footer><b>{items.length} items</b><em>Open →</em></footer></div></button>}):<div className="researchEmpty">No saved folders yet.</div>}</div>

  {selected&&<div className="researchModalBackdrop"><section className="researchModal researchWorkflow"><button className="researchClose" onClick={()=>setSelected(null)}>×</button>
   <header><span>CREATE FROM AD</span><h2>{selected.name}</h2><p>1 Select ad · 2 Inspect full creative · 3 Gemini analysis · 4 Product match · 5 Adapt · 6 Generate variants</p></header>
   <div className="workflowSteps"><b className={sourceAd?"done":"active"}>1 Select ad</b><b className={resolvedAd?"done":""}>2 Full creative</b><b className={sourceAnalysis?"done":""}>3 Gemini analysis</b><b className={productResults.length?"done":""}>4 Catalogue match</b><b className={creativePlan?"done":""}>5 Adapt</b><b className={createResults.length?"done":""}>6 Generate</b></div>

   {!sourceAd&&<section className="adChooser"><div className="researchAnalysisHead"><div><span>STEP 1</span><h3>Choose one ad to build from</h3></div><small>{ads.length} ads</small></div><div className="adChooserGrid">{ads.map(item=>{const a=adObject(item);return <button key={item.id} onClick={()=>void selectAd(item)}><div className="adChooserMedia">{a.videoUrl?<video src={a.videoUrl} muted playsInline preload="metadata"/>:item.image_url?<img src={item.image_url} alt=""/>:<span>Y</span>}</div><strong>{a.advertiser||item.title}</strong><p>{a.headline||a.body||item.summary||""}</p><em>{a.platform||item.source}</em></button>})}</div></section>}

   {sourceAd&&<>
    <section className="fullAdWorkspace"><div className="fullAdMedia"><div className="fullAdStage">{sourceBusy&&!resolvedAd?<div className="mediaResolving">Resolving full ad media…</div>:activeUrl?(activeKind==="video"?<video key={activeUrl} src={activeUrl} controls autoPlay muted playsInline preload="auto"/>:<img src={activeUrl} alt="Source ad creative"/>):<div className="mediaResolving">No playable media returned yet.</div>}</div>{fullAssets.length>0&&<div className="fullAdThumbs">{fullAssets.map((a:any,i:number)=>{const u=displayAssetUrl(resolvedAd?.platform,a);return <button key={assetUrl(a)+i} className={activeAsset===a?"active":""} onClick={()=>setActiveAsset(a)}>{assetKind(a)==="video"?<video src={u} muted playsInline preload="metadata"/>:<img src={u} alt=""/>}<span>{assetKind(a)}</span></button>})}</div>}{mediaResolveError&&<div className="mediaFallbackNote">Resolver issue: {mediaResolveError}. Saved media fallback remains available.</div>}</div>
     <aside className="fullAdContext"><span>FULL AD CONTEXT</span><h3>{resolvedAd?.advertiser||sourceAd.title}</h3><strong>{resolvedAd?.headline||resolvedAd?.title||sourceAd.title}</strong><p>{resolvedAd?.body||sourceAd.summary||"No body copy returned."}</p><dl><div><dt>CTA</dt><dd>{resolvedAd?.cta||"—"}</dd></div><div><dt>Platform</dt><dd>{resolvedAd?.platform||sourceAd.source||"—"}</dd></div><div><dt>Format</dt><dd>{resolvedAd?.format||"—"}</dd></div><div><dt>Media</dt><dd>{fullAssets.length||((resolvedAd?.imageUrl||resolvedAd?.videoUrl)?1:0)} asset(s)</dd></div></dl><button className="analyseSourceBtn" disabled={sourceBusy} onClick={()=>void analyseSource()}>{sourceBusy?"Gemini analysing…":"Analyse complete ad with Gemini"}</button><button className="changeAdBtn" onClick={()=>{setSourceAd(null);setResolvedAd(null);setSourceAnalysis(null);setProductResults([]);setChosenProduct(null);setCreativePlan(null);setMediaResolveError("")}}>Choose another ad</button></aside>
    </section>

    {(sourceBusy||createProgress)&&<div className="creativeJobProgress"><i/><span>{createProgress||"Working…"}</span></div>}

    {sourceAnalysis&&<section className="sourceAnalysisExpanded"><div className="researchAnalysisHead"><div><span>STEP 3 · {String(sourceAnalysis.model||"GEMINI").toUpperCase()}</span><h3>{sourceAnalysis.summary||"Complete ad analysis"}</h3></div><b>{sourceAnalysis.media_inputs||0} media inputs analysed</b></div><div className="analysisFacts"><div><span>Hook</span><strong>{sourceAnalysis.analysis?.marketing_structure?.hook||"—"}</strong></div><div><span>Promise</span><strong>{sourceAnalysis.analysis?.marketing_structure?.promise||"—"}</strong></div><div><span>Visual style</span><strong>{sourceAnalysis.analysis?.style?.visual_style||"—"}</strong></div><div><span>Camera / motion</span><strong>{sourceAnalysis.analysis?.style?.camera_or_motion||"—"}</strong></div><div><span>Audience</span><strong>{sourceAnalysis.analysis?.audience?.segment||"—"}</strong></div><div><span>Product type</span><strong>{sourceAnalysis.analysis?.product_type||sourceAnalysis.analysis?.product_category||"—"}</strong></div></div><div className="creativeDirectionPills">{(sourceAnalysis.product_search_queries||[]).map((q:string)=><button key={q} onClick={()=>void searchProducts(q,"supplier",1)}>{q}</button>)}</div></section>}

    {sourceAnalysis&&<section className="productSearchStage"><div className="researchAnalysisHead"><div><span>STEP 4 · PRODUCT SOURCING</span><h3>Choose from supplier-ready products or Etsy</h3></div><small>Major retail brands are filtered out of supplier results</small></div><form onSubmit={(e:FormEvent)=>{e.preventDefault();void searchProducts(productQuery,productSource,1)}}><input value={productQuery} onChange={e=>setProductQuery(e.target.value)} placeholder="Search products…"/><input className="country" value={productCountry} onChange={e=>setProductCountry(e.target.value.toUpperCase().slice(0,3))}/><button disabled={productBusy}>{productBusy?"Searching…":productSource==="etsy"?"Search Etsy":"Search suppliers"}</button><button type="button" className={productSource==="etsy"?"etsySource active":"etsySource"} disabled={productBusy} onClick={()=>void searchProducts(productQuery||sourceAnalysis?.product_search_queries?.[0]||"", "etsy",1)}>Etsy</button><button type="button" className={productSource==="supplier"?"supplierSource active":"supplierSource"} disabled={productBusy} onClick={()=>void searchProducts(productQuery||sourceAnalysis?.product_search_queries?.[0]||"", "supplier",1)}>Supplier catalogue</button></form><div className="productSourceMeta"><b>{productSource==="etsy"?"Etsy catalogue":"Supplier-ready catalogue"}</b><span>{productSource==="etsy"?`Page ${productPage}`:`Page ${productPage} of ${supplierPageCount}`} · {productResults.length} results</span></div><div className="createProductGrid">{displayedProducts.map((p:any,i:number)=><article key={pId(p,i)} className={chosenProduct&&pId(chosenProduct)===pId(p)?"chosen":""}>{pImage(p)?<img src={pImage(p)} alt=""/>:<div className="researchItemPlaceholder">Y</div>}<div><strong>{p.title||"Untitled product"}</strong><small>{p.brand||p.source||"YNOT"} · {p.currency||""} {p.price??p.supplierPrice??"—"}</small>{productSource==="supplier"&&<em className="supplierReady">supplier-ready</em>}{p.etsy&&<em className="etsyReady">Etsy</em>}</div><button disabled={createBusy} onClick={()=>void chooseProduct(p)}>{chosenProduct&&pId(chosenProduct)===pId(p)?"Selected":"Use product"}</button></article>)}</div><div className="productPager"><button disabled={productBusy||productPage<=1} onClick={()=>{if(productSource==="etsy")void searchProducts(productQuery,"etsy",productPage-1);else setProductPage(p=>Math.max(1,p-1))}}>← Previous</button><span>Page {productPage}</span><button disabled={productBusy||(productSource==="etsy"?!etsyHasNext:productPage>=supplierPageCount)} onClick={()=>{if(productSource==="etsy")void searchProducts(productQuery,"etsy",productPage+1);else setProductPage(p=>Math.min(supplierPageCount,p+1))}}>Next →</button></div></section>}

    {creativePlan&&<section className="creativePlanExpanded"><div className="researchAnalysisHead"><div><span>STEP 5 · PRODUCT ADAPTATION</span><h3>{creativePlan.adaptation?.adapted_angle||"5 original creative directions"}</h3></div><button className="generateAllBtn" disabled={createBusy} onClick={()=>void generateAll()}>{createBusy?"Generating…":"Generate all 10"}</button></div><p>{creativePlan.adaptation?.reason_for_match}</p><div className="directionCards">{(creativePlan.directions||[]).map((d:any)=><article key={d.direction_id}><span>{d.direction_id}</span><strong>{d.name}</strong><p>{d.hook}</p><small>{d.layout_concept}</small></article>)}</div></section>}

    {createResults.length>0&&<section className="generatedStage"><div className="researchAnalysisHead"><div><span>STEP 6 · GENERATED VARIANTS</span><h3>{createResults.length} assets</h3></div><b>Gemini scored</b></div><div className="generatedVariantGrid">{[...createResults].sort((a,b)=>Number(b.score?.overall||0)-Number(a.score?.overall||0)).map((v:any,i)=><article key={`${v.directionId}-${v.variantIndex}-${i}`}><img src={v.url} alt="Generated YNOT ad"/><div><strong>{v.direction?.name||v.directionId}</strong><span>Variant {v.variantIndex}{v.score?.overall!=null?` · ${Math.round(Number(v.score.overall))}/100`:""}</span>{v.score?.summary&&<small>{v.score.summary}</small>}</div></article>)}</div></section>}
   </>}
  </section></div>}
 </section>
}
