import {NextRequest,NextResponse} from "next/server";
import type Stripe from "stripe";
import {releaseCredit} from "@/lib/circle/server";
import {operatorAuthorized,releaseExpiredAuthorization,stripeClient} from "@/lib/commerce/stripe";

export const runtime="nodejs";
const unauthorized=()=>NextResponse.json({error:"OWNER_AUTH_REQUIRED"},{status:401,headers:{"WWW-Authenticate":"Bearer"}});
function view(session:Stripe.Checkout.Session,paymentIntent:Stripe.PaymentIntent|null){const shipping=session.collected_information?.shipping_details;return{id:session.id,created:session.created*1000,status:paymentIntent?.status||"unknown",orderStatus:session.metadata?.orderStatus||"pending",amount:(session.amount_total||0)/100,currency:String(session.currency||"eur").toUpperCase(),product:{id:session.metadata?.productId,title:session.metadata?.productTitle,variantId:session.metadata?.variantId||null,quantity:Number(session.metadata?.quantity||1),url:session.metadata?.supplierUrl,expectedSupplierPrice:Number(session.metadata?.supplierPrice||0),ynotPrice:Number(session.metadata?.ynotPrice||0)},customer:{name:shipping?.name||session.customer_details?.name||null,email:session.customer_details?.email||null,phone:session.customer_details?.phone||null,address:shipping?.address||session.customer_details?.address||null},merchantOrderId:session.metadata?.merchantOrderId||null,actualSupplierTotal:session.metadata?.actualSupplierTotal?Number(session.metadata.actualSupplierTotal):null}}

export async function GET(req:NextRequest){if(!operatorAuthorized(req.headers.get("authorization")))return unauthorized();try{const stripe=stripeClient(),sessions=await stripe.checkout.sessions.list({status:"complete",limit:50,expand:["data.payment_intent"]}),orders=[];for(const session of sessions.data){if(session.metadata?.ynotFlow!=="manual_procurement")continue;let paymentIntent=typeof session.payment_intent==="string"?await stripe.paymentIntents.retrieve(session.payment_intent):session.payment_intent;paymentIntent=await releaseExpiredAuthorization(stripe,session);orders.push(view(await stripe.checkout.sessions.retrieve(session.id),paymentIntent||null))}return NextResponse.json({orders})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load orders"},{status:400})}}

export async function POST(req:NextRequest){if(!operatorAuthorized(req.headers.get("authorization")))return unauthorized();try{const {sessionId,action,merchantOrderId,actualSupplierTotal}=await req.json();if(!/^cs_(test_|live_)?[A-Za-z0-9_]+$/.test(String(sessionId)))throw new Error("INVALID_SESSION");const stripe=stripeClient(),session=await stripe.checkout.sessions.retrieve(String(sessionId),{expand:["payment_intent"]});if(session.metadata?.ynotFlow!=="manual_procurement")throw new Error("UNKNOWN_ORDER");let paymentIntent=typeof session.payment_intent==="string"?await stripe.paymentIntents.retrieve(session.payment_intent):session.payment_intent;if(!paymentIntent)throw new Error("PAYMENT_NOT_FOUND");paymentIntent=await releaseExpiredAuthorization(stripe,session)||paymentIntent;
 if(action==="cancel"){if(paymentIntent.status!=="requires_capture")throw new Error(`PAYMENT_${paymentIntent.status.toUpperCase()}`);await stripe.paymentIntents.cancel(paymentIntent.id,{cancellation_reason:"requested_by_customer"},{idempotencyKey:`ynot-release-${session.id}`});await stripe.checkout.sessions.update(session.id,{metadata:{...session.metadata,orderStatus:"authorization_released",releasedAt:String(Date.now()),releaseReason:"operator_declined"}});if(session.metadata?.checkoutRef)try{await releaseCredit(session.metadata.checkoutRef)}catch(error){console.error("YNOT credit release requires intervention",session.id,error)}return NextResponse.json({ok:true,status:"released"})}
 if(action!=="capture")throw new Error("INVALID_ACTION");const orderId=String(merchantOrderId||"").trim().slice(0,120),supplierTotal=Number(actualSupplierTotal);if(!orderId)throw new Error("MERCHANT_ORDER_ID_REQUIRED");if(!Number.isFinite(supplierTotal)||supplierTotal<=0)throw new Error("ACTUAL_SUPPLIER_TOTAL_REQUIRED");if(paymentIntent.status!=="requires_capture")throw new Error(`PAYMENT_${paymentIntent.status.toUpperCase()}`);const authorized=(paymentIntent.amount_capturable||paymentIntent.amount)/100,minMargin=Number(process.env.YNOT_MIN_REALIZED_MARGIN_EUR||0);if(authorized-supplierTotal<minMargin)throw new Error("ORDER_BELOW_MARGIN_FLOOR");const metadata={...paymentIntent.metadata,orderStatus:"captured",merchantOrderId:orderId,actualSupplierTotal:String(Math.round(supplierTotal*100)/100),capturedAt:String(Date.now())};await stripe.paymentIntents.update(paymentIntent.id,{metadata});await stripe.paymentIntents.capture(paymentIntent.id,{}, {idempotencyKey:`ynot-capture-${session.id}`});await stripe.checkout.sessions.update(session.id,{metadata:{...session.metadata,...metadata}});return NextResponse.json({ok:true,status:"confirmed"});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to update order"},{status:400})}}
