import {NextRequest,NextResponse} from "next/server";
import {requireYnotAdmin,adminDb,adminErrorStatus} from "@/lib/ynot/admin-server";
import {enrichHostContact} from "@/lib/intelligence/fetchlayer-contacts";
export const runtime="nodejs";
export async function POST(req:NextRequest){
 try{const admin=await requireYnotAdmin(req);const b=await req.json();const platform=String(b.platform||"").toLowerCase(),kind=String(b.kind||"social_prospect"),handle=String(b.handle||"").replace(/^@/,"").trim(),name=String(b.display_name||b.displayName||handle||"Prospect").trim();if(!platform||(!handle&&!name))return NextResponse.json({error:"PROSPECT_REQUIRED"},{status:400});
 let contact=b.contact||null;if(!contact?.email&&Array.isArray(b.known_targets)&&b.known_targets.length){try{const e=await enrichHostContact({hostName:name,companyHint:String(b.bio||"").slice(0,160),knownTargets:b.known_targets.slice(0,5)});contact=e?.bestContact||null}catch{}}
 const externalKey=String(b.external_key||platform+":"+kind+":"+(handle||name.toLowerCase().replace(/\s+/g,"-"))).slice(0,300);
 const draft=String(b.draft_message||("Hi "+name+" — I came across your "+platform+" content around "+String(b.niche||"your niche")+". We work with YNOT to connect creators and brands with products and growth opportunities that fit their audience. I put together a few relevant ideas and can send them over if useful.")).slice(0,3000);
 const payload={external_key:externalKey,kind,platform,handle:handle||null,display_name:name,profile_url:String(b.profile_url||b.profileUrl||""),source_post_url:String(b.source_post_url||b.sourcePostUrl||""),niche:String(b.niche||"social prospecting"),country:b.country?String(b.country):null,followers:Number.isFinite(Number(b.followers))?Number(b.followers):null,engagement:Number.isFinite(Number(b.engagement))?Number(b.engagement):null,intent_strength:Number.isFinite(Number(b.score))?Number(b.score):null,creator_fit:Number.isFinite(Number(b.creator_fit))?Number(b.creator_fit):null,summary:String(b.summary||"Social prospect discovered through YNOT Growth."),reason:String(b.reason||"Relevant public activity and commercial fit."),source_quote:b.source_quote?String(b.source_quote):null,budget_min:null,budget_max:null,budget_currency:null,intent_tags:Array.isArray(b.tags)?b.tags.slice(0,20):[platform,kind],constraints:{contact_email:contact?.email||null,contact_confidence:contact?.confidence||null,contact_source:contact?.sourceUrl||null,bio:b.bio||null,metrics:b.metrics||null,source:b.source||null},personalization_context:String(b.personalization_context||b.bio||""),matched_product_ids:Array.isArray(b.matched_product_ids)?b.matched_product_ids:[],matched_products:Array.isArray(b.matched_products)?b.matched_products:[],draft_message:draft,channel:contact?.email?"email":String(b.channel||"manual research"),status:"ready",owner:"ARROW",outreach_approved:false,next_action:contact?.email?"Review and approve the outreach draft.":"Enrich a public business contact before sending.",updated_at:new Date().toISOString()};
 const rows=await adminDb("ynot_growth_opportunities?on_conflict=external_key",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify([payload])});const saved=rows?.[0]||payload;
 const acts=await adminDb("ynot_growth_activity",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({opportunity_id:saved.id,event_type:"social_prospect_saved",actor:admin.profile.display_name||admin.profile.email||"admin",detail:{platform,kind,handle,contact_email:contact?.email||null}})});
 return NextResponse.json({ok:true,opportunity:saved,activity:acts?.[0]||null});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"SOCIAL_PROSPECT_SAVE_FAILED"},{status:adminErrorStatus(e)});}}