import {NextRequest,NextResponse} from "next/server";
import {ELECTRIC_VISUAL_TAXONOMY} from "@/lib/electric/image-taxonomy";
export const dynamic="force-dynamic";
const SB=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://iycxkwoxbkanfyraohge.supabase.co",KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||"",BUCKET="YNOT FEED",ROOT="electric";
const imageRx=/\.(jpe?g|png|webp|avif)$/i;
async function list(prefix:string,limit=100){if(!KEY)return[];const r=await fetch(`${SB}/storage/v1/object/list/${encodeURIComponent(BUCKET)}`,{method:"POST",headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"},body:JSON.stringify({prefix,limit,offset:0,sortBy:{column:"created_at",order:"desc"}}),cache:"no-store"});if(!r.ok)return[];const rows=await r.json();return Array.isArray(rows)?rows:[]}
const pub=(path:string)=>`${SB}/storage/v1/object/public/${encodeURIComponent(BUCKET)}/${path.split("/").map(encodeURIComponent).join("/")}`;
async function cover(def:(typeof ELECTRIC_VISUAL_TAXONOMY)[number]){const prefix=`${ROOT}/${def.category}/${def.subcategory}`,rows=await list(prefix,20),row=rows.find((x:any)=>imageRx.test(x.name||""));return row?pub(`${prefix}/${row.name}`):""}
export async function GET(req:NextRequest){const sub=req.nextUrl.searchParams.get("subcategory")||"";if(sub==="__covers__"){const entries=await Promise.all(ELECTRIC_VISUAL_TAXONOMY.map(async d=>[d.subcategory,await cover(d)] as const));return NextResponse.json({covers:Object.fromEntries(entries.filter(([,url])=>url))})}const def=ELECTRIC_VISUAL_TAXONOMY.find(x=>x.subcategory===sub);if(!def)return NextResponse.json({error:"Unknown subcategory"},{status:404});const prefix=`${ROOT}/${def.category}/${def.subcategory}`,rows=await list(prefix),images=rows.filter((x:any)=>imageRx.test(x.name||"")).slice(0,50).map((x:any,i:number)=>({id:`${sub}-${i}-${x.name}`,url:pub(`${prefix}/${x.name}`),name:x.name,category:def.category,subcategory:def.subcategory,query:def.queries[0]}));return NextResponse.json({category:def.category,subcategory:def.subcategory,count:images.length,images});}
