import { createMcpHandler } from "mcp-handler";
import { registerAppResource, registerAppTool, RESOURCE_MIME_TYPE } from "@modelcontextprotocol/ext-apps/server";
import { z } from "zod";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const SITE="https://ynotworld.app", PRODUCT_UI="ui://ynot/bubble-world/v12.html";
type Product={id?:string;title?:string;brand?:string;price?:number|null;currency?:string;image?:string;images?:string[];url?:string;description?:string;tags?:string[];source?:string;[key:string]:unknown};
function country(v:string){const c=String(v||"FR").toUpperCase();return /^[A-Z]{2}$/.test(c)?c:"FR"} function clean(p:Product){return{id:String(p.id||""),title:String(p.title||"Product"),brand:String(p.brand||""),description:String(p.description||"").slice(0,1200),price:typeof p.price==="number"?p.price:null,currency:String(p.currency||"EUR"),image:String(p.image||p.images?.[0]||""),images:Array.isArray(p.images)?p.images.slice(0,8):[],tags:Array.isArray(p.tags)?p.tags.slice(0,12):[],source:String(p.source||"ynot"),merchant_url:String(p.url||""),ynot_url:p.id?`${SITE}/p/${encodeURIComponent(String(p.id))}`:SITE}}
async function search(q:string,dc:string,l:number){const p=new URLSearchParams({q:q.slice(0,300),country:country(dc),source:"all",category_load:l>20?"1":"0"}),r=await fetch(`${SITE}/api/catalog?${p}`,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`CATALOG_${r.status}`);const d=await r.json();return{query:d?.query||q,sources:d?.sources||[],products:(Array.isArray(d?.products)?d.products:[]).slice(0,l).map(clean),error:d?.error||null}}
function result(v:unknown,u=false){return{structuredContent:v as Record<string,unknown>,content:[{type:"text" as const,text:JSON.stringify(v,null,2)}],...(u?{_meta:{ui:{resourceUri:PRODUCT_UI},"ui/resourceUri":PRODUCT_UI,"openai/outputTemplate":PRODUCT_UI}}:{})}}
const bubbleHtml=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>
:root{color-scheme:dark;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;min-width:0;min-height:0;background:#080909;color:#fff;overflow:hidden}body{height:100dvh}.world{position:relative;width:100%;height:100%;min-height:0;overflow:hidden;background:radial-gradient(circle at 50% 42%,#303232 0,#171919 31%,#080909 68%)}.head{position:absolute;z-index:20;top:20px;left:24px;right:24px;display:flex;gap:14px;justify-content:space-between;font-size:12px}.brand{font-weight:900;letter-spacing:.2em}.query{opacity:.58;min-width:0;max-width:72%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:right}.stage{position:absolute;inset:52px 0 0;overflow:hidden}.b{position:absolute;width:clamp(78px,10vw,126px);aspect-ratio:1;border-radius:50%;border:1px solid #ffffff4a;background:radial-gradient(circle at 30% 22%,#ffffff24,#ffffff0e 48%,#ffffff05 74%);box-shadow:inset 0 1px #ffffff35,0 15px 38px #0007;backdrop-filter:blur(17px);display:grid;place-items:center;padding:12px;transform:translate(-50%,-50%);transition:transform .18s,border-color .18s;cursor:pointer}.b:hover,.b:focus{transform:translate(-50%,-50%) scale(1.08);border-color:#ffffffaa;z-index:6}.b img{width:84%;height:84%;object-fit:contain;filter:drop-shadow(0 8px 9px #0005)}.card{position:absolute;z-index:30;left:50%;bottom:10px;transform:translateX(-50%);width:min(440px,calc(100% - 20px));padding:12px;border-radius:20px;background:#181919ed;border:1px solid #ffffff2d;backdrop-filter:blur(22px);display:none}.card.on{display:block}.title{font-size:13px;font-weight:720}.price{margin-top:4px;font-weight:850}.open{display:block;margin-top:8px;padding:8px;text-align:center;border-radius:999px;background:#fff;color:#111;text-decoration:none;font-size:12px;font-weight:800}.empty{height:100%;display:grid;place-items:center;opacity:.6}
@media(min-width:700px){body{height:min(82vh,820px);min-height:600px}.world{height:100%;min-height:600px}.head{top:24px;left:30px;right:30px}.stage{inset:58px 0 0}.b{width:clamp(96px,9vw,142px)}}
@media(min-width:1200px){body{height:min(86vh,900px);min-height:680px}.world{min-height:680px}.b{width:clamp(108px,8vw,152px)}}
@media(max-width:699px){html,body,.world{height:100%;min-height:0}.head{top:8px;left:12px;right:12px;font-size:10px}.stage{inset:28px 0 0}.b{width:clamp(42px,17vw,68px);padding:6px}.card{bottom:max(6px,env(safe-area-inset-bottom));padding:9px}.title{font-size:11px}.price{font-size:12px}.open{margin-top:6px;padding:6px;font-size:10px}}
</style></head><body><div id="w" class="world"><div class="empty">Opening YNOT…</div></div><script>
const w=document.getElementById('w'),mobile=[[13,16],[50,11],[86,16],[29,39],[67,37],[88,46],[12,64],[45,61],[78,66],[27,85],[64,84]],desktop=[[7,15],[24,8],[42,16],[60,8],[78,16],[94,9],[14,38],[33,34],[51,41],[70,34],[88,41],[5,62],[23,58],[42,66],[61,58],[80,66],[96,59],[14,84],[34,81],[53,87],[73,81],[91,86]];const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));function money(p,c){try{return p==null?'Price on YNOT':new Intl.NumberFormat(undefined,{style:'currency',currency:c||'EUR'}).format(p)}catch{return String(p||'')}}function render(x){const d=x?.structuredContent||x||{},wide=innerWidth>=700,slots=wide?desktop:mobile,max=wide?22:11,ps=Array.isArray(d.products)?d.products.slice(0,max):[];if(!ps.length){w.innerHTML='<div class="empty">No matching products.</div>';return}w.innerHTML='<div class="head"><span class="brand">YNOT</span><span class="query">'+esc(d.query||'Products')+'</span></div><div class="stage">'+ps.map((p,i)=>'<button class="b" data-i="'+i+'" aria-label="'+esc(p.title)+'" style="left:'+slots[i%slots.length][0]+'%;top:'+slots[i%slots.length][1]+'%">'+(p.image?'<img src="'+esc(p.image)+'" alt="">':'')+'</button>').join('')+'</div><div id="c" class="card"></div>';document.querySelectorAll('.b').forEach(b=>b.onclick=()=>{const p=ps[+b.dataset.i],c=document.getElementById('c');c.innerHTML='<div class="title">'+esc(p.title)+'</div><div class="price">'+esc(money(p.price,p.currency))+'</div><a class="open" target="_blank" href="'+esc(p.ynot_url)+'">Open in YNOT</a>';c.classList.add('on')})}
let n=0,last=null;const pending=new Map();function send(method,params){parent.postMessage({jsonrpc:'2.0',method,params},'*')}function req(method,params){return new Promise((resolve,reject)=>{const id=++n;pending.set(id,{resolve,reject});parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}addEventListener('message',e=>{if(e.source!==parent)return;const m=e.data;if(!m||m.jsonrpc!=='2.0')return;if(m.id!==undefined&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);return}if(m.method==='ui/notifications/tool-result'){last=m.params;render(last)}});addEventListener('resize',()=>{if(last)render(last)});(async()=>{try{await req('ui/initialize',{appInfo:{name:'ynot-bubble-world',version:'12.0.0'},appCapabilities:{},protocolVersion:'2026-01-26'});send('ui/notifications/initialized',{})}catch{if(window.openai?.toolOutput){last=window.openai.toolOutput;render(last)}}})();if(window.openai?.toolOutput){last=window.openai.toolOutput;render(last)};
</script></body></html>`;
const handler=createMcpHandler(server=>{
  const rm={ui:{prefersBorder:false,csp:{connectDomains:[SITE],resourceDomains:[SITE,"https://cdn.shopify.com","https://images.unsplash.com"]}},"openai/ui":{availableDisplayModes:["inline","fullscreen"]},"openai/widgetDescription":"Responsive YNOT Bubble World fitted to the host viewport."};
  registerAppResource(server,"YNOT Bubble World",PRODUCT_UI,{description:"Responsive visual product explorer",_meta:rm},async()=>({contents:[{uri:PRODUCT_UI,mimeType:RESOURCE_MIME_TYPE,text:bubbleHtml,_meta:rm}]}));
  const um={ui:{resourceUri:PRODUCT_UI},"ui/resourceUri":PRODUCT_UI,"openai/outputTemplate":PRODUCT_UI,"openai/widgetAccessible":true,"openai/toolInvocation/invoking":"Opening Bubble World…","openai/toolInvocation/invoked":"Explore the results below"},ro={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:true};
  const productSchema=z.object({
    id:z.string(),title:z.string(),brand:z.string().optional(),description:z.string().optional(),
    price:z.number().nullable().optional(),currency:z.string().optional(),image:z.string().optional(),
    images:z.array(z.string()).optional(),tags:z.array(z.string()).optional(),source:z.string().optional(),
    merchant_url:z.string().optional(),ynot_url:z.string().optional()
  }).passthrough();
  server.registerTool("search_products",{
    title:"Search YNOT products",
    description:"Search YNOT's live multi-source catalogue and return product data. After this succeeds, call render_bubble_world with the returned query, products, sources, and error to visually present the results.",
    inputSchema:{query:z.string().min(2).max(300),country:z.string().length(2).default("FR"),limit:z.number().int().min(1).max(40).default(22)},annotations:ro
  },async({query,country,limit})=>result(await search(query,country,limit)));
  registerAppTool(server,"render_bubble_world",{
    title:"Render YNOT Bubble World",
    description:"Visually present product data returned by search_products in YNOT's interactive responsive Bubble World. Call this immediately after search_products; pass through its query, products, sources, and error without inventing or changing catalogue data.",
    inputSchema:{query:z.string().max(300),products:z.array(productSchema).max(40),sources:z.array(z.unknown()).optional(),error:z.unknown().optional()},annotations:ro,_meta:um
  },async({query,products,sources,error})=>result({query,products,sources:sources||[],error:error??null},true));
  registerAppTool(server,"get_product",{title:"Get YNOT product",description:"Get a live YNOT product and display it in YNOT's embedded UI.",inputSchema:{product_id:z.string().min(1),query:z.string().min(2).max(300),country:z.string().length(2).default("FR")},annotations:ro,_meta:um},async({product_id,query,country})=>{const d=await search(query,country,40),p=d.products.find((x:any)=>x.id===product_id);return result(p?{query,products:[p]}:{query,products:[],error:"PRODUCT_NOT_FOUND",product_id},true)});
  registerAppTool(server,"find_similar_products",{title:"Find similar YNOT products",description:"Find live YNOT alternatives and display them in the Bubble World.",inputSchema:{product:z.string().min(2).max(300),preference:z.string().max(200).default("similar alternatives"),country:z.string().length(2).default("FR"),limit:z.number().int().min(1).max(30).default(18)},annotations:ro,_meta:um},async({product,preference,country,limit})=>result(await search(`${product}, ${preference}`,country,limit),true));
  server.registerTool("get_product_images",{title:"Get YNOT product images",description:"Return images for a YNOT catalogue product.",inputSchema:{product_id:z.string().min(1),query:z.string().min(2).max(300),country:z.string().length(2).default("FR")},annotations:ro},async({product_id,query,country})=>{const d=await search(query,country,40),p:any=d.products.find((x:any)=>x.id===product_id);return result(p?{id:p.id,title:p.title,images:[...new Set([p.image,...(p.images||[])].filter(Boolean))],ynot_url:p.ynot_url,merchant_url:p.merchant_url}:{error:"PRODUCT_NOT_FOUND",product_id})});
  server.registerTool("open_in_ynot",{title:"Open YNOT website",description:"Use only when the user explicitly asks to open or continue on YNOT.",inputSchema:{product_id:z.string().max(240).optional(),query:z.string().max(300).optional()},annotations:ro},async({product_id,query})=>result({url:product_id?`${SITE}/p/${encodeURIComponent(product_id)}`:query?`${SITE}/?q=${encodeURIComponent(query)}`:SITE}));
},{instructions:"YNOT is a visual multi-source shopping service. For product discovery, call search_products first, then immediately call render_bubble_world with the returned catalogue payload so the user can explore the results visually. Keep product discovery inside the conversation and use the Bubble World when MCP Apps are supported. Never invent, omit, or change product details, prices, availability, shipping, or merchants. get_product and find_similar_products retain direct Bubble World rendering for host compatibility."},{basePath:"/api/chatgpt"});
export{handler as GET,handler as POST,handler as DELETE};
