import type {Metadata} from "next";
import QuickRoomExperience from "./QuickRoomExperience";
import RoomDesktopInteractionFix from "./RoomDesktopInteractionFix";
import RoomCommerceBridge from "./RoomCommerceBridge";
import RoomChannel3Bridge from "./RoomChannel3Bridge";
import RoomPhotoBackdrop from "./RoomPhotoBackdrop";
import RoomSearchBar from "./RoomSearchBar";
import RoomLiveCamera from "./RoomLiveCamera";
import RoomScanHandoff from "./RoomScanHandoff";
import RoomScanLine from "./RoomScanLine";
import RoomDrawerScrollFix from "./RoomDrawerScrollFix";
import RoomPlus from "./RoomPlus";
import RoomOnboarding from "./RoomOnboarding";
import RoomProductFullscreen from "./RoomProductFullscreen";
import RoomProductImageDots from "./RoomProductImageDots";
import RoomExitToWorld from "./RoomExitToWorld";
import RoomInspiration from "./RoomInspiration";
import RoomInspirationScanBridge from "./RoomInspirationScanBridge";
import RoomInspirationStrip from "./RoomInspirationStrip";
import AdTrafficMount from "../AdTrafficMount";
import UnifiedBag from "../../components/lumina/UnifiedBag";
import AuthGate from "../../components/lumina/AuthGate";
export const metadata:Metadata={title:"YNOT Room — Tap your room. Shop anything.",description:"Take one photo and let YNOT identify objects, suggest what to add, and find matching products automatically.",alternates:{canonical:"https://ynotworld.app/room"}};
export default function RoomPage(){return <><AdTrafficMount/><RoomExitToWorld/><RoomChannel3Bridge/><QuickRoomExperience/><RoomInspiration/><RoomInspirationScanBridge/><RoomInspirationStrip/><RoomProductFullscreen/><RoomProductImageDots/><RoomLiveCamera/><RoomScanHandoff/><RoomScanLine/><RoomDrawerScrollFix/><RoomDesktopInteractionFix/><RoomCommerceBridge/><RoomPhotoBackdrop/><RoomSearchBar/><RoomPlus/><UnifiedBag/><AuthGate/><RoomOnboarding/></>}
