"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Camera,ImagePlus,LoaderCircle,Plus,ShoppingBag,Sparkles,X} from "lucide-react";
type Detected={id:string;label:string;category:string;searchQuery:string;confidence:number;box_2d:number[]};type Spot={id:string;label:string;searchQuery:string;point_2d:number[]};type Analysis={sceneTitle:string;objects:Detected[];suggestionSpots:Spot[]};type Product={id:string;title:string;brand?:string;price?:number|null;currency?:string;image?:string};
function money(p:Product){if(typeof p.price!=="number")return"";try{return new Intl.NumberFormat(undefined,{style:"currency",currency:p.currency||"EUR",maximumFractionDigits:2}).format(p.price)}catch{return`${p.price} ${p.currency||"EUR"}`}}
export default function QuickRoomExperience(){
 const[file,setFile]=useState<File|null>(null),[analysis,setAnalysis]=useState<Analysis|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");const[selected,setSelected]=useState<{id:string;label:string;query:string;kind:"object"|"spot"}|null>(null),[products,setProducts]=useState<Product[]>([]),[searching,setSearching]=useState(false),[openProduct,setOpenProduct]=useState<Product|null>(null);const cameraRef=useRef<HTMLInputElement>(null),uploadRef=useRef<HTMLInputElement>(null);const preview=useMemo(()=>file?URL.createObjectURL(file):"",[file]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 async function analyze(next:File){setFile(next);setAnalysis(null);setSelected(null);setProducts([]);setOpenProduct(null);setError("");setLoading(true);try{const fd=new FormData();fd.append("image",next);const r=await fetch("/api/room/quick/analyze",{method:"POST",body:fd});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not analyze this photo");setAnalysis(d)}catch(e){setError(e instanceof Error?e.message:"Could not analyze this photo")}finally{setLoading(false)}}
 async function choose(item:{id:string;label:string;query:string;kind:"object"|"spot"}){setSelected(item);setProducts([]);setSearching(true);try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(item.query)}&source=shopify&category_load=1`,{cache:"no-store"});const d=await r.json().catch(()=>({}));setProducts(Array.isArray(d?.products)?d.products.slice(0,18):[])}finally{setSearching(false)}}
 const pick=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)analyze(f)};
 return <main className="yr"><style jsx global>{`
 .yr{position:fixed;inset:0;z-index:70;color:#fff;background:rgba(4,6,6,.72);overflow:auto}.yr:before{content:"";position:fixed;inset:0;z-index:-1;background:transparent;backdrop-filter:blur(32px) saturate(125%);-webkit-backdrop-filter:blur(32px) saturate(125%)}.yr-wrap{min-height:100%;max-width:1180px;margin:auto;padding:18px;display:flex;flex-direction:column}.yr-glass{background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.16);box-shadow:inset 0 1px rgba(255,255,255,.09),0 22px 70px rgba(0,0,0,.16);backdrop-filter:blur(26px) saturate(140%);-webkit-backdrop-filter:blur(26px) saturate(140%)}.yr-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.yr-round{width:44px;height:44px;border-radius:50%;border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.045);color:white;display:grid;place-items:center}.yr-camera{position:relative;flex:1;min-height:70vh;border-radius:32px;overflow:hidden;display:grid;place-items:center;background:rgba(255,255,255,.018)}.yr-camera:after{content:"";position:absolute;inset:16px;border:1px solid rgba(255,255,255,.12);border-radius:24px;pointer-events:none}.yr-empty{text-align:center;padding:40px 22px;position:relative;z-index:2}.yr-viewfinder{width:88px;height:88px;border-radius:50%;margin:0 auto 18px;display:grid;place-items:center;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.2);box-shadow:0 0 0 12px rgba(255,255,255,.018)}.yr-shutter{width:76px;height:76px;border-radius:50%;border:5px solid rgba(255,255,255,.9);background:rgba(255,255,255,.08);box-shadow:inset 0 0 0 4px rgba(0,0,0,.16);display:grid;place-items:center;color:white;cursor:pointer}.yr-upload{border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.04);color:white;border-radius:999px;padding:12px 17px;display:inline-flex;gap:8px;align-items:center;cursor:pointer}.yr-photo{position:relative;width:100%;height:70vh;display:grid;place-items:center}.yr-photo>img{width:100%;height:100%;object-fit:contain}.yr-row{display:flex;gap:13px;overflow-x:auto;padding:12px 2px 5px;scrollbar-width:none}.yr-row::-webkit-scrollbar{display:none}.yr-bubble{flex:0 0 105px;border:0;background:transparent;color:white;text-align:center}.yr-bubble-img{width:100px;height:100px;border-radius:50%;overflow:hidden;display:grid;place-items:center;border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.04)}.yr-bubble-img img{width:100%;height:100%;object-fit:contain;background:transparent}.yr-results{margin-top:12px;border-radius:26px;padding:13px}.yr-modal{position:fixed;inset:0;z-index:90;background:rgba(0,0,0,.22);backdrop-filter:blur(10px);display:grid;place-items:center;padding:18px}.yr-card{width:min(450px,94vw);border-radius:30px;padding:15px}.yr-card img{width:100%;aspect-ratio:1;object-fit:contain;border-radius:22px;background:transparent}
 @media(max-width:700px){.yr{background:rgba(4,6,6,.58)}.yr-wrap{padding:10px;min-height:100dvh}.yr-head{padding:2px 3px}.yr-camera{min-height:calc(100dvh - 82px);border-radius:26px;background:rgba(255,255,255,.012)}.yr-photo{height:calc(100dvh - 90px)}.yr-results{position:fixed;left:8px;right:8px;bottom:8px;z-index:75;background:rgba(255,255,255,.035)}.yr:before{background:transparent;backdrop-filter:blur(26px) saturate(130%);-webkit-backdrop-filter:blur(26px) saturate(130%)}}
 `}</style><div className="yr-wrap"><header className="yr-head"><Link href="/" className="yr-round"><ArrowLeft size={20}/></Link><div style={{textAlign:"center"}}><b style={{letterSpacing:1}}>YNOT ROOM</b><div style={{fontSize:10,opacity:.55,marginTop:2}}>POINT · TAP · SHOP</div></div><button className="yr-round" onClick={()=>uploadRef.current?.click()} aria-label="Upload photo"><ImagePlus size={19}/></button></header>
 <input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onChange={pick}/><input ref={uploadRef} hidden type="file" accept="image/*" onChange={pick}/>
 <section className="yr-camera yr-glass">{!file?<div className="yr-empty"><div className="yr-viewfinder"><Camera size={34}/></div><h1 style={{fontSize:"clamp(27px,5vw,46px)",margin:"0 0 8px"}}>See it. Tap it. Find it.</h1><p style={{opacity:.64,maxWidth:430,margin:"0 auto 28px",lineHeight:1.45}}>Take a photo and YNOT will scan the objects and useful spaces around you.</p><div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:17}}><button className="yr-shutter" onClick={()=>cameraRef.current?.click()} aria-label="Take photo"><Camera size={25}/></button><button className="yr-upload" onClick={()=>uploadRef.current?.click()}><ImagePlus size={17}/>Upload a photo</button></div></div>:<div className="yr-photo"><img src={preview} alt="Your space"/>{analysis?.objects.map(o=>{const b=o.box_2d||[];if(b.length<4)return null;const x=((b[1]+b[3])/2)/10,y=((b[0]+b[2])/2)/10;return <button key={o.id} title={o.label} onClick={()=>choose({id:o.id,label:o.label,query:o.searchQuery,kind:"object"})} style={{position:"absolute",left:`${x}%`,top:`${y}%`,transform:"translate(-50%,-50%)",width:32,height:32,borderRadius:50,border:"2px solid white",background:selected?.id===o.id?"white":"rgba(8,10,10,.38)",boxShadow:"0 4px 18px #0007"}}/>})}{analysis?.suggestionSpots.map(s=>{const p=s.point_2d||[];return p.length>=2?<button key={s.id} title={s.label} onClick={()=>choose({id:s.id,label:s.label,query:s.searchQuery,kind:"spot"})} style={{position:"absolute",left:`${p[0]/10}%`,top:`${p[1]/10}%`,transform:"translate(-50%,-50%)",width:34,height:34,borderRadius:50,border:"2px solid white",background:"rgba(8,10,10,.42)",color:"white",display:"grid",placeItems:"center"}}><Plus size={16}/></button>:null})}{loading&&<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",background:"rgba(8,10,10,.08)",backdropFilter:"blur(5px)"}}><div className="yr-glass" style={{padding:"15px 19px",borderRadius:999,display:"flex",gap:10,alignItems:"center"}}><LoaderCircle className="animate-spin"/>Scanning your space…</div></div>}</div>}</section>
 {error&&<div style={{padding:12,textAlign:"center",color:"#ffd0cb"}}>{error}</div>}{analysis&&!selected&&<div style={{padding:"9px 5px",fontSize:12,opacity:.58}}>{analysis.objects.length} things found · tap a dot to shop it <Sparkles size={12} style={{verticalAlign:"middle"}}/></div>}
 {selected&&<section className="yr-results yr-glass"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><small style={{opacity:.55,textTransform:"uppercase"}}>{selected.kind==="spot"?"Ideas for this spot":"YNOT found"}</small><div style={{fontWeight:700,marginTop:2}}>{selected.label}</div></div><button className="yr-round" onClick={()=>{setSelected(null);setProducts([])}}><X size={16}/></button></div>{searching?<div style={{padding:20,display:"flex",gap:9,alignItems:"center",opacity:.65}}><LoaderCircle className="animate-spin"/>Finding matches…</div>:<div className="yr-row">{products.map(p=><button key={p.id} className="yr-bubble" onClick={()=>setOpenProduct(p)}><span className="yr-bubble-img">{p.image?<img src={p.image} alt=""/>:<ShoppingBag/>}</span><span style={{display:"block",fontSize:11,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis",marginTop:6}}>{p.title}</span><span style={{fontSize:11,opacity:.65}}>{money(p)}</span></button>)}</div>}</section>}
 {openProduct&&<div className="yr-modal" onClick={()=>setOpenProduct(null)}><article className="yr-card yr-glass" onClick={e=>e.stopPropagation()}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><small style={{opacity:.6}}>YNOT MATCH</small><button className="yr-round" onClick={()=>setOpenProduct(null)}><X size={16}/></button></div>{openProduct.image&&<img src={openProduct.image} alt=""/>}<h2 style={{margin:"14px 0 5px"}}>{openProduct.title}</h2><div style={{opacity:.6,fontSize:13}}>{openProduct.brand}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:16}}><b>{money(openProduct)}</b><Link href={`/p/${encodeURIComponent(openProduct.id)}`} style={{background:"rgba(255,255,255,.9)",color:"#111",padding:"11px 15px",borderRadius:999,textDecoration:"none",fontWeight:700}}>Open product</Link></div></article></div>}
 </div></main>}
