"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,ImagePlus} from "lucide-react";

export default function RoomLiveCamera(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null);const[media,setMedia]=useState<MediaStream|null>(null),[denied,setDenied]=useState(false);
 const stop=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setMedia(null)};
 const start=async()=>{if(typeof navigator==="undefined"||!navigator.mediaDevices?.getUserMedia){setDenied(true);return}try{stop();const s=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}}});stream.current=s;setDenied(false);setMedia(s)}catch{setDenied(true);setMedia(null)}};
 useEffect(()=>{void start();return()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}},[]);
 useEffect(()=>{const v=video.current;if(!v||!media)return;v.srcObject=media;const p=v.play();if(p&&typeof p.catch==="function")p.catch(()=>{});return()=>{if(v.srcObject===media)v.srcObject=null}},[media]);
 const upload=()=>{const inputs=Array.from(document.querySelectorAll<HTMLInputElement>('input[type="file"][accept*="image"]'));(inputs[1]||inputs[0])?.click()};
 const snap=async()=>{const v=video.current;if(!v||!v.videoWidth||!v.videoHeight)return;const c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;const ctx=c.getContext("2d");if(!ctx)return;ctx.drawImage(v,0,0,c.width,c.height);const blob=await new Promise<Blob|null>(resolve=>c.toBlob(resolve,"image/jpeg",.9));if(!blob)return;const file=new File([blob],`ynot-room-${Date.now()}.jpg`,{type:"image/jpeg"});const input=document.querySelector<HTMLInputElement>('input[type="file"][accept*="image"]');if(!input)return;try{const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;input.dispatchEvent(new Event("change",{bubbles:true}))}catch{setDenied(true);return}stop()};
 if(!media&&!denied)return null;
 return <div className="yr-live-camera" aria-label="YNOT Room live camera">
  {media&&<video ref={video} autoPlay muted playsInline className="yr-live-video"/>}
  <div className="yr-live-corners"><i/><i/><i/><i/></div>
  {denied?<div className="yr-live-denied"><Camera size={28}/><b>Camera access needed</b><span>Allow camera access to scan what you see.</span><button onClick={()=>void start()}>Allow camera</button><button onClick={upload}><ImagePlus size={15}/> Upload instead</button></div>:<button className="yr-live-shutter" onClick={()=>void snap()} aria-label="Take photo and scan"><span/></button>}
  <style jsx>{`.yr-live-camera{position:fixed;z-index:74;left:18px;right:18px;top:78px;bottom:22px;border-radius:32px;overflow:hidden;border:1px solid rgba(255,255,255,.18);background:#111;box-shadow:inset 0 1px rgba(255,255,255,.12),0 20px 60px rgba(0,0,0,.18)}.yr-live-video{width:100%;height:100%;object-fit:cover}.yr-live-camera:after{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(to bottom,rgba(0,0,0,.08),transparent 24%,transparent 72%,rgba(0,0,0,.18))}.yr-live-shutter{position:absolute;z-index:3;left:50%;bottom:28px;transform:translateX(-50%);width:74px;height:74px;border-radius:50%;border:4px solid rgba(255,255,255,.86);background:rgba(255,255,255,.16);display:grid;place-items:center;backdrop-filter:blur(12px)}.yr-live-shutter span{width:58px;height:58px;border-radius:50%;background:rgba(255,255,255,.92)}.yr-live-corners{position:absolute;z-index:2;inset:15% 14% 20%;pointer-events:none}.yr-live-corners i{position:absolute;width:42px;height:42px;border-color:rgba(255,255,255,.72);border-style:solid}.yr-live-corners i:nth-child(1){left:0;top:0;border-width:3px 0 0 3px;border-radius:18px 0 0}.yr-live-corners i:nth-child(2){right:0;top:0;border-width:3px 3px 0 0;border-radius:0 18px 0 0}.yr-live-corners i:nth-child(3){left:0;bottom:0;border-width:0 0 3px 3px;border-radius:0 0 0 18px}.yr-live-corners i:nth-child(4){right:0;bottom:0;border-width:0 3px 3px 0;border-radius:0 0 18px}.yr-live-denied{position:absolute;z-index:4;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;padding:30px;text-align:center;background:rgba(12,13,13,.82);backdrop-filter:blur(18px);color:white}.yr-live-denied span{font-size:12px;opacity:.62}.yr-live-denied button{border:1px solid rgba(255,255,255,.18);border-radius:999px;padding:11px 17px;background:rgba(255,255,255,.1);color:white;display:flex;align-items:center;gap:7px}@media(min-width:701px){.yr-live-camera{left:50%;right:auto;width:min(760px,calc(100vw - 36px));transform:translateX(-50%);top:84px;bottom:28px}}`}</style>
 </div>
}
