"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {Camera,ImagePlus,Upload} from "lucide-react";

const PREVIEW="https://iycxkwoxbkanfyraohge.supabase.co/storage/v1/object/public/ad-creatives/IMG_6763.jpeg";
export default function RoomOnboardingEntryChoices(){
 const[host,setHost]=useState<Element|null>(null);
 useEffect(()=>{let cancelled=false,tries=0;const find=()=>{if(cancelled)return;const el=document.querySelector(".ro-video-shell");if(el){setHost(el);return}if(tries++<80)setTimeout(find,100)};find();return()=>{cancelled=true}},[]);
 const leave=(after:()=>void)=>{setHost(null);setTimeout(()=>{(document.querySelector(".ro-skip") as HTMLButtonElement|null)?.click();setTimeout(after,120)},40)};
 const camera=()=>leave(()=>window.dispatchEvent(new CustomEvent("ynot:room-live-camera-open")));
 const upload=()=>leave(()=>{const all=[...document.querySelectorAll<HTMLInputElement>('input[type="file"][accept*="image"]')];const input=all.find(x=>!x.hasAttribute("capture"))||all[0];input?.click()});
 const explore=()=>leave(()=>window.dispatchEvent(new CustomEvent("ynot:room-inspiration",{detail:{source:"onboarding"}})));
 if(!host)return null;
 return createPortal(<div className="roe"><style jsx global>{`.ro-video-shell>.ro-video-placeholder,.ro-video-shell>.ro-video,.ro-video-shell>.ro-video-glass{display:none!important}.roe{position:absolute;inset:7px;z-index:6;border-radius:31px;overflow:hidden;background:#292725;color:#fff}.roe-camera{position:absolute;inset:-18px;width:calc(100% + 36px);height:calc(100% + 36px);object-fit:cover;filter:blur(14px) saturate(.65) brightness(.66);transform:scale(1.04)}.roe-frost{position:absolute;inset:0;background:linear-gradient(180deg,rgba(10,10,10,.2),rgba(10,10,10,.05) 40%,rgba(10,10,10,.58))}.roe-corners{position:absolute;left:12%;right:12%;top:12%;bottom:27%;border:1px solid rgba(255,255,255,.17);border-radius:27px}.roe-corners:before,.roe-corners:after{content:"";position:absolute;width:36px;height:36px;border-color:#fff;border-style:solid}.roe-corners:before{left:-1px;top:-1px;border-width:2px 0 0 2px;border-radius:12px 0 0}.roe-corners:after{right:-1px;bottom:-1px;border-width:0 2px 2px 0;border-radius:0 0 12px}.roe-copy{position:absolute;z-index:2;top:14%;left:20px;right:20px;text-align:center;text-shadow:0 2px 18px #000}.roe-copy small{font-size:9px;letter-spacing:.22em;text-transform:uppercase;opacity:.68}.roe-copy strong{display:block;margin-top:7px;font-size:clamp(24px,6vw,38px);letter-spacing:-.04em}.roe-actions{position:absolute;z-index:3;left:14px;right:14px;bottom:14px;display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}.roe-action{min-width:0;height:76px;border-radius:19px;border:1px solid rgba(255,255,255,.25);background:rgba(18,18,18,.36);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);color:#fff;padding:8px 5px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;font-size:9px;font-weight:750;line-height:1.15}.roe-action:first-child{background:rgba(255,255,255,.88);color:#161412}.roe-action svg{flex:none}@media(min-width:700px){.roe-actions{left:24px;right:24px;bottom:22px}.roe-action{height:82px;font-size:10px}}`}</style><img src={PREVIEW} className="roe-camera" alt="Blurred room camera preview"/><div className="roe-frost"/><div className="roe-corners"/><div className="roe-copy"><small>Three ways to start</small><strong>Point at your space.</strong></div><div className="roe-actions"><button className="roe-action" onClick={camera}><Camera size={20}/>Point at your space</button><button className="roe-action" onClick={upload}><Upload size={20}/>Upload inspiration</button><button className="roe-action" onClick={explore}><ImagePlus size={20}/>Explore interiors</button></div></div>,host)
}
