"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {ChevronDown,ChevronUp,Play} from "lucide-react";
type Item={id:string;type:"photo"|"video";src:string;thumb:string;alt?:string;source?:string};
const FALLBACK=["IMG_6763.jpeg","IMG_6764.jpeg","IMG_6765.jpeg"].map((file,i)=>({id:`fallback-${i}`,type:"photo" as const,src:`https://iycxkwoxbkanfyraohge.supabase.co/storage/v1/object/public/ad-creatives/${file}`,thumb:`https://iycxkwoxbkanfyraohge.supabase.co/storage/v1/object/public/ad-creatives/${file}`,alt:"Interior inspiration"}));
export default function RoomInspirationStrip(){
 const[items,setItems]=useState<Item[]>(FALLBACK),[ready,setReady]=useState(false),[mounted,setMounted]=useState(false),[expanded,setExpanded]=useState(true);
 useEffect(()=>setMounted(true),[]);
 useEffect(()=>{let alive=true;const load=async()=>{try{const [dr,pr]=await Promise.allSettled([fetch('/api/room/drive-interiors',{cache:'no-store'}),fetch('/api/room/inspiration',{cache:'force-cache'})]);const d=dr.status==='fulfilled'&&dr.value.ok?await dr.value.json():{};const p=pr.status==='fulfilled'&&pr.value.ok?await pr.value.json():{};const next=[...(Array.isArray(d.items)?d.items:[]),...(Array.isArray(p.items)?p.items:[]),...FALLBACK] as Item[];const seen=new Set<string>();if(alive)setItems(next.filter(x=>x?.id&&x?.src&&!seen.has(x.id)&&(seen.add(x.id),true)))}catch{}finally{if(alive)setReady(true)}};void load();return()=>{alive=false}},[]);
 if(!mounted)return null;
 const open=(i:number)=>window.dispatchEvent(new CustomEvent('ynot:room-inspiration',{detail:{pexelsId:items[i]?.id,index:i}}));
 return createPortal(<section className={`yr-inspo-strip${expanded?' expanded':''}`} aria-label="Room inspiration feed"><div className="yr-inspo-head"><button className="yr-inspo-title" type="button" onClick={()=>open(0)}><small>INSPIRATION · {ready?`${items.length} SPACES`:'LOADING'}</small><b>Explore interiors</b></button><button className="yr-inspo-toggle" type="button" onClick={()=>setExpanded(v=>!v)} aria-label={expanded?'Collapse interior previews':'Show interior previews'}>{expanded?<ChevronDown size={18}/>:<ChevronUp size={18}/>}</button></div>{expanded&&<div className="yr-inspo-rail">{items.slice(0,40).map((x,i)=><button type="button" key={x.id} className={`yr-inspo-tile n${i%6}`} onClick={()=>open(i)}>{x.type==='video'?<><img src={x.thumb||x.src} alt={x.alt||'Home inspiration'} loading={i<5?'eager':'lazy'}/><span><Play size={11} fill="currentColor"/></span></>:<img src={x.thumb||x.src} alt={x.alt||'Home inspiration'} loading={i<5?'eager':'lazy'}/>}</button>)}</div>}<style jsx>{`.yr-inspo-strip{position:fixed;left:12px;right:12px;bottom:calc(105px + env(safe-area-inset-bottom));z-index:86;max-width:900px;margin:auto;color:#fff;border:1px solid rgba(255,255,255,.18);background:rgba(24,24,24,.74);border-radius:23px;padding:11px;box-shadow:0 8px 28px rgba(0,0,0,.19);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}.yr-inspo-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.yr-inspo-title{text-align:left;border:0;background:none;color:#fff;padding:1px 4px}.yr-inspo-head small{display:block;font-size:9px;letter-spacing:.15em;opacity:.58}.yr-inspo-head b{display:block;margin-top:3px;font-size:16px;letter-spacing:-.025em}.yr-inspo-toggle{flex:none;width:34px;height:34px;border-radius:50%;border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.1);color:#fff;display:grid;place-items:center}.yr-inspo-rail{display:flex;gap:9px;overflow-x:auto;scrollbar-width:none;padding:9px 3px 1px;align-items:center;-webkit-overflow-scrolling:touch}.yr-inspo-rail::-webkit-scrollbar{display:none}.yr-inspo-tile{position:relative;flex:0 0 103px;height:104px;padding:0;border:0;border-radius:14px;overflow:hidden;background:rgba(255,255,255,.08)}.yr-inspo-tile.n2{flex-basis:130px}.yr-inspo-tile img{width:100%;height:100%;object-fit:cover;display:block}.yr-inspo-tile span{position:absolute;right:6px;bottom:6px;width:24px;height:24px;border-radius:50%;display:grid;place-items:center;background:rgba(0,0,0,.4)}@media(min-width:760px){.yr-inspo-strip{bottom:24px}.yr-inspo-tile{flex-basis:132px;height:118px}}`}</style></section>,document.body)
}
