"use client";
import {useEffect,useMemo,useState} from "react";
import {ChevronUp,Heart,ScanLine,X} from "lucide-react";

/* Permanent Room inspiration collection. Add the purchased Supabase URLs here as they are uploaded; the UI automatically accepts the full ~100 image set. */
export const ROOM_INTERIORS=[
 "https://iycxkwoxbkanfyraohge.supabase.co/storage/v1/object/public/ad-creatives/IMG_6763.jpeg",
 "https://iycxkwoxbkanfyraohge.supabase.co/storage/v1/object/public/ad-creatives/IMG_6764.jpeg",
 "https://iycxkwoxbkanfyraohge.supabase.co/storage/v1/object/public/ad-creatives/IMG_6765.jpeg"
];

export default function RoomInspiration(){
 const[open,setOpen]=useState(false),[index,setIndex]=useState(0),[grid,setGrid]=useState(false),[saved,setSaved]=useState<Set<number>>(new Set());
 const images=useMemo(()=>ROOM_INTERIORS.filter(Boolean),[]);
 useEffect(()=>{const fn=(e:Event)=>{const i=Number((e as CustomEvent).detail?.index||0);setIndex(Math.max(0,Math.min(images.length-1,i)));setGrid(false);setOpen(true)};window.addEventListener("ynot:room-inspiration",fn);return()=>window.removeEventListener("ynot:room-inspiration",fn)},[images.length]);
 if(!open||!images.length)return null;
 const select=(i:number)=>{setIndex(i);setGrid(false)};
 const scan=()=>{window.dispatchEvent(new CustomEvent("ynot:scan-inspiration",{detail:{src:images[index],index}}));setOpen(false)};
 return <div className="yri"><style jsx global>{`
 .yri{position:fixed;inset:0;z-index:10020;background:#0b0b0a;color:#fff;font-family:inherit;overflow:hidden}.yri-stage{position:absolute;inset:0;touch-action:pan-y}.yri-slide{position:absolute;inset:0;display:grid;place-items:center}.yri-slide img{width:100%;height:100%;object-fit:cover;user-select:none;-webkit-user-drag:none}.yri-shade{position:absolute;inset:0;pointer-events:none;background:linear-gradient(180deg,rgba(0,0,0,.22),transparent 24%,transparent 64%,rgba(0,0,0,.54))}.yri-close{position:absolute;z-index:4;top:calc(16px + env(safe-area-inset-top));right:16px;width:44px;height:44px;border-radius:50%;border:1px solid rgba(255,255,255,.28);background:rgba(20,20,20,.22);color:#fff;display:grid;place-items:center;backdrop-filter:blur(16px)}.yri-controls{position:absolute;z-index:4;left:16px;right:16px;bottom:calc(20px + env(safe-area-inset-bottom));display:grid;grid-template-columns:48px 1fr 48px;gap:10px;align-items:center}.yri-control,.yri-scan{height:48px;border:1px solid rgba(255,255,255,.28);background:rgba(18,18,18,.26);color:#fff;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}.yri-control{border-radius:50%;display:grid;place-items:center}.yri-scan{border-radius:999px;font-weight:780;font-size:14px;display:flex;align-items:center;justify-content:center;gap:8px}.yri-count{position:absolute;z-index:4;left:18px;top:calc(22px + env(safe-area-inset-top));font-size:10px;letter-spacing:.16em;text-transform:uppercase;text-shadow:0 1px 10px #000}.yri-grid{position:absolute;z-index:8;inset:0;background:#f1f0ec;color:#111;overflow:auto;padding:calc(70px + env(safe-area-inset-top)) 12px calc(30px + env(safe-area-inset-bottom));animation:yriUp .25s ease}.yri-grid-head{position:fixed;z-index:10;left:0;right:0;top:0;height:calc(62px + env(safe-area-inset-top));padding:env(safe-area-inset-top) 16px 0;display:flex;align-items:center;justify-content:space-between;background:linear-gradient(#f1f0ec 65%,transparent)}.yri-grid-head b{letter-spacing:.12em;font-size:12px}.yri-grid-close{width:40px;height:40px;border:1px solid rgba(0,0,0,.1);background:rgba(255,255,255,.7);border-radius:50%;display:grid;place-items:center}.yri-cosmos{columns:2;column-gap:12px;max-width:900px;margin:auto}.yri-tile{width:100%;padding:0;border:0;background:transparent;margin:0 0 12px;break-inside:avoid;display:block;border-radius:18px;overflow:hidden}.yri-tile:nth-child(5n+1){margin-top:24px}.yri-tile:nth-child(4n+2) img{aspect-ratio:4/5}.yri-tile:nth-child(4n+3) img{aspect-ratio:1/1}.yri-tile:nth-child(4n){width:88%;margin-left:auto}.yri-tile img{display:block;width:100%;height:auto;min-height:150px;max-height:420px;object-fit:cover}.yri-stage{transition:transform .22s ease}@keyframes yriUp{from{transform:translateY(100%)}to{transform:none}}@media(min-width:760px){.yri-cosmos{columns:3}.yri-controls{width:min(560px,calc(100% - 32px));left:50%;right:auto;transform:translateX(-50%)}}
 `}</style><SwipeStage images={images} index={index} setIndex={setIndex}><div className="yri-shade"/><div className="yri-count">Interior {index+1} / {images.length}</div><button className="yri-close" onClick={()=>setOpen(false)} aria-label="Close inspiration"><X size={20}/></button><div className="yri-controls"><button className="yri-control" onClick={()=>setSaved(s=>{const n=new Set(s);n.has(index)?n.delete(index):n.add(index);return n})} aria-label="Save interior"><Heart size={19} fill={saved.has(index)?"currentColor":"none"}/></button><button className="yri-scan" onClick={scan}><ScanLine size={18}/>Scan this room</button><button className="yri-control" onClick={()=>setGrid(true)} aria-label="Browse all interiors"><ChevronUp size={20}/></button></div></SwipeStage>{grid&&<div className="yri-grid"><div className="yri-grid-head"><b>INTERIOR INSPIRATION</b><button className="yri-grid-close" onClick={()=>setGrid(false)}><X size={18}/></button></div><div className="yri-cosmos">{images.map((src,i)=><button className="yri-tile" key={`${src}-${i}`} onClick={()=>select(i)}><img src={src} alt={`Interior inspiration ${i+1}`} loading={i<8?"eager":"lazy"}/></button>)}</div></div>}</div>
}
function SwipeStage({images,index,setIndex,children}:{images:string[];index:number;setIndex:(n:number)=>void;children:React.ReactNode}){const[start,setStart]=useState<{x:number;y:number}|null>(null);return <div className="yri-stage" onTouchStart={e=>setStart({x:e.touches[0].clientX,y:e.touches[0].clientY})} onTouchEnd={e=>{if(!start)return;const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){setIndex((index+(dx<0?1:-1)+images.length)%images.length)}else if(dy<-55){window.dispatchEvent(new CustomEvent("ynot:room-inspiration-grid"))}setStart(null)}}><div className="yri-slide"><img src={images[index]} alt={`Interior inspiration ${index+1}`} draggable={false}/></div>{children}</div>}
