"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {ChevronUp,Play} from "lucide-react";
type Item={id:string;type:"photo"|"video";src:string;thumb:string;alt?:string;source?:string};
const FALLBACK=["IMG_6763.jpeg","IMG_6764.jpeg","IMG_6765.jpeg"].map((file,i)=>({id:`fallback-${i}`,type:"photo" as const,src:`https://iycxkwoxbkanfyraohge.supabase.co/storage/v1/object/public/ad-creatives/${file}`,thumb:`https://iycxkwoxbkanfyraohge.supabase.co/storage/v1/object/public/ad-creatives/${file}`,alt:"Interior inspiration"}));
export default function RoomInspirationStrip(){
 const[items,setItems]=useState<Item[]>(FALLBACK),[host,setHost]=useState<HTMLElement|null>(null),[ready,setReady]=useState(false);
 useEffect(()=>{let alive=true;const load=async()=>{try{const [dr,pr]=await Promise.allSettled([fetch('/api/room/drive-interiors',{cache:'no-store'}),fetch('/api/room/inspiration',{cache:'force-cache'})]);const d=dr.status==='fulfilled'&&dr.value.ok?await dr.value.json():{};const p=pr.status==='fulfilled'&&pr.value.ok?await pr.value.json():{};const next=[...(Array.isArray(d.items)?d.items:[]),...(Array.isArray(p.items)?p.items:[]),...FALLBACK] as Item[];const seen=new Set<string>();const unique=next.filter(x=>x?.id&&x?.src&&!seen.has(x.id)&&(seen.add(x.id),true));if(alive)setItems(unique)}catch{}finally{if(alive)setReady(true)}};void load();return()=>{alive=false}},[]);
 useEffect(()=>{let frame=0;const mount=()=>{const search=document.querySelector<HTMLElement>('.yr-room-search');let h=document.getElementById('yr-inspo-strip-host') as HTMLElement|null;if(!h){h=document.createElement('div');h.id='yr-inspo-strip-host';document.body.appendChild(h)}// Use a separate React-safe host. Position after search visually without moving React-owned elements.
  if(search){const r=search.getBoundingClientRect();h.style.position='absolute';h.style.top=`${window.scrollY+r.bottom+12}px`;h.style.left='0';h.style.width='100%';h.style.zIndex='80'}else{h.style.position='fixed';h.style.top='auto';h.style.bottom='calc(16px + env(safe-area-inset-bottom))';h.style.left='8px';h.style.width='calc(100% - 16px)';h.style.zIndex='80'}if(h!==host)setHost(h)};
  mount();const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(mount)};const observer=new MutationObserver(update);observer.observe(document.body,{subtree:true,childList:true});window.addEventListener('resize',update);window.addEventListener('scroll',update,true);return()=>{observer.disconnect();cancelAnimationFrame(frame);window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true)}},[host]);
 if(!host)return null;
 const open=(i:number)=>window.dispatchEvent(new CustomEvent('ynot:room-inspiration',{detail:{pexelsId:items[i]?.id,index:i}}));
 return createPortal(<section className="yr-inspo-strip"><div className="yr-inspo-head"><div><small>INSPIRATION · {ready?`${items.length} SPACES`:'LOADING'}</small><b>Explore interiors</b></div><button type="button" onClick={()=>open(0)} aria-label="Open inspiration feed"><ChevronUp size={16}/></button></div><div className="yr-inspo-rail">{items.slice(0,40).map((x,i)=><button type="button" key={x.id} className={`yr-inspo-tile n${i%6}`} onClick={()=>open(i)}>{x.type==='video'?<><img src={x.thumb||x.src} alt={x.alt||'Home inspiration'} loading={i<5?'eager':'lazy'}/><span><Play size={11} fill="currentColor"/></span></>:<img src={x.thumb||x.src} alt={x.alt||'Home inspiration'} loading={i<5?'eager':'lazy'}/>}</button>)}</div><style jsx>{`.yr-inspo-strip{position:relative;z-index:18;width:min(900px,calc(100vw - 24px));margin:0 auto 34px;color:#fff}.yr-inspo-head{display:flex;align-items:end;justify-content:space-between;padding:0 4px 11px}.yr-inspo-head small{display:block;font-size:8px;letter-spacing:.18em;opacity:.55}.yr-inspo-head b{display:block;margin-top:3px;font-size:17px;letter-spacing:-.025em}.yr-inspo-head button{width:34px;height:34px;border-radius:50%;border:1px solid rgba(255,255,255,.16);background:rgba(30,30,30,.45);color:#fff;display:grid;place-items:center;backdrop-filter:blur(18px)}.yr-inspo-rail{display:flex;gap:9px;overflow-x:auto;scrollbar-width:none;padding:0 3px 4px;align-items:center}.yr-inspo-rail::-webkit-scrollbar{display:none}.yr-inspo-tile{position:relative;flex:0 0 116px;height:146px;padding:0;border:0;border-radius:17px;overflow:hidden;background:rgba(255,255,255,.08)}.yr-inspo-tile.n1,.yr-inspo-tile.n4{height:116px}.yr-inspo-tile.n2{flex-basis:150px;height:126px}.yr-inspo-tile img{width:100%;height:100%;object-fit:cover;display:block}.yr-inspo-tile span{position:absolute;right:7px;bottom:7px;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:rgba(0,0,0,.34);backdrop-filter:blur(10px)}@media(max-width:700px){.yr-inspo-strip{width:calc(100vw - 16px);margin-bottom:26px}.yr-inspo-tile{flex-basis:104px;height:132px}.yr-inspo-tile.n1,.yr-inspo-tile.n4{height:104px}.yr-inspo-tile.n2{flex-basis:136px;height:116px}}`}</style></section>,host)
}
