'use client';
import {useEffect,useState} from 'react';
export default function RoomEntryGate(){
 const[open,setOpen]=useState(true),[waiting,setWaiting]=useState(false);
 useEffect(()=>{const ready=()=>{setWaiting(false);setOpen(false)};const fail=()=>setWaiting(false);window.addEventListener('ynot:room-camera-ready',ready);window.addEventListener('ynot:room-camera-error',fail);return()=>{window.removeEventListener('ynot:room-camera-ready',ready);window.removeEventListener('ynot:room-camera-error',fail)}},[]);
 useEffect(()=>{const click=(e:MouseEvent)=>{if((e.target as Element|null)?.closest?.('.ro-go,.ro-skip'))window.dispatchEvent(new Event('ynot:room-onboarding-complete'))};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true)},[]);
 if(!open)return null;
 return <div style={{position:'fixed',inset:0,zIndex:12000,display:'grid',placeItems:'center',padding:24,background:'#f4f1eb',color:'#171513'}}><div style={{width:'min(420px,100%)',textAlign:'center'}}><div style={{fontSize:11,letterSpacing:'.28em',fontWeight:800,marginBottom:18}}>YNOT ROOM</div><h1 style={{fontSize:'clamp(38px,10vw,56px)',lineHeight:.94,letterSpacing:'-.055em',margin:'0 0 18px'}}>See your space.<br/><span style={{opacity:.42}}>Shop what belongs.</span></h1><p style={{fontSize:15,lineHeight:1.55,opacity:.58,margin:'0 auto 28px',maxWidth:350}}>Allow access once to prepare the live Room experience. The introduction will appear next, with your Room ready behind it.</p><button type="button" disabled={waiting} onClick={()=>{setWaiting(true);window.dispatchEvent(new Event('ynot:room-camera-preview'))}} style={{width:'100%',height:64,border:0,borderRadius:999,background:'#191715',color:'#fff',fontSize:16,fontWeight:800}}>{waiting?'Opening…':'Continue to YNOT Room'}</button></div></div>
}
