"use client";
import {useEffect,useState} from "react";
import {Crown,ScanSearch,Shirt,Sparkles,X} from "lucide-react";

const FREE_LIMIT=150;
export default function RoomPlus(){
 const[open,setOpen]=useState(false);const[locked,setLocked]=useState(0);
 useEffect(()=>{const show=(e:Event)=>{const d=(e as CustomEvent).detail||{};setLocked(Number(d.locked||0));setOpen(true)};window.addEventListener("ynot:room-plus",show);return()=>window.removeEventListener("ynot:room-plus",show)},[]);
 if(!open)return null;
 return <div className="rp-backdrop" onClick={()=>setOpen(false)}><section className="rp-card" onClick={e=>e.stopPropagation()}><button className="rp-close" onClick={()=>setOpen(false)}><X size={17}/></button><div className="rp-mark"><Crown size={22}/></div><h2>YNOT+</h2><p className="rp-sub">Discover without limits. Generate what you imagine.</p><div className="rp-perks"><div><ScanSearch/><span><b>Unlimited Room discovery</b><small>Unlock every product YNOT finds in your scans.</small></span></div><div><Shirt/><span><b>Clothes discovery</b><small>Scan clothes on people and discover matching pieces.</small></span></div><div><Sparkles/><span><b>AI generations</b><small>Generate room ideas, looks and future visual experiences.</small></span></div></div>{locked>0&&<div className="rp-found">+{locked} more matches waiting</div>}<button className="rp-cta" onClick={()=>window.dispatchEvent(new CustomEvent("ynot:room-plus-pricing"))}>See YNOT+ plans</button><small className="rp-note">Shopping stays free. YNOT+ unlocks deeper discovery and generations.</small></section><style jsx>{`.rp-backdrop{position:fixed;z-index:7000;inset:0;background:rgba(0,0,0,.48);backdrop-filter:blur(18px);display:grid;place-items:end center;padding:14px}.rp-card{position:relative;width:min(440px,100%);border:1px solid rgba(255,255,255,.16);border-radius:30px;padding:24px 18px 20px;background:rgba(16,17,17,.9);box-shadow:0 24px 80px rgba(0,0,0,.45);color:#fff}.rp-close{position:absolute;right:14px;top:14px;width:36px;height:36px;border-radius:50%;border:1px solid rgba(255,255,255,.13);background:rgba(255,255,255,.06);color:#fff;display:grid;place-items:center}.rp-mark{width:48px;height:48px;border-radius:16px;border:1px solid rgba(255,255,255,.15);display:grid;place-items:center;background:rgba(255,255,255,.07)}h2{font-size:29px;margin:12px 0 3px}.rp-sub{opacity:.58;font-size:13px;margin:0 0 18px}.rp-perks{display:grid;gap:9px}.rp-perks>div{display:flex;gap:12px;align-items:center;border:1px solid rgba(255,255,255,.1);border-radius:18px;padding:12px;background:rgba(255,255,255,.035)}.rp-perks :global(svg){width:20px;flex:none}.rp-perks span{display:grid;gap:2px}.rp-perks b{font-size:13px}.rp-perks small{font-size:10px;opacity:.5;line-height:1.35}.rp-found{text-align:center;margin:14px 0 9px;font-size:12px;opacity:.75}.rp-cta{width:100%;border:0;border-radius:999px;padding:14px;background:#fff;color:#111;font-weight:750;font-size:14px}.rp-note{display:block;text-align:center;margin-top:10px;font-size:9px;opacity:.4}@media(min-width:700px){.rp-backdrop{place-items:center}.rp-card{padding:27px 22px 22px}}`}</style></div>
}
export {FREE_LIMIT};
