"use client";
import {useEffect} from "react";

export default function RoomProductFullscreen(){
 useEffect(()=>{
  let startX=0,startY=0,active:HTMLElement|null=null;
  const visited:string[]=[];let cursor=-1;
  const title=()=>document.querySelector<HTMLElement>(".yr-modal .yr-card-title")?.textContent?.trim()||"";
  const clickTitle=(wanted:string)=>{const all=[...document.querySelectorAll<HTMLButtonElement>(".yr-bubble")];const hit=all.find(b=>b.querySelector(".yr-bubble-title")?.textContent?.trim()===wanted);hit?.click();return!!hit};
  const seed=()=>{const t=title();if(t&&visited[cursor]!==t){const existing=visited.indexOf(t);if(existing>=0)cursor=existing;else{visited.splice(cursor+1);visited.push(t);cursor=visited.length-1}}};
  const ensureHandle=()=>{const card=document.querySelector<HTMLElement>(".yr-modal .yr-card");if(!card||card.querySelector(".yr-pull-down"))return;const handle=document.createElement("button");handle.type="button";handle.className="yr-pull-down";handle.setAttribute("aria-label","Swipe down or tap to return to your picture");handle.innerHTML='<span></span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 9 6 6 6-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';handle.onclick=()=>card.closest<HTMLElement>(".yr-modal")?.click();card.prepend(handle)};
  const observer=new MutationObserver(ensureHandle);observer.observe(document.body,{subtree:true,childList:true});ensureHandle();
  const down=(e:TouchEvent)=>{const card=(e.target as Element|null)?.closest<HTMLElement>(".yr-modal .yr-card");if(!card)return;active=card;startX=e.touches[0]?.clientX||0;startY=e.touches[0]?.clientY||0;seed()};
  const up=(e:TouchEvent)=>{if(!active)return;const target=e.target as Element|null,x=e.changedTouches[0]?.clientX||0,y=e.changedTouches[0]?.clientY||0,dx=x-startX,dy=y-startY,card=active;active=null;
   if(target?.closest(".yr-similar"))return;
   if(dy>85&&Math.abs(dy)>Math.abs(dx)*1.15&&card.scrollTop<=18){card.classList.add("yr-swipe-down");window.setTimeout(()=>card.closest<HTMLElement>(".yr-modal")?.click(),120);return}
   if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.15)return;const forward=dx<0;card.classList.add(forward?"yr-swipe-left":"yr-swipe-right");window.setTimeout(()=>{seed();if(!forward&&cursor>0){cursor--;clickTitle(visited[cursor])}else if(forward&&cursor<visited.length-1){cursor++;clickTitle(visited[cursor])}else if(forward){const current=title(),bubbles=[...document.querySelectorAll<HTMLButtonElement>(".yr-bubble")],currentIndex=bubbles.findIndex(b=>b.querySelector(".yr-bubble-title")?.textContent?.trim()===current),next=bubbles[currentIndex>=0?currentIndex+1:0];if(next){const nextTitle=next.querySelector(".yr-bubble-title")?.textContent?.trim()||"";if(nextTitle){visited.splice(cursor+1);visited.push(nextTitle);cursor++;next.click()}}else{const choices=[...card.querySelectorAll<HTMLButtonElement>(".yr-similar button")];choices[0]?.click()}}card.classList.remove("yr-swipe-left","yr-swipe-right")},115)};
  document.addEventListener("touchstart",down,{passive:true});document.addEventListener("touchend",up,{passive:true});return()=>{observer.disconnect();document.removeEventListener("touchstart",down);document.removeEventListener("touchend",up)};
 },[]);
 return <style jsx global>{`
 .yr-modal{padding:0!important;place-items:stretch!important;background:rgba(4,6,6,.26)!important;backdrop-filter:blur(24px) saturate(125%)!important;-webkit-backdrop-filter:blur(24px) saturate(125%)!important;overflow:hidden!important}
 .yr-modal .yr-card{box-sizing:border-box!important;width:100%!important;max-width:none!important;height:100dvh!important;min-height:0!important;border-radius:0!important;padding:max(18px,env(safe-area-inset-top)) clamp(16px,4vw,34px) max(40px,calc(env(safe-area-inset-bottom) + 24px))!important;display:flex!important;flex-direction:column!important;overflow-x:hidden!important;overflow-y:auto!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior-y:contain!important;background:rgba(255,255,255,.055)!important;border:0!important;box-shadow:inset 0 1px rgba(255,255,255,.11)!important;backdrop-filter:blur(34px) saturate(145%)!important;-webkit-backdrop-filter:blur(34px) saturate(145%)!important;touch-action:pan-y!important;transition:transform .14s ease,opacity .14s ease!important}
 .yr-pull-down{flex:0 0 auto;position:sticky;top:0;z-index:8;align-self:center;width:52px;height:30px;margin:-7px auto 5px;border:0;background:transparent;color:rgba(255,255,255,.72);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1px}.yr-pull-down span{width:30px;height:3px;border-radius:999px;background:rgba(255,255,255,.38)}.yr-pull-down svg{width:17px;height:17px}.yr-modal .yr-card.yr-swipe-down{transform:translateY(7%);opacity:.55}
 .yr-modal .yr-card-img{flex:0 0 auto!important;width:100%!important;max-width:760px!important;height:min(56dvh,680px)!important;min-height:320px!important;aspect-ratio:auto!important;object-fit:contain!important;margin:12px auto 0!important;border-radius:28px!important;background:rgba(255,255,255,.025)!important}
 .yr-modal .yr-card-title{flex:0 0 auto!important;font-size:clamp(24px,6vw,38px)!important;line-height:1.08!important;letter-spacing:-.035em!important;max-height:none!important;height:auto!important;overflow:visible!important;white-space:normal!important;text-overflow:clip!important;margin:20px 0 8px!important;max-width:760px!important;padding:0 1px!important}.yr-modal .yr-card>b{flex:0 0 auto!important;font-size:18px!important}.yr-modal .yr-actions{flex:0 0 auto!important;width:100%!important;max-width:760px!important;margin-top:18px!important}.yr-modal .yr-pill{min-height:48px!important}
 .yr-modal .yr-similar{box-sizing:border-box!important;flex:0 0 auto!important;width:100%!important;max-width:none!important;min-height:92px!important;margin:22px 0 0!important;padding:7px 4px 18px!important;display:flex!important;flex-wrap:nowrap!important;align-items:center!important;gap:14px!important;overflow-x:auto!important;overflow-y:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior-x:contain!important;touch-action:pan-x!important;scroll-snap-type:x proximity!important;scrollbar-width:none!important}.yr-modal .yr-similar::-webkit-scrollbar{display:none}.yr-modal .yr-similar button{flex:0 0 auto!important;scroll-snap-align:start!important}.yr-modal .yr-similar img{display:block!important;width:68px!important;height:68px!important;border-radius:50%!important;object-fit:contain!important;border:1px solid rgba(255,255,255,.16)!important;background:rgba(255,255,255,.035)!important}.yr-modal .yr-card:after{content:"Swipe for next match";flex:0 0 auto!important;order:99;display:block;text-align:center;margin:18px auto 12px;font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.38)}.yr-modal .yr-card.yr-swipe-left{transform:translateX(-5%);opacity:.68}.yr-modal .yr-card.yr-swipe-right{transform:translateX(5%);opacity:.68}
 @media(max-width:700px){.yr-modal .yr-card-img{height:auto!important;min-height:0!important;max-height:none!important;aspect-ratio:4/5!important}.yr-modal .yr-card-title{font-size:30px!important;margin-top:22px!important}.yr-modal .yr-similar{min-height:100px!important;padding-bottom:22px!important}}
 @media(min-width:800px){.yr-modal{padding:22px!important;place-items:center!important}.yr-modal .yr-card{width:min(880px,94vw)!important;height:min(900px,94vh)!important;min-height:0!important;border-radius:38px!important;border:1px solid rgba(255,255,255,.14)!important;padding:24px 28px 34px!important}.yr-modal .yr-similar{max-width:760px!important}}
 `}</style>
}
