"use client";
import {useEffect,useState} from "react";
import {ChevronUp,Play} from "lucide-react";
type Item={id:string;type:"photo"|"video";src:string;thumb:string;alt?:string};
export default function RoomInspirationStrip(){
 const[items,setItems]=useState<Item[]>([]);
 useEffect(()=>{fetch("/api/room/inspiration").then(r=>r.ok?r.json():null).then(d=>setItems(Array.isArray(d?.items)?d.items.slice(0,30):[])).catch(()=>{})},[]);
 useEffect(()=>{const mount=()=>{const search=document.querySelector<HTMLElement>(".yr-room-search"),strip=document.querySelector<HTMLElement>(".yr-inspo-strip");if(search&&strip&&strip.previousElementSibling!==search)search.insertAdjacentElement("afterend",strip)};const o=new MutationObserver(mount);o.observe(document.body,{subtree:true,childList:true});mount();return()=>o.disconnect()},[]);
 if(!items.length)return null;
 const open=(i:number)=>window.dispatchEvent(new CustomEvent("ynot:room-inspiration",{detail:{index:i}}));
 return <section className="yr-inspo-strip"><div className="yr-inspo-head"><div><small>INSPIRATION</small><b>Explore spaces</b></div><button onClick={()=>open(0)} aria-label="Open inspiration"><ChevronUp size={16}/></button></div><div className="yr-inspo-rail">{items.map((x,i)=><button key={x.id} className={`yr-inspo-tile n${i%6}`} onClick={()=>open(i)}>{x.type==="video"?<><img src={x.thumb} alt={x.alt||"Home inspiration"}/><span><Play size={11} fill="currentColor"/></span></>:<img src={x.thumb||x.src} alt={x.alt||"Home inspiration"}/>}</button>)}</div><style jsx>{`.yr-inspo-strip{position:relative;z-index:18;width:min(900px,calc(100vw - 24px));margin:0 auto 34px;color:#fff}.yr-inspo-head{display:flex;align-items:end;justify-content:space-between;padding:0 4px 11px}.yr-inspo-head small{display:block;font-size:8px;letter-spacing:.18em;opacity:.42}.yr-inspo-head b{display:block;margin-top:3px;font-size:17px;letter-spacing:-.025em}.yr-inspo-head button{width:34px;height:34px;border-radius:50%;border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.055);color:#fff;display:grid;place-items:center;backdrop-filter:blur(18px)}.yr-inspo-rail{display:flex;gap:9px;overflow-x:auto;scrollbar-width:none;padding:0 3px 4px;align-items:center}.yr-inspo-rail::-webkit-scrollbar{display:none}.yr-inspo-tile{position:relative;flex:0 0 116px;height:146px;padding:0;border:0;border-radius:17px;overflow:hidden;background:rgba(255,255,255,.05)}.yr-inspo-tile.n1,.yr-inspo-tile.n4{height:116px}.yr-inspo-tile.n2{flex-basis:150px;height:126px}.yr-inspo-tile img{width:100%;height:100%;object-fit:cover;display:block}.yr-inspo-tile span{position:absolute;right:7px;bottom:7px;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:rgba(0,0,0,.34);backdrop-filter:blur(10px)}@media(max-width:700px){.yr-inspo-strip{width:calc(100vw - 16px);margin-bottom:26px}.yr-inspo-tile{flex-basis:104px;height:132px}.yr-inspo-tile.n1,.yr-inspo-tile.n4{height:104px}.yr-inspo-tile.n2{flex-basis:136px;height:116px}}`}</style></section>
}
