import {NextRequest,NextResponse} from "next/server";
import {adminDb,adminErrorStatus,requireYnotAdmin} from "@/lib/ynot/admin-server";
import {MARKET_CATEGORIES,RESEARCH_AXES,scoreMarket,productReasoning,combinationCandidates,optionalAiJson,inferArchetypes,inferAudience,type CatalogueProduct} from "@/lib/ynot/commercial-intelligence";

export const runtime="nodejs";export const maxDuration=60;

type CatalogueSearch={products:CatalogueProduct[];searchedQueries:string[];rawCount:number;pagesFetched:number};
const STOP=new Set("the a an and or for with to of in on by from this that these those product products item items shop buy best good premium quality setup system accessories accessory".split(" "));
function tokens(text:string){return [...new Set(text.toLowerCase().replace(/[^a-z0-9 ]/g," ").split(/\s+/).filter(w=>w.length>=3&&!STOP.has(w)))].slice(0,10)}
function relevance(p:CatalogueProduct,q:string){const t=tokens(q);if(!t.length)return 1;const hay=`${p.title||""} ${p.brand||""} ${(p.tags||[]).join(" ")} ${p.description||""}`.toLowerCase();return t.reduce((n,w)=>n+(hay.includes(w)?1:0),0)/t.length}
function dedupe(rows:CatalogueProduct[]){const seen=new Set<string>();return rows.filter(p=>{const key=String(p.id||`${p.title}|${p.brand}`).toLowerCase();const alt=`${String(p.title||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}|${String(p.brand||"").toLowerCase()}`;if(seen.has(key)||seen.has(alt))return false;seen.add(key);seen.add(alt);return true})}
function diversify(rows:CatalogueProduct[],limit:number){const counts=new Map<string,number>(),first:CatalogueProduct[]=[],overflow:CatalogueProduct[]=[];for(const p of rows){const brand=String(p.brand||"unknown").toLowerCase();const n=counts.get(brand)||0;if(n<4){first.push(p);counts.set(brand,n+1)}else overflow.push(p)}return [...first,...overflow].slice(0,limit)}
function queryVariants(q:string){const clean=q.trim().replace(/\s+/g," ");const core=tokens(clean).join(" ")||clean;const variants=[clean,core,`${core} accessories`,`${core} professional`,`${core} tools`,`${core} setup`,`${core} smart`,`${core} premium`];return [...new Set(variants.map(x=>x.trim()).filter(Boolean))].slice(0,8)}
async function catalogPage(origin:string,q:string,cursor?:string){const u=new URL("/api/catalog",origin);u.searchParams.set("q",q);u.searchParams.set("source","shopify");u.searchParams.set("country","FR");if(cursor)u.searchParams.set("cursor",cursor);const r=await fetch(u,{cache:"no-store",headers:{"x-ynot-research":"brain"}});const d=await r.json().catch(()=>({}));const rows:(CatalogueProduct[])=(Array.isArray(d?.products)?d.products:[]).filter((p:CatalogueProduct)=>p?.id&&p?.title&&p?.image&&p?.url&&p.url!=="#");return {rows,cursor:String(d?.pagination?.next_cursor||""),hasNext:Boolean(d?.pagination?.has_next_page)} }
async function catalogue(origin:string,q:string,limit=96):Promise<CatalogueSearch>{
 const fallbackQueries=queryVariants(q);
 const aiQueries=await optionalAiJson("You generate Shopify catalogue search queries for commercial research. Return JSON with a queries array of 4-8 short, specific searches. Stay tightly anchored to the user's niche; include useful subtypes/accessories/professional variants, but do not switch categories.",{niche:q}, {queries:fallbackQueries});
 const searchedQueries=[...new Set([q,...(Array.isArray((aiQueries.value as any)?.queries)?(aiQueries.value as any).queries:[]),...fallbackQueries].map(x=>String(x||"").trim()).filter(Boolean))].slice(0,8);
 const first=await Promise.all(searchedQueries.map(s=>catalogPage(origin,s).catch(()=>({rows:[] as CatalogueProduct[],cursor:"",hasNext:false}))));
 let rows=first.flatMap(x=>x.rows),pagesFetched=first.length;
 const secondTargets=first.map((x,i)=>({x,i})).filter(v=>v.x.hasNext&&v.x.cursor).slice(0,6);
 if(secondTargets.length){const second=await Promise.all(secondTargets.map(({x,i})=>catalogPage(origin,searchedQueries[i],x.cursor).catch(()=>({rows:[] as CatalogueProduct[],cursor:"",hasNext:false}))));rows.push(...second.flatMap(x=>x.rows));pagesFetched+=second.length}
 const rawCount=rows.length;let unique=dedupe(rows);
 unique.sort((a,b)=>relevance(b,q)-relevance(a,q));
 const relevant=unique.filter(p=>relevance(p,q)>0);if(relevant.length>=12)unique=[...relevant,...unique.filter(p=>relevance(p,q)===0)];
 return {products:diversify(unique,Math.max(12,Math.min(160,limit))),searchedQueries,rawCount,pagesFetched};
}
async function upsertNode(row:any){const existing=await adminDb(`ynot_market_nodes?parent_id=${row.parent_id?`eq.${row.parent_id}`:"is.null"}&name=eq.${encodeURIComponent(row.name)}&select=id&limit=1`);if(existing?.[0]){const updated=await adminDb(`ynot_market_nodes?id=eq.${existing[0].id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({...row,updated_at:new Date().toISOString()})});return updated?.[0]}const created=await adminDb("ynot_market_nodes",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});return created?.[0]}

export async function POST(req:NextRequest){try{const admin=await requireYnotAdmin(req);const body=await req.json().catch(()=>({}));const action=String(body?.action||"overview");const origin=req.nextUrl.origin;
 if(action==="bootstrap") {for(const name of MARKET_CATEGORIES){await upsertNode({parent_id:null,node_type:"category",name,status:"hypothesis",depth:0,coverage_score:0,created_by:admin.profile.id})}return NextResponse.json({ok:true,count:MARKET_CATEGORIES.length})}
 if(action==="overview"){const nodes=await adminDb("ynot_market_nodes?select=*&order=opportunity_score.desc&limit=300");const coverage=await adminDb("ynot_coverage_map?select=*&limit=300");return NextResponse.json({ok:true,nodes:nodes||[],coverage:coverage||[],categories:MARKET_CATEGORIES,axes:RESEARCH_AXES})}
 if(action==="evaluate"){
  const name=String(body?.name||"").trim().slice(0,140),query=String(body?.query||name).trim().slice(0,500),parentId=body?.parentId||null;if(!name||!query)return NextResponse.json({ok:false,error:"NAME_AND_QUERY_REQUIRED"},{status:400});
  const search=await catalogue(origin,query,120),products=search.products;const base=scoreMarket(products,Math.max(68,Math.min(96,Number(body?.novelty||82))));const fallback={name,query,archetypes:inferArchetypes(`${name} ${query}`),audiences:inferAudience(`${name} ${query}`),whyPeopleCare:"The niche has a distinct use case with catalogue evidence.",whyNow:"It can be introduced through discovery, utility or specialist-content angles.",skeptic:{risks:products.length<6?["Catalogue evidence is still thin."]:[],verdict:base.evidence>=45?"continue":"hold"},angles:["I didn't know this existed","specialist version vs generic version","complete setup","problem before product","premium/pro version"]};
  const ai=await optionalAiJson("You are YNOT's commercial research analyst. Return only JSON. Classify the niche, identify audiences, why people care, why now, strong content/ad angles, and a skeptical counter-case. Do not invent catalogue evidence; use only supplied metrics/products.",{name,query,metrics:base,searchQueries:search.searchedQueries,products:products.slice(0,18).map(p=>({title:p.title,brand:p.brand,price:p.price,tags:p.tags}))},fallback);
  const dossier:any=ai.value;const node=await upsertNode({parent_id:parentId,node_type:parentId?"micro_niche":"niche",name,query,archetypes:dossier.archetypes||fallback.archetypes,audience:dossier.audiences||fallback.audiences,intents:[],status:base.evidence>=45?"validated":"hypothesis",depth:parentId?1:0,coverage_score:Math.min(100,products.length),opportunity_score:base.opportunity,evidence_score:base.evidence,discovery_score:base.discovery,conversion_score:base.conversion,organic_score:base.organic,ynot_fit_score:base.ynot,cross_sell_score:base.crossSell,high_ticket_score:base.highTicket,repeat_purchase_score:base.repeat,competition_risk:base.merchantCount>10?"high":base.merchantCount>4?"medium":"low",price_min:base.price.min,price_median:base.price.median,price_max:base.price.max,merchant_count:base.merchantCount,product_count:base.productCount,reasoning:{...dossier,aiUsed:ai.usedAi,searchMeta:{queries:search.searchedQueries,rawCount:search.rawCount,pagesFetched:search.pagesFetched}},evidence:{metrics:base,sample:products.slice(0,20)},created_by:admin.profile.id});
  return NextResponse.json({ok:true,node,products:products.slice(0,48),metrics:base,dossier,aiUsed:ai.usedAi,searchMeta:{queries:search.searchedQueries,rawCount:search.rawCount,uniqueCount:products.length,pagesFetched:search.pagesFetched}})
 }
 if(action==="products"){
  const nodeId=String(body?.nodeId||"");const nodes=await adminDb(`ynot_market_nodes?id=eq.${nodeId}&select=*&limit=1`);const node=nodes?.[0];if(!node)return NextResponse.json({ok:false,error:"NODE_NOT_FOUND"},{status:404});const search=await catalogue(origin,node.query||node.name,120),products=search.products;const analyzed=[] as any[];
  for(const p of products.slice(0,60)){const intel=productReasoning(p,node.name);const rows=await adminDb("ynot_product_intelligence?on_conflict=source,product_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({source:p.source||"shopify",product_id:String(p.id),title:p.title,merchant:p.brand,url:p.url,image:p.image,price:p.price,currency:p.currency,primary_market_node_id:nodeId,archetypes:intel.archetypes,audiences:intel.audience,problems:intel.problems,use_cases:intel.useCases,organic_hooks:intel.organicHooks,paid_hooks:intel.paidHooks,ynot_hooks:intel.ynotHooks,objections:intel.objections,cross_sell_queries:intel.crossSellQueries,visual_score:intel.visualScore,advertability_score:intel.advertabilityScore,novelty_score:intel.noveltyScore,confidence:intel.confidence,reasoning:{why:intel.why,searchQuery:node.query||node.name},raw_product:p,updated_at:new Date().toISOString()})});analyzed.push({...p,intelligence:intel,intelligenceId:rows?.[0]?.id})}
  return NextResponse.json({ok:true,node,products:analyzed,searchMeta:{queries:search.searchedQueries,rawCount:search.rawCount,uniqueCount:products.length,pagesFetched:search.pagesFetched}})
 }
 if(action==="combinations"){
  const nodeId=String(body?.nodeId||"");const nodes=await adminDb(`ynot_market_nodes?id=eq.${nodeId}&select=*&limit=1`);const node=nodes?.[0];if(!node)return NextResponse.json({ok:false,error:"NODE_NOT_FOUND"},{status:404});const search=await catalogue(origin,node.query||node.name,100);const enriched=search.products.slice(0,50).map(p=>({...p,intelligence:productReasoning(p,node.name)}));const combos=combinationCandidates(enriched,node.name);for(const c of combos){const created=await adminDb("ynot_product_clusters",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({market_node_id:nodeId,name:c.name,cluster_type:c.type,audience:(node.audience||[])[0]||null,moment:c.logic,strategy:{logic:c.logic},score:c.score})});const cluster=created?.[0];if(cluster)for(const p of c.products){const pi=await adminDb(`ynot_product_intelligence?product_id=eq.${encodeURIComponent(String(p.id))}&select=id&limit=1`);if(pi?.[0])await adminDb("ynot_cluster_products",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({cluster_id:cluster.id,product_intelligence_id:pi[0].id,role:"member",score:p.intelligence?.advertabilityScore||0})}).catch(()=>null)}}return NextResponse.json({ok:true,node,combinations:combos,searchMeta:{queries:search.searchedQueries,uniqueCount:search.products.length}})
 }
 if(action==="expand"){
  const nodeId=String(body?.nodeId||"");const nodes=await adminDb(`ynot_market_nodes?id=eq.${nodeId}&select=*&limit=1`);const node=nodes?.[0];if(!node)return NextResponse.json({ok:false,error:"NODE_NOT_FOUND"},{status:404});const axes=(body?.axes||RESEARCH_AXES.map(x=>x[0])).slice(0,12);const branches=[] as any[];for(const axisId of axes){const axis=RESEARCH_AXES.find(x=>x[0]===axisId);if(!axis)continue;const q=`${node.query||node.name} ${axis[2]}`;const search=await catalogue(origin,q,72),products=search.products;const s=scoreMarket(products,84);if(s.productCount<2)continue;const child=await upsertNode({parent_id:nodeId,node_type:node.depth>=1?"sub_micro_niche":"micro_niche",name:`${node.name} → ${axis[1]}`,query:q,archetypes:inferArchetypes(`${node.name} ${axis[1]}`),audience:node.audience||[],status:s.evidence>=40?"validated":"hypothesis",depth:Number(node.depth||0)+1,coverage_score:Math.min(100,s.productCount*2),opportunity_score:s.opportunity,evidence_score:s.evidence,discovery_score:s.discovery,conversion_score:s.conversion,organic_score:s.organic,ynot_fit_score:s.ynot,cross_sell_score:s.crossSell,high_ticket_score:s.highTicket,repeat_purchase_score:s.repeat,price_min:s.price.min,price_median:s.price.median,price_max:s.price.max,merchant_count:s.merchantCount,product_count:s.productCount,reasoning:{axis:axis[0],question:axis[2],searchMeta:{queries:search.searchedQueries,rawCount:search.rawCount}},evidence:{metrics:s,sample:products.slice(0,12)},created_by:admin.profile.id});branches.push({node:child,metrics:s,products:products.slice(0,10),searchMeta:{queries:search.searchedQueries,uniqueCount:products.length}})}
  await adminDb("ynot_coverage_map?on_conflict=market_node_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({market_node_id:nodeId,explored_queries:branches.length,validated_children:branches.filter(x=>x.metrics.evidence>=40).length,rejected_children:Math.max(0,axes.length-branches.length),product_sample_count:branches.reduce((n,x)=>n+x.metrics.productCount,0),coverage_percent:Math.min(100,branches.length/Math.max(1,axes.length)*100),novelty_gap:Math.max(0,100-branches.length/Math.max(1,axes.length)*100),last_explored_at:new Date().toISOString()})});return NextResponse.json({ok:true,parent:node,branches})
 }
 return NextResponse.json({ok:false,error:"UNKNOWN_ACTION"},{status:400})
}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"BRAIN_ERROR"},{status:adminErrorStatus(error)})}}