import {NextRequest,NextResponse} from "next/server";
import {adminDb,adminErrorStatus,requireYnotAdmin} from "@/lib/ynot/admin-server";
import {MARKET_CATEGORIES,RESEARCH_AXES,scoreMarket,productReasoning,optionalAiJson,researchMarketWithWeb,inferArchetypes,inferAudience,aiProductBatchIntelligence,aiCombinationPlan,type CatalogueProduct} from "@/lib/ynot/commercial-intelligence";

export const runtime="nodejs";
export const maxDuration=60;

type CatalogueSearch={products:CatalogueProduct[];searchedQueries:string[];rawCount:number;pagesFetched:number};
const STOP=new Set("the a an and or for with to of in on by from this that these those product products item items shop buy best good premium quality setup system accessories accessory".split(" "));
function tokens(text:string){return [...new Set(text.toLowerCase().replace(/[^a-z0-9 ]/g," ").split(/\s+/).filter(w=>w.length>=3&&!STOP.has(w)))].slice(0,12)}
function relevance(p:CatalogueProduct,q:string){const t=tokens(q);if(!t.length)return 1;const hay=`${p.title||""} ${p.brand||""} ${(p.tags||[]).join(" ")} ${p.description||""}`.toLowerCase();return t.reduce((n,w)=>n+(hay.includes(w)?1:0),0)/t.length}
function dedupe(rows:CatalogueProduct[]){const seen=new Set<string>();return rows.filter(p=>{const key=String(p.id||`${p.title}|${p.brand}`).toLowerCase();const alt=`${String(p.title||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}|${String(p.brand||"").toLowerCase()}`;if(seen.has(key)||seen.has(alt))return false;seen.add(key);seen.add(alt);return true})}
function diversify(rows:CatalogueProduct[],limit:number){const counts=new Map<string,number>(),first:CatalogueProduct[]=[],overflow:CatalogueProduct[]=[];for(const p of rows){const brand=String(p.brand||"unknown").toLowerCase(),n=counts.get(brand)||0;if(n<4){first.push(p);counts.set(brand,n+1)}else overflow.push(p)}return [...first,...overflow].slice(0,limit)}
function queryVariants(q:string){const clean=q.trim().replace(/\s+/g," "),core=tokens(clean).join(" ")||clean;return [...new Set([clean,core,`${core} replacement`,`${core} upgrade`,`${core} professional`,`${core} premium`,`${core} accessories`,`${core} maintenance`,`${core} diagnostic`,`${core} complete system`])].slice(0,10)}
async function catalogPage(origin:string,q:string,cursor?:string){const u=new URL("/api/catalog",origin);u.searchParams.set("q",q);u.searchParams.set("source","shopify");u.searchParams.set("country","FR");if(cursor)u.searchParams.set("cursor",cursor);const r=await fetch(u,{cache:"no-store",headers:{"x-ynot-research":"brain"}}),d=await r.json().catch(()=>({}));const rows:(CatalogueProduct[])=(Array.isArray(d?.products)?d.products:[]).filter((p:CatalogueProduct)=>p?.id&&p?.title&&p?.image&&p?.url&&p.url!=="#");return {rows,cursor:String(d?.pagination?.next_cursor||""),hasNext:Boolean(d?.pagination?.has_next_page)}}
async function catalogue(origin:string,q:string,limit=96,plannedQueries:string[]=[]):Promise<CatalogueSearch>{const fallbackQueries=queryVariants(q);let generated:string[]=[];if(!plannedQueries.length){const aiQueries=await optionalAiJson("Generate 8-12 commercially useful Shopify catalogue searches for this niche. Cover proven core products, upgrades, replacements, professional/high-ticket versions, accessories and overlooked adjacent needs. Return JSON {queries:string[]}.",{niche:q},{queries:fallbackQueries},{model:String(process.env.YNOT_PRODUCT_MODEL||"gpt-5.6-luna"),reasoning:"low"});generated=Array.isArray((aiQueries.value as any)?.queries)?(aiQueries.value as any).queries:[]}const searchedQueries=[...new Set([q,...plannedQueries,...generated,...fallbackQueries].map(x=>String(x||"").trim()).filter(Boolean))].slice(0,20);const first=await Promise.all(searchedQueries.map(s=>catalogPage(origin,s).catch(()=>({rows:[] as CatalogueProduct[],cursor:"",hasNext:false}))));let rows=first.flatMap(x=>x.rows),pagesFetched=first.length;const secondTargets=first.map((x,i)=>({x,i})).filter(v=>v.x.hasNext&&v.x.cursor).slice(0,10);if(secondTargets.length){const second=await Promise.all(secondTargets.map(({x,i})=>catalogPage(origin,searchedQueries[i],x.cursor).catch(()=>({rows:[] as CatalogueProduct[],cursor:"",hasNext:false}))));rows.push(...second.flatMap(x=>x.rows));pagesFetched+=second.length}const rawCount=rows.length;let unique=dedupe(rows);unique.sort((a,b)=>{const br=Math.max(relevance(b,q),...searchedQueries.slice(0,10).map(x=>relevance(b,x))),ar=Math.max(relevance(a,q),...searchedQueries.slice(0,10).map(x=>relevance(a,x)));return br-ar});const relevant=unique.filter(p=>Math.max(relevance(p,q),...searchedQueries.slice(0,10).map(x=>relevance(p,x)))>0);if(relevant.length>=12)unique=[...relevant,...unique.filter(p=>!relevant.includes(p))];return {products:diversify(unique,Math.max(12,Math.min(180,limit))),searchedQueries,rawCount,pagesFetched}}
async function upsertNode(row:any){const existing=await adminDb(`ynot_market_nodes?parent_id=${row.parent_id?`eq.${row.parent_id}`:"is.null"}&name=eq.${encodeURIComponent(row.name)}&select=id&limit=1`);if(existing?.[0]){const updated=await adminDb(`ynot_market_nodes?id=eq.${existing[0].id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({...row,updated_at:new Date().toISOString()})});return updated?.[0]}const created=await adminDb("ynot_market_nodes",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});return created?.[0]}
function mergeAiIntel(p:CatalogueProduct,market:string,ai:any){const base=productReasoning(p,market);if(!ai)return {...base,aiUsed:false};return {...base,aiUsed:true,relevance:ai.relevance,commercialPotential:ai.commercialPotential,highTicketFit:ai.highTicketFit,replicability:ai.replicability,confidence:ai.confidence??base.confidence,buyer:ai.buyer,jobToBeDone:ai.jobToBeDone,why:ai.whyItMaySell||base.why,whyItMaySell:ai.whyItMaySell,upgradeFrom:ai.upgradeFrom,upgradeTo:ai.upgradeTo,replacementTrigger:ai.replacementTrigger,proofNeeded:ai.proofNeeded||[],organicHooks:ai.organicHooks||base.organicHooks,paidHooks:ai.paidHooks||base.paidHooks,objections:ai.objections||base.objections,crossSellQueries:ai.crossSellQueries||base.crossSellQueries,evidenceClass:ai.evidenceClass||["catalogue_measured","model_hypothesis"],advertabilityScore:Math.round(((ai.commercialPotential||base.advertabilityScore)+(ai.replicability||base.advertabilityScore))/2)}}

export async function POST(req:NextRequest){try{const admin=await requireYnotAdmin(req),body=await req.json().catch(()=>({})),action=String(body?.action||"overview"),origin=req.nextUrl.origin;
 if(action==="bootstrap"){for(const name of MARKET_CATEGORIES)await upsertNode({parent_id:null,node_type:"category",name,status:"hypothesis",depth:0,coverage_score:0,created_by:admin.profile.id});return NextResponse.json({ok:true,count:MARKET_CATEGORIES.length})}
 if(action==="overview"){const nodes=await adminDb("ynot_market_nodes?select=*&order=opportunity_score.desc&limit=300"),coverage=await adminDb("ynot_coverage_map?select=*&limit=300");return NextResponse.json({ok:true,nodes:nodes||[],coverage:coverage||[],categories:MARKET_CATEGORIES,axes:RESEARCH_AXES,aiConfig:{researchModel:String(process.env.YNOT_RESEARCH_MODEL||process.env.YNOT_INTELLIGENCE_MODEL||"gpt-5.6-terra"),productModel:String(process.env.YNOT_PRODUCT_MODEL||"gpt-5.6-luna"),keyConfigured:Boolean(process.env.OPENAI_API_KEY)}})}
 if(action==="evaluate"){
  const name=String(body?.name||"").trim().slice(0,140),query=String(body?.query||name).trim().slice(0,500),parentId=body?.parentId||null;if(!name||!query)return NextResponse.json({ok:false,error:"NAME_AND_QUERY_REQUIRED"},{status:400});let parentName:string|null=null;if(parentId){const p=await adminDb(`ynot_market_nodes?id=eq.${encodeURIComponent(String(parentId))}&select=name&limit=1`);parentName=p?.[0]?.name||null}
  const marketResearch=await researchMarketWithWeb(name,query,parentName),researchPlan=marketResearch.value,search=await catalogue(origin,query,160,researchPlan.catalogueQueries||[]),products=search.products,base=scoreMarket(products,Math.max(68,Math.min(96,Number(body?.novelty||82))));
  const productAi=await aiProductBatchIntelligence(name,researchPlan,products.slice(0,60)),intelMap=new Map(productAi.items.map(x=>[String(x.productId),x]));const ranked=[...products].sort((a,b)=>{const A=intelMap.get(String(a.id)),B=intelMap.get(String(b.id));const sa=(A?.commercialPotential||0)*.42+(A?.highTicketFit||0)*.28+(A?.relevance||0)*.2+(A?.replicability||0)*.1,sb=(B?.commercialPotential||0)*.42+(B?.highTicketFit||0)*.28+(B?.relevance||0)*.2+(B?.replicability||0)*.1;return sb-sa});
  const fallback={name,query,archetypes:researchPlan.marketArchetypes?.length?researchPlan.marketArchetypes:inferArchetypes(`${name} ${query}`),audiences:researchPlan.buyerSegments?.map(x=>x.segment).filter(Boolean)||inferAudience(`${name} ${query}`),whyPeopleCare:researchPlan.summary||"The niche has a distinct use case with catalogue evidence.",whyNow:"Research identified replacement, upgrade, professional and accessory pathways before catalogue validation.",skeptic:{risks:products.length<10?["Catalogue evidence remains thin."]:[],verdict:base.evidence>=45?"continue":"hold"},angles:[...(researchPlan.contentAngles||[]),...(researchPlan.paidAngles||[])].slice(0,10),topProductIds:ranked.slice(0,8).map(p=>String(p.id))};
  const ai=await optionalAiJson("You are YNOT's senior commercial synthesis analyst. Synthesize current web research, real Shopify supply and AI product-portfolio ranking. Focus on which specific product families deserve testing, especially mid/high-ticket upgrade ladders, replacements, professionalization, system completion and pain escalation. Distinguish observed evidence from model hypotheses. Do not invent sales, ROAS or bestseller claims. Return JSON matching the fallback structure and include topProductIds.",{name,query,marketResearch:researchPlan,metrics:base,searchQueries:search.searchedQueries,products:ranked.slice(0,40).map(p=>({id:String(p.id),title:p.title,brand:p.brand,price:p.price,tags:p.tags,portfolio:intelMap.get(String(p.id))}))},fallback,{reasoning:"medium"});
  const dossier:any=ai.value,node=await upsertNode({parent_id:parentId,node_type:parentId?"micro_niche":"niche",name,query,archetypes:dossier.archetypes||fallback.archetypes,audience:dossier.audiences||fallback.audiences,intents:researchPlan.buyingMoments||[],status:base.evidence>=45?"validated":"hypothesis",depth:parentId?1:0,coverage_score:Math.min(100,products.length),opportunity_score:base.opportunity,evidence_score:base.evidence,discovery_score:base.discovery,conversion_score:base.conversion,organic_score:base.organic,ynot_fit_score:base.ynot,cross_sell_score:base.crossSell,high_ticket_score:base.highTicket,repeat_purchase_score:base.repeat,competition_risk:base.merchantCount>10?"high":base.merchantCount>4?"medium":"low",price_min:base.price.min,price_median:base.price.median,price_max:base.price.max,merchant_count:base.merchantCount,product_count:base.productCount,reasoning:{...dossier,aiUsed:ai.usedAi,aiDiagnostic:ai.diagnostic,productAiUsed:productAi.usedAi,productAiDiagnostic:productAi.diagnostic,marketResearch:researchPlan,researchUsedAi:marketResearch.usedAi,researchUsedWeb:marketResearch.usedWeb,researchDiagnostic:marketResearch.diagnostic,searchMeta:{queries:search.searchedQueries,rawCount:search.rawCount,pagesFetched:search.pagesFetched}},evidence:{metrics:base,sample:ranked.slice(0,24)},created_by:admin.profile.id});
  return NextResponse.json({ok:true,node,products:ranked.slice(0,60).map(p=>({...p,intelligence:mergeAiIntel(p,name,intelMap.get(String(p.id)))})),metrics:base,dossier,aiUsed:ai.usedAi,research:{usedAi:marketResearch.usedAi,usedWeb:marketResearch.usedWeb,diagnostic:marketResearch.diagnostic,...researchPlan},aiStatus:{research:marketResearch.diagnostic,portfolio:productAi.diagnostic,synthesis:ai.diagnostic},searchMeta:{queries:search.searchedQueries,rawCount:search.rawCount,uniqueCount:products.length,pagesFetched:search.pagesFetched}})
 }
 if(action==="products"){
  const nodeId=String(body?.nodeId||""),nodes=await adminDb(`ynot_market_nodes?id=eq.${nodeId}&select=*&limit=1`),node=nodes?.[0];if(!node)return NextResponse.json({ok:false,error:"NODE_NOT_FOUND"},{status:404});const planned=node?.reasoning?.marketResearch?.catalogueQueries||[],search=await catalogue(origin,node.query||node.name,160,planned),products=search.products,portfolio=await aiProductBatchIntelligence(node.name,node?.reasoning?.marketResearch||null,products.slice(0,60)),byId=new Map(portfolio.items.map(x=>[String(x.productId),x])),ranked=[...products].sort((a,b)=>(byId.get(String(b.id))?.commercialPotential||0)-(byId.get(String(a.id))?.commercialPotential||0)),analyzed:any[]=[];
  for(const p of ranked.slice(0,60)){const intel=mergeAiIntel(p,node.name,byId.get(String(p.id)));const rows=await adminDb("ynot_product_intelligence?on_conflict=source,product_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({source:p.source||"shopify",product_id:String(p.id),title:p.title,merchant:p.brand,url:p.url,image:p.image,price:p.price,currency:p.currency,primary_market_node_id:nodeId,archetypes:intel.archetypes,audiences:Array.isArray(intel.audience)?intel.audience:[intel.buyer].filter(Boolean),problems:intel.problems,use_cases:intel.useCases,organic_hooks:intel.organicHooks,paid_hooks:intel.paidHooks,ynot_hooks:intel.ynotHooks,objections:intel.objections,cross_sell_queries:intel.crossSellQueries,visual_score:intel.visualScore,advertability_score:intel.advertabilityScore,novelty_score:intel.noveltyScore,confidence:intel.confidence,reasoning:{why:intel.why,aiUsed:intel.aiUsed,commercialPotential:intel.commercialPotential,highTicketFit:intel.highTicketFit,replicability:intel.replicability,buyer:intel.buyer,jobToBeDone:intel.jobToBeDone,upgradeFrom:intel.upgradeFrom,upgradeTo:intel.upgradeTo,replacementTrigger:intel.replacementTrigger,proofNeeded:intel.proofNeeded,evidenceClass:intel.evidenceClass,aiDiagnostic:portfolio.diagnostic,searchQuery:node.query||node.name,marketResearch:node?.reasoning?.marketResearch||null},raw_product:p,updated_at:new Date().toISOString()})});analyzed.push({...p,intelligence:intel,intelligenceId:rows?.[0]?.id})}
  return NextResponse.json({ok:true,node,products:analyzed,research:node?.reasoning?.marketResearch||null,aiStatus:{portfolio:portfolio.diagnostic},searchMeta:{queries:search.searchedQueries,rawCount:search.rawCount,uniqueCount:products.length,pagesFetched:search.pagesFetched}})
 }
 if(action==="combinations"){
  const nodeId=String(body?.nodeId||""),nodes=await adminDb(`ynot_market_nodes?id=eq.${nodeId}&select=*&limit=1`),node=nodes?.[0];if(!node)return NextResponse.json({ok:false,error:"NODE_NOT_FOUND"},{status:404});const planned=node?.reasoning?.marketResearch?.catalogueQueries||[],search=await catalogue(origin,node.query||node.name,140,planned),portfolio=await aiProductBatchIntelligence(node.name,node?.reasoning?.marketResearch||null,search.products.slice(0,50)),byId=new Map(portfolio.items.map(x=>[String(x.productId),x])),enriched=search.products.slice(0,50).map(p=>({...p,intelligence:mergeAiIntel(p,node.name,byId.get(String(p.id)))})),plannedCombos=await aiCombinationPlan(node.name,node?.reasoning?.marketResearch||null,enriched),combos=plannedCombos.combinations;for(const c of combos){const created=await adminDb("ynot_product_clusters",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({market_node_id:nodeId,name:c.name,cluster_type:c.type,audience:(node.audience||[])[0]||null,moment:c.logic,strategy:{logic:c.logic,aiUsed:plannedCombos.usedAi},score:c.score})});const cluster=created?.[0];if(cluster)for(const p of c.products){const pi=await adminDb(`ynot_product_intelligence?product_id=eq.${encodeURIComponent(String(p.id))}&select=id&limit=1`);if(pi?.[0])await adminDb("ynot_cluster_products",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({cluster_id:cluster.id,product_intelligence_id:pi[0].id,role:"member",score:p.intelligence?.commercialPotential||p.intelligence?.advertabilityScore||0})}).catch(()=>null)}}return NextResponse.json({ok:true,node,combinations:combos,aiStatus:{portfolio:portfolio.diagnostic,combinations:plannedCombos.diagnostic},searchMeta:{queries:search.searchedQueries,uniqueCount:search.products.length}})
 }
 if(action==="expand"){
  const nodeId=String(body?.nodeId||""),nodes=await adminDb(`ynot_market_nodes?id=eq.${nodeId}&select=*&limit=1`),node=nodes?.[0];if(!node)return NextResponse.json({ok:false,error:"NODE_NOT_FOUND"},{status:404});const research=node?.reasoning?.marketResearch||null,researchQueries:string[]=[...(research?.replacementCycles||[]).map((x:any)=>x.searchQuery),...(research?.upgradePaths||[]).map((x:any)=>x.searchQuery),...(research?.overlookedProblems||[]).map((x:any)=>x.searchQuery),...(research?.accessoryEcosystems||[]).flatMap((x:any)=>x.searchQueries||[])].filter(Boolean),fallbackBranches=[...researchQueries.slice(0,10).map((q:string,i:number)=>({name:`Evidence path ${i+1}`,query:q,axis:"market_research"})),...RESEARCH_AXES.slice(0,8).map(a=>({name:a[1],query:`${node.query||node.name} ${a[2]}`,axis:a[0]}))].slice(0,14);const branchAi=await optionalAiJson("Plan the next product-market branches to investigate. Prefer concrete upgrade, replacement, professional/high-ticket, accessory ecosystem and pain-escalation branches grounded in supplied market research. Return JSON {branches:[{name,query,axis}]}. Do not invent sales evidence.",{market:node.name,query:node.query,research},{branches:fallbackBranches},{reasoning:"medium"}),candidates=(Array.isArray((branchAi.value as any)?.branches)?(branchAi.value as any).branches:fallbackBranches).slice(0,14),branches:any[]=[];
  for(const candidate of candidates){const search=await catalogue(origin,String(candidate.query||node.query||node.name),80,[String(candidate.query||"")]),products=search.products,s=scoreMarket(products,86);if(s.productCount<2)continue;const child=await upsertNode({parent_id:nodeId,node_type:node.depth>=1?"sub_micro_niche":"micro_niche",name:`${node.name} → ${String(candidate.name||candidate.axis||"branch")}`,query:String(candidate.query||node.query||node.name),archetypes:inferArchetypes(`${node.name} ${candidate.name||""} ${candidate.query||""}`),audience:node.audience||[],status:s.evidence>=40?"validated":"hypothesis",depth:Number(node.depth||0)+1,coverage_score:Math.min(100,s.productCount*2),opportunity_score:s.opportunity,evidence_score:s.evidence,discovery_score:s.discovery,conversion_score:s.conversion,organic_score:s.organic,ynot_fit_score:s.ynot,cross_sell_score:s.crossSell,high_ticket_score:s.highTicket,repeat_purchase_score:s.repeat,price_min:s.price.min,price_median:s.price.median,price_max:s.price.max,merchant_count:s.merchantCount,product_count:s.productCount,reasoning:{axis:candidate.axis,aiPlanned:branchAi.usedAi,aiDiagnostic:branchAi.diagnostic,searchMeta:{queries:search.searchedQueries,rawCount:search.rawCount}},evidence:{metrics:s,sample:products.slice(0,12)},created_by:admin.profile.id});branches.push({node:child,metrics:s,products:products.slice(0,10),searchMeta:{queries:search.searchedQueries,uniqueCount:products.length}})}
  await adminDb("ynot_coverage_map?on_conflict=market_node_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({market_node_id:nodeId,explored_queries:branches.length,validated_children:branches.filter(x=>x.metrics.evidence>=40).length,rejected_children:Math.max(0,candidates.length-branches.length),product_sample_count:branches.reduce((n,x)=>n+x.metrics.productCount,0),coverage_percent:Math.min(100,branches.length/Math.max(1,candidates.length)*100),novelty_gap:Math.max(0,100-branches.length/Math.max(1,candidates.length)*100),last_explored_at:new Date().toISOString()})});return NextResponse.json({ok:true,parent:node,branches,researchUsed:Boolean(research),aiStatus:{branches:branchAi.diagnostic}})
 }
 return NextResponse.json({ok:false,error:"UNKNOWN_ACTION"},{status:400})
}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"BRAIN_ERROR"},{status:adminErrorStatus(error)})}}
