import "./globals.css";
import "./frameless.css";
import "./spatial-ui.css";
import "./world-map.css";
import "./ynot.css";
import "./ynot-polish.css";
import "./premium-world.css";
import "./product-popup.css";
import "./stage3-market.css";
import "./deep-explore.css";
import "./commerce-polish.css";
import "./subcategory-nav.css";
import "./ynot-story-saves.css";
import "./discovery.css";
import "./navigation-refresh.css";
import "./commerce-verification.css";
import "./tag-combo-minimal.css";
import "./product-card-sync.css";
import "./world-visual-polish.css";
import "./ynot-left-rail.css";
import "./world-compass.css";
import "./ynot-side-tab.css";
import "./ynot-circle.css";
import "./ynot-profile.css";
export const metadata={title:"YNOT — Spatial Shopping",description:"Explore products through an endless spatial shopping world"};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en"><body>{children}</body></html>}
