export type VisualSubcategory={id:string;title:string;queries:string[]};
export type VisualCategory={id:string;title:string;subcategories:VisualSubcategory[]};
export type VisualWorld={id:string;title:string;categories:VisualCategory[]};
const s=(id:string,title:string,...queries:string[]):VisualSubcategory=>({id,title,queries});
const many=(items:string[]):VisualSubcategory[]=>items.map(x=>{const [id,title,q]=x.split('|');return s(id,title,q||title)});
export const YNOT_VISUAL_WORLDS:VisualWorld[]=[
{id:'electric',title:'Electric',categories:[{id:'ride',title:'Ride',subcategories:many(['dirt-bikes|Dirt bikes|electric dirt bike','ebikes|E-bikes|electric bike','cargo-ebikes|Cargo e-bikes|electric cargo bike','folding-ebikes|Folding e-bikes|folding electric bike','scooters|Scooters|electric scooter','offroad-scooters|Off-road scooters|off road electric scooter','motorcycles|Motorcycles|electric motorcycle','eskateboards|E-skateboards|electric skateboard','onewheels|One-wheels|electric one wheel','hoverboards|Hoverboards|hoverboard'])},{id:'water',title:'Water',subcategories:many(['efoils|E-foils|electric hydrofoil efoil','jetboards|Jetboards|electric jetboard','sea-scooters|Sea scooters|underwater electric scooter','electric-surf|Electric surf|motorized surfboard'])},{id:'play',title:'Play',subcategories:many(['go-karts|Go-karts|electric go kart','drift-karts|Drift karts|electric drift kart','atvs|ATVs|electric ATV','buggies|Buggies|electric buggy','rc-cars|RC cars|RC car','rc-boats|RC boats|RC boat'])},{id:'family',title:'Family',subcategories:many(['ride-ons|Kids ride-ons|kids electric ride on car','kids-quads|Kids quads|kids electric quad'])},{id:'home',title:'Home',subcategories:many(['robot-mowers|Robot mowers|robot lawn mower','pool-robots|Pool robots|robot pool cleaner','home-robots|Home robots|home robot'])},{id:'mods',title:'Parts & mods',subcategories:many(['batteries|Batteries|ebike battery','chargers|Chargers|electric vehicle charger','wheels|Wheels|ebike wheels','tyres|Tyres|electric bike tyres','motors|Motors|ebike motor','controllers|Controllers|ebike controller','custom-parts|Custom parts|electric vehicle custom parts'])},{id:'pro',title:'Pro',subcategories:many(['utility|Utility|electric utility vehicle','cargo|Cargo|electric cargo vehicle','warehouse|Warehouse|electric warehouse vehicle'])}]},
{id:'fashion',title:'Fashion',categories:[{id:'women',title:'Women',subcategories:many(['dresses|Dresses|womens dresses','tops|Tops|womens tops','tshirts|T-shirts|womens t shirt','shirts|Shirts & blouses|womens blouse','knitwear|Knitwear|womens knitwear','hoodies|Hoodies|womens hoodie','jeans|Jeans|womens jeans','trousers|Trousers|womens trousers','skirts|Skirts|womens skirts','shorts|Shorts|womens shorts','leggings|Leggings|womens leggings','sets|Sets|womens matching sets','jumpsuits|Jumpsuits|womens jumpsuit','activewear|Activewear|womens activewear','swimwear|Swimwear|womens swimwear','lingerie|Lingerie|womens lingerie','jackets|Jackets|womens jacket','coats|Coats|womens coat','blazers|Blazers|womens blazer'])},{id:'men',title:'Men',subcategories:many(['mens-tshirts|T-shirts|mens t shirt','mens-shirts|Shirts|mens shirt','polos|Polos|mens polo','mens-knitwear|Knitwear|mens knitwear','mens-hoodies|Hoodies|mens hoodie','mens-jeans|Jeans|mens jeans','mens-trousers|Trousers|mens trousers','mens-shorts|Shorts|mens shorts','tracksuits|Tracksuits|mens tracksuit','mens-sets|Sets|mens matching set','mens-activewear|Activewear|mens activewear','mens-swimwear|Swimwear|mens swimwear','mens-jackets|Jackets|mens jacket','mens-coats|Coats|mens coat','mens-blazers|Blazers|mens blazer'])},{id:'accessories',title:'Accessories',subcategories:many(['bags|Bags|fashion bags','backpacks|Backpacks|fashion backpack','wallets|Wallets|fashion wallet','belts|Belts|fashion belt','sunglasses|Sunglasses|fashion sunglasses','hats|Hats & caps|fashion hat cap','scarves|Scarves|fashion scarf','gloves|Gloves|fashion gloves','hair-accessories|Hair accessories|hair accessories'])}]},
{id:'home-interiors',title:'Home & Interiors',categories:[{id:'living',title:'Living',subcategories:many(['sofas|Sofas|sofa','sectionals|Sectionals|sectional sofa','loveseats|Loveseats|loveseat','armchairs|Armchairs|armchair','lounge-chairs|Lounge chairs|lounge chair','coffee-tables|Coffee tables|coffee table','side-tables|Side tables|side table','tv-units|TV units|TV unit','bookcases|Bookcases|bookcase','shelving|Shelving|shelving','rugs|Rugs|rug'])},{id:'dining',title:'Dining',subcategories:many(['dining-tables|Dining tables|dining table','dining-chairs|Dining chairs|dining chair','bar-stools|Bar stools|bar stool','sideboards|Sideboards|sideboard'])},{id:'bedroom',title:'Bedroom',subcategories:many(['beds|Beds|bed','mattresses|Mattresses|mattress','nightstands|Nightstands|nightstand','dressers|Dressers|dresser','wardrobes|Wardrobes|wardrobe'])},{id:'office',title:'Office',subcategories:many(['desks|Desks|desk','office-chairs|Office chairs|office chair','cabinets|Cabinets|storage cabinet'])},{id:'lighting',title:'Lighting',subcategories:many(['chandeliers|Chandeliers|chandelier','pendants|Pendant lights|pendant light','floor-lamps|Floor lamps|floor lamp','table-lamps|Table lamps|table lamp','wall-lights|Wall lights|wall light'])},{id:'decor',title:'Decor',subcategories:many(['mirrors|Mirrors|mirror','wall-art|Wall art|wall art','vases|Vases|vase','candles|Candles|candle','planters|Planters|planter','curtains|Curtains|curtains','cushions|Cushions|cushion','throws|Throws|throw blanket'])}]},
{id:'beauty',title:'Beauty',categories:[{id:'skincare',title:'Skincare',subcategories:many(['cleansers|Cleansers|face cleanser','toners|Toners|face toner','essences|Essences|skin essence','serums|Serums|face serum','ampoules|Ampoules|skin ampoule','moisturizers|Moisturizers|face moisturizer','face-oils|Face oils|face oil','eye-care|Eye care|eye cream','masks|Masks|face mask','exfoliators|Exfoliators|face exfoliator','acne|Acne care|acne skincare','spf|SPF|face sunscreen SPF','lip-care|Lip care|lip balm','body-care|Body care|body skincare','hand-care|Hand care|hand cream','skincare-sets|Sets|skincare set'])},{id:'makeup',title:'Makeup',subcategories:many(['foundation|Foundation|foundation makeup','concealer|Concealer|concealer makeup','powder|Powder|face powder makeup','primer|Primer|makeup primer','blush|Blush|blush makeup','bronzer|Bronzer|bronzer makeup','highlighter|Highlighter|highlighter makeup','contour|Contour|contour makeup','lipstick|Lipstick|lipstick','lip-gloss|Lip gloss|lip gloss','lip-liner|Lip liner|lip liner','mascara|Mascara|mascara','eyeliner|Eyeliner|eyeliner','eyeshadow|Eyeshadow|eyeshadow','brows|Brows|eyebrow makeup','setting-spray|Setting spray|setting spray'])},{id:'hair',title:'Hair',subcategories:many(['shampoo|Shampoo|shampoo','conditioner|Conditioner|conditioner','hair-masks|Hair masks|hair mask','hair-oils|Hair oils|hair oil','styling|Styling|hair styling'])},{id:'fragrance',title:'Fragrance',subcategories:many(['womens-fragrance|Women|womens perfume','mens-fragrance|Men|mens fragrance','unisex-fragrance|Unisex|unisex fragrance'])},{id:'tools',title:'Tools & devices',subcategories:many(['beauty-devices|Beauty devices|beauty device','brushes|Brushes|makeup brushes','hair-tools|Hair tools|hair styling tool','nails|Nails|nail care'])}]},
{id:'sports',title:'Sports',categories:[
{id:'football',title:'Football',subcategories:many(['boots|Boots|football boots','balls|Balls|football ball','kits|Kits & jerseys|football kit jersey','goalkeeper|Goalkeeper|goalkeeper gloves gear','training|Training gear|football training equipment','bags|Bags|football bag'])},
{id:'basketball',title:'Basketball',subcategories:many(['shoes|Shoes|basketball shoes','balls|Balls|basketball ball','jerseys|Jerseys|basketball jersey','hoops|Hoops|basketball hoop','training|Training gear|basketball training equipment','accessories|Accessories|basketball accessories'])},
{id:'tennis',title:'Tennis',subcategories:many(['rackets|Rackets|tennis racket','balls|Balls|tennis balls','shoes|Shoes|tennis shoes','clothing|Clothing|tennis clothing','bags|Bags|tennis racket bag','accessories|Accessories|tennis accessories'])},
{id:'padel',title:'Padel',subcategories:many(['rackets|Rackets|padel racket','balls|Balls|padel balls','shoes|Shoes|padel shoes','clothing|Clothing|padel clothing','bags|Bags|padel bag','accessories|Accessories|padel accessories'])},
{id:'golf',title:'Golf',subcategories:many(['clubs|Clubs|golf clubs','balls|Balls|golf balls','shoes|Shoes|golf shoes','clothing|Clothing|golf clothing','bags|Bags|golf bag','rangefinders|Rangefinders|golf rangefinder','accessories|Accessories|golf accessories'])},
{id:'boxing',title:'Boxing',subcategories:many(['gloves|Gloves|boxing gloves','bags|Punch bags|boxing punch bag','protective|Protective gear|boxing protective gear','shoes|Shoes|boxing shoes','clothing|Clothing|boxing clothing','training|Training gear|boxing training equipment'])},
{id:'running',title:'Running',subcategories:many(['shoes|Shoes|running shoes','clothing|Clothing|running clothing','watches|Watches|running GPS watch','hydration|Hydration|running hydration','belts|Belts & vests|running belt vest','accessories|Accessories|running accessories'])},
{id:'cycling',title:'Cycling',subcategories:many(['bikes|Bikes|road mountain bicycle','helmets|Helmets|cycling helmet','shoes|Shoes|cycling shoes','clothing|Clothing|cycling clothing','lights|Lights|bike lights','computers|Bike computers|cycling computer','accessories|Accessories|cycling accessories'])},
{id:'swimming',title:'Swimming',subcategories:many(['swimwear|Swimwear|competitive swimwear','goggles|Goggles|swimming goggles','caps|Caps|swimming cap','training|Training gear|swimming training equipment','bags|Bags|swimming bag','accessories|Accessories|swimming accessories'])},
{id:'rugby',title:'Rugby',subcategories:many(['boots|Boots|rugby boots','balls|Balls|rugby ball','kits|Kits|rugby kit jersey','protective|Protective gear|rugby protective gear','training|Training gear|rugby training equipment'])},
{id:'american-football',title:'American Football',subcategories:many(['cleats|Cleats|american football cleats','footballs|Footballs|american football ball','helmets|Helmets|american football helmet','pads|Pads|american football shoulder pads','jerseys|Jerseys|american football jersey','training|Training gear|american football training equipment'])},
{id:'baseball',title:'Baseball',subcategories:many(['bats|Bats|baseball bat','gloves|Gloves|baseball glove','balls|Balls|baseball balls','cleats|Cleats|baseball cleats','helmets|Helmets|baseball helmet','jerseys|Jerseys|baseball jersey','training|Training gear|baseball training equipment'])},
{id:'volleyball',title:'Volleyball',subcategories:many(['balls|Balls|volleyball ball','shoes|Shoes|volleyball shoes','clothing|Clothing|volleyball clothing','nets|Nets|volleyball net','protective|Protective gear|volleyball knee pads','training|Training gear|volleyball training equipment'])},
{id:'winter-sports',title:'Ski & Snowboard',subcategories:many(['skis|Skis|snow skis','snowboards|Snowboards|snowboard','boots|Boots|ski snowboard boots','helmets|Helmets|ski snowboard helmet','goggles|Goggles|ski snowboard goggles','clothing|Clothing|ski snowboard clothing','accessories|Accessories|ski snowboard accessories'])},
{id:'skateboarding',title:'Skateboarding',subcategories:many(['skateboards|Skateboards|skateboard','decks|Decks|skateboard deck','trucks|Trucks|skateboard trucks','wheels|Wheels|skateboard wheels','shoes|Shoes|skate shoes','protective|Protective gear|skateboard protective gear'])},
{id:'water-sports',title:'Water Sports',subcategories:many(['surfing|Surfing|surfboard surf gear','paddleboarding|Paddleboarding|paddleboard SUP','kayaking|Kayaking|kayak gear','wakeboarding|Wakeboarding|wakeboard gear','waterskiing|Water skiing|water skis','wetsuits|Wetsuits|water sports wetsuit'])}
]},
{id:'fitness',title:'Fitness',categories:[{id:'training',title:'Training',subcategories:many(['gymwear|Gymwear|gym wear','dumbbells|Dumbbells|dumbbells','barbells|Barbells|barbell','plates|Plates|weight plates','benches|Benches|weight bench','racks|Racks|gym rack','kettlebells|Kettlebells|kettlebell','bands|Resistance bands|resistance bands','treadmills|Treadmills|treadmill','bikes|Exercise bikes|exercise bike','rowers|Rowers|rowing machine','ellipticals|Ellipticals|elliptical machine','cable-machines|Cable machines|cable machine','boxing|Boxing|boxing equipment'])},{id:'wellness',title:'Wellness',subcategories:many(['yoga|Yoga|yoga equipment','pilates|Pilates|pilates equipment','recovery|Recovery|fitness recovery','massage-guns|Massage guns|massage gun','foam-rollers|Foam rollers|foam roller','shakers|Shakers|protein shaker','hydration|Hydration|fitness water bottle'])}]},
{id:'baby-kids',title:'Baby & Kids',categories:[{id:'baby',title:'Baby',subcategories:many(['strollers|Strollers|baby stroller','travel-systems|Travel systems|baby travel system','car-seats|Car seats|baby car seat','carriers|Carriers|baby carrier','cribs|Cribs|baby crib','bassinets|Bassinets|bassinet','baby-mattresses|Mattresses|baby mattress','changing|Changing|changing table','high-chairs|High chairs|baby high chair','bottles|Bottles|baby bottle','breastfeeding|Breastfeeding|breastfeeding products','sterilizers|Sterilizers|baby sterilizer','monitors|Monitors|baby monitor','bath|Bath|baby bath','diapers|Diapers|diapers','baby-clothing|Clothing|baby clothing'])},{id:'kids',title:'Kids',subcategories:many(['kids-fashion|Fashion|kids clothing','educational-toys|Educational toys|educational toys','plush|Plush toys|plush toy','building-toys|Building toys|building toys','outdoor-toys|Outdoor toys|outdoor kids toys','ride-ons|Ride-ons|kids ride on','playroom|Playroom|playroom products'])}]},
{id:'jewelry',title:'Jewelry',categories:[{id:'jewelry',title:'Jewelry',subcategories:many(['necklaces|Necklaces|necklace','chains|Chains|jewelry chain','pendants|Pendants|pendant','chokers|Chokers|choker','bracelets|Bracelets|bracelet','bangles|Bangles|bangle','rings|Rings|ring','engagement|Engagement rings|engagement ring','earrings|Earrings|earrings','studs|Studs|stud earrings','hoops|Hoops|hoop earrings','watches|Watches|watch','anklets|Anklets|anklet','brooches|Brooches|brooch','jewelry-sets|Sets|jewelry set'])}]},
{id:'tech',title:'Tech',categories:[{id:'personal',title:'Personal tech',subcategories:many(['phones|Smartphones|smartphone','cases|Phone cases|phone case','chargers|Chargers|phone charger','power-banks|Power banks|power bank','laptops|Laptops|laptop','gaming-laptops|Gaming laptops|gaming laptop','desktops|Desktops|desktop computer','monitors|Monitors|computer monitor','tablets|Tablets|tablet','keyboards|Keyboards|keyboard','mice|Mice|computer mouse','headphones|Headphones|headphones','earbuds|Earbuds|earbuds','speakers|Speakers|speaker','microphones|Microphones|microphone','cameras|Cameras|camera','lenses|Lenses|camera lens','drones|Drones|drone','wearables|Smartwatches|smartwatch','fitness-trackers|Fitness trackers|fitness tracker','vr|VR|VR headset','gaming|Gaming|gaming accessories','storage|Storage|computer storage','networking|Networking|networking equipment'])},{id:'smart-home',title:'Smart home',subcategories:many(['security|Security|smart home security','smart-lighting|Lighting|smart lighting','displays|Displays|smart display','smart-speakers|Smart speakers|smart speaker'])}]},
{id:'automotive',title:'Automotive',categories:[{id:'cars',title:'Cars',subcategories:many(['performance-cars|Performance|performance car','suvs|SUVs|SUV','classic-cars|Classics|classic car','ev-cars|EVs|electric car'])},{id:'garage',title:'Garage',subcategories:many(['wheels|Wheels|car wheels','tyres|Tyres|car tyres','car-lighting|Lighting|car lighting','interior-accessories|Interior|car interior accessories','exterior-accessories|Exterior|car exterior accessories','car-electronics|Electronics|car electronics','dashcams|Dashcams|dashcam','car-audio|Audio|car audio','detailing|Detailing|car detailing','cleaning|Cleaning|car cleaning','tools|Tools|automotive tools','storage|Storage|car storage','ev-charging|EV charging|EV charger'])}]},
{id:'outdoor',title:'Outdoor',categories:[{id:'adventure',title:'Adventure',subcategories:many(['camping|Camping|camping gear','tents|Tents|camping tent','sleeping-bags|Sleeping bags|sleeping bag','camping-furniture|Camping furniture|camping furniture','hiking|Hiking|hiking gear','backpacks|Backpacks|hiking backpack','climbing|Climbing|climbing gear','cycling|Cycling|cycling gear','fishing|Fishing|fishing gear','kayaking|Kayaking|kayak','paddleboarding|Paddleboarding|paddleboard','surfing|Surfing|surf gear'])},{id:'garden',title:'Garden',subcategories:many(['outdoor-furniture|Outdoor furniture|outdoor furniture','grills|Grills|outdoor grill','fire-pits|Fire pits|fire pit','garden-lighting|Lighting|garden lighting','garden-decor|Decor|garden decor','planters|Planters|garden planter','garden-equipment|Equipment|garden equipment'])}]},
{id:'pets',title:'Pets',categories:[{id:'dogs',title:'Dogs',subcategories:many(['dog-food|Food|dog food','dog-treats|Treats|dog treats','dog-beds|Beds|dog bed','dog-collars|Collars|dog collar','dog-harnesses|Harnesses|dog harness','dog-leads|Leads|dog lead','dog-toys|Toys|dog toy','dog-bowls|Bowls|dog bowl','dog-grooming|Grooming|dog grooming','dog-travel|Travel|dog travel'])},{id:'cats',title:'Cats',subcategories:many(['cat-food|Food|cat food','cat-beds|Beds|cat bed','cat-trees|Cat trees|cat tree','scratchers|Scratchers|cat scratcher','litter|Litter|cat litter','cat-toys|Toys|cat toy'])},{id:'pet-tech',title:'Pet tech',subcategories:many(['feeders|Feeders|smart pet feeder','fountains|Fountains|pet water fountain','gps|GPS trackers|pet GPS tracker','pet-cameras|Cameras|pet camera'])}]},
{id:'kitchen',title:'Kitchen',categories:[{id:'appliances',title:'Appliances',subcategories:many(['coffee|Coffee machines|coffee machine','espresso|Espresso machines|espresso machine','kettles|Kettles|kettle','toasters|Toasters|toaster','blenders|Blenders|blender','juicers|Juicers|juicer','mixers|Mixers|mixer','air-fryers|Air fryers|air fryer','multicookers|Multicookers|multicooker'])},{id:'cookware',title:'Cookware',subcategories:many(['pans|Pans|cooking pan','pots|Pots|cooking pot','knives|Knives|kitchen knife','cutting-boards|Cutting boards|cutting board','storage|Storage|kitchen storage','bakeware|Bakeware|bakeware'])},{id:'tabletop',title:'Tabletop',subcategories:many(['glassware|Glassware|glassware','dinnerware|Dinnerware|dinnerware','cutlery|Cutlery|cutlery','barware|Barware|barware'])}]},
{id:'travel',title:'Travel',categories:[{id:'luggage',title:'Luggage',subcategories:many(['suitcases|Suitcases|suitcase','carry-ons|Carry-ons|carry on luggage','checked-luggage|Checked luggage|checked luggage','weekenders|Weekenders|weekender bag','duffels|Duffels|duffel bag','travel-backpacks|Backpacks|travel backpack','toiletry-bags|Toiletry bags|toiletry bag','packing-cubes|Packing cubes|packing cubes','organizers|Organizers|travel organizer'])},{id:'essentials',title:'Essentials',subcategories:many(['passport-holders|Passport holders|passport holder','travel-wallets|Travel wallets|travel wallet','adapters|Adapters|travel adapter','travel-power|Power banks|travel power bank','travel-pillows|Travel pillows|travel pillow','sleep-accessories|Sleep accessories|travel sleep accessories','luggage-accessories|Luggage accessories|luggage accessories'])}]}
];
export const ALL_VISUAL_SUBCATEGORIES=YNOT_VISUAL_WORLDS.flatMap(world=>world.categories.flatMap(category=>category.subcategories.map(subcategory=>({world:world.id,category:category.id,subcategory:subcategory.id,queries:subcategory.queries}))));
