export type VisualSubcategory={id:string;title:string;queries:string[]};
export type VisualCategory={id:string;title:string;subcategories:VisualSubcategory[]};
export type VisualWorld={id:string;title:string;categories:VisualCategory[]};
const s=(id:string,title:string,...queries:string[]):VisualSubcategory=>({id,title,queries});
export const YNOT_VISUAL_WORLDS:VisualWorld[]=[
{id:"electric",title:"Electric",categories:[
{id:"ride",title:"Ride",subcategories:[s("dirt-bikes","Electric dirt bikes","electric dirt bike","electric motocross bike"),s("ebikes","E-bikes","premium electric bike","electric cargo bike"),s("scooters","Scooters","performance electric scooter","off road electric scooter"),s("motorcycles","Motorcycles","electric motorcycle","electric cafe racer"),s("boards","Boards & one-wheel","electric skateboard","electric one wheel")]},
{id:"water",title:"Water",subcategories:[s("efoils","E-foils","electric hydrofoil efoil"),s("jetboards","Jetboards","electric jetboard","motorized surfboard"),s("underwater","Underwater","underwater electric scooter","sea scooter")]},
{id:"play",title:"Play",subcategories:[s("go-karts","Go-karts","electric go kart","electric drift kart"),s("atv-buggies","ATVs & buggies","electric ATV","electric buggy"),s("rc","RC","premium RC car","RC boat")]},
{id:"family",title:"Family",subcategories:[s("ride-ons","Kids ride-ons","kids electric ride on car","kids electric quad")]},
{id:"home",title:"Home",subcategories:[s("garden","Electric garden","robot lawn mower","electric garden machine"),s("robots","Home robots","premium home robot","robot pool cleaner")]},
{id:"mods",title:"Parts & mods",subcategories:[s("customization","Customization","electric vehicle customization","custom ebike parts"),s("batteries","Batteries","ebike battery pack","electric motorcycle battery")]},
{id:"pro",title:"Pro",subcategories:[s("utility","Utility","electric utility vehicle","electric cargo vehicle")]}]},
{id:"fashion",title:"Fashion",categories:[{id:"women",title:"Women",subcategories:[s("dresses","Dresses","editorial womens dresses","designer dresses"),s("tops","Tops","womens fashion tops"),s("bottoms","Bottoms","womens trousers skirts fashion"),s("sets","Sets","womens matching sets fashion"),s("outerwear","Outerwear","womens jackets outerwear")]},{id:"men",title:"Men",subcategories:[s("mens-tops","Tops","mens premium shirts tops"),s("mens-bottoms","Bottoms","mens trousers fashion"),s("mens-sets","Sets","mens matching sets streetwear"),s("mens-outerwear","Outerwear","mens jackets outerwear")]},{id:"accessories",title:"Accessories",subcategories:[s("bags","Bags","designer style bags editorial"),s("sunglasses","Sunglasses","fashion sunglasses editorial"),s("belts","Belts","fashion belts luxury"),s("hats","Hats","fashion hats editorial")]}]},
{id:"home-interiors",title:"Home & Interiors",categories:[{id:"living",title:"Living",subcategories:[s("sofas","Sofas","luxury modern sofa interior"),s("armchairs","Armchairs","designer armchair interior"),s("coffee-tables","Coffee tables","designer coffee table interior"),s("rugs","Rugs","luxury rug interior")]},{id:"dining",title:"Dining",subcategories:[s("dining-tables","Dining tables","designer dining table"),s("dining-chairs","Dining chairs","designer dining chairs"),s("bar-stools","Bar stools","modern bar stools interior")]},{id:"bedroom",title:"Bedroom",subcategories:[s("beds","Beds","luxury modern bed bedroom"),s("nightstands","Nightstands","designer bedside table"),s("dressers","Dressers","modern dresser interior")]},{id:"lighting",title:"Lighting",subcategories:[s("pendants","Pendant lights","designer pendant lighting"),s("floor-lamps","Floor lamps","designer floor lamp"),s("table-lamps","Table lamps","designer table lamp")]},{id:"decor",title:"Decor",subcategories:[s("mirrors","Mirrors","designer mirror interior"),s("wall-art","Wall art","modern wall art interior"),s("vases","Vases","designer vase decor"),s("storage","Storage","designer sideboard storage")]}]},
{id:"beauty",title:"Beauty",categories:[{id:"skincare",title:"Skincare",subcategories:[s("serums","Serums","luxury skincare serum product"),s("moisturizers","Moisturizers","premium face moisturizer product"),s("cleansers","Cleansers","premium face cleanser product"),s("masks","Masks","skincare face mask product")]},{id:"makeup",title:"Makeup",subcategories:[s("lip","Lip","luxury lipstick makeup"),s("face","Face","premium foundation makeup"),s("eyes","Eyes","luxury eye makeup palette")]},{id:"tools",title:"Tools",subcategories:[s("beauty-devices","Beauty devices","premium beauty device skincare"),s("brushes","Brushes","luxury makeup brushes")]}]},
{id:"fitness",title:"Fitness",categories:[{id:"training",title:"Training",subcategories:[s("gymwear","Gymwear","premium gym wear fitness fashion"),s("weights","Weights","premium dumbbells home gym"),s("machines","Machines","premium home gym machine"),s("recovery","Recovery","premium fitness recovery equipment")]},{id:"wellness",title:"Wellness",subcategories:[s("yoga","Yoga","premium yoga equipment aesthetic"),s("pilates","Pilates","premium pilates equipment aesthetic"),s("hydration","Hydration","premium fitness water bottle")]}]},
{id:"baby-kids",title:"Baby & Kids",categories:[{id:"baby",title:"Baby",subcategories:[s("strollers","Strollers","premium baby stroller"),s("nursery","Nursery","modern luxury nursery products"),s("feeding","Feeding","premium baby feeding products"),s("car-seats","Car seats","premium baby car seat")]},{id:"kids",title:"Kids",subcategories:[s("toys","Toys","premium kids toys aesthetic"),s("kids-fashion","Fashion","kids fashion editorial"),s("playroom","Playroom","modern kids playroom products")]}]},
{id:"jewelry",title:"Jewelry",categories:[{id:"jewelry",title:"Jewelry",subcategories:[s("necklaces","Necklaces","luxury necklace product editorial"),s("bracelets","Bracelets","luxury bracelet product"),s("rings","Rings","luxury ring product"),s("earrings","Earrings","luxury earrings product"),s("watches","Watches","luxury watch editorial")]}]},
{id:"tech",title:"Tech",categories:[{id:"personal",title:"Personal tech",subcategories:[s("phones","Phones","premium smartphone product photography"),s("laptops","Laptops","premium laptop product photography"),s("tablets","Tablets","premium tablet product"),s("audio","Audio","premium headphones speaker product"),s("wearables","Wearables","premium smartwatch wearable tech")]},{id:"smart-home",title:"Smart home",subcategories:[s("security","Security","premium smart home security"),s("smart-lighting","Lighting","premium smart lighting home"),s("displays","Displays","premium smart display home")]}]},
{id:"automotive",title:"Automotive",categories:[{id:"cars",title:"Cars",subcategories:[s("performance-cars","Performance","premium performance car editorial"),s("suvs","SUVs","premium SUV automotive"),s("classic-cars","Classic","classic car editorial"),s("ev-cars","EV","premium electric car editorial")]},{id:"garage",title:"Garage",subcategories:[s("car-accessories","Accessories","premium car accessories"),s("detailing","Detailing","premium car detailing products"),s("wheels","Wheels","premium automotive wheels rims")]}]},
{id:"outdoor",title:"Outdoor",categories:[{id:"adventure",title:"Adventure",subcategories:[s("camping","Camping","premium camping gear aesthetic"),s("hiking","Hiking","premium hiking gear aesthetic"),s("cycling","Cycling","premium cycling gear"),s("watersports","Watersports","premium watersports gear")]},{id:"garden",title:"Garden",subcategories:[s("outdoor-furniture","Outdoor furniture","luxury outdoor furniture"),s("grills","Grills","premium outdoor grill"),s("garden-decor","Garden decor","modern garden decor")]}]},
{id:"pets",title:"Pets",categories:[{id:"dogs",title:"Dogs",subcategories:[s("dog-beds","Beds","premium dog bed interior"),s("dog-accessories","Accessories","premium dog accessories"),s("dog-travel","Travel","premium dog travel products")]},{id:"cats",title:"Cats",subcategories:[s("cat-furniture","Furniture","designer cat furniture"),s("cat-accessories","Accessories","premium cat accessories")]},{id:"pet-tech",title:"Pet tech",subcategories:[s("feeders","Feeders","smart pet feeder"),s("pet-cameras","Cameras","smart pet camera")]}]},
{id:"kitchen",title:"Kitchen",categories:[{id:"appliances",title:"Appliances",subcategories:[s("coffee","Coffee","premium coffee machine kitchen"),s("blenders","Blenders","premium blender product"),s("air-fryers","Air fryers","premium air fryer kitchen"),s("cookware","Cookware","premium cookware aesthetic")]},{id:"tabletop",title:"Tabletop",subcategories:[s("glassware","Glassware","designer glassware tabletop"),s("dinnerware","Dinnerware","designer dinnerware table"),s("cutlery","Cutlery","premium cutlery flatware")]}]},
{id:"travel",title:"Travel",categories:[{id:"luggage",title:"Luggage",subcategories:[s("suitcases","Suitcases","premium suitcase luggage editorial"),s("travel-bags","Travel bags","premium travel bag"),s("organizers","Organizers","premium travel organizer") ]},{id:"essentials",title:"Essentials",subcategories:[s("travel-tech","Travel tech","premium travel tech accessories"),s("comfort","Comfort","premium travel comfort accessories")]}]}
];
export const ALL_VISUAL_SUBCATEGORIES=YNOT_VISUAL_WORLDS.flatMap(world=>world.categories.flatMap(category=>category.subcategories.map(subcategory=>({world:world.id,category:category.id,subcategory:subcategory.id,queries:subcategory.queries}))));
