"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {YNOT_VISUAL_WORLDS} from "@/lib/visual/expanded-world-taxonomy";
import YnotWorldOrb from "@/components/electric/YnotWorldOrb";
const fallback="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=960&q=75";
const tagWords=(q:string)=>q.replace(/womens|mens|fashion|products|equipment/gi,"").trim().split(/\s+/).slice(0,3);
function AlbumCover({world,category,subcategory,title}:{world:string;category:string;subcategory:string;title:string}){const[imgs,setImgs]=useState<string[]>([]),[n,setN]=useState(0);useEffect(()=>{fetch(`/api/worlds/album-covers/feed?world=${encodeURIComponent(world)}&category=${encodeURIComponent(category)}&subcategory=${encodeURIComponent(subcategory)}`,{cache:"no-store"}).then(r=>r.json()).then(j=>setImgs(Array.isArray(j.images)?j.images:[])).catch(()=>{})},[world,category,subcategory]);useEffect(()=>{if(imgs.length<2)return;const t=setInterval(()=>setN(v=>(v+1)%imgs.length),4200);return()=>clearInterval(t)},[imgs.length]);return <img src={imgs[n]||fallback} alt={title} loading="eager" decoding="async" onError={e=>{e.currentTarget.src=fallback}}/>}
export default function CategoryAlbums(){const p=useParams(),router=useRouter(),world=YNOT_VISUAL_WORLDS.find(w=>w.id===String(p.world)),cat=world?.categories.find(c=>c.id===String(p.category));if(!world||!cat)return <main/>;return <main className="page"><section className="albums">{cat.subcategories.map((sub,i)=><button className={`album a${i%5}`} key={sub.id} onClick={()=>router.push(`/worlds/${world.id}/${cat.id}/${sub.id}`)}><AlbumCover world={world.id} category={cat.id} subcategory={sub.id} title={sub.title}/><span className="shade"/><span className="copy"><small>{tagWords(sub.queries[0]).join(" · ")}</small><b>{sub.title}</b></span></button>)}</section><YnotWorldOrb canBack onBack={()=>router.push(`/worlds/${world.id}`)} onSearch={()=>{}}/><style jsx global>{`html,body{height:auto!important;overflow-y:auto!important;overflow-x:hidden!important;background:#070707!important}.page{min-height:100dvh;background:#070707;color:#fff;padding-bottom:140px}.albums{columns:3 260px;column-gap:4px;padding:0;max-width:1500px;margin:auto}.album{position:relative;display:block;width:100%;height:360px;margin:0 0 4px;padding:0;border:0;background:#151515;overflow:hidden;break-inside:avoid;color:#fff;text-align:left;transform:translateZ(0)}.album.a1,.album.a4{height:470px}.album.a2{height:285px}.album img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;display:block;opacity:1;transition:opacity .45s ease}.shade{position:absolute;inset:0;background:linear-gradient(180deg,transparent 42%,rgba(0,0,0,.78))}.copy{position:absolute;left:14px;right:10px;bottom:14px}.copy small{display:block;font-size:8px;letter-spacing:.08em;opacity:.72;margin-bottom:4px;text-transform:capitalize}.copy b{display:block;font-size:25px;line-height:1}@media(max-width:650px){.albums{columns:2;column-gap:3px}.album{height:250px;margin-bottom:3px}.album.a1,.album.a4{height:345px}.album.a2{height:205px}.copy{left:11px;bottom:11px}.copy b{font-size:20px}.copy small{font-size:7px}}`}</style></main>}
