import {NextRequest,NextResponse} from "next/server";
import crypto from "node:crypto";
export const runtime="nodejs";
const base=()=>String(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL||"").replace(/\/$/,""),service=()=>String(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||"");
const serviceHeaders=()=>{const k=service();return{apikey:k,...(k.startsWith("sb_")?{}:{Authorization:`Bearer ${k}`}),"Content-Type":"application/json",Prefer:"return=representation"}};
async function user(req:NextRequest){const token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)throw new Error("SIGN_IN_REQUIRED");const r=await fetch(`${base()}/auth/v1/user`,{headers:{apikey:String(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||""),Authorization:`Bearer ${token}`},cache:"no-store"}),u=await r.json();if(!r.ok||!u?.id)throw new Error("INVALID_SESSION");return u}
async function db(path:string,init:RequestInit={}){const r=await fetch(`${base()}/rest/v1/${path}`,{...init,headers:{...serviceHeaders(),...(init.headers||{})},cache:"no-store"}),t=await r.text();if(!r.ok)throw new Error(t||"DATABASE_ERROR");return t?JSON.parse(t):null}
function code(){return crypto.randomBytes(4).toString("hex").toUpperCase()}
async function ensureAccount(u:any){let rows=await db(`ynot_users?auth_user_id=eq.${u.id}&select=id,display_name,email,referral_code,avatar_data,auth_provider,email_verified_at`);if(!rows?.[0]){const meta=u.user_metadata||{},name=String(meta.full_name||meta.name||u.email?.split("@")[0]||"YNOT shopper").slice(0,30),avatar=String(meta.avatar_url||meta.picture||"").slice(0,1000);rows=await db("ynot_users",{method:"POST",body:JSON.stringify({id:u.id,auth_user_id:u.id,email:u.email||null,display_name:name,avatar_data:avatar,auth_provider:String(u.app_metadata?.provider||"email"),email_verified_at:u.email_confirmed_at||null,referral_code:code(),last_seen_at:new Date().toISOString()})})}return rows[0]}
function publicAccount(u:any,p:any){return{id:p.id,name:p.display_name||"",email:u.email||p.email||"",avatar:p.avatar_data||u.user_metadata?.avatar_url||u.user_metadata?.picture||"",provider:u.app_metadata?.provider||p.auth_provider||"email",verified:Boolean(u.email_confirmed_at||p.email_verified_at),referralCode:p.referral_code}}
export async function GET(req:NextRequest){try{const u=await user(req);let p=await ensureAccount(u);await db(`ynot_users?id=eq.${p.id}`,{method:"PATCH",body:JSON.stringify({last_seen_at:new Date().toISOString(),email:u.email||p.email,email_verified_at:u.email_confirmed_at||p.email_verified_at})});const rows=await db(`ynot_users?id=eq.${p.id}&select=id,display_name,email,referral_code,avatar_data,auth_provider,email_verified_at`);p=rows?.[0]||p;return NextResponse.json({account:publicAccount(u,p)})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"ACCOUNT_UNAVAILABLE"},{status:401})}}
export async function PATCH(req:NextRequest){try{const u=await user(req);const p=await ensureAccount(u);const body=await req.json().catch(()=>({}));const name=typeof body?.name==="string"?body.name.trim().slice(0,30):undefined;const avatar=typeof body?.avatar==="string"?body.avatar.slice(0,2_000_000):undefined;const patch:Record<string,unknown>={last_seen_at:new Date().toISOString()};if(name!==undefined){if(name.length<2)return NextResponse.json({error:"NAME_TOO_SHORT"},{status:400});patch.display_name=name}if(avatar!==undefined)patch.avatar_data=avatar;const rows=await db(`ynot_users?id=eq.${p.id}`,{method:"PATCH",body:JSON.stringify(patch)});const updated=rows?.[0]||{...p,...patch};return NextResponse.json({account:publicAccount(u,updated)})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"PROFILE_UPDATE_FAILED"},{status:400})}}
