import {NextRequest,NextResponse} from "next/server";
import crypto from "node:crypto";
export const runtime="nodejs";
const base=()=>String(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL||"").replace(/\/$/,""),service=()=>String(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||"");
const serviceHeaders=()=>{const k=service();return{apikey:k,...(k.startsWith("sb_")?{}:{Authorization:`Bearer ${k}`}),"Content-Type":"application/json",Prefer:"return=representation"}};
async function user(req:NextRequest){const token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)throw new Error("SIGN_IN_REQUIRED");const r=await fetch(`${base()}/auth/v1/user`,{headers:{apikey:String(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||""),Authorization:`Bearer ${token}`},cache:"no-store"}),u=await r.json();if(!r.ok||!u?.id)throw new Error("INVALID_SESSION");return u}
async function db(path:string,init:RequestInit={}){const r=await fetch(`${base()}/rest/v1/${path}`,{...init,headers:{...serviceHeaders(),...(init.headers||{})},cache:"no-store"}),t=await r.text();if(!r.ok)throw new Error(t||"DATABASE_ERROR");return t?JSON.parse(t):null}
function code(){return crypto.randomBytes(4).toString("hex").toUpperCase()}
export async function GET(req:NextRequest){try{const u=await user(req);let rows=await db(`ynot_users?auth_user_id=eq.${u.id}&select=id,display_name,email,referral_code,avatar_data,auth_provider,email_verified_at`);if(!rows?.[0]){const meta=u.user_metadata||{},name=String(meta.full_name||meta.name||u.email?.split("@")[0]||"YNOT shopper").slice(0,30),avatar=String(meta.avatar_url||meta.picture||"").slice(0,1000);rows=await db("ynot_users",{method:"POST",body:JSON.stringify({auth_user_id:u.id,email:u.email||null,display_name:name,avatar_data:avatar,auth_provider:String(u.app_metadata?.provider||"email"),email_verified_at:u.email_confirmed_at||null,referral_code:code(),last_seen_at:new Date().toISOString()})})}else await db(`ynot_users?id=eq.${rows[0].id}`,{method:"PATCH",body:JSON.stringify({last_seen_at:new Date().toISOString(),email:u.email||rows[0].email,email_verified_at:u.email_confirmed_at||rows[0].email_verified_at})});const p=rows[0];return NextResponse.json({account:{id:p.id,name:p.display_name||"",email:u.email||p.email||"",avatar:p.avatar_data||u.user_metadata?.avatar_url||u.user_metadata?.picture||"",provider:u.app_metadata?.provider||p.auth_provider||"email",verified:Boolean(u.email_confirmed_at||p.email_verified_at),referralCode:p.referral_code}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"ACCOUNT_UNAVAILABLE"},{status:401})}}
