import {NextRequest,NextResponse} from "next/server";
import crypto from "node:crypto";
import {YNOT_VISUAL_WORLDS} from "@/lib/visual/expanded-world-taxonomy";
export const maxDuration=300;export const dynamic="force-dynamic";
const SB=process.env.NEXT_PUBLIC_SUPABASE_URL||"",KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||"",APIFY=process.env.APIFY_API_KEY||process.env.APIFY_API_TOKEN||process.env.APIFY_TOKEN||process.env.APIFY_KEY||"",ACTOR=process.env.PINTEREST_APIFY_ACTOR||"accountable_eel~pinterest-search-lookup",BUCKET="YNOT FEED",ROOT="album-covers",TARGET=5,DEFAULT_BATCH=4;
const enc=(s:string)=>s.split("/").map(encodeURIComponent).join("/");
async function list(prefix:string){const r=await fetch(`${SB}/storage/v1/object/list/${encodeURIComponent(BUCKET)}`,{method:"POST",headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"},body:JSON.stringify({prefix,limit:100,offset:0}),cache:"no-store"});if(!r.ok)return[];const j=await r.json();return Array.isArray(j)?j:[]}
async function count(d:Def){return (await list(d.folder)).filter((x:any)=>/\.(jpe?g|png|webp)$/i.test(x.name||"")).length}
async function upload(path:string,b:Buffer,type:string){const r=await fetch(`${SB}/storage/v1/object/${encodeURIComponent(BUCKET)}/${enc(path)}`,{method:"POST",headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":type,"x-upsert":"false"},body:b});return r.ok}
async function pins(q:string){const r=await fetch(`https://api.apify.com/v2/acts/${ACTOR}/run-sync-get-dataset-items?token=${encodeURIComponent(APIFY)}&clean=true`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({searchQueries:[q],queries:[q],query:q,maxPinsPerSearch:12,maxResults:12,resultsPerPage:12}),cache:"no-store"});if(!r.ok)throw new Error(`Apify ${r.status}`);const j=await r.json();return Array.isArray(j)?j:(j.items||j.results||[])}
const pick=(x:any)=>x.imageUrl||x.image_url||x.image?.url||x.images?.orig?.url||x.images?.original?.url||x.src||"";
type Def={world:string;category?:string;subcategory?:string;title:string;query:string;folder:string};
function defs():Def[]{const out:Def[]=[];for(const w of YNOT_VISUAL_WORLDS){out.push({world:w.id,title:w.title,query:`${w.title} products aesthetic`,folder:`${ROOT}/${w.id}/_world`});for(const c of w.categories){out.push({world:w.id,category:c.id,title:c.title,query:`${c.title} ${w.title} aesthetic products`,folder:`${ROOT}/${w.id}/${c.id}/_category`});for(const s of c.subcategories)out.push({world:w.id,category:c.id,subcategory:s.id,title:s.title,query:s.queries?.[0]||`${s.title} products`,folder:`${ROOT}/${w.id}/${c.id}/${s.id}`})}}return out}
async function fill(d:Def){const before=await count(d);let need=Math.max(0,TARGET-before),added=0;if(!need)return{...d,total:before,added:0,status:"full"};const items=await pins(d.query);for(const x of items){if(!need)break;try{const url=pick(x);if(!url)continue;const r=await fetch(url,{redirect:"follow"});if(!r.ok)continue;const type=r.headers.get("content-type")||"";if(!type.startsWith("image/"))continue;const b=Buffer.from(await r.arrayBuffer());if(b.length<40000)continue;const hash=crypto.createHash("sha256").update(b).digest("hex").slice(0,20),ext=type.includes("png")?"png":type.includes("webp")?"webp":"jpg";if(await upload(`${d.folder}/${hash}.${ext}`,b,type)){added++;need--}}catch{}}return{...d,total:before+added,added,status:need?"partial":"full"}}
async function run(scope="",batch=DEFAULT_BATCH){if(!SB||!KEY||!APIFY)return NextResponse.json({error:"Missing server credentials",supabaseConfigured:Boolean(SB&&KEY),apifyConfigured:Boolean(APIFY)},{status:500});let all=defs();if(scope)all=all.filter(x=>x.world===scope||x.category===scope||x.subcategory===scope);const counts=await Promise.all(all.map(async d=>({d,n:await count(d)}))),pending=counts.filter(x=>x.n<TARGET),todo=pending.slice(0,Math.max(1,Math.min(batch,8))),results=[];for(const x of todo)results.push(await fill(x.d));const remaining=Math.max(0,pending.length-todo.length),savedImages=counts.reduce((n,x)=>n+Math.min(x.n,TARGET),0)+results.reduce((n,x)=>n+x.added,0);return NextResponse.json({ok:true,target:TARGET,totalAlbums:all.length,processed:results.length,remaining,complete:remaining===0&&results.every(x=>x.status==="full"),savedImages,results})}
export async function POST(req:NextRequest){const b=await req.json().catch(()=>({}));return run(String(b?.scope||""),Number(b?.batch)||DEFAULT_BATCH)}
export async function GET(req:NextRequest){if(req.nextUrl.searchParams.get("run")==="1")return run(String(req.nextUrl.searchParams.get("scope")||""),Number(req.nextUrl.searchParams.get("batch"))||DEFAULT_BATCH);const all=defs();return NextResponse.json({ready:Boolean(SB&&KEY&&APIFY),target:TARGET,albums:all.length,batch:DEFAULT_BATCH,usage:"POST repeatedly until complete=true. The endpoint skips albums that already have 5 images."})}
