"use client";

import {useEffect,useMemo,useState} from "react";
import {authedFetch,readSession} from "@/lib/ynot/supabase-browser";
import styles from "./brain.module.css";

type NodeRow={id:string;parent_id?:string|null;node_type:string;name:string;query?:string;status:string;depth:number;coverage_score:number;opportunity_score:number;evidence_score:number;discovery_score:number;conversion_score:number;organic_score:number;ynot_fit_score:number;cross_sell_score:number;high_ticket_score:number;repeat_purchase_score:number;competition_risk?:string;price_min?:number;price_median?:number;price_max?:number;merchant_count:number;product_count:number;archetypes?:string[];audience?:string[];reasoning?:any};
type ProductRow={id?:string;title?:string;brand?:string;price?:number;currency?:string;image?:string;url?:string;intelligence?:any};

export default function BrainPage(){
 const[access,setAccess]=useState(readSession()?"ready":"signin"),[nodes,setNodes]=useState<NodeRow[]>([]),[categories,setCategories]=useState<string[]>([]),[coverage,setCoverage]=useState<any[]>([]),[selected,setSelected]=useState<NodeRow|null>(null),[products,setProducts]=useState<ProductRow[]>([]),[combinations,setCombinations]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]),[name,setName]=useState(""),[query,setQuery]=useState(""),[parentId,setParentId]=useState(""),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 async function api(payload:any){const r=await authedFetch("/api/admin/ads/brain",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(r.status===401){setAccess("signin");throw new Error("Sign in required")}if(r.status===403){setAccess("forbidden");throw new Error("Owner access required")}if(!r.ok)throw new Error(d?.error||"BRAIN_ERROR");return d}
 async function refresh(){setBusy("overview");try{let d=await api({action:"overview"});if(!(d.nodes||[]).length){await api({action:"bootstrap"});d=await api({action:"overview"})}setNodes(d.nodes||[]);setCategories(d.categories||[]);setCoverage(d.coverage||[])}catch(e){setNotice(e instanceof Error?e.message:"Could not load")}finally{setBusy("")}}
 useEffect(()=>{void refresh()},[]);
 async function evaluate(){if(!name.trim())return;setBusy("evaluate");setNotice("");try{const d=await api({action:"evaluate",name,query:query||name,parentId:parentId||null});setSelected(d.node);setProducts((d.products||[]).map((p:any)=>p));setCombinations([]);setBranches([]);setNotice(`Evaluated ${d.node.name}. ${d.aiUsed?"Reasoning model used.":"Evidence engine used; AI model adapter is ready when OPENAI_API_KEY is configured."}`);await refresh()}catch(e){setNotice(e instanceof Error?e.message:"Evaluation failed")}finally{setBusy("")}}
 async function analyze(node:NodeRow){setSelected(node);setBusy("products");setNotice("");try{const d=await api({action:"products",nodeId:node.id});setProducts(d.products||[]);setNotice(`${(d.products||[]).length} products analyzed with Why YNOT reasoning.`)}catch(e){setNotice(e instanceof Error?e.message:"Product analysis failed")}finally{setBusy("")}}
 async function combine(){if(!selected)return;setBusy("combine");try{const d=await api({action:"combinations",nodeId:selected.id});setCombinations(d.combinations||[]);setNotice(`${(d.combinations||[]).length} product systems built from audience/use-case compatibility.`)}catch(e){setNotice(e instanceof Error?e.message:"Combination analysis failed")}finally{setBusy("")}}
 async function deepen(){if(!selected)return;setBusy("expand");try{const d=await api({action:"expand",nodeId:selected.id});setBranches(d.branches||[]);setNotice(`${(d.branches||[]).length} evidence-backed child markets found.`);await refresh()}catch(e){setNotice(e instanceof Error?e.message:"Expansion failed")}finally{setBusy("")}}
 const roots=useMemo(()=>nodes.filter(n=>n.node_type==="category"),[nodes]);const opportunities=useMemo(()=>nodes.filter(n=>n.node_type!=="category").sort((a,b)=>Number(b.opportunity_score)-Number(a.opportunity_score)),[nodes]);const cov=new Map(coverage.map((c:any)=>[c.market_node_id,c]));
 if(access!=="ready")return <main className={styles.shell}><div className={styles.lock}><h1>{access==="signin"?"Sign in required":"Owner access required"}</h1><a href="/admin/ads">Back</a></div></main>;
 return <main className={styles.shell}><div className={styles.wrap}>
  <header className={styles.hero}><div><span>YNOT / COMMERCIAL INTELLIGENCE BRAIN</span><h1>Market graph → niche proof → product reasoning → combinations.</h1><p>This is the evidence layer above Deep Intelligence. It evaluates a market before digging deeper, explains why each product matters, connects products across use cases, and tracks which commercial universes remain under-explored.</p></div><button onClick={()=>void refresh()} disabled={!!busy}>Refresh graph</button></header>
  {notice&&<div className={styles.notice}>{notice}</div>}
  <section className={styles.stats}><div><b>{roots.length}</b><span>market universes</span></div><div><b>{opportunities.length}</b><span>researched niches</span></div><div><b>{opportunities.filter(n=>n.status==="validated").length}</b><span>validated</span></div><div><b>{opportunities.filter(n=>Number(n.evidence_score)>=60).length}</b><span>strong evidence</span></div></section>

  <section className={styles.panel}><div className={styles.panelHead}><div><small>1 / MARKET COVERAGE</small><h2>Hit every category, not only obvious ecommerce.</h2></div></div><div className={styles.coverageGrid}>{roots.map(r=>{const c:any=cov.get(r.id);const pct=Math.round(Number(c?.coverage_percent||r.coverage_score||0));return <button key={r.id} onClick={()=>{setParentId(r.id);setName(r.name);setQuery(r.name)}}><div><b>{r.name}</b><span>{pct}% explored</span></div><i><em style={{width:`${pct}%`}}/></i></button>})}</div></section>

  <section className={styles.panel}><div className={styles.panelHead}><div><small>2 / NICHE EVALUATOR</small><h2>Prove the parent niche before recursion.</h2></div></div><div className={styles.form}><select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">No parent category</option>{roots.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Niche: e.g. Home security cameras"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Catalogue query (optional)"/><button onClick={()=>void evaluate()} disabled={busy==="evaluate"}>{busy==="evaluate"?"Evaluating…":"Evaluate niche"}</button></div></section>

  <section className={styles.grid}><div className={styles.panel}><div className={styles.panelHead}><div><small>3 / OPPORTUNITY DOSSIERS</small><h2>What deserves deeper research?</h2></div></div><div className={styles.nodeList}>{opportunities.slice(0,40).map(n=><button key={n.id} className={selected?.id===n.id?styles.selected:""} onClick={()=>setSelected(n)}><div><b>{n.name}</b><span>{n.node_type} · {n.status} · {n.product_count} products · {n.merchant_count} merchants</span></div><strong>{Math.round(Number(n.opportunity_score||0))}</strong></button>)}</div></div>
   <div className={styles.panel}>{selected?<><div className={styles.panelHead}><div><small>SELECTED DOSSIER</small><h2>{selected.name}</h2></div><strong className={styles.score}>{Math.round(Number(selected.opportunity_score||0))}</strong></div><div className={styles.scoreGrid}><div><b>{Math.round(Number(selected.evidence_score||0))}</b><span>Evidence</span></div><div><b>{Math.round(Number(selected.discovery_score||0))}</b><span>Discovery</span></div><div><b>{Math.round(Number(selected.conversion_score||0))}</b><span>Convert</span></div><div><b>{Math.round(Number(selected.ynot_fit_score||0))}</b><span>YNOT</span></div><div><b>{Math.round(Number(selected.cross_sell_score||0))}</b><span>Cross-sell</span></div><div><b>{Math.round(Number(selected.high_ticket_score||0))}</b><span>High ticket</span></div></div><div className={styles.tags}>{(selected.archetypes||[]).map(a=><span key={a}>{a}</span>)}</div><div className={styles.actions}><button onClick={()=>void analyze(selected)} disabled={!!busy}>Analyze products</button><button onClick={()=>void deepen()} disabled={!!busy}>Go deeper</button><button onClick={()=>void combine()} disabled={!!busy}>Build combinations</button></div></>:<div className={styles.empty}>Select or evaluate a niche to inspect it.</div>}</div></section>

  {branches.length>0&&<section className={styles.panel}><div className={styles.panelHead}><div><small>4 / RECURSIVE BRANCHES</small><h2>Evidence-backed child markets.</h2></div></div><div className={styles.branchGrid}>{branches.map((b:any)=><button key={b.node.id} onClick={()=>setSelected(b.node)}><b>{b.node.name}</b><span>{b.metrics.productCount} products · evidence {b.metrics.evidence} · opportunity {b.metrics.opportunity}</span></button>)}</div></section>}

  {products.length>0&&<section className={styles.panel}><div className={styles.panelHead}><div><small>5 / PRODUCT INTELLIGENCE</small><h2>Why YNOT found each product.</h2></div></div><div className={styles.products}>{products.map((p:any)=>{const i=p.intelligence;return <article key={p.id}><div className={styles.image}>{p.image&&<img src={p.image} alt=""/>}</div><small>{p.brand||"Shopify"}</small><h3>{p.title}</h3><b>{p.price?`${p.price} ${p.currency||""}`:"Price unavailable"}</b>{i?<><p>{i.why}</p><div className={styles.mini}><span>Advertability {i.advertabilityScore}</span><span>Visual {i.visualScore}</span><span>Novelty {i.noveltyScore}</span><span>Confidence {i.confidence}</span></div><div className={styles.tags}>{(i.archetypes||[]).map((a:string)=><span key={a}>{a}</span>)}</div><details><summary>Why / audience / hooks</summary><p><b>Audience:</b> {(i.audience||[]).join(" · ")}</p><p><b>Problem:</b> {(i.problems||[]).join(" · ")}</p><p><b>Organic:</b> {(i.organicHooks||[]).join(" · ")}</p><p><b>Paid:</b> {(i.paidHooks||[]).join(" · ")}</p><p><b>YNOT:</b> {(i.ynotHooks||[]).join(" · ")}</p></details></>:<p>Run Analyze products to build the full reasoning card.</p>}</article>})}</div></section>}

  {combinations.length>0&&<section className={styles.panel}><div className={styles.panelHead}><div><small>6 / COMBINATION ENGINE</small><h2>Useful systems, not random bundles.</h2></div></div><div className={styles.comboGrid}>{combinations.map((c:any)=><article key={c.name}><div><small>{c.type}</small><h3>{c.name}</h3><p>{c.logic}</p></div><strong>{c.score}</strong><div className={styles.comboProducts}>{c.products.map((p:any)=><span key={p.id}>{p.title}</span>)}</div></article>)}</div></section>}
 </div></main>
}
