import {NextRequest,NextResponse} from "next/server";
export const dynamic="force-dynamic";
const SB=process.env.NEXT_PUBLIC_SUPABASE_URL||"",KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||"",PEXELS=process.env.PEXELS_API_KEY||process.env.PEXELS_KEY||"",BUCKET="YNOT FEED",ROOT="album-covers";
const enc=(s:string)=>s.split("/").map(encodeURIComponent).join("/");
async function signed(path:string){const r=await fetch(`${SB}/storage/v1/object/sign/${encodeURIComponent(BUCKET)}/${enc(path)}`,{method:"POST",headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"},body:JSON.stringify({expiresIn:3600}),cache:"no-store"});if(!r.ok)return"";const j=await r.json();const u=String(j?.signedURL||j?.signedUrl||"");if(!u)return"";return u.startsWith("http")?u:`${SB}/storage/v1${u.startsWith("/")?u:`/${u}`}`}
async function urls(prefix:string){if(!SB||!KEY)return[];const r=await fetch(`${SB}/storage/v1/object/list/${encodeURIComponent(BUCKET)}`,{method:"POST",headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"},body:JSON.stringify({prefix,limit:20,offset:0}),cache:"no-store"});if(!r.ok)return[];const j=await r.json();const names=(Array.isArray(j)?j:[]).filter((x:any)=>/\.(jpe?g|png|webp)$/i.test(x.name||"")).slice(0,5).map((x:any)=>String(x.name));return (await Promise.all(names.map(n=>signed(`${prefix}/${n}`)))).filter(Boolean)}
async function upload(path:string,b:ArrayBuffer,type:string){const r=await fetch(`${SB}/storage/v1/object/${encodeURIComponent(BUCKET)}/${enc(path)}`,{method:"POST",headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":type,"x-upsert":"false"},body:b,cache:"no-store"});return r.ok}
const clean=(x:string)=>x.replace(/[-_]+/g," ").replace(/\b(world|category)\b/gi," ").replace(/\s+/g," ").trim();
async function fillPexels(prefix:string,w:string,c:string,s:string){if(!PEXELS||!SB||!KEY)return[];const label=clean(s||c||w),context=clean([w,c].filter(Boolean).join(" "));const q=`${label} ${context} products lifestyle aesthetic`;const r=await fetch(`https://api.pexels.com/v1/search?query=${encodeURIComponent(q)}&orientation=portrait&per_page=10`,{headers:{Authorization:PEXELS},cache:"no-store"});if(!r.ok)return[];const j=await r.json();const photos=Array.isArray(j?.photos)?j.photos.slice(0,5):[];let i=0;for(const p of photos){try{const src=p?.src?.large2x||p?.src?.large||p?.src?.portrait||p?.src?.original;if(!src)continue;const ir=await fetch(src,{cache:"no-store"});if(!ir.ok)continue;const type=ir.headers.get("content-type")||"image/jpeg";if(!type.startsWith("image/"))continue;const body=await ir.arrayBuffer();if(body.byteLength<30000)continue;const ext=type.includes("png")?"png":type.includes("webp")?"webp":"jpg";await upload(`${prefix}/pexels-${p.id||Date.now()}-${i++}.${ext}`,body,type)}catch{}}return urls(prefix)}
export async function GET(req:NextRequest){const w=req.nextUrl.searchParams.get("world")||"",c=req.nextUrl.searchParams.get("category")||"",s=req.nextUrl.searchParams.get("subcategory")||"";if(!w)return NextResponse.json({images:[]});const prefix=s?`${ROOT}/${w}/${c}/${s}`:c?`${ROOT}/${w}/${c}/_category`:`${ROOT}/${w}/_world`;let images=await urls(prefix);if(images.length<2)images=await fillPexels(prefix,w,c,s);return NextResponse.json({images},{headers:{"Cache-Control":"private, max-age=300"}})}
