import {NextRequest,NextResponse} from "next/server";
import {createHash} from "node:crypto";
import {requireYnotAdmin,adminErrorStatus,adminDb} from "@/lib/ynot/admin-server";
import {getAdMedia,googleAutocomplete,searchGoogleAdLibrary,searchGoogleIntent,searchLinkedInAdLibrary,searchMetaAdLibrary,searchTikTokAdLibrary,type AdMediaPlatform} from "@/lib/intelligence/fetchlayer-social";

export const runtime="nodejs";

type Mode="meta_ads"|"tiktok_ads"|"google_ads"|"linkedin_ads"|"google_demand"|"ad_media";
function arr(v:any,...keys:string[]){for(const k of keys){if(Array.isArray(v?.[k]))return v[k]}return []}
function pickText(v:any):string{if(v==null)return"";if(typeof v==="string"||typeof v==="number")return String(v).replace(/\s+/g," ").trim();if(Array.isArray(v))return v.map(pickText).find(Boolean)||"";if(typeof v==="object"){for(const k of ["pageName","advertiserName","businessName","displayName","name","title","text","value","label","caption","body","description"]){const s=pickText(v?.[k]);if(s)return s}}return""}
function pickUrl(...values:any[]){for(const v of values){const s=pickText(v);if(/^https?:\/\//i.test(s))return s}return""}
function sourceMediaUrl(x:any){const direct=pickUrl(x?.url);if(direct)return direct;const dl=pickUrl(x?.downloadUrl,x?.download_url);if(!dl)return"";try{const u=new URL(dl);const nested=u.searchParams.get("url");if(nested&&/^https?:\/\//i.test(nested))return nested}catch{}return dl}
function mediaUrl(a:any,c:any){return pickUrl(c?.imageUrl,c?.image_url,c?.thumbnailUrl,c?.thumbnail_url,c?.mediaUrl,c?.media_url,a?.imageUrl,a?.image_url,a?.thumbnailUrl,a?.thumbnail_url,a?.mediaUrl,a?.media_url,a?.snapshot?.imageUrl,a?.snapshot?.image_url,c?.assets?.[0]?.url,a?.assets?.[0]?.url,c?.cards?.[0]?.imageUrl,c?.cards?.[0]?.image_url,a?.cards?.[0]?.imageUrl,a?.cards?.[0]?.image_url)}
function videoUrl(a:any,c:any){return pickUrl(c?.videoUrl,c?.video_url,a?.videoUrl,a?.video_url,c?.assets?.find?.((x:any)=>pickText(x?.type).toLowerCase().includes("video"))?.url,a?.assets?.find?.((x:any)=>pickText(x?.type).toLowerCase().includes("video"))?.url)}
function stableAdRef(value:string){
 const raw=String(value||"").trim();if(!raw)return"";
 if(/^\d{8,}$/.test(raw))return raw;
 try{const u=new URL(raw);for(const k of ["id","ad_archive_id","adArchiveId","ad_id","adId"]){const v=u.searchParams.get(k);if(v&&/^\d{8,}$/.test(v))return v}const nums=[...raw.matchAll(/\d{8,}/g)].map(m=>m[0]).sort((a,b)=>b.length-a.length);if(nums[0])return nums[0]}catch{}
 return raw;
}
function normalizeAd(a:any,platform:string){
 const c=a?.creative||a?.ad||a||{};
 const advertiser=pickText(a?.advertiser?.pageName)||pickText(a?.advertiser?.name)||pickText(a?.advertiser)||pickText(a?.advertiserName)||pickText(a?.businessName)||pickText(a?.pageName)||pickText(a?.payerName)||pickText(a?.companyName)||"Unknown advertiser";
 const advertiserId=pickText(a?.advertiserId)||pickText(a?.advertiser_id)||pickText(a?.advertiser?.id);
 const rawId=pickText(a?.adArchiveId||a?.adId||a?.id||a?.creativeId);
 const adLibraryUrl=pickUrl(a?.adLibraryUrl,a?.ad_library_url,a?.previewUrl,a?.preview_url,a?.snapshotUrl,a?.snapshot_url,c?.adLibraryUrl,c?.ad_library_url);
 const headline=pickText(c?.headline)||pickText(c?.title)||pickText(a?.headline)||pickText(a?.title)||pickText(c?.body)||pickText(a?.body)||"Ad creative";
 const facebookUrl=pickUrl(a?.facebookPageUrl,a?.facebook_page_url,a?.pageUrl,a?.page_url,a?.advertiser?.facebookUrl,a?.advertiser?.facebook_page_url,a?.advertiser?.pageUrl,a?.advertiser?.url,c?.facebookPageUrl,c?.pageUrl);
 const instagramUrl=pickUrl(a?.instagramUrl,a?.instagram_url,a?.instagramProfileUrl,a?.instagram_profile_url,a?.advertiser?.instagramUrl,a?.advertiser?.instagram_url,a?.advertiser?.instagramProfileUrl,c?.instagramUrl,c?.instagram_profile_url);
 const advertiserProfileUrl=pickUrl(a?.advertiserProfileUrl,a?.advertiser_profile_url,a?.profileUrl,a?.profile_url,a?.accountUrl,a?.account_url,a?.advertiser?.profileUrl,a?.advertiser?.profile_url,a?.advertiser?.url,facebookUrl,instagramUrl);
 const facebookHandle=pickText(a?.facebookHandle||a?.facebook_handle||a?.pageUsername||a?.page_username||a?.advertiser?.pageUsername);
 const instagramHandle=pickText(a?.instagramHandle||a?.instagram_handle||a?.instagramUsername||a?.instagram_username||a?.advertiser?.instagramUsername);
 return{id:rawId||adLibraryUrl||crypto.randomUUID(),rawId,mediaRef:rawId||adLibraryUrl,adLibraryUrl,advertiserId,platform,advertiser,headline,body:pickText(c?.body)||pickText(c?.text)||pickText(c?.caption)||pickText(a?.body)||pickText(a?.text)||pickText(a?.caption),cta:pickText(c?.ctaText)||pickText(c?.callToAction)||pickText(a?.ctaText)||pickText(a?.callToAction),landingPage:pickUrl(c?.linkUrl,c?.destinationUrl,a?.landingPageUrl,a?.linkUrl,a?.destinationUrl),imageUrl:mediaUrl(a,c),videoUrl:videoUrl(a,c),previewUrl:adLibraryUrl,facebookUrl,instagramUrl,advertiserProfileUrl,facebookHandle,instagramHandle,format:pickText(a?.mediaType)||pickText(c?.displayFormat)||pickText(c?.format)||pickText(a?.format)||pickText(c?.type)||pickText(a?.type),started:a?.startDate||a?.shownFrom||a?.firstShownAt||a?.firstShownDate||null,ended:a?.endDate||a?.shownTo||a?.lastShownAt||a?.lastShownDate||null,impressions:a?.impressions||a?.estimatedAudience||a?.impressionsRange||a?.uniqueUsersSeen||null}
}
function cacheKey(kind:string,parts:unknown[]){return createHash("sha256").update(JSON.stringify([kind,...parts])).digest("hex")}
async function readCache(key:string){try{const rows=await adminDb(`ynot_growth_intelligence_cache?cache_key=eq.${encodeURIComponent(key)}&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=payload,hit_count&limit=1`);const row=rows?.[0];if(!row)return null;void adminDb(`ynot_growth_intelligence_cache?cache_key=eq.${encodeURIComponent(key)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({hit_count:Number(row.hit_count||0)+1,updated_at:new Date().toISOString()})}).catch(()=>{});return row.payload}catch{return null}}
async function writeCache(key:string,kind:string,payload:any,ttlMs:number){try{await adminDb("ynot_growth_intelligence_cache?on_conflict=cache_key",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({cache_key:key,kind,payload,expires_at:new Date(Date.now()+ttlMs).toISOString(),updated_at:new Date().toISOString()})})}catch{}}
function withCache(payload:any,hit:boolean,ttlHours:number){return {...payload,cache:{hit,ttlHours}}}

export async function POST(req:NextRequest){
 try{
  await requireYnotAdmin(req);const b=await req.json();const mode=String(b.mode||"") as Mode;const country=(pickText(b.country)||"FR").toUpperCase().slice(0,2);
  if(mode==="ad_media"){
   const platform=pickText(b.platform).toLowerCase() as AdMediaPlatform,requested=pickText(b.ad).slice(0,1200),advertiser=pickText(b.advertiser).slice(0,500),ad=stableAdRef(requested);if(!["meta","tiktok","google","linkedin"].includes(platform))return NextResponse.json({error:"PLATFORM_NOT_SUPPORTED"},{status:400});if(!ad)return NextResponse.json({error:"AD_REQUIRED"},{status:400});
   const key=cacheKey("ad_media_v3",[platform,ad,country,advertiser]);const cached=await readCache(key);if(cached&&Array.isArray(cached?.assets)&&cached.assets.length)return NextResponse.json(withCache(cached,true,168));
   const raw=await getAdMedia(platform,ad,country,advertiser);const assets=arr(raw,"assets").map((x:any)=>{const contentType=pickText(x?.contentType||x?.content_type).toLowerCase();let kind=pickText(x?.kind).toLowerCase();if(!kind){if(contentType.startsWith("video/"))kind="video";else if(contentType.startsWith("image/"))kind="image";else kind="media"}return{kind,quality:pickText(x?.quality),label:pickText(x?.label),url:sourceMediaUrl(x),downloadUrl:pickUrl(x?.downloadUrl,x?.download_url),contentType:pickText(x?.contentType||x?.content_type),contentLength:Number(x?.contentLength||x?.content_length||0)||null,attachmentIndex:x?.attachmentIndex??x?.attachment_index??null}}).filter((x:any)=>x.url||x.downloadUrl);const payload={mode,platform,requestedAd:requested,adId:pickText(raw?.adId||raw?.adArchiveId)||ad,assetCount:Number(raw?.assetCount||assets.length),assets,notes:Array.isArray(raw?.notes)?raw.notes:[]};if(assets.length)await writeCache(key,"ad_media",payload,7*24*60*60*1000);return NextResponse.json(withCache(payload,false,assets.length?168:0));
  }
  const query=pickText(b.query).slice(0,300),language=(pickText(b.language)||"en").slice(0,12),cursor=pickText(b.cursor).slice(0,4000);const limit=Math.max(20,Math.min(200,Number(b.limit)||100)),pages=Math.max(1,Math.min(10,Number(b.pages)||5));if(!query)return NextResponse.json({error:"QUERY_REQUIRED"},{status:400});
  const normalizedQuery=query.toLowerCase().replace(/\s+/g," ").trim();const key=cacheKey("search_v4_"+mode,[normalizedQuery,country,language,limit,pages,cursor]);const ttlHours=mode==="google_demand"?12:24;const cached=await readCache(key);if(cached)return NextResponse.json(withCache(cached,true,ttlHours));
  if(mode==="google_demand"){
   const [serp,auto]=await Promise.all([searchGoogleIntent(query,country,language),googleAutocomplete(query,country,language)]);const related=arr(serp,"relatedSearches","related_searches").map((x:any)=>pickText(x?.query||x?.text||x)).filter(Boolean),questions=arr(serp,"peopleAlsoAsk","people_also_ask").map((x:any)=>pickText(x?.question||x?.text||x)).filter(Boolean),suggestions=arr(auto,"suggestions","completions","results").map((x:any)=>pickText(x?.query||x?.text||x?.value||x)).filter(Boolean),discussions=arr(serp,"discussions","discussionResults").slice(0,20).map((x:any)=>({title:pickText(x?.title),url:pickUrl(x?.url),snippet:pickText(x?.snippet),imageUrl:pickUrl(x?.imageUrl,x?.image_url,x?.thumbnailUrl,x?.thumbnail_url)}));const payload={mode,query,country,language,signals:{suggestions:[...new Set(suggestions)].slice(0,30),questions:[...new Set(questions)].slice(0,30),related:[...new Set(related)].slice(0,30),discussions},notes:Array.isArray(serp?.notes)?serp.notes:[]};await writeCache(key,"google_demand",payload,12*60*60*1000);return NextResponse.json(withCache(payload,false,12));
  }
  let raw:any,platform="";if(mode==="meta_ads"){raw=await searchMetaAdLibrary(query,country,limit,pages,cursor);platform="Meta"}else if(mode==="tiktok_ads"){raw=await searchTikTokAdLibrary(query,country,limit,pages,cursor);platform="TikTok"}else if(mode==="google_ads"){raw=await searchGoogleAdLibrary(query,country,limit,pages,cursor);platform="Google"}else if(mode==="linkedin_ads"){raw=await searchLinkedInAdLibrary(query,country,limit,pages,cursor);platform="LinkedIn"}else return NextResponse.json({error:"MODE_NOT_SUPPORTED"},{status:400});
  const ads=arr(raw,"ads","results","adResults").map((x:any)=>normalizeAd(x,platform));const matchedAdvertisers=arr(raw,"matchedAdvertisers","advertisers").map((x:any)=>pickText(x)).filter(Boolean);const groups=new Map<string,{advertiser:string,count:number,samples:any[]}>();for(const ad of ads){const groupKey=ad.advertiser.toLowerCase(),g=groups.get(groupKey)||{advertiser:ad.advertiser,count:0,samples:[]};g.count++;if(g.samples.length<3)g.samples.push(ad);groups.set(groupKey,g)}
  const payload={mode,query,country,platform,ads,advertisers:[...groups.values()].sort((a,b)=>b.count-a.count).slice(0,30),matchedAdvertisers,adCount:Number(raw?.adCount||ads.length),totalMatches:raw?.totalMatches??raw?.totalMatchCount??raw?.approximateTotal??null,pagesScraped:Number(raw?.pagesScraped||0)||null,pagesRequested:Number(raw?.pagesRequested||pages)||pages,hasNextPage:Boolean(raw?.hasNextPage),nextCursor:raw?.nextCursor||null,notes:Array.isArray(raw?.notes)?raw.notes:[]};await writeCache(key,"ad_search",payload,24*60*60*1000);return NextResponse.json(withCache(payload,false,24));
 }catch(e){const m=e instanceof Error?e.message:"GROWTH_INTELLIGENCE_FAILED";return NextResponse.json({error:m},{status:/FETCHLAYER_NOT_CONFIGURED/.test(m)?503:adminErrorStatus(e)})}
}
