import {NextRequest,NextResponse} from "next/server";
import {requireYnotAdmin,adminErrorStatus} from "@/lib/ynot/admin-server";
import {getAdMedia,googleAutocomplete,searchGoogleAdLibrary,searchGoogleIntent,searchLinkedInAdLibrary,searchMetaAdLibrary,searchTikTokAdLibrary,type AdMediaPlatform} from "@/lib/intelligence/fetchlayer-social";

export const runtime="nodejs";

type Mode="meta_ads"|"tiktok_ads"|"google_ads"|"linkedin_ads"|"google_demand"|"ad_media";
function arr(v:any,...keys:string[]){for(const k of keys){if(Array.isArray(v?.[k]))return v[k]}return []}
function pickText(v:any):string{if(v==null)return"";if(typeof v==="string"||typeof v==="number")return String(v).replace(/\s+/g," ").trim();if(Array.isArray(v))return v.map(pickText).find(Boolean)||"";if(typeof v==="object"){for(const k of ["pageName","advertiserName","businessName","displayName","name","title","text","value","label","caption","body","description"]){const s=pickText(v?.[k]);if(s)return s}}return""}
function pickUrl(...values:any[]){for(const v of values){const s=pickText(v);if(/^https?:\/\//i.test(s))return s}return""}
function mediaUrl(a:any,c:any){return pickUrl(c?.imageUrl,c?.image_url,c?.thumbnailUrl,c?.thumbnail_url,c?.mediaUrl,c?.media_url,a?.imageUrl,a?.image_url,a?.thumbnailUrl,a?.thumbnail_url,a?.mediaUrl,a?.media_url,a?.snapshot?.imageUrl,a?.snapshot?.image_url,c?.assets?.[0]?.url,a?.assets?.[0]?.url,c?.cards?.[0]?.imageUrl,c?.cards?.[0]?.image_url,a?.cards?.[0]?.imageUrl,a?.cards?.[0]?.image_url)}
function videoUrl(a:any,c:any){return pickUrl(c?.videoUrl,c?.video_url,a?.videoUrl,a?.video_url,c?.assets?.find?.((x:any)=>pickText(x?.type).toLowerCase().includes("video"))?.url,a?.assets?.find?.((x:any)=>pickText(x?.type).toLowerCase().includes("video"))?.url)}
function normalizeAd(a:any,platform:string){const c=a?.creative||a?.ad||a||{};const advertiser=pickText(a?.advertiser?.pageName)||pickText(a?.advertiser?.name)||pickText(a?.advertiser)||pickText(a?.advertiserName)||pickText(a?.businessName)||pickText(a?.pageName)||pickText(a?.payerName)||pickText(a?.companyName)||"Unknown advertiser";const headline=pickText(c?.headline)||pickText(c?.title)||pickText(a?.headline)||pickText(a?.title)||pickText(c?.body)||pickText(a?.body)||"Ad creative";return{id:String(a?.adArchiveId||a?.adId||a?.id||a?.creativeId||crypto.randomUUID()),platform,advertiser,headline,body:pickText(c?.body)||pickText(c?.text)||pickText(c?.caption)||pickText(a?.body)||pickText(a?.text)||pickText(a?.caption),cta:pickText(c?.ctaText)||pickText(c?.callToAction)||pickText(a?.ctaText)||pickText(a?.callToAction),landingPage:pickUrl(c?.linkUrl,c?.destinationUrl,a?.landingPageUrl,a?.linkUrl,a?.destinationUrl),imageUrl:mediaUrl(a,c),videoUrl:videoUrl(a,c),previewUrl:pickUrl(a?.previewUrl,a?.preview_url,a?.adLibraryUrl,a?.ad_library_url,a?.snapshotUrl,a?.snapshot_url),format:pickText(a?.mediaType)||pickText(c?.displayFormat)||pickText(c?.format)||pickText(a?.format)||pickText(c?.type)||pickText(a?.type),started:a?.startDate||a?.shownFrom||a?.firstShownAt||a?.firstShownDate||null,ended:a?.endDate||a?.shownTo||a?.lastShownAt||a?.lastShownDate||null,impressions:a?.impressions||a?.estimatedAudience||a?.impressionsRange||a?.uniqueUsersSeen||null}}

export async function POST(req:NextRequest){
 try{
  await requireYnotAdmin(req);const b=await req.json();const mode=String(b.mode||"") as Mode;const country=(pickText(b.country)||"FR").toUpperCase().slice(0,2);
  if(mode==="ad_media"){
   const platform=pickText(b.platform).toLowerCase() as AdMediaPlatform;const ad=pickText(b.ad).slice(0,700);if(!["meta","tiktok","google","linkedin"].includes(platform))return NextResponse.json({error:"PLATFORM_NOT_SUPPORTED"},{status:400});if(!ad)return NextResponse.json({error:"AD_REQUIRED"},{status:400});
   const raw=await getAdMedia(platform,ad,country);const assets=arr(raw,"assets").map((x:any)=>({kind:pickText(x?.kind)||"media",quality:pickText(x?.quality),label:pickText(x?.label),url:pickUrl(x?.url),downloadUrl:pickUrl(x?.downloadUrl,x?.download_url),contentType:pickText(x?.contentType||x?.content_type),contentLength:Number(x?.contentLength||x?.content_length||0)||null,attachmentIndex:x?.attachmentIndex??x?.attachment_index??null})).filter((x:any)=>x.url||x.downloadUrl);
   return NextResponse.json({mode,platform,adId:pickText(raw?.adId||raw?.adArchiveId)||ad,assetCount:Number(raw?.assetCount||assets.length),assets,notes:Array.isArray(raw?.notes)?raw.notes:[]});
  }
  const query=pickText(b.query).slice(0,300),language=(pickText(b.language)||"en").slice(0,12),cursor=pickText(b.cursor).slice(0,4000);const limit=Math.max(20,Math.min(200,Number(b.limit)||100)),pages=Math.max(1,Math.min(10,Number(b.pages)||5));if(!query)return NextResponse.json({error:"QUERY_REQUIRED"},{status:400});
  if(mode==="google_demand"){const [serp,auto]=await Promise.all([searchGoogleIntent(query,country,language),googleAutocomplete(query,country,language)]);const related=arr(serp,"relatedSearches","related_searches").map((x:any)=>pickText(x?.query||x?.text||x)).filter(Boolean),questions=arr(serp,"peopleAlsoAsk","people_also_ask").map((x:any)=>pickText(x?.question||x?.text||x)).filter(Boolean),suggestions=arr(auto,"suggestions","completions","results").map((x:any)=>pickText(x?.query||x?.text||x?.value||x)).filter(Boolean),discussions=arr(serp,"discussions","discussionResults").slice(0,20).map((x:any)=>({title:pickText(x?.title),url:pickUrl(x?.url),snippet:pickText(x?.snippet),imageUrl:pickUrl(x?.imageUrl,x?.image_url,x?.thumbnailUrl,x?.thumbnail_url)}));return NextResponse.json({mode,query,country,language,signals:{suggestions:[...new Set(suggestions)].slice(0,30),questions:[...new Set(questions)].slice(0,30),related:[...new Set(related)].slice(0,30),discussions},notes:Array.isArray(serp?.notes)?serp.notes:[]})}
  let raw:any,platform="";if(mode==="meta_ads"){raw=await searchMetaAdLibrary(query,country,limit,pages,cursor);platform="Meta"}else if(mode==="tiktok_ads"){raw=await searchTikTokAdLibrary(query,country,limit,pages,cursor);platform="TikTok"}else if(mode==="google_ads"){raw=await searchGoogleAdLibrary(query,country,limit,pages,cursor);platform="Google"}else if(mode==="linkedin_ads"){raw=await searchLinkedInAdLibrary(query,country,limit,pages,cursor);platform="LinkedIn"}else return NextResponse.json({error:"MODE_NOT_SUPPORTED"},{status:400});
  const ads=arr(raw,"ads","results","adResults").map((x:any)=>normalizeAd(x,platform));const matchedAdvertisers=arr(raw,"matchedAdvertisers","advertisers").map((x:any)=>pickText(x)).filter(Boolean);const groups=new Map<string,{advertiser:string,count:number,samples:any[]}>();for(const ad of ads){const key=ad.advertiser.toLowerCase(),g=groups.get(key)||{advertiser:ad.advertiser,count:0,samples:[]};g.count++;if(g.samples.length<3)g.samples.push(ad);groups.set(key,g)}
  return NextResponse.json({mode,query,country,platform,ads,advertisers:[...groups.values()].sort((a,b)=>b.count-a.count).slice(0,30),matchedAdvertisers,adCount:Number(raw?.adCount||ads.length),totalMatches:raw?.totalMatches??raw?.totalMatchCount??raw?.approximateTotal??null,pagesScraped:Number(raw?.pagesScraped||0)||null,pagesRequested:Number(raw?.pagesRequested||pages)||pages,hasNextPage:Boolean(raw?.hasNextPage),nextCursor:raw?.nextCursor||null,notes:Array.isArray(raw?.notes)?raw.notes:[]});
 }catch(e){const m=e instanceof Error?e.message:"GROWTH_INTELLIGENCE_FAILED";return NextResponse.json({error:m},{status:/FETCHLAYER_NOT_CONFIGURED/.test(m)?503:adminErrorStatus(e)})}
}