"use client";
import {useEffect,useMemo,useState} from "react";

type Preset={id:string;label:string;title:string;price:string;description:string;tags:string[];format:string;bundle?:boolean};
const help=`\n\nDIGITAL DOWNLOAD\nNo physical item will be shipped.\n\nNEED IMPLEMENTATION HELP?\nContact us through the platform where you purchased this product. Send your store/business URL, platform, target market and the module or step you need help with.`;
const PRESETS:Preset[]=[
 {id:"flagship",label:"01 · Flagship",title:"Sell Through AI: AI Commerce Playbook",price:"24.90",format:"Digital PDF",tags:["ai commerce","ai shopping guide","chatgpt business","ecommerce guide","ai marketing","product discovery","shopify guide","business playbook","online selling","small business ai","product seo","ai business","pinterest guide"],description:`Sell Through AI is the flagship visual AI Commerce Playbook for founders, ecommerce sellers, marketers, creators and service businesses.\n\nWHAT YOU'LL LEARN\n• How AI-assisted buying and product discovery work\n• How products and services can become understandable to AI systems\n• Shopify, ecommerce and structured product-data paths\n• SEO and machine-readable information fundamentals\n• When MCP makes sense\n• Real AI-shopping examples and visual breakdowns\n• Product and service discovery paths\n• Pinterest and other discovery channels\n• Implementation checklist, prompts and action plan\n\nUse this as the broad starting point before moving into the specialist courses.`+help},
 {id:"shopify",label:"02 · Shopify + ChatGPT",title:"Shopify Products in ChatGPT: AI Shopping Course",price:"19.90",format:"Digital PDF Course",tags:["shopify chatgpt","ai shopping","shopify seo","shopify course","ecommerce ai","product discovery","chatgpt shopping","product data","shopify marketing","online store seo","ai ecommerce","product feed","seller course"],description:`A practical implementation course for Shopify sellers who want their catalogue to be clearer, more accurate and better prepared for AI-assisted product discovery.\n\nINSIDE THE COURSE\n• Understand the ChatGPT shopping discovery system\n• Rewrite weak product titles\n• Build retrieval-friendly product descriptions\n• Clean variants, price and availability\n• Upgrade product imagery\n• Test real buyer prompts\n• Understand when deeper ACP integration matters\n• Build a 30-day optimization loop\n• Implementation scorecard and reference library\n\nDesigned for Shopify founders, ecommerce operators and marketers who want a concrete workflow rather than a generic AI ebook.`+help},
 {id:"google",label:"03 · Google AI Shopping",title:"Google AI Shopping & Merchant Center Course 2026",price:"24.90",format:"Digital PDF Course",tags:["google shopping","merchant center","google ai shopping","ecommerce seo","product schema","product feed","shopping seo","google merchant","ai ecommerce","structured data","product listing","seller course","ai shopping"],description:`A step-by-step 2026 course for improving the product-data foundation behind Google shopping experiences and Merchant Center.\n\nINSIDE THE COURSE\n• Map Google's shopping surfaces\n• Build a clean product-data foundation\n• Add Product + Offer structured data\n• Improve product imagery\n• Work with conversational product attributes\n• Read AI Performance Insights where available\n• Prioritize high-value visibility gaps\n• Create a monthly Merchant Center routine\n• Implementation scorecard and official reference library\n\nFor ecommerce sellers and marketers who want a practical Merchant Center and AI-shopping workflow.`+help},
 {id:"seo",label:"04 · AI SEO",title:"AI SEO for Ecommerce: Product Page Course",price:"19.90",format:"Digital PDF Course",tags:["ai seo","ecommerce seo","product page seo","product schema","structured data","product seo","seo course","ai search seo","online store seo","product discovery","ecommerce course","search visibility","ai ecommerce"],description:`A practical ecommerce SEO course focused on making product pages crawlable, structured, descriptive and easier for search and AI shopping systems to understand.\n\nINSIDE THE COURSE\n• Check crawlability and canonical product URLs\n• Build entity-rich product pages\n• Implement Product + Offer structured data\n• Write around real buyer questions\n• Use product images as evidence\n• Align page, feed and inventory data\n• Test conversational buyer queries\n• Build a repeatable optimization loop\n• Implementation scorecard and reference library\n\nBuilt for store owners, ecommerce marketers and SEO practitioners.`+help},
 {id:"mcp",label:"05 · MCP Shopping Assistant",title:"Build an MCP Shopping Assistant: Store Course",price:"29.90",format:"Digital PDF Course",tags:["mcp course","shopping assistant","ai agent course","ecommerce mcp","mcp server","ai ecommerce","product api","chatgpt tools","ai shopping","agentic commerce","product search","developer course","store automation"],description:`A hands-on architecture course for turning a product catalogue into a controlled set of tools an AI assistant can search and use.\n\nINSIDE THE COURSE\n• Decide whether MCP fits your store\n• Design a small, useful tool set\n• Build search around buyer intent\n• Return clean product-detail data\n• Separate public tools from private admin capabilities\n• Test assistant behavior with real prompts\n• Add visual UI without making it the source of truth\n• Deploy read-only first and monitor quality\n• Architecture checklist and implementation scorecard\n\nBest suited to technical founders, developers and ecommerce teams building AI-assisted catalogue experiences.`+help},
 {id:"bundle",label:"06 · Complete Bundle",title:"AI Commerce Course Bundle: 5 Guides for 2026",price:"59.90",format:"5 Digital PDFs",bundle:true,tags:["ai course bundle","ai commerce","ecommerce bundle","ai shopping","chatgpt business","google shopping","ecommerce seo","mcp course","shopify course","business bundle","product discovery","ai marketing","seller toolkit"],description:`The complete Sell Through AI learning system: the flagship AI Commerce Playbook plus four specialist implementation courses.\n\nYOU RECEIVE 5 PDFs\n1. Sell Through AI — The AI Commerce Playbook\n2. Shopify Products in ChatGPT — AI Shopping Course\n3. Google AI Shopping & Merchant Center Masterclass 2026\n4. AI SEO for Ecommerce — Product Page to AI Answer\n5. Build an MCP Shopping Assistant for Your Store\n\nTogether they cover the broad AI-commerce strategy, Shopify catalogue optimization, Google Merchant Center, ecommerce structured data and SEO, and MCP shopping-assistant architecture.\n\nEach specialist course includes practical actions, a scorecard and reference material. Buy the bundle if you want the complete system rather than one specialist topic.`+help}
];

export default function EtsyListingBuilder(){
 const [setup,setSetup]=useState<any>(null),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState(""),[presetId,setPresetId]=useState("flagship");
 const preset=useMemo(()=>PRESETS.find(p=>p.id===presetId)||PRESETS[0],[presetId]);
 useEffect(()=>{fetch("/api/etsy/admin/listing",{cache:"no-store"}).then(r=>r.json()).then(setSetup).catch(()=>setSetup({ok:false}))},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setResult(null);try{const fd=new FormData(e.currentTarget);fd.set("presetId",preset.id);const r=await fetch("/api/etsy/admin/listing",{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not create Etsy draft");setResult(j)}catch(e:any){setError(e?.message||"Could not create Etsy draft")}finally{setBusy(false)}}
 return <section className="etsyCard listingBuilder"><div className="etsyHead"><div><span>SELL THROUGH AI · 6 LISTINGS</span><h2>Etsy launch queue</h2></div><div className="etsyStatus connected"><i/>Drafts only</div></div>
 <p className="etsyCopy">Choose a product, attach its final PDF(s) and listing gallery, then create an Etsy draft. Nothing is published automatically.</p>
 {!setup?<div className="etsyMuted">Loading connected shop…</div>:!setup.ok?<div className="etsyError">{setup.error||"Could not load Etsy shop."}</div>:<form key={preset.id} onSubmit={submit}>
  <label className="etsyField"><span>Product to prepare</span><select value={presetId} onChange={e=>setPresetId(e.target.value)}>{PRESETS.map(p=><option value={p.id} key={p.id}>{p.label}</option>)}</select></label>
  <div className="etsyFacts"><div><small>Connected shop</small><strong>{setup.shop?.name}</strong></div><div><small>Suggested category</small><strong>{setup.taxonomy?.path||"Review category"}</strong></div><div><small>Format</small><strong>{preset.format}</strong></div></div>
  <label className="etsyField"><span>Title</span><input name="title" defaultValue={preset.title} maxLength={140}/><small>Buyer-readable title first; tags and description carry the broader search vocabulary.</small></label>
  <label className="etsyField"><span>Description</span><textarea name="description" defaultValue={preset.description} rows={18}/></label>
  <div className="etsyTwo"><label className="etsyField"><span>Price</span><input name="price" type="number" min="0.2" step="0.01" defaultValue={preset.price}/></label><label className="etsyField"><span>Taxonomy ID</span><input name="taxonomyId" type="number" defaultValue={setup.taxonomy?.id||""}/></label></div>
  <label className="etsyField"><span>13 discovery tags</span><textarea name="tags" defaultValue={preset.tags.join(", ")} rows={5}/><small>13 varied, relevant phrases. The server validates Etsy's 20-character limit.</small></label>
  <label className="etsyUpload"><span>{preset.bundle?"Course PDFs — select all 5":"Course PDF"}</span><input name="pdfs" type="file" accept="application/pdf" multiple={preset.bundle} required/><small>{preset.bundle?"Attach the flagship plus all four specialist course PDFs.":"Attach the final redesigned PDF for this listing."}</small></label>
  <label className="etsyUpload"><span>Listing images — cover first</span><input name="images" type="file" accept="image/png,image/jpeg,image/webp" multiple required/><small>Use the unique cover first, then course previews, modules, workbook and implementation-help slides.</small></label>
  <button className="etsyPrimary createDraft" disabled={busy}>{busy?"Creating Etsy draft…":`Create ${preset.label.replace(/^\d+ · /,"")} draft`}</button>
  {error&&<div className="etsyError">{error}</div>}{result&&<div className="etsySuccess"><strong>Draft created ✓</strong><span>Listing #{result.listingId}</span><span>{result.filesUploaded} PDF file(s) · {result.imagesUploaded} image(s)</span><span>{result.tags?.join(" · ")}</span></div>}
 </form>}
 </section>
}
