import {NextRequest,NextResponse} from "next/server";
import {checkoutMode} from "@/lib/commerce/checkout";
import {dynamicLuminaPrice} from "@/lib/commerce/engine";
import {searchChannel3} from "@/lib/catalog/channel3";
export const runtime="nodejs";
type P={id:string;title:string;brand:string;price:number|null;currency?:string;image:string;images?:string[];url?:string;tags?:string[];source?:string;description?:string;variants?:unknown[];[k:string]:unknown};
type Intent={min?:number;max?:number;currency:string;explicitCurrency:boolean};
const CURRENCY:Record<string,string>={US:"USD",GB:"GBP",FR:"EUR",DE:"EUR",ES:"EUR",IT:"EUR",BE:"EUR",CA:"CAD",AU:"AUD"};
const AMAZON:Record<string,string>={US:"amazon.com",GB:"amazon.co.uk",FR:"amazon.fr",DE:"amazon.de",ES:"amazon.es",IT:"amazon.it",BE:"amazon.com.be",CA:"amazon.ca",AU:"amazon.com.au"};
function clean(s:any){return String(s||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function stripPrice(s:string){return s.replace(/(?:under|below|less than|up to|max|over|above|more than|at least|min)\s*(?:€|eur|£|gbp|\$|usd)?\s*\d+(?:[.,]\d+)?/ig," ").replace(/\s+/g," ").trim()||s}
function intent(q:string,country:string):Intent{const l=q.toLowerCase(),upper=l.match(/(?:under|below|less than|up to|max)\s*(?:€|eur|£|gbp|\$|usd)?\s*(\d+(?:[.,]\d+)?)/),lower=l.match(/(?:over|above|more than|at least|min)\s*(?:€|eur|£|gbp|\$|usd)?\s*(\d+(?:[.,]\d+)?)/),currency=/£|gbp/.test(l)?"GBP":/\$|usd/.test(l)?"USD":/€|eur/.test(l)?"EUR":CURRENCY[country]||"EUR";return{min:lower?Number(lower[1].replace(",",".")):undefined,max:upper?Number(upper[1].replace(",",".")):undefined,currency,explicitCurrency:/€|eur|£|gbp|\$|usd/.test(l)}}
function category(p:P){const s=`${p.title} ${(p.tags||[]).join(" ")}`.toLowerCase();if(/dress|shirt|shoe|bag|jewel|apparel|clothing|hoodie|jeans/.test(s))return"fashion";if(/fitness|gym|training|running|sport|protein|creatine/.test(s))return"fitness";if(/skin|beauty|serum|cream|spf/.test(s))return"skin";if(/hair|scalp|shampoo/.test(s))return"hair";if(/home|decor|furniture|sofa|chair|table|lamp|rug|bed/.test(s))return"home";if(/tech|phone|audio|headphone|charger|gaming|smart|laptop|monitor|camera/.test(s))return"tech";return"default"}
function retail(p:P){const cost=Number(p.price);if(!Number.isFinite(cost)||cost<=0)return p;const price=dynamicLuminaPrice({sourceId:p.source||"discovery",productId:p.id,title:p.title,category:category(p),price:cost,currency:p.currency||"EUR",shipping:0,stockConfidence:.75,returnPolicyScore:.7,regionMatch:.75});return{...p,supplierPrice:cost,retailPrice:price,price,pricingMode:"ynot-retail",checkout:checkoutMode(p)}}
function safe(list:P[],i:Intent){return list.filter(p=>p.id&&p.title&&p.image&&p.url&&p.url!=="#"&&p.price!=null).map(retail).filter(p=>(i.min==null||Number(p.price)>=i.min)&&(i.max==null||Number(p.price)<=i.max)&&(!i.explicitCurrency||!p.currency||p.currency===i.currency))}
function key(p:P){return clean(p.title).toLowerCase().replace(/[^a-z0-9]+/g," ").trim()+"|"+clean(p.brand).toLowerCase()}
function relevance(p:P,q:string){const words=stripPrice(q).toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2),text=`${p.title} ${p.brand} ${p.description||""} ${(p.tags||[]).join(" ")}`.toLowerCase();let n=0;for(const w of words)if(text.includes(w))n+=8;if(p.source==="channel3")n+=1;return n}
function mix(groups:P[][],q:string,limit=180){const seen=new Set<string>(),all: P[]=[];for(const p of groups.flat()){const k=key(p);if(!k||seen.has(k))continue;seen.add(k);all.push(p)}return all.sort((a,b)=>relevance(b,q)-relevance(a,q)).slice(0,limit)}
async function shopify(q:string,country:string,cursor?:string){const payload={jsonrpc:"2.0",method:"tools/call",id:1,params:{name:"search_catalog",arguments:{meta:{"ucp-agent":{profile:"https://shopify.dev/ucp/agent-profiles/2026-08-25/valid-with-capabilities.json"}},catalog:{query:stripPrice(q),filters:{available:true,ships_to:{country}},context:{address_country:country,intent:q},pagination:{limit:50,...(cursor?{cursor}:{})}}}}};const r=await fetch("https://catalog.shopify.com/api/ucp/mcp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const raw:any=await r.json(),c=raw?.result?.structuredContent;if(!r.ok||!Array.isArray(c?.products))throw new Error("SHOPIFY_UNAVAILABLE");const products:P[]=c.products.map((x:any)=>{const pr=x?.price_range?.min||x?.variants?.[0]?.price,media=(x?.media||[]).map((m:any)=>m?.url||m?.image?.url).filter(Boolean),variants=(x?.variants||[]).map((v:any)=>({id:String(v.id||""),label:clean(v.title||v.name||"Option"),price:v?.price?Number(v.price.amount)/100:null,currency:v?.price?.currency||pr?.currency,url:v.url||v?.seller?.url||x.url,available:v.available!==false}));return{id:String(x.id),title:clean(x.title),brand:clean(x?.seller?.name||x?.variants?.[0]?.seller?.name||"Shopify merchant"),price:pr?Number(pr.amount)/100:null,currency:pr?.currency||"USD",image:media[0]||"",images:media.slice(0,10),url:x.url||x?.variants?.[0]?.seller?.url||"#",description:clean(x.description)||clean(x.descriptionHtml),variants,tags:[],source:"shopify-global-catalog"}});return{products,pagination:c.pagination||{}}}
async function channel3(q:string,country:string){const rows=await searchChannel3(stripPrice(q),{limit:80,country});return rows.map(x=>({...x,source:"channel3",verified:true,verifiedMerchant:true,tags:[...(x.tags||[]),"Verified"]})) as P[]}
async function amazon(q:string,country:string,page:number){const apiKey=process.env.RAINFOREST_API_KEY;if(!apiKey)return[];const domain=AMAZON[country]||"amazon.fr",params=new URLSearchParams({api_key:apiKey,type:"search",amazon_domain:domain,search_term:stripPrice(q),number_of_results:"48",exclude_sponsored:"true"});if(page)params.set("page",String(page+1));const r=await fetch(`https://api.rainforestapi.com/request?${params}`,{cache:"no-store"});if(!r.ok)return[];const raw:any=await r.json();return (raw?.search_results||[]).map((x:any)=>({id:`amazon-${x.asin}`,title:clean(x.title),brand:clean(x.brand||x.manufacturer||"Amazon"),price:Number(x?.price?.value)||null,currency:x?.price?.currency||CURRENCY[country]||"EUR",image:x?.image||x?.main_image?.link||x?.images?.[0]?.link||"",url:x?.link||x?.url||`https://${domain}/dp/${x.asin}`,description:clean(x.description||x.snippet),tags:["Amazon"],source:"amazon-rainforest"})) as P[]}
export async function GET(req:NextRequest){const s=req.nextUrl.searchParams,base=(s.get("q")||"black dress for a wedding under 150").slice(0,300),direction=(s.get("direction")||"").slice(0,120),q=direction?`${base}, ${direction}`:base,country=(s.get("country")||"FR").toUpperCase().slice(0,2),source=s.get("source")||"all",cursor=s.get("cursor")||undefined,page=Math.max(0,Number(s.get("page")||0)),i=intent(q,country);
 if(s.get("market")==="ebay")return NextResponse.json({source:"ebay-marketplace",sources:[],market:"ebay",query:q,products:[],pagination:{has_next_page:false},error:"eBay search is temporarily routed separately."},{status:200});
 if(source==="shopify"){try{const x=await shopify(q,country,cursor);return NextResponse.json({source:"shopify-global-catalog",sources:["shopify-global-catalog"],market:"lumina",luminaSource:"shopify",query:q,products:safe(x.products,i),pagination:x.pagination})}catch{return NextResponse.json({source:"shopify-global-catalog",sources:[],products:[],pagination:{has_next_page:false},error:"Shopify products are temporarily unavailable in YNOT."})}}
 if(source==="amazon"){const a=safe(await amazon(q,country,page),i);return NextResponse.json({source:"amazon-rainforest",sources:a.length?["amazon-rainforest"]:[],market:"lumina",luminaSource:"amazon",query:q,products:a,pagination:{has_next_page:a.length>=20}})}
 const [sr,cr,ar]=await Promise.allSettled([shopify(q,country,cursor),channel3(q,country),amazon(q,country,page)]);const sp=safe(sr.status==="fulfilled"?sr.value.products:[],i),cp=safe(cr.status==="fulfilled"?cr.value:[],i),ap=safe(ar.status==="fulfilled"?ar.value:[],i),products=mix([sp,cp,ap],q);return NextResponse.json({source:"ynot-multi-source",sources:[...(sp.length?["shopify-global-catalog"]:[]),...(cp.length?["channel3"]:[]),...(ap.length?["amazon-rainforest"]:[])],market:"lumina",luminaSource:"all",query:q,products,pagination:{...(sr.status==="fulfilled"?sr.value.pagination:{}),amazon_has_next_page:ap.length>=20,channel3_count:cp.length},error:products.length?undefined:"No live products found for this search yet."},{headers:{"Cache-Control":"s-maxage=20, stale-while-revalidate=90"}})}
