"use client";

import {useMemo,useState} from "react";
import {authedFetch,readSession} from "@/lib/ynot/supabase-browser";
import styles from "./intelligence.module.css";

type ScanResult={probe:any;products:any[];metrics:any;strategy:any;error?:string;frontier?:boolean;recursive?:boolean;parent?:string;depth?:number};
type Lens="gems"|"broad"|"conversion"|"ynot"|"high"|"low";

export default function IntelligencePage(){
 const[access,setAccess]=useState(readSession()?"ready":"signin");
 const[running,setRunning]=useState(false),[progress,setProgress]=useState(0),[results,setResults]=useState<ScanResult[]>([]),[lens,setLens]=useState<Lens>("gems"),[notice,setNotice]=useState(""),[researchQuery,setResearchQuery]=useState(""),[filterText,setFilterText]=useState(""),[expanded,setExpanded]=useState<string|null>(null),[digging,setDigging]=useState<string|null>(null);

 async function call(path:string,payload:any){const r=await authedFetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(r.status===401){setAccess("signin");throw new Error("Sign in required")}if(r.status===403){setAccess("forbidden");throw new Error("Owner access required")}if(!r.ok)throw new Error(d?.error||"INTELLIGENCE_FAILED");return d}
 async function api(payload:any){return call("/api/admin/ads/intelligence",payload)}
 function mapRecursive(branch:any):ScanResult{return{recursive:true,parent:branch.parent,depth:branch.depth,probe:{name:branch.name,query:branch.query,vertical:`Recursive · ${branch.axisLabel}`,audience:`Owners and specialist buyers around ${branch.parent}`,intent:branch.axis},products:branch.products||[],metrics:{...branch.metrics,gem:branch.metrics?.opportunity||0,broad:Math.round((branch.metrics?.visual||0)*.35+(branch.metrics?.inventory||0)*.25+(branch.metrics?.opportunity||0)*.4),conversion:Math.round((branch.metrics?.evidence||0)*.42+(branch.metrics?.opportunity||0)*.58),ynot:Math.round((branch.metrics?.visual||0)*.3+(branch.metrics?.opportunity||0)*.7),priceSpread:branch.metrics?.price||{}},strategy:{audience:`People already using, buying or solving problems around ${branch.parent}.`,organic:branch.strategy?.content,paid:branch.strategy?.paid,ynot:branch.strategy?.ynot,firstTest:branch.metrics?.opportunity>=80?"6–10 creatives across reveal, utility and specialist-proof hooks":"3–6 creatives across reveal and utility hooks",angles:[branch.why,branch.strategy?.next].filter(Boolean)}}}
 function mapBrain(data:any,term:string):ScanResult{const m=data.metrics||{};const research=data.marketResearch||data.dossier||{};return{probe:{name:data.node?.name||term,query:data.node?.query||term,vertical:"AI market research",audience:(research.buyerSegments||research.audiences||data.node?.audience||[]).map((x:any)=>typeof x==="string"?x:x.segment).filter(Boolean).join(" · ")||"Research-derived buyers",intent:"market-research"},products:data.products||[],metrics:{...m,gem:m.opportunity||0,broad:m.discovery||0,conversion:m.conversion||0,ynot:m.ynot||0,evidence:m.evidence||0,productCount:m.productCount||(data.products||[]).length,brandCount:m.merchantCount||0,priceSpread:m.price||{},visual:m.visual||0,ticket:m.ticket||"mixed"},strategy:{audience:(research.buyerSegments||[]).map((x:any)=>x.segment).join(" · ")||"Research-derived buyers",organic:(research.contentAngles||[]).slice(0,3).join(" · ")||research.whyPeopleCare||"Discovery-led education",paid:(research.paidAngles||[]).slice(0,3).join(" · ")||"Problem-aware and upgrade-led testing",ynot:"Use the research plan to reveal the product ecosystem, not just one SKU.",firstTest:"Research the strongest replacement, upgrade and accessory pathways first.",angles:[...(research.replacementCycles||[]).slice(0,2).map((x:any)=>`Replace: ${x.thing}`),...(research.upgradePaths||[]).slice(0,2).map((x:any)=>`Upgrade: ${x.from} → ${x.to}`),...(research.overlookedProblems||[]).slice(0,2).map((x:any)=>x.productOpportunity)].filter(Boolean)}}}

 async function researchTyped(){const term=researchQuery.trim();if(!term)return;setRunning(true);setProgress(8);setNotice(`Researching ${term} across the market first, then validating against Shopify…`);setFilterText("");try{const brain=await call("/api/admin/ads/brain",{action:"evaluate",name:term,query:term,parentId:null});setProgress(58);const root=mapBrain(brain,term);const rec=await call("/api/admin/ads/recursive",{seedName:term,seedQuery:term,depth:1,maxBranches:12}).catch(()=>({branches:[],summary:{live:0}}));const branches=(rec.branches||[]).filter((b:any)=>b.metrics?.productCount>0).map(mapRecursive);setResults([root,...branches]);setProgress(100);setNotice(`${term}: ${(root.metrics?.productCount||0)} catalogue products validated and ${branches.length} adjacent micro-niches found from AI-led market research.`)}catch(e){setNotice(e instanceof Error?e.message:"Research failed")}finally{setRunning(false)}}

 async function runScan(mode:"quick"|"deep"|"frontier"="deep"){setRunning(true);setProgress(0);setNotice("");setResults([]);setFilterText("");try{if(mode==="frontier"){const batches=12,all:ScanResult[]=[];for(let batch=0;batch<batches;batch++){const data=await call("/api/admin/ads/frontier",{mode:"frontier",batch,size:8,country:"France"});all.push(...(data.results||[]).map((x:any)=>({...x,frontier:true,metrics:{...x.metrics,gem:x.metrics?.frontier||0}})));setResults([...all]);setProgress(Math.round(((batch+1)/batches)*100));if(!data.hasMore)break}setNotice(`Frontier scan complete: ${all.length} specialist pathways tested.`);return}const batches=mode==="deep"?8:3,all:ScanResult[]=[];for(let batch=0;batch<batches;batch++){const data=await api({action:"scan",batch,size:6,country:"France"});all.push(...(data.results||[]));setResults([...all]);setProgress(Math.round(((batch+1)/batches)*100));if(!data.hasMore)break}setNotice(`${mode==="deep"?"Deep":"Quick"} scan complete: ${all.length} micro-markets tested.`)}catch(e){setNotice(e instanceof Error?e.message:"Scan failed")}finally{setRunning(false)}}

 async function digDeeper(item:ScanResult,depth?:number){const d=depth||Math.min(4,(item.depth||0)+1);setDigging(item.probe.name);setNotice("");try{const data=await call("/api/admin/ads/recursive",{seedName:item.probe.name,seedQuery:item.probe.query,depth:d,maxBranches:10});const mapped=(data.branches||[]).filter((b:any)=>b.metrics?.productCount>0).map(mapRecursive);setResults(current=>{const keys=new Set(current.map(x=>x.probe.query));return [...current,...mapped.filter((x:ScanResult)=>!keys.has(x.probe.query))]});setNotice(`${item.probe.name}: ${data.summary?.live||mapped.length} live child markets found.`)}catch(e){setNotice(e instanceof Error?e.message:"Recursive scan failed")}finally{setDigging(null)}}

 async function runRecursiveUniverse(){setRunning(true);setProgress(0);setNotice("");setFilterText("");try{let base=results.filter(x=>x.metrics?.productCount>0&&!x.recursive).sort((a,b)=>(b.metrics?.gem||0)-(a.metrics?.gem||0));if(base.length<6){const frontier:ScanResult[]=[];for(let batch=0;batch<6;batch++){const data=await call("/api/admin/ads/frontier",{mode:"frontier",batch,size:8,country:"France"});frontier.push(...(data.results||[]).map((x:any)=>({...x,frontier:true,metrics:{...x.metrics,gem:x.metrics?.frontier||0}})));setProgress(Math.round(((batch+1)/12)*100));if(!data.hasMore)break}base=frontier.filter(x=>x.metrics?.productCount>0).sort((a,b)=>(b.metrics?.gem||0)-(a.metrics?.gem||0));setResults(frontier)}const roots=base.slice(0,6),children:ScanResult[]=[];for(let i=0;i<roots.length;i++){const data=await call("/api/admin/ads/recursive",{seedName:roots[i].probe.name,seedQuery:roots[i].probe.query,depth:1,maxBranches:8});children.push(...(data.branches||[]).filter((b:any)=>b.metrics?.productCount>0).map(mapRecursive));setProgress(50+Math.round(((i+1)/roots.length)*28))}const level2=[...children].sort((a,b)=>(b.metrics?.gem||0)-(a.metrics?.gem||0)).slice(0,3),grand:ScanResult[]=[];for(let i=0;i<level2.length;i++){const data=await call("/api/admin/ads/recursive",{seedName:level2[i].probe.name,seedQuery:level2[i].probe.query,depth:2,maxBranches:8});grand.push(...(data.branches||[]).filter((b:any)=>b.metrics?.productCount>0).map(mapRecursive));setProgress(78+Math.round(((i+1)/Math.max(1,level2.length))*22))}setResults(current=>{const map=new Map(current.map(x=>[x.probe.query,x]));for(const x of [...children,...grand])map.set(x.probe.query,x);return [...map.values()]});setNotice(`Recursive universe complete: ${children.length} child markets and ${grand.length} second-generation micro-niches.`)}catch(e){setNotice(e instanceof Error?e.message:"Recursive universe failed")}finally{setRunning(false);setProgress(100)}}

 async function sendToFactory(item:ScanResult){setNotice("");try{const r=await authedFetch("/api/admin/ads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create_niche",name:item.probe.name,category:item.probe.vertical,query:item.probe.query,status:"active",attributes:[item.metrics.ticket,item.probe.intent,item.recursive?`recursive-depth-${item.depth||1}`:item.frontier?"frontier-intelligence":"intelligence-lab"]})});if(!r.ok)throw new Error("Could not save niche");setNotice(`${item.probe.name} is now saved as an active YNOT niche.`)}catch(e){setNotice(e instanceof Error?e.message:"Unable to save niche")}}

 const filtered=useMemo(()=>{let rows=results.filter(x=>x.metrics?.productCount>0);if(filterText.trim()){const q=filterText.toLowerCase();rows=rows.filter(x=>`${x.probe.name} ${x.probe.vertical} ${x.probe.audience} ${x.probe.query} ${x.parent||""}`.toLowerCase().includes(q))}const value=(x:ScanResult)=>lens==="broad"?x.metrics.broad:lens==="conversion"?x.metrics.conversion:lens==="ynot"?x.metrics.ynot:x.metrics.gem;if(lens==="high")rows=rows.filter(x=>x.metrics.ticket==="high");if(lens==="low")rows=rows.filter(x=>x.metrics.ticket==="low");return [...rows].sort((a,b)=>value(b)-value(a))},[results,lens,filterText]);
 const liveResults=results.filter(x=>x.metrics?.productCount>0),skuCount=liveResults.reduce((n,x)=>n+(x.metrics?.productCount||0),0),scoreKey=lens==="broad"?"broad":lens==="conversion"?"conversion":lens==="ynot"?"ynot":"gem",topScore=filtered[0]?.metrics?.[scoreKey]||0,recursiveCount=results.filter(x=>x.recursive).length;

 if(access!=="ready")return <main className={styles.shell}><div className={styles.lock}><div className={styles.kicker}>YNOT / DEEP INTELLIGENCE</div><h1>{access==="signin"?"Sign in required":"Owner access required"}</h1><a href="/admin/ads">Back to Ad Factory</a></div></main>;
 return <main className={styles.shell}><div className={styles.wrap}>
  <header className={styles.hero}><div><div className={styles.kicker}>YNOT / DEEP INTELLIGENCE</div><h1>Research a market first. Then search the catalogue.</h1><p>The main input now starts real research instead of silently filtering an empty result set. Enter any niche, product world or problem and YNOT will evaluate it, validate products, then branch into adjacent replacement, upgrade and accessory opportunities.</p></div><div className={styles.heroActions}><button disabled={running} onClick={()=>void runRecursiveUniverse()}>{running?`Researching ${progress}%`:"Run recursive universe"}</button><button className={styles.secondary} disabled={running} onClick={()=>void runScan("frontier")}>Frontier scan</button><button className={styles.secondary} disabled={running} onClick={()=>void runScan("deep")}>Deep scan</button></div></header>
  <section className={styles.researchBar}><input autoComplete="off" value={researchQuery} onChange={e=>setResearchQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void researchTyped()}} placeholder="Research any niche: tennis tech, mirror TVs, sauna, drones, resin furniture, disability accessories…"/><button disabled={running||!researchQuery.trim()} onClick={()=>void researchTyped()}>{running?"Researching…":"Research this niche"}</button></section>
  {running&&<div className={styles.progress}><i style={{width:`${progress}%`}}/><span>{progress}% · market research → catalogue validation → micro-niche branching</span></div>}
  {notice&&<div className={styles.notice}>{notice}</div>}
  <section className={styles.metrics}><div><b>{results.length}</b><span>markets probed</span></div><div><b>{recursiveCount}</b><span>recursive discoveries</span></div><div><b>{skuCount}</b><span>live product samples</span></div><div><b>{topScore}</b><span>top active score</span></div></section>
  <section className={styles.control}><div className={styles.lenses}>{([['gems','Hidden gems'],['broad','Broad reach'],['conversion','Conversion'],['ynot','YNOT lens'],['high','High ticket'],['low','Low ticket']] as [Lens,string][]).map(([k,label])=><button key={k} className={lens===k?styles.active:""} onClick={()=>setLens(k)}>{label}</button>)}</div><input value={filterText} onChange={e=>setFilterText(e.target.value)} placeholder="Filter current results…"/></section>
  {!results.length&&!running&&<section className={styles.empty}><b>Type a market above and press Research this niche.</b><p>The input now launches research directly. You can also run Frontier or Recursive Universe for broad autonomous discovery.</p></section>}
  <section className={styles.grid}>{filtered.map((item,index)=>{const m=item.metrics,open=expanded===item.probe.name;return <article className={styles.card} key={`${item.probe.name}-${index}`}><div className={styles.rank}>#{index+1}</div><div className={styles.cardHead}><div><small>{item.probe.vertical} · {m.ticket} ticket {item.recursive?`· RECURSIVE L${item.depth||1}`:item.frontier?"· FRONTIER":""}</small><h2>{item.probe.name}</h2></div><div className={styles.gem}>{m.gem}</div></div><p className={styles.audience}>{item.strategy.audience||item.probe.audience}</p><div className={styles.scoreGrid}><div><b>{m.broad}</b><span>Reach</span></div><div><b>{m.conversion}</b><span>Convert</span></div><div><b>{m.ynot}</b><span>YNOT</span></div><div><b>{m.evidence}</b><span>Evidence</span></div></div><div className={styles.evidence}><span>{m.productCount} live products</span><span>{m.brandCount} brands</span><span>median {m.priceSpread?.median||0}</span><span>visual {m.visual}/100</span></div><div className={styles.thumbs}>{(item.products||[]).slice(0,5).map((p:any)=><div key={p.id}>{p.image?<img src={p.image} alt=""/>:null}</div>)}</div><button className={styles.expand} onClick={()=>setExpanded(open?null:item.probe.name)}>{open?"Hide field brief":"Open field brief"}</button>{open&&<div className={styles.brief}><div><b>Audience</b><p>{item.strategy.audience||item.probe.audience}</p></div><div><b>Organic entry</b><p>{item.strategy.organic}</p></div><div><b>Paid structure</b><p>{item.strategy.paid}</p></div><div><b>YNOT play</b><p>{item.strategy.ynot}</p></div><div><b>First test</b><p>{item.strategy.firstTest}</p></div>{item.parent&&<div><b>Parent market</b><p>{item.parent}</p></div>}{item.strategy.angles?.length?<div><b>Why this branch exists</b><p>{item.strategy.angles.join(" · ")}</p></div>:null}<div><b>Search footprint</b><p>{item.probe.query}</p></div></div>}<div className={styles.actions}><button disabled={digging===item.probe.name} onClick={()=>void digDeeper(item)}>{digging===item.probe.name?"Digging…":"Dig deeper"}</button><button onClick={()=>void sendToFactory(item)}>Promote to active niche</button><a href={`/admin/ads?intelligence=${encodeURIComponent(item.probe.name)}`}>Open Ad Factory</a></div></article>})}</section>
 </div></main>
}
