"use client";
import {useEffect,useMemo,useState} from "react";

type Review={rating?:number|null;title?:string;body?:string;author?:string;image?:string|null};
type Props={price?:number|null;currency?:string;cartSubtotal?:number;rating?:number|null;reviewCount?:number;reviews?:Review[]};
const THRESHOLD=250;
const symbol=(c="EUR")=>({EUR:"€",USD:"$",GBP:"£"} as Record<string,string>)[c]||`${c} `;
export default function ProductTrustPanel({currency="EUR",cartSubtotal=0,rating,reviewCount=0,reviews=[]}:Props){
 const[payOpen,setPayOpen]=useState(false),[reviewsOpen,setReviewsOpen]=useState(false),[faceStart,setFaceStart]=useState(0);
 const subtotal=Math.max(0,Number(cartSubtotal||0)),qualified=subtotal>=THRESHOLD,remaining=Math.max(0,THRESHOLD-subtotal),instalment=subtotal/3,hasReviews=Boolean(rating||reviewCount||reviews.length);
 const faces=useMemo(()=>Array.from(new Set(reviews.map(r=>r.image).filter((x):x is string=>Boolean(x)))),[reviews]);
 useEffect(()=>{if(faces.length<=3)return;const t=window.setInterval(()=>setFaceStart(v=>(v+1)%faces.length),2600);return()=>window.clearInterval(t)},[faces.length]);
 const visibleFaces=faces.length?Array.from({length:Math.min(3,faces.length)},(_,i)=>faces[(faceStart+i)%faces.length]):[];
 return <div className="trustPanel">
  {visibleFaces.length>0&&<div className="socialProof"><div className="faceStack">{visibleFaces.map((src,i)=><img key={`${src}-${faceStart}-${i}`} src={src} alt="" className="face" loading="lazy"/>)}</div><span><b>1,200+ purchases</b> in the last month across the YNOT catalogue</span></div>}
  <div className={`klarna ${qualified?"qualified":""}`}><button className="klarnaRow" onClick={()=>setPayOpen(v=>!v)} aria-expanded={payOpen}><span className="klarnaMark">Klarna.</span><span className="klarnaCopy"><b>{qualified?"Flexible payment available":"Flexible payment on carts €250+"}</b><small>{qualified?"Your cart has reached €250":"Add items until your cart reaches €250"}</small></span><span className="chev">{payOpen?"−":"+"}</span></button>{payOpen&&<div className="klarnaInfo"><b>Pay flexibly with Klarna</b>{qualified?<p>Your cart subtotal is <strong>{symbol(currency)}{subtotal.toFixed(2)}</strong>. If an eligible 3-part option is offered at checkout, an illustrative split would be about <strong>{symbol(currency)}{instalment.toFixed(2)} × 3</strong>.</p>:<p>Build a cart of at least <strong>€250</strong> to unlock YNOT's flexible-payment prompt. You are <strong>€{remaining.toFixed(2)}</strong> away.</p>}<small>Klarna is selected at checkout when available. Payment options, eligibility, approval and limits depend on Klarna, the customer and market. Reaching €250 does not guarantee financing approval.</small></div>}</div>
  {hasReviews&&<div className="reviews"><button className="reviewSummary" onClick={()=>setReviewsOpen(v=>!v)}><span className="stars">★ {rating?Number(rating).toFixed(1):"Reviews"}</span>{reviewCount>0&&<span>{reviewCount.toLocaleString()} verified-source reviews</span>}<span>{reviewsOpen?"−":"+"}</span></button>{reviewsOpen&&reviews.length>0&&<div className="reviewStrip">{reviews.map((r,i)=><article key={i}>{r.image&&<img src={r.image} alt="" loading="lazy"/>}<div className="rStars">{"★".repeat(Math.max(1,Math.min(5,Math.round(Number(r.rating||5)))))} </div>{r.title&&<b>{r.title}</b>}{r.body&&<p>{r.body}</p>}{r.author&&<small>{r.author}</small>}</article>)}</div>}</div>}
  <style jsx>{`.trustPanel{max-width:760px;margin:12px 0}.socialProof{display:flex;align-items:center;gap:10px;padding:9px 0 12px;color:#fff;font-size:10px;line-height:1.25}.socialProof>span{opacity:.72}.socialProof b{opacity:1;color:#fff;font-weight:700}.faceStack{display:flex;align-items:center;min-width:62px;padding-left:1px}.face{width:27px;height:27px;border-radius:50%;object-fit:cover;border:2px solid #111;margin-left:-9px;background:#222;animation:faceIn .38s ease both}.face:first-child{margin-left:0}@keyframes faceIn{from{opacity:0;transform:translateX(6px) scale(.9)}to{opacity:1;transform:none}}.klarna,.reviews{border-top:1px solid #ffffff18}.klarnaRow,.reviewSummary{width:100%;border:0;background:transparent;color:#fff;display:flex;align-items:center;gap:11px;padding:12px 0;text-align:left}.klarnaMark{background:#ffb3c7;color:#000;font-weight:900;letter-spacing:-.04em;border-radius:4px;padding:5px 7px;font-size:13px}.klarnaCopy{display:flex;flex-direction:column;gap:1px;flex:1}.klarnaCopy b{font-size:11px}.klarnaCopy small{font-size:9px;opacity:.55}.qualified .klarnaCopy b:after{content:" ✓"}.chev{font-size:17px;opacity:.7}.klarnaInfo{padding:3px 0 15px;max-width:620px}.klarnaInfo>b{font-size:13px}.klarnaInfo p{font-size:11px!important;opacity:.8!important;margin:7px 0}.klarnaInfo small{display:block;font-size:8px;line-height:1.45;opacity:.45}.reviewSummary{font-size:10px}.reviewSummary .stars{font-weight:700}.reviewSummary span:nth-child(2){opacity:.6;flex:1}.reviewStrip{display:grid;grid-auto-flow:column;grid-auto-columns:min(80vw,310px);gap:7px;overflow-x:auto;padding:0 0 12px;scrollbar-width:none}.reviewStrip article{background:#ffffff08;border:1px solid #ffffff12;border-radius:9px;padding:11px}.reviewStrip img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:6px;margin-bottom:8px}.rStars{font-size:9px;letter-spacing:.05em}.reviewStrip b{display:block;font-size:10px;margin-top:5px}.reviewStrip p{font-size:9px!important;line-height:1.4!important;opacity:.65!important}.reviewStrip small{font-size:8px;opacity:.4}`}</style>
 </div>
}
