import {NextRequest,NextResponse} from "next/server";
export const runtime="nodejs";
type Input={id?:string;title?:string;brand?:string;description?:string;url?:string;source?:string;tags?:string[];variants?:unknown[];model?:string;sku?:string;gtin?:string;upc?:string};
type Enrichment={packageContents:string[];dimensions:string[];materials:string[];compatibility:string[];specifications:string[];warranty:string[];model:string[];confidence:"confirmed"|"partial"|"unconfirmed";evidence:string[]};
const cache=new Map<string,{at:number,value:Enrichment}>();const TTL=1000*60*60*24*7;
function clean(v:unknown){return String(v||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim()}
function uniq(xs:string[]){return [...new Set(xs.map(clean).filter(x=>x.length>1))].slice(0,12)}
function lines(text:string,re:RegExp){const out:string[]=[];for(const sentence of text.split(/(?:\n|\r|[.!?]\s+)/)){if(re.test(sentence)){const after=sentence.replace(/^.*?(?:in the box|box contents|package contents|what(?:'s| is) included|includes?|comes with|supplied with)\s*[:\-]?\s*/i,"");for(const bit of after.split(/[,;•|]/))if(clean(bit).length>1&&clean(bit).length<140)out.push(clean(bit))}}return uniq(out)}
function extract(text:string):Enrichment{const packageContents=lines(text,/\b(in the box|box contents|package contents|what(?:'s| is) included|includes?|comes with|supplied with)\b/i),dimensions=lines(text,/\b(dimensions?|measurements?|size:)\b/i),materials=lines(text,/\b(materials?|made (?:from|of)|construction)\b/i),compatibility=lines(text,/\b(compatible|compatibility|works with|supports?)\b/i),specifications=lines(text,/\b(specifications?|specs?|technical|capacity|battery|power|weight|resolution|connectivity)\b/i),warranty=lines(text,/\b(warranty|guarantee)\b/i),model=lines(text,/\b(model|mpn|sku|gtin|upc|ean)\b/i);const count=packageContents.length+dimensions.length+materials.length+compatibility.length+specifications.length+warranty.length+model.length;return{packageContents,dimensions,materials,compatibility,specifications,warranty,model,confidence:packageContents.length?"confirmed":count?"partial":"unconfirmed",evidence:[]}}
async function pageText(url?:string){if(!url||!/^https?:\/\//i.test(url))return"";try{const u=new URL(url);if(!/^https?:$/.test(u.protocol))return"";const r=await fetch(url,{headers:{"User-Agent":"YNOT Product Research/1.0",Accept:"text/html,application/xhtml+xml"},signal:AbortSignal.timeout(5500),cache:"no-store",redirect:"follow"});if(!r.ok)return"";const type=r.headers.get("content-type")||"";if(!type.includes("text/html")&&!type.includes("text/plain"))return"";return clean((await r.text()).slice(0,900000)).slice(0,120000)}catch{return""}}
function merge(a:Enrichment,b:Enrichment,evidence:string[]):Enrichment{const packageContents=uniq([...a.packageContents,...b.packageContents]),dimensions=uniq([...a.dimensions,...b.dimensions]),materials=uniq([...a.materials,...b.materials]),compatibility=uniq([...a.compatibility,...b.compatibility]),specifications=uniq([...a.specifications,...b.specifications]),warranty=uniq([...a.warranty,...b.warranty]),model=uniq([...a.model,...b.model]);const count=dimensions.length+materials.length+compatibility.length+specifications.length+warranty.length+model.length;return{packageContents,dimensions,materials,compatibility,specifications,warranty,model,confidence:packageContents.length?"confirmed":count?"partial":"unconfirmed",evidence}}
export async function POST(req:NextRequest){let p:Input={};try{p=await req.json()}catch{return NextResponse.json({error:"Invalid product"},{status:400})}const identity=[p.brand,p.title,p.model,p.sku,p.gtin,p.upc].map(clean).filter(Boolean).join("|").toLowerCase();if(!identity)return NextResponse.json({error:"Product identity required"},{status:400});const hit=cache.get(identity);if(hit&&Date.now()-hit.at<TTL)return NextResponse.json({...hit.value,cached:true});const supplied=clean([p.title,p.brand,p.description,(p.tags||[]).join(" "),JSON.stringify(p.variants||[]),p.model,p.sku,p.gtin,p.upc].join(". "));const direct=extract(supplied),web=await pageText(p.url),fromPage=extract(web),evidence=[...(supplied?["catalogue"]:[]),...(web?["product-page"]:[])];const value=merge(direct,fromPage,evidence);cache.set(identity,{at:Date.now(),value});return NextResponse.json({...value,cached:false,identity},{headers:{"Cache-Control":"private, max-age=3600"}})}
