const base=()=>String(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL||"").replace(/\/$/,"");
const key=()=>String(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||"");
const headers=()=>{const k=key();return{apikey:k,...(k.startsWith("sb_")?{}:{Authorization:`Bearer ${k}`}),"Content-Type":"application/json"}};
async function rest(path:string,init:RequestInit={}){if(!base()||!key())throw new Error("CREATOR_STORE_NOT_CONFIGURED");const r=await fetch(`${base()}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},cache:"no-store"});if(!r.ok)throw new Error(`Creator store ${r.status}: ${(await r.text()).slice(0,240)}`);const t=await r.text();return t?JSON.parse(t):null}
export type Creator={id:string;instagram_username:string|null;display_name:string|null;email:string|null;status:string;referral_code:string;commission_rate:number;commission_basis:string;discovery_score:number|null;metadata:Record<string,unknown>};
export async function creatorByCode(code:string){const clean=code.toLowerCase().replace(/[^a-z0-9_-]/g,"").slice(0,40);if(!clean)return null;const rows=await rest(`ynot_creators?referral_code=eq.${encodeURIComponent(clean)}&status=eq.active&select=*&limit=1`) as Creator[];return rows?.[0]||null}
export async function creatorById(id:string){const clean=id.replace(/[^a-f0-9-]/gi,"").slice(0,36);if(!clean)return null;const rows=await rest(`ynot_creators?id=eq.${encodeURIComponent(clean)}&status=eq.active&select=*&limit=1`) as Creator[];return rows?.[0]||null}
export async function recordClick(c:Creator,landingPath:string,userAgent:string){await rest("ynot_creator_clicks",{method:"POST",body:JSON.stringify([{creator_id:c.id,referral_code:c.referral_code,landing_path:landingPath.slice(0,500),user_agent:userAgent.slice(0,500)}])})}
export async function upsertProspects(profiles:Array<{username:string;fullName?:string;publicEmail?:string|null;relevanceScore:number;followers?:number|null;biography?:string|null;website?:string|null}>){if(!profiles.length)return;const rows=profiles.map(p=>({instagram_username:p.username,display_name:p.fullName||null,email:p.publicEmail||null,referral_code:(p.username.replace(/[^a-z0-9]/gi,"").toLowerCase().slice(0,24)||crypto.randomUUID().slice(0,8)),status:"prospect",source:"instagram_discovery",discovery_score:p.relevanceScore,metadata:{followers:p.followers??null,biography:p.biography??null,website:p.website??null}}));await rest("ynot_creators?on_conflict=instagram_username",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates"},body:JSON.stringify(rows)})}
export async function createCommission(input:{creatorId:string;sessionId:string;paymentIntentId?:string;subtotalCents:number;basisCents:number;rate:number;currency:string}){const cents=Math.max(0,Math.round(input.basisCents*input.rate));await rest("ynot_creator_commissions?on_conflict=stripe_session_id",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates"},body:JSON.stringify([{creator_id:input.creatorId,stripe_session_id:input.sessionId,stripe_payment_intent_id:input.paymentIntentId||null,order_subtotal_cents:input.subtotalCents,commission_basis_cents:input.basisCents,commission_rate:input.rate,commission_cents:cents,currency:input.currency,status:"earned",earned_at:new Date().toISOString()}])})}
export async function reverseCommission(sessionId:string){await rest(`ynot_creator_commissions?stripe_session_id=eq.${encodeURIComponent(sessionId)}&status=neq.paid`,{method:"PATCH",body:JSON.stringify({status:"reversed",reversed_at:new Date().toISOString()})})}
