const API="https://api.apify.com/v2";
const PRODUCT_AFFILIATE_ACTOR=process.env.APIFY_TIKTOK_PRODUCT_AFFILIATE_ACTOR||"george.the.developer~tiktok-shop-affiliate-sales-scraper";
function token(){const v=process.env.APIFY_API_TOKEN;if(!v)throw new Error("APIFY_API_TOKEN is not configured");return v}
function str(...v:unknown[]){for(const x of v)if(typeof x==="string"&&x.trim())return x.trim();return""}
function num(...v:unknown[]){for(const x of v){const n=Number(x);if(Number.isFinite(n))return n}return null}
export type PartnerLead={source:"tiktok_shop";username:string;displayName?:string;profileUrl?:string;avatar?:string;followers?:number|null;engagementRate?:number|null;email?:string|null;category?:string|null;shopUrl?:string|null;metadata:Record<string,unknown>};
export async function discoverTikTokShop(query:string,target=100){
 const maxProducts=Math.max(1,Math.min(10,Math.ceil(target/30)));
 const maxAffiliatesPerProduct=Math.max(1,Math.min(100,Math.ceil(target/maxProducts)));
 const r=await fetch(`${API}/acts/${PRODUCT_AFFILIATE_ACTOR}/run-sync-get-dataset-items?clean=true`,{method:"POST",headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json"},body:JSON.stringify({searchQuery:query,maxProducts,maxAffiliatesPerProduct}),signal:AbortSignal.timeout(180000),cache:"no-store"});
 if(!r.ok)throw new Error(`TikTok Shop product affiliate actor failed: ${r.status} ${(await r.text()).slice(0,240)}`);
 const rows=await r.json() as Record<string,any>[];const byCreator=new Map<string,PartnerLead>();
 for(const row of Array.isArray(rows)?rows:[]){const product=row.product||row;const affiliates=Array.isArray(row.affiliates)?row.affiliates:Array.isArray(row.creators)?row.creators:[];for(const a of affiliates){const username=str(a.username,a.userName,a.handle,a.author_name).replace(/^@/,"").toLowerCase();if(!username)continue;const existing=byCreator.get(username);const proof={name:str(product.name,product.title),price:product.price??null,salesCount:num(product.salesCount,product.sold_count),rating:num(product.rating),url:str(product.url,product.product_url),creatorSales:num(a.salesCount,a.sales_count)};if(existing){const products=Array.isArray(existing.metadata.affiliateProducts)?existing.metadata.affiliateProducts as any[]:[];products.push(proof);existing.metadata.affiliateProducts=products;existing.metadata.affiliateProductCount=products.length;existing.metadata.creatorSales=Math.max(Number(existing.metadata.creatorSales||0),Number(proof.creatorSales||0));continue}byCreator.set(username,{source:"tiktok_shop",username,displayName:str(a.displayName,a.nickname,a.name)||undefined,profileUrl:str(a.profileUrl,a.url)||`https://www.tiktok.com/@${username}`,avatar:str(a.avatar,a.avatarUrl,a.profilePicture)||undefined,followers:num(a.followers,a.followerCount,a.followersCount),engagementRate:num(a.engagementRate,a.engagement_rate),email:str(a.email,a.businessEmail,a.publicEmail)||null,category:query,shopUrl:str(product.url,product.product_url)||null,metadata:{affiliateProductCount:1,affiliateProducts:[proof],creatorSales:proof.creatorSales,verificationStatus:str(row.dataSource,row.verificationStatus)||null}});if(byCreator.size>=target)break}if(byCreator.size>=target)break}
 return [...byCreator.values()].sort((a,b)=>Number(b.metadata.creatorSales||0)-Number(a.metadata.creatorSales||0)||Number(b.followers||0)-Number(a.followers||0)).slice(0,target);
}
