import {NextRequest,NextResponse} from "next/server";

export const runtime="nodejs";
export const maxDuration=60;

const GEMINI_KEY=process.env.GEMINI_API_KEY||process.env.GOOGLE_GENERATIVE_AI_API_KEY||process.env.GOOGLE_API_KEY;
const configuredGemini=process.env.GEMINI_VISION_MODEL?.trim();
const GEMINI_MODELS=[...new Set([configuredGemini,"gemini-3.8-flash","gemini-3.6-flash","gemini-3.5-flash"].filter(Boolean) as string[])];

const schema={type:"object",additionalProperties:false,properties:{sceneTitle:{type:"string"},roomType:{type:"string"},sceneKind:{type:"string"},objects:{type:"array",items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},label:{type:"string"},category:{type:"string"},searchQuery:{type:"string"},alternateQueries:{type:"array",items:{type:"string"}},confidence:{type:"number"},box_2d:{type:"array",items:{type:"integer"}},mask:{type:"array",items:{type:"array",items:{type:"integer"}}}},required:["id","label","category","searchQuery","alternateQueries","confidence","box_2d","mask"]}},suggestionSpots:{type:"array",items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},label:{type:"string"},reason:{type:"string"},suggestedCategories:{type:"array",items:{type:"string"}},searchQuery:{type:"string"},point_2d:{type:"array",items:{type:"integer"}}},required:["id","label","reason","suggestedCategories","searchQuery","point_2d"]}}},required:["sceneTitle","roomType","sceneKind","objects","suggestionSpots"]};
const prompt=`Analyze this image as a visual-shopping scene for YNOT. Detect the prominent VISIBLE purchasable objects in the actual image. The image can contain furniture, clothing, electronics, beauty products, sports equipment, tools, decor or other purchasable items. Do not assume it is an interior.
For every detected object return ONE tight bounding box around that exact visible object. box_2d MUST be [ymin,xmin,ymax,xmax] normalized from 0 to 1000, following Gemini object-detection coordinates exactly. Do not create a grid, evenly spaced boxes, duplicate objects, background regions, empty-space detections, or arbitrary points. If two chairs are visible, each chair may be its own object; a large rug should have one box centered on that rug, a plant one box on that plant, a light one box on that light. Return only objects you can visually ground with confidence.
label must be concise and visually grounded. category is a broad shopping category. searchQuery is a useful catalogue query without inventing brands. alternateQueries contains up to 6 broader searches. mask is a polygon of [x,y] normalized 0-1000 or [] if uncertain.
Also return at most 5 suggestionSpots only for genuinely useful empty locations. point_2d is [x,y] normalized 0-1000. Do not put suggestion spots on top of detected products. Return at most 16 detected objects.`;
function clamp(n:any){const x=Number(n);return Number.isFinite(x)?Math.max(0,Math.min(1000,Math.round(x))):0}
function normalize(x:any){if(!x||!Array.isArray(x.objects))return x;x.objects=x.objects.map((o:any)=>({...o,box_2d:Array.isArray(o?.box_2d)&&o.box_2d.length===4?o.box_2d.map(clamp):[0,0,0,0]})).filter((o:any)=>{const [y1,x1,y2,x2]=o.box_2d;return y2>y1&&x2>x1&&(y2-y1)>8&&(x2-x1)>8});return x}
function valid(x:any){return !!(x&&Array.isArray(x.objects)&&x.objects.length>0&&x.objects.some((o:any)=>o&&typeof o.label==="string"&&typeof o.searchQuery==="string"&&Array.isArray(o.box_2d)&&o.box_2d.length===4)&&Array.isArray(x.suggestionSpots))}

async function scanGemini(bytes:string,mime:string){if(!GEMINI_KEY)return {ok:false,error:"Gemini is not configured"};let last="";const geminiSchema=JSON.parse(JSON.stringify(schema).replace(/"object"/g,'"OBJECT"').replace(/"string"/g,'"STRING"').replace(/"array"/g,'"ARRAY"').replace(/"integer"/g,'"INTEGER"').replace(/"number"/g,'"NUMBER"'));function strip(o:any){if(o&&typeof o==="object"){delete o.additionalProperties;for(const v of Object.values(o))strip(v)}}strip(geminiSchema);for(const model of GEMINI_MODELS){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":GEMINI_KEY},body:JSON.stringify({contents:[{parts:[{text:prompt},{inlineData:{mimeType:mime,data:bytes}}]}],generationConfig:{responseMimeType:"application/json",responseSchema:geminiSchema,temperature:0,thinkingConfig:{thinkingLevel:"minimal"}}})});const raw=await r.json().catch(()=>({}));if(!r.ok){last=raw?.error?.message||`${model} failed`;continue}const text=raw?.candidates?.[0]?.content?.parts?.find((p:any)=>typeof p?.text==="string")?.text;if(!text){last=`${model} returned no analysis`;continue}const parsed=normalize(JSON.parse(text));if(valid(parsed))return {ok:true,data:parsed,model};last=`${model} returned no usable detected objects`}catch(e){last=e instanceof Error?e.message:"Gemini scanner failed"}}return {ok:false,error:last||"Gemini scanner failed"}}

export async function POST(req:NextRequest){if(!GEMINI_KEY)return NextResponse.json({error:"Image scanning is temporarily unavailable",code:"VISION_NOT_CONFIGURED"},{status:503});const form=await req.formData();const image=form.get("image");if(!(image instanceof File)||!image.type.startsWith("image/"))return NextResponse.json({error:"Upload an image"},{status:400});if(image.size>15*1024*1024)return NextResponse.json({error:"Image is too large"},{status:413});const bytes=Buffer.from(await image.arrayBuffer()).toString("base64");const gemini=await scanGemini(bytes,image.type);if(gemini.ok)return NextResponse.json(gemini.data,{headers:{"Cache-Control":"no-store","X-YNOT-Scanner":"gemini","X-YNOT-Scanner-Model":String((gemini as any).model||"")}});console.error("YNOT_ROOM_SCAN_FAILED",{gemini:gemini.error});return NextResponse.json({error:"Could not detect any shoppable objects in this photo. Try another photo or try again.",code:"VISION_ANALYSIS_FAILED"},{status:502})}
