import { createMcpHandler } from "mcp-handler";
import { z } from "zod";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SITE = "https://ynotworld.app";
const PRODUCT_UI = "ui://ynot/product-carousel/v1.html";
type Product = {id?:string;title?:string;brand?:string;price?:number|null;currency?:string;image?:string;images?:string[];url?:string;description?:string;tags?:string[];source?:string;[key:string]:unknown};

function result(value:unknown){return{structuredContent:value as Record<string,unknown>,content:[{type:"text" as const,text:JSON.stringify(value,null,2)}]}}
function country(value:string){const code=String(value||"FR").toUpperCase();return /^[A-Z]{2}$/.test(code)?code:"FR"}
function clean(p:Product){return{id:String(p.id||""),title:String(p.title||"Product"),brand:String(p.brand||""),description:String(p.description||"").slice(0,1200),price:typeof p.price==="number"?p.price:null,currency:String(p.currency||"EUR"),image:String(p.image||p.images?.[0]||""),images:Array.isArray(p.images)?p.images.slice(0,8):[],tags:Array.isArray(p.tags)?p.tags.slice(0,12):[],source:String(p.source||"ynot"),merchant_url:String(p.url||""),ynot_url:p.id?`${SITE}/p/${encodeURIComponent(String(p.id))}`:SITE}}
async function search(query:string,deliveryCountry:string,limit:number){const params=new URLSearchParams({q:query.slice(0,300),country:country(deliveryCountry),source:"all",category_load:limit>20?"1":"0"});const response=await fetch(`${SITE}/api/catalog?${params}`,{cache:"no-store",headers:{Accept:"application/json"}});if(!response.ok)throw new Error(`CATALOG_${response.status}`);const data=await response.json();return{query:data?.query||query,sources:data?.sources||[],products:(Array.isArray(data?.products)?data.products:[]).slice(0,limit).map(clean),error:data?.error||null}}

const carouselHtml=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;font-family:ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;background:transparent;color:inherit}.shell{padding:12px 2px}.top{display:flex;justify-content:space-between;align-items:end;gap:12px;margin:0 10px 10px}.brand{font-size:12px;font-weight:800;letter-spacing:.16em}.query{font-size:13px;opacity:.62;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.rail{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(180px,220px);gap:10px;overflow-x:auto;padding:2px 10px 12px;scroll-snap-type:x mandatory}.card{scroll-snap-align:start;border:1px solid color-mix(in srgb,currentColor 14%,transparent);border-radius:20px;overflow:hidden;background:color-mix(in srgb,Canvas 92%,transparent);box-shadow:0 8px 30px rgba(0,0,0,.06)}.image{aspect-ratio:1/1;background:color-mix(in srgb,currentColor 5%,transparent);display:flex;align-items:center;justify-content:center}.image img{width:100%;height:100%;object-fit:contain}.body{padding:11px}.merchant{font-size:11px;opacity:.55;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.title{font-size:14px;font-weight:650;line-height:1.25;height:35px;overflow:hidden;margin-top:3px}.price{font-size:15px;font-weight:800;margin:9px 0 10px}.actions{display:flex;gap:7px}.actions a{flex:1;text-align:center;text-decoration:none;color:inherit;border:1px solid color-mix(in srgb,currentColor 18%,transparent);border-radius:999px;padding:8px 9px;font-size:12px;font-weight:700}.actions a.primary{background:currentColor}.actions a.primary span{color:Canvas}.empty{margin:10px;padding:20px;border:1px dashed color-mix(in srgb,currentColor 20%,transparent);border-radius:18px;text-align:center;opacity:.7}@media(max-width:480px){.rail{grid-auto-columns:minmax(158px,72vw)}}
</style></head><body><div id="app" class="shell"><div class="empty">Searching YNOT…</div></div><script>
const app=document.getElementById('app');
const esc=(s)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=(p,c)=>p==null?'Price on YNOT':new Intl.NumberFormat(undefined,{style:'currency',currency:c||'EUR',maximumFractionDigits:2}).format(p);
function render(payload){const data=payload?.structuredContent||payload||{};const products=Array.isArray(data.products)?data.products:[];if(!products.length){app.innerHTML='<div class="empty">No matching YNOT products yet.</div>';return}app.innerHTML='<div class="top"><div class="brand">YNOT</div><div class="query">'+esc(data.query||'Products')+'</div></div><div class="rail">'+products.map(p=>'<article class="card"><div class="image">'+(p.image?'<img loading="lazy" src="'+esc(p.image)+'" alt="'+esc(p.title)+'">':'')+'</div><div class="body"><div class="merchant">'+esc(p.brand||p.source||'YNOT')+'</div><div class="title">'+esc(p.title)+'</div><div class="price">'+esc(money(p.price,p.currency))+'</div><div class="actions"><a class="primary" target="_blank" rel="noreferrer" href="'+esc(p.ynot_url)+'"><span>View</span></a><a target="_blank" rel="noreferrer" href="'+esc(p.merchant_url||p.ynot_url)+'">Merchant</a></div></div></article>').join('')+'</div>'}
window.addEventListener('message',e=>{const m=e.data;if(m?.method==='ui/notifications/tool-result')render(m.params)});
if(window.openai?.toolOutput)render(window.openai.toolOutput);
</script></body></html>`;

const handler=createMcpHandler((server)=>{
 server.resource("ynot-product-carousel",PRODUCT_UI,async()=>({contents:[{uri:PRODUCT_UI,mimeType:"text/html;profile=mcp-app",text:carouselHtml,_meta:{ui:{prefersBorder:true,domain:SITE,csp:{connectDomains:[SITE],resourceDomains:[SITE,"https://cdn.shopify.com","https://images.unsplash.com"]}},"openai/widgetDescription":"A horizontally scrollable YNOT product carousel showing live product images, prices, brands, and continuation links.","openai/widgetPrefersBorder":true}}]}));
 const uiMeta={ui:{resourceUri:PRODUCT_UI},"openai/outputTemplate":PRODUCT_UI};
 server.tool("search_products","Search YNOT's live multi-source shopping catalogue using natural language. Use this for product discovery, budgets, styles, categories and shopping requests.",{query:z.string().min(2).max(300),country:z.string().length(2).default("FR"),limit:z.number().int().min(1).max(40).default(18)},async({query,country,limit})=>result(await search(query,country,limit)),uiMeta as any);
 server.tool("get_product","Find one specific YNOT product from a bounded live catalogue search.",{product_id:z.string().min(1),query:z.string().min(2).max(300),country:z.string().length(2).default("FR")},async({product_id,query,country})=>{const data=await search(query,country,40);const product=data.products.find((p:any)=>p.id===product_id);return result(product?{query,products:[product]}:{query,products:[],error:"PRODUCT_NOT_FOUND",product_id})},uiMeta as any);
 server.tool("find_similar_products","Find YNOT alternatives to a product, optionally applying a preference such as cheaper, another colour, or a price ceiling.",{product:z.string().min(2).max(300),preference:z.string().max(200).default("similar alternatives"),country:z.string().length(2).default("FR"),limit:z.number().int().min(1).max(30).default(12)},async({product,preference,country,limit})=>result(await search(`${product}, ${preference}`,country,limit)),uiMeta as any);
 server.tool("get_product_images","Return product images and links for a YNOT catalogue item.",{product_id:z.string().min(1),query:z.string().min(2).max(300),country:z.string().length(2).default("FR")},async({product_id,query,country})=>{const data=await search(query,country,40);const p:any=data.products.find((x:any)=>x.id===product_id);return result(p?{id:p.id,title:p.title,images:[...new Set([p.image,...(p.images||[])].filter(Boolean))],ynot_url:p.ynot_url,merchant_url:p.merchant_url}:{error:"PRODUCT_NOT_FOUND",product_id})});
 server.tool("open_in_ynot","Return a user-openable YNOT URL for a product or shopping search.",{product_id:z.string().max(240).optional(),query:z.string().max(300).optional()},async({product_id,query})=>result({url:product_id?`${SITE}/p/${encodeURIComponent(product_id)}`:query?`${SITE}/?q=${encodeURIComponent(query)}`:SITE}));
},{instructions:"YNOT is a visual multi-source shopping service. Search live products with search_products, inspect selected products with get_product, use find_similar_products for alternatives, and open_in_ynot when the shopper wants to continue on YNOT. Never invent product details, prices, availability, shipping, or merchants. Prefer YNOT URLs for continuing the shopping journey."});

export {handler as GET,handler as POST};
