import {NextRequest,NextResponse} from "next/server";
import {adminErrorStatus,requireYnotAdmin} from "@/lib/ynot/admin-server";

export const runtime="nodejs";
export const maxDuration=60;

type Product={id?:string;title?:string;brand?:string;price?:number|null;currency?:string;image?:string;images?:string[];url?:string;tags?:string[]};
type Seed={sector:string;audience:string;terms:string[];contexts:string[];intent:string};

const SEEDS:Seed[]=[
 {sector:"Tennis tech",audience:"club players, coaches, competitive amateurs",terms:["tennis sensor","ball machine accessory","racket vibration dampener","stringing tool","smart grip","tennis camera mount"],contexts:["training","match analysis","recovery","travel"],intent:"performance + hobby"},
 {sector:"Camera ecosystem",audience:"creators, photographers, filmmakers, small studios",terms:["camera cage","follow focus","field monitor","camera slider","lens filter system","camera power solution","wireless video transmitter"],contexts:["mobile studio","travel","low light","solo creator"],intent:"workflow + quality"},
 {sector:"Gaming setup",audience:"PC/console players, streamers, desk-setup buyers",terms:["sim racing accessory","controller dock","gaming keypad","monitor light","cable management","acoustic panel","stream deck alternative"],contexts:["small desk","competitive","streaming","ergonomic"],intent:"identity + performance"},
 {sector:"Drone accessories",audience:"drone pilots, real-estate creators, outdoor filmmakers",terms:["drone landing pad","ND filter drone","drone case","battery charging hub","propeller guard","drone payload accessory"],contexts:["travel","survey","cinematic","beginner"],intent:"specialist utility"},
 {sector:"Car specialist tools",audience:"DIY car owners, detailers, enthusiasts, mechanics",terms:["OBD diagnostic tool","paint thickness gauge","battery tester","borescope car","trim removal tool","torque adapter","jump starter"],contexts:["preventive maintenance","used car inspection","roadside","garage"],intent:"problem prevention"},
 {sector:"Accessibility",audience:"disabled users, caregivers, older adults, families",terms:["adaptive utensil","wheelchair accessory","reacher grabber premium","bed assist rail","one hand kitchen tool","visual alert device","adaptive clothing accessory"],contexts:["independent living","travel","home safety","daily routine"],intent:"independence + utility"},
 {sector:"Smart home safety",audience:"homeowners, renters, families, landlords",terms:["indoor security camera","door sensor","water leak sensor","smart smoke detector","window alarm","video doorbell accessory","safe box sensor"],contexts:["apartment","elder care","pet monitoring","vacation"],intent:"safety + reassurance"},
 {sector:"Tracking & GPS",audience:"families, travelers, vehicle owners, pet owners",terms:["GPS tracker","anti theft tracker","bike tracker","pet GPS","asset tracker","luggage tracker","vehicle locator"],contexts:["travel","fleet","elder care","outdoor"],intent:"loss prevention"},
 {sector:"Massage & recovery",audience:"athletes, office workers, wellness buyers",terms:["massage gun accessory","compression recovery","heated massage pad","foot massager","neck traction","myofascial tool","cupping set"],contexts:["desk worker","post workout","travel","sleep routine"],intent:"relief + recovery"},
 {sector:"Sauna & cold therapy",audience:"wellness enthusiasts, home gym owners, athletes",terms:["portable sauna","sauna blanket","sauna accessory","cold plunge accessory","ice bath thermometer","sauna light","sauna headrest"],contexts:["small home","recovery","premium wellness","outdoor"],intent:"ritual + high ticket"},
 {sector:"Furniture niches",audience:"interior buyers, homeowners, design enthusiasts",terms:["resin dining table","epoxy river table","travertine side table","modular sofa","acoustic furniture","hidden TV cabinet","mirror TV","transforming furniture"],contexts:["luxury","small space","statement piece","custom"],intent:"aspiration + design"},
 {sector:"Rare materials",audience:"makers, designers, premium-home buyers",terms:["carbon fiber sheet","acoustic felt panel","cork wall panel","microcement kit","resin casting material","wood veneer sheet","brass mesh"],contexts:["DIY","interior finish","furniture making","custom project"],intent:"hard to find material"},
 {sector:"Workshop precision",audience:"DIY builders, makers, tradespeople",terms:["laser level accessory","digital angle finder","inspection camera","precision caliper","stud finder advanced","thermal camera","endoscope tool"],contexts:["home repair","woodworking","electrical","inspection"],intent:"professional utility"},
 {sector:"Home energy",audience:"homeowners, renters, energy-conscious buyers",terms:["smart energy monitor","thermal leak detector","solar charger home","power station accessory","smart plug energy meter","air quality monitor"],contexts:["cost saving","backup power","rental","off grid"],intent:"efficiency + preparedness"},
 {sector:"Air quality",audience:"families, allergy sufferers, pet owners, urban renters",terms:["CO2 monitor","air quality sensor","VOC meter","mold detector","humidity logger","radon detector","air purifier monitor"],contexts:["bedroom","nursery","office","basement"],intent:"invisible problem detection"},
 {sector:"Water quality",audience:"families, travelers, homeowners, outdoor users",terms:["water quality tester","TDS meter","shower filter","portable water purifier","leak shutoff","water hardness tester"],contexts:["home","travel","aquarium","camping"],intent:"health-adjacent utility"},
 {sector:"Home cinema",audience:"movie fans, gamers, premium-home buyers",terms:["ultra short throw projector accessory","acoustic panel cinema","projector screen motorized","ambient light rejection screen","media console hidden","home theater calibration"],contexts:["small room","luxury","gaming","living room"],intent:"experience upgrade"},
 {sector:"Mirror & hidden displays",audience:"luxury-home, bathroom, hospitality, design buyers",terms:["mirror TV","bathroom mirror display","hidden television cabinet","art frame TV accessory","smart mirror display"],contexts:["bathroom","bedroom","hotel style","minimal interior"],intent:"novelty + premium"},
 {sector:"Pet tech",audience:"pet owners, frequent travelers, busy professionals",terms:["automatic pet feeder camera","pet GPS","smart litter box accessory","pet water fountain sensor","pet camera treat dispenser","microchip feeder"],contexts:["remote monitoring","multi pet","travel","health routine"],intent:"care + tech"},
 {sector:"Aquarium tech",audience:"aquarium hobbyists, premium hobby buyers",terms:["aquarium dosing pump","smart aquarium light","aquarium controller","water parameter monitor","automatic fish feeder premium","aquascaping tool"],contexts:["reef","planted tank","automation","travel"],intent:"specialist hobby"},
 {sector:"Cycling tech",audience:"road cyclists, commuters, gravel riders",terms:["bike radar","cycling camera","smart bike light","power meter accessory","bike GPS mount","tubeless repair tool"],contexts:["commute","training","safety","bikepacking"],intent:"performance + safety"},
 {sector:"Racquet micro niches",audience:"tennis, padel, pickleball, badminton players",terms:["racket sensor","grip trainer","ball pressure saver","string tension meter","racket balance tool","court camera tripod"],contexts:["club player","coach","travel","competition"],intent:"specialist performance"},
 {sector:"Golf tech",audience:"golfers, coaches, gift buyers",terms:["golf launch monitor accessory","rangefinder mount","swing trainer sensor","putting alignment tool","golf GPS","club cleaning machine"],contexts:["practice","home simulator","course","gift"],intent:"performance + premium hobby"},
 {sector:"Home mobility",audience:"older adults, caregivers, rehab households",terms:["transfer aid","bed mobility aid","shower safety accessory","stair assist accessory","walker organizer premium","portable ramp"],contexts:["home independence","caregiver","travel","bathroom"],intent:"access + safety"},
 {sector:"Sleep tech",audience:"sleep optimization, travelers, light/noise-sensitive buyers",terms:["sleep earbuds","bed cooling system","sunrise alarm premium","white noise machine","sleep tracking pad","blackout window solution"],contexts:["hot sleeper","travel","couples","apartment"],intent:"sleep improvement"},
 {sector:"Desk health",audience:"remote workers, gamers, developers, creators",terms:["under desk footrest premium","monitor arm heavy duty","desk treadmill accessory","vertical mouse","wrist support premium","desk posture sensor"],contexts:["long hours","small desk","multi monitor","standing desk"],intent:"comfort + productivity"},
 {sector:"Specialty lighting",audience:"interior buyers, creators, workshop users",terms:["architectural linear light","picture light rechargeable","motion stair light","cabinet task light","portable photography tube light","high CRI work light"],contexts:["rental","gallery","workbench","cinematic"],intent:"visual transformation"},
 {sector:"Emergency preparedness",audience:"families, drivers, travelers, homeowners",terms:["emergency radio","portable power station","water storage system","vehicle emergency tool","fire blanket","gas leak detector","emergency lighting"],contexts:["apartment","car","storm","travel"],intent:"preparedness + safety"},
 {sector:"Outdoor surveillance",audience:"homeowners, farms, cabins, outdoor-property owners",terms:["trail camera cellular","solar security camera","gate camera","wildlife camera","long range driveway sensor","outdoor camera battery"],contexts:["rural","vacation property","wildlife","construction"],intent:"remote visibility"},
 {sector:"Specialty storage",audience:"collectors, hobbyists, luxury-item owners",terms:["watch winder safe","camera dry cabinet","vinyl storage premium","shoe display cabinet","tool storage modular","wine storage accessory"],contexts:["collection","humidity control","display","small space"],intent:"protect + organize"},
 {sector:"Maker fabrication",audience:"3D printing, electronics, model making, prototyping",terms:["3D printer enclosure","filament dryer","soldering microscope","PCB tool","laser engraver accessory","resin printer wash cure accessory"],contexts:["home workshop","small business","precision","safety"],intent:"maker workflow"},
 {sector:"Specialty kitchen tech",audience:"home cooks, food enthusiasts, precision buyers",terms:["vacuum sealer chamber","sous vide accessory","precision scale coffee","smart meat thermometer","dehydrator accessory","fermentation monitor"],contexts:["meal prep","coffee","BBQ","fermentation"],intent:"precision + hobby"},
 {sector:"Luxury bathroom tech",audience:"premium-home buyers, renovators, hospitality",terms:["smart toilet accessory","heated towel rail","mirror TV bathroom","digital shower controller","bathroom dehumidifier","waterproof speaker built in"],contexts:["spa bathroom","renovation","hotel style","aging in place"],intent:"premium transformation"},
 {sector:"Home diagnostics",audience:"homeowners, landlords, property inspectors",terms:["thermal imaging camera","moisture meter","wall scanner","endoscope inspection camera","mold test meter","electrical tester smart"],contexts:["buying house","maintenance","rental","DIY"],intent:"find hidden problems"},
 {sector:"Specific setups",audience:"enthusiasts building purpose-specific spaces",terms:["flight simulator setup","sim racing cockpit","music production desk","streaming setup accessory","home golf simulator","watch repair bench"],contexts:["compact","premium","starter","modular"],intent:"system building"}
];

const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
const median=(v:number[])=>{if(!v.length)return 0;const s=[...v].sort((a,b)=>a-b);const i=Math.floor(s.length/2);return s.length%2?s[i]:(s[i-1]+s[i])/2};
function quality(p:Product){const imgs=[p.image,...(p.images||[])].filter(Boolean);let s=Math.min(35,imgs.length*7);if(String(p.image||"").startsWith("https://"))s+=15;if(String(p.title||"").length>14)s+=12;if((p.tags||[]).length>2)s+=12;if(Number(p.price)>0)s+=12;if(p.brand)s+=8;if(p.url&&p.url!=="#")s+=6;return clamp(s)}
function hash(s:string){let h=0;for(const c of s)h=((h<<5)-h+c.charCodeAt(0))|0;return Math.abs(h)}
function expand(seed:Seed,offset:number){const term=seed.terms[offset%seed.terms.length];const context=seed.contexts[Math.floor(offset/seed.terms.length)%seed.contexts.length];const novelty=78+(hash(term+context)%22);return {name:`${seed.sector} · ${term}`,query:`${term} ${context} premium accessories tools`,vertical:seed.sector,audience:seed.audience,intent:seed.intent,context,novelty,ynot:76+(hash(seed.sector+term)%24),organic:70+(hash(term)%29),conversion:74+(hash(context+term)%25)}}

export async function POST(req:NextRequest){
 try{
  await requireYnotAdmin(req);
  const body=await req.json().catch(()=>({}));
  const mode=String(body?.mode||"frontier");const batch=Math.max(0,Math.min(19,Number(body?.batch||0)));const size=Math.max(4,Math.min(10,Number(body?.size||8)));const origin=req.nextUrl.origin;
  const universe=SEEDS.flatMap(seed=>Array.from({length:Math.min(8,seed.terms.length*2)},(_,i)=>expand(seed,i)));
  const start=batch*size;const probes=universe.slice(start,start+size);
  const results=await Promise.all(probes.map(async probe=>{
   try{
    const url=new URL("/api/catalog",origin);url.searchParams.set("q",probe.query);url.searchParams.set("source","shopify");url.searchParams.set("limit","36");
    const res=await fetch(url,{cache:"no-store"});const data=await res.json().catch(()=>({}));const products:(Product[])=(Array.isArray(data?.products)?data.products:[]).filter((p:Product)=>p?.id&&p?.title&&p?.image&&p?.url&&p.url!=="#");
    const deduped=Array.from(new Map(products.map(p=>[`${String(p.title).toLowerCase()}|${String(p.brand||"").toLowerCase()}`,p])).values());const prices=deduped.map(p=>Number(p.price)).filter(n=>Number.isFinite(n)&&n>0);const brands=new Set(deduped.map(p=>p.brand).filter(Boolean));const qs=deduped.map(quality);
    const inventory=clamp(Math.min(1,deduped.length/28)*100);const visual=qs.length?Math.round(qs.reduce((a,b)=>a+b,0)/qs.length):0;const diversity=clamp(Math.min(1,brands.size/10)*100);const price=median(prices);const ticket=price>=250?"high":price>=80?"mid":"low";const evidence=clamp(inventory*.36+visual*.30+diversity*.14+(prices.length?20:0));const frontier=clamp(evidence*.34+probe.novelty*.26+probe.ynot*.16+probe.organic*.1+probe.conversion*.14);
    return {probe,products:deduped.slice(0,10),metrics:{inventory,visual,diversity,evidence,frontier,broad:clamp(probe.organic*.44+visual*.22+inventory*.18+probe.ynot*.16),conversion:clamp(probe.conversion*.4+evidence*.28+inventory*.12+probe.ynot*.2),ynot:clamp(probe.ynot*.48+probe.novelty*.2+visual*.18+inventory*.14),ticket,priceSpread:prices.length?{min:Math.min(...prices),median:Math.round(price*100)/100,max:Math.max(...prices)}:{min:0,median:0,max:0},productCount:deduped.length,brandCount:brands.size},strategy:{audience:probe.audience,organic:`Teach or reveal why ${probe.query.split(" ").slice(0,4).join(" ")} is useful before selling it. Use demonstrations, comparisons and unexpected-use cases.`,paid:ticket==="high"?"Use education + demo + proof, then retarget engaged viewers with the strongest product cluster.":"Lead with the overlooked problem, demonstrate the product quickly, then open the matching YNOT product world.",ynot:`Build a YNOT world around ${probe.vertical}; show multiple specialist products so the ad sells discovery as well as the item.`,firstTest:frontier>=86?"8–12 creatives across 4 angles":"4–8 creatives across 3 angles",angles:["I didn't know this existed","specialist setup","problem you don't notice until it happens","premium upgrade vs generic alternative"]}};
   }catch(error){return {probe,products:[],metrics:{inventory:0,visual:0,diversity:0,evidence:0,frontier:0,broad:probe.organic,conversion:probe.conversion,ynot:probe.ynot,ticket:"unknown",priceSpread:{min:0,median:0,max:0},productCount:0,brandCount:0},strategy:{audience:probe.audience},error:error instanceof Error?error.message:"FRONTIER_SCAN_FAILED"}}
  }));
  return NextResponse.json({ok:true,mode,batch,size,totalProbes:universe.length,hasMore:start+size<universe.length,results});
 }catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"FRONTIER_ERROR"},{status:adminErrorStatus(error)})}
}
