import {NextRequest,NextResponse} from "next/server";
export const runtime="nodejs";
const cache=new Map<string,{description:string;images:string[];enrichedBy:string;at:number}>();
const TTL=1000*60*60*24*7;
function text(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>/gi,"\n\n").replace(/<\/li>/gi,"\n").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/[ \t]+/g," ").replace(/\n\s+/g,"\n").replace(/\n{3,}/g,"\n\n").trim()}
function pageImages(html:string,base:URL){const found:string[]=[];const push=(raw:string)=>{try{const u=new URL(raw,base);if((u.protocol==="https:"||u.protocol==="http:")&&!/logo|icon|avatar|payment|badge/i.test(u.pathname))found.push(u.toString())}catch{}};for(const m of html.matchAll(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)["']/gi))push(m[1]);for(const m of html.matchAll(/<img[^>]+(?:src|data-src)=["']([^"']+)["']/gi))push(m[1]);return [...new Set(found)].slice(0,20)}
function candidates(html:string){const out:string[]=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const raw=JSON.parse(m[1]);const walk=(v:any)=>{if(!v)return;if(Array.isArray(v))return v.forEach(walk);if(typeof v==="object"){if((v["@type"]==="Product"||v["@type"]?.includes?.("Product"))&&v.description)out.push(text(String(v.description)));Object.values(v).forEach(walk)}};walk(raw)}catch{}}for(const re of [/<meta[^>]+(?:property|name)=["'](?:og:description|description)["'][^>]+content=["']([^"']+)["'][^>]*>/gi,/<(?:div|section)[^>]+(?:id|class)=["'][^"']*(?:product[^"']*description|description[^"']*product|product-description|product__description|rte)[^"']*["'][^>]*>([\s\S]*?)<\/(?:div|section)>/gi])for(const m of html.matchAll(re))out.push(text(m[1]));return out.filter(v=>v.length>40).sort((a,b)=>b.length-a.length)}
function safe(url:string){try{const u=new URL(url);if(u.protocol!=="https:"&&u.protocol!=="http:")return null;const h=u.hostname.toLowerCase();if(h==="localhost"||h.endsWith(".local")||/^127\.|^10\.|^192\.168\.|^169\.254\.|^172\.(1[6-9]|2\d|3[01])\./.test(h))return null;return u}catch{return null}}
async function groqDescription(input:{title:string;brand:string;catalogue:string;merchant:string}){const apiKey=process.env.GROQ_API_KEY;if(!apiKey)return"";const evidence=[input.catalogue,input.merchant].map(v=>text(v).slice(0,9000)).filter(Boolean).join("\n\n");if(!evidence)return"";try{const response=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.GROQ_PRODUCT_MODEL||"llama-3.3-70b-versatile",temperature:0.15,max_completion_tokens:500,messages:[{role:"system",content:"You write accurate ecommerce product descriptions for YNOT. Use only supplied evidence. Never mention, infer, change, compare, or invent any price. Do not invent specifications, materials, compatibility, claims, reviews, availability, shipping, or warranty. Return only a polished About this product description in 2-4 concise paragraphs; no heading, bullets, markdown, or preamble."},{role:"user",content:`Product: ${input.title}\nBrand: ${input.brand}\n\nEvidence:\n${evidence}`}]}),cache:"no-store",signal:AbortSignal.timeout(7000)});if(!response.ok)return"";const data=await response.json();return text(String(data?.choices?.[0]?.message?.content||"")).slice(0,3500)}catch{return""}}
export async function POST(req:NextRequest){try{const body=await req.json(),u=safe(String(body?.url||""));if(!u)return NextResponse.json({error:"INVALID_MERCHANT_URL"},{status:400});const key=[u.origin+u.pathname,String(body?.title||"").trim()].join("|");const hit=cache.get(key);if(hit&&Date.now()-hit.at<TTL)return NextResponse.json({description:hit.description,images:hit.images,enrichedBy:hit.enrichedBy,cached:true});const response=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0 (compatible; YNOTProductEnricher/2.0)","Accept":"text/html,application/xhtml+xml"},redirect:"follow",cache:"no-store",signal:AbortSignal.timeout(6500)});if(!response.ok)return NextResponse.json({error:"MERCHANT_FETCH_FAILED",status:response.status,host:u.hostname},{status:502});const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return NextResponse.json({error:"MERCHANT_NOT_HTML"},{status:422});const html=(await response.text()).slice(0,2500000),merchant=candidates(html)[0]||"",images=pageImages(html,u),catalogue=text(String(body?.description||"")),title=text(String(body?.title||"")),brand=text(String(body?.brand||""));const groq=await groqDescription({title,brand,catalogue,merchant}),description=groq||merchant||catalogue,enrichedBy=groq?"groq":merchant?"merchant":"catalogue";if(!description&&!images.length)return NextResponse.json({description:"",images:[],found:false,enrichedBy:"none"});cache.set(key,{description,images,enrichedBy,at:Date.now()});return NextResponse.json({description,images,found:true,enrichedBy,debug:{host:u.hostname,descriptionLength:description.length,imageCount:images.length,groq:Boolean(groq)}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"ENRICH_FAILED"},{status:500})}}
