"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Bell,ChevronDown,Compass,Minus,Search,UserRound} from "lucide-react";
import LuminaWorld from "./LuminaWorld";import EtsyCatalogBridge from "./EtsyCatalogBridge";import YnotDrawer from "./YnotDrawer";import UnifiedBag from "./UnifiedBag";import YnotBuyPolish from "./YnotBuyPolish";import YnotCloseStability from "./YnotCloseStability";import YnotIntentBridge from "./YnotIntentBridge";import SavedNotebook from "./SavedNotebook";import SavesBookToast from "./SavesBookToast";import DiscoveryUniverse from "./DiscoveryUniverse";import ProductCardEnhancer from "./ProductCardEnhancer";import ProductDetailHydrator from "./ProductDetailHydrator";import ProductReferenceEnhancer from "./ProductReferenceEnhancer";import ProductCardSync from "./ProductCardSync";import WorldVisualPolish from "./WorldVisualPolish";import WorldCompass from "./WorldCompass";import WorldSaveBridge from "./WorldSaveBridge";import CircleDrawer from "./CircleDrawer";import ProfilePanel from "./ProfilePanel";import CheckoutStatus from "./CheckoutStatus";import DesktopLatticeController from "./DesktopLatticeController";import DesktopProductStepper from "./DesktopProductStepper";import MobileProductSwipeController from "./MobileProductSwipeController";import YnotTryPricing from "./YnotTryPricing";import AuthGate from "./AuthGate";import EntryAmbientBubbles from "./EntryAmbientBubbles";import TaxonomyRail from "./TaxonomyRail";import {authedFetch,readSession} from "../../lib/ynot/supabase-browser";
type Mode="shop"|"discover";type Source="Shopify"|"eBay"|"Etsy";type Account={name?:string;avatar?:string}|null;
function setReactInput(input:HTMLInputElement,value:string){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;setter?.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}))}
function sourceDisplay(source:Source){return source==="Shopify"?"YNOT":source==="eBay"?"Commerce":"Marketplace"}
const SOURCE_RENAMES:[[RegExp,string],[RegExp,string],[RegExp,string],[RegExp,string],[RegExp,string]]=[[/\bShopify\b/g,"YNOT"],[/\beBay Marketplace\b/g,"Commerce"],[/\beBay\b/g,"Commerce"],[/\bEtsy Marketplace\b/g,"Marketplace"],[/\bEtsy\b/g,"Marketplace"]];
function publicSourceText(value:string){return SOURCE_RENAMES.reduce((text,[pattern,replacement])=>text.replace(pattern,replacement),String(value||""))}
function brandNode(root:Node){
 const element=root instanceof Element?root:null;
 if(element?.closest("script,style,noscript,code,pre"))return;
 const textNodes:Text[]=[];
 if(root.nodeType===Node.TEXT_NODE)textNodes.push(root as Text);
 if(root instanceof Element){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(walker.nextNode())textNodes.push(walker.currentNode as Text)}
 for(const node of textNodes){if(node.parentElement?.closest("script,style,noscript,code,pre"))continue;const current=node.nodeValue||"",next=publicSourceText(current);if(next!==current)node.nodeValue=next}
 if(root instanceof Element){const targets=[root,...root.querySelectorAll<HTMLElement>("[title],[aria-label],[placeholder]")];for(const target of targets){for(const attr of ["title","aria-label","placeholder"]){const current=target.getAttribute(attr);if(!current)continue;const next=publicSourceText(current);if(next!==current)target.setAttribute(attr,next)}}}
}
export default function AppShell(){const[mode,setMode]=useState<Mode>("shop"),[source,setSource]=useState<Source>("Shopify"),[sourceOpen,setSourceOpen]=useState(false),[bottomQuery,setBottomQuery]=useState(""),[chromeHidden,setChromeHidden]=useState(false),[selectedTags,setSelectedTags]=useState<string[]>([]),[account,setAccount]=useState<Account>(null);const effectiveQuery=useMemo(()=>[bottomQuery.trim(),...selectedTags].filter(Boolean).join(" ").replace(/\s+/g," ").trim(),[bottomQuery,selectedTags]);
useEffect(()=>{const selector=[".lv4-detail",".lv4-detail-backdrop",".ynot-selected",".ynot-story",".ynot-cart",".ynot-unified-bag",".ynot-drawer.open",".discover-profile-backdrop",".ynot-notebook-shell",".ynot-auth-shell"].join(","),sync=()=>setChromeHidden(Boolean(document.querySelector(selector)));sync();const observer=new MutationObserver(sync);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});return()=>observer.disconnect()},[]);
useEffect(()=>{brandNode(document.body);const observer=new MutationObserver(mutations=>{for(const mutation of mutations)for(const node of mutation.addedNodes)brandNode(node)});observer.observe(document.body,{subtree:true,childList:true});return()=>observer.disconnect()},[]);
useEffect(()=>{let live=true;const load=async()=>{if(!readSession()){if(live)setAccount(null);return}try{const r=await authedFetch("/api/account"),d=await r.json().catch(()=>({}));if(live&&r.ok)setAccount(d.account||null)}catch{}};void load();const ready=(e:Event)=>setAccount((e as CustomEvent<Account>).detail),auth=()=>{if(!readSession())setAccount(null);else void load()};window.addEventListener("ynot:account-ready",ready as EventListener);window.addEventListener("ynot:auth-changed",auth);return()=>{live=false;window.removeEventListener("ynot:account-ready",ready as EventListener);window.removeEventListener("ynot:auth-changed",auth)}},[]);
useEffect(()=>{const onTags=(event:Event)=>{const detail=(event as CustomEvent<{tags?:string[]}>).detail,tags=Array.isArray(detail?.tags)?detail.tags:[];setSelectedTags(tags);if(mode==="shop")setBottomQuery(tags.join(" "))};window.addEventListener("shop:tags-changed",onTags as EventListener);return()=>window.removeEventListener("shop:tags-changed",onTags as EventListener)},[mode]);
function openYnot(){const clickPeek=()=>{const button=document.querySelector<HTMLButtonElement>(".ynot-peek");if(!button)return false;button.click();return true};window.dispatchEvent(new Event("ynot:open-deals"));if(clickPeek())return;requestAnimationFrame(()=>{if(clickPeek())return;window.setTimeout(()=>{if(clickPeek())return;window.setTimeout(clickPeek,120)},40)})}
function goHome(){document.querySelector<HTMLButtonElement>(".lv4-logo")?.click()}function toggleFar(){document.querySelector<HTMLButtonElement>(".ynot-far-button")?.click()}function toggleCompass(){document.querySelector<HTMLButtonElement>(".ynot-compass-button")?.click()}function openAccount(){window.dispatchEvent(new CustomEvent("ynot:open-auth",{detail:{mode:"signin"}}))}function openSaved(){window.dispatchEvent(new Event("ynot:open-saves"))}function openNotifications(){window.dispatchEvent(new Event("ynot:open-circle"))}
function chooseNativeSource(){const worldButtons=[...document.querySelectorAll<HTMLButtonElement>(".lv4-market-toggle button")],world=worldButtons.find(button=>!button.classList.contains("ebay"));if(world&&!world.classList.contains("active"))world.click();document.querySelector<HTMLButtonElement>(".lv4-source-trigger")?.click();requestAnimationFrame(()=>{const choices=[...document.querySelectorAll<HTMLButtonElement>(".lv4-source-menu button,.lv4-source-popover button,.lv4-source-options button")];choices.find(button=>["shopify","ynot"].some(term=>button.textContent?.toLowerCase().includes(term)))?.click()})}
function reloadNativeWorldForEtsy(){const worldButtons=[...document.querySelectorAll<HTMLButtonElement>(".lv4-market-toggle button")],world=worldButtons.find(button=>!button.classList.contains("ebay"));if(world&&!world.classList.contains("active"))world.click();requestAnimationFrame(()=>{const input=document.querySelector<HTMLInputElement>(".lv4-search input"),term=effectiveQuery||input?.value.trim()||"handmade gifts jewelry clothing home decor";if(input)setReactInput(input,term);requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>(".lv4-search button")?.click())})}
function switchSource(next:Source){setSource(next);setSourceOpen(false);window.dispatchEvent(new CustomEvent("ynot:catalog-source",{detail:{source:next.toLowerCase()}}));if(next==="eBay"){document.querySelector<HTMLButtonElement>(".lv4-market-toggle button.ebay")?.click();return}if(next==="Etsy"){reloadNativeWorldForEtsy();return}chooseNativeSource()}
function submitBottomSearch(e:FormEvent){e.preventDefault();if(mode==="discover"){const clean=bottomQuery.trim();if(clean.length>=2)window.dispatchEvent(new CustomEvent("discover:search",{detail:clean}));return}const clean=effectiveQuery,input=document.querySelector<HTMLInputElement>(".lv4-search input");if(clean.length<2||!input)return;setReactInput(input,clean);window.dispatchEvent(new CustomEvent("shop:tag-search",{detail:{query:clean,tags:selectedTags}}));requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>(".lv4-search button")?.click())}
const signed=Boolean(account||readSession()),etsy=source==="Etsy";return <div className={`ynot-app-shell source-${source.toLowerCase()} ${chromeHidden?"chrome-hidden":""}`}><EntryAmbientBubbles/><EtsyCatalogBridge/><header className="ynot-reference-header"><div className="ynot-reference-left"><button className="ynot-reference-brand" onClick={goHome}><b>YNOT</b></button></div><div className="ynot-reference-center"><div className="ynot-reference-topline"><nav className="ynot-top-mode"><button className={mode==="shop"?"active":""} onClick={()=>setMode("shop")}>SHOP</button><button className={mode==="discover"?"active":""} onClick={()=>setMode("discover")}>DISCOVER</button></nav>{mode==="shop"&&<div className="ynot-reference-nav-tools"><button onClick={toggleFar}><Minus/></button><button onClick={toggleCompass}><Compass/></button></div>}</div>{mode==="shop"&&<div className="ynot-world-controls"><div className="ynot-world-row"><button className="active">WORLD</button><button type="button" onClick={openYnot} onPointerUp={openYnot}>YNOT</button></div><div className="ynot-view-source"><button className="ynot-source-trigger-clean" onClick={()=>setSourceOpen(v=>!v)}>{sourceDisplay(source)}<ChevronDown/></button>{sourceOpen&&<div className="ynot-source-list">{(["Shopify","eBay","Etsy"] as Source[]).map(option=><button key={option} className={source===option?"active":""} onClick={()=>switchSource(option)}>{sourceDisplay(option)}</button>)}</div>}</div></div>}</div><div className="ynot-reference-right"><button className="ynot-reference-notify" onClick={openNotifications}><Bell/><i/></button>{signed?<button className="ynot-reference-signin has-profile" onClick={openSaved}><span>Worlds</span></button>:<button className="ynot-reference-signin" onClick={openAccount}><span>Sign in</span></button>}<button className={`ynot-reference-avatar ${account?.avatar?"has-image":""}`} onClick={openAccount} aria-label={signed?"Open profile":"Open sign in"}>{account?.avatar?<img src={account.avatar} alt="Your profile"/>:<UserRound/>}</button></div></header>{mode==="discover"?<DiscoveryUniverse/>:<><LuminaWorld/><WorldCompass/></>}{mode==="shop"&&<TaxonomyRail/>}<form className={`ynot-bottom-search ${mode}`} onSubmit={submitBottomSearch}><Search/><input value={bottomQuery} onChange={e=>setBottomQuery(e.target.value)} placeholder={mode==="discover"?"Search Instagram niches, brands or styles":etsy?"Search Marketplace — products, styles or shops":"Search products, brands or categories"}/><button>Search</button></form><YnotDrawer/><UnifiedBag/><YnotBuyPolish/><YnotCloseStability/><YnotIntentBridge/><SavedNotebook/><SavesBookToast/><ProductCardEnhancer/><ProductDetailHydrator/><ProductReferenceEnhancer/><ProductCardSync/><WorldSaveBridge/><CircleDrawer/><ProfilePanel/><AuthGate/><YnotTryPricing/><WorldVisualPolish/><DesktopLatticeController/><DesktopProductStepper/><MobileProductSwipeController/><CheckoutStatus/></div>}
