"use client";

import {useEffect} from "react";
import ProductImageScanBridge from "./ProductImageScanBridge";

type Product={id?:string;title?:string;brand?:string;image?:string;images?:string[];source?:string;verifiedMerchant?:boolean;[key:string]:unknown};
type CatalogPayload={products?:Product[];pagination?:Record<string,unknown>;sources?:string[];[key:string]:unknown};
const INITIAL_PRODUCT_TARGET=180,EXPANSION_DIRECTIONS=["more like this","alternative styles","fresh finds"],PREFETCH_IMAGES=48,CACHE_MS=90_000;
const responseCache=new Map<string,{at:number,payload:CatalogPayload}>(),verifiedTitles=new Set<string>(),verifiedImages=new Set<string>(),verifiedIds=new Set<string>();
function titleKey(v:unknown){return String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim()}
function imageKey(v:unknown){try{const u=new URL(String(v||""),location.origin);return `${u.hostname}${u.pathname}`.toLowerCase()}catch{return String(v||"").split("?")[0].toLowerCase()}}
function normalizedCopy(p:Product){return `${titleKey(p?.title)}|${titleKey(p?.brand)}`}
function productKey(p:Product){const c=normalizedCopy(p);if(c!=="|")return`copy:${c}`;const id=String(p?.id||"").trim();return id?`id:${id}`:""}
function mergeProducts(groups:Product[][]){const seen=new Set<string>(),out:Product[]=[];for(const g of groups)for(const p of g){const k=productKey(p);if(!k||seen.has(k))continue;seen.add(k);out.push(p);if(out.length>=INITIAL_PRODUCT_TARGET)return out}return out}
function interleave(primary:Product[],channel3:Product[]){if(!channel3.length)return primary;const out:Product[]=[],seen=new Set<string>();let a=0,b=0;while(out.length<INITIAL_PRODUCT_TARGET&&(a<primary.length||b<channel3.length)){for(let i=0;i<2&&a<primary.length;i++,a++){const p=primary[a],k=productKey(p);if(k&&!seen.has(k)){seen.add(k);out.push(p)}}if(b<channel3.length){const p=channel3[b++],k=productKey(p);if(k&&!seen.has(k)){seen.add(k);out.push({...p,source:"channel3",verifiedMerchant:true})}}}return out}
function withTimeout<T>(promise:Promise<T>,ms:number):Promise<T|null>{return new Promise(resolve=>{const timer=window.setTimeout(()=>resolve(null),ms);promise.then(v=>{window.clearTimeout(timer);resolve(v)}).catch(()=>{window.clearTimeout(timer);resolve(null)})})}
function imageUrls(products:Product[]){const urls:string[]=[],seen=new Set<string>();for(const p of products)for(const v of [p.image,...(p.images||[]).slice(0,1)]){const u=String(v||"").trim();if(!u||seen.has(u))continue;seen.add(u);urls.push(u);if(urls.length>=PREFETCH_IMAGES)return urls}return urls}
function prefetchImages(products:Product[]){const run=()=>{for(const url of imageUrls(products)){const image=new Image();image.decoding="async";image.fetchPriority="low";image.src=url}};const w=window as Window&{requestIdleCallback?:(cb:()=>void,opts?:{timeout:number})=>number};typeof w.requestIdleCallback==="function"?w.requestIdleCallback(run,{timeout:650}):window.setTimeout(run,30)}
function jsonResponse(payload:CatalogPayload,status=200,headers?:HeadersInit){const h=new Headers(headers);h.set("Content-Type","application/json; charset=utf-8");h.set("X-YNOT-Search-Accelerated","1");return new Response(JSON.stringify(payload),{status,headers:h})}
function rememberVerified(products:Product[]){for(const p of products){const t=titleKey(p.title);if(t)verifiedTitles.add(t);const id=String(p.id||"");if(id)verifiedIds.add(id);for(const image of [p.image,...(p.images||[])]){const k=imageKey(image);if(k)verifiedImages.add(k)}}window.dispatchEvent(new Event("ynot:verified-products-changed"))}
function isVerifiedCard(card:HTMLElement){const id=card.dataset.productId||card.getAttribute("data-id")||"";if(id&&verifiedIds.has(id))return true;for(const img of card.querySelectorAll<HTMLImageElement>("img")){const k=imageKey(img.currentSrc||img.src);if(k&&verifiedImages.has(k))return true}const copy=titleKey(card.textContent);if(copy.length>3)for(const title of verifiedTitles)if(copy===title||copy.includes(title)||title.includes(copy))return true;return false}
function cardForImage(img:HTMLImageElement){let el:HTMLElement|null=img.parentElement;for(let depth=0;el&&depth<7;depth++,el=el.parentElement){if(el.closest(".lv4-detail,.ynot-product-scan-layer"))return null;const r=el.getBoundingClientRect(),images=el.querySelectorAll("img").length,txt=el.textContent||"";if(r.width>=80&&r.width<=520&&r.height>=120&&r.height<=900&&images<=3&&(/\b(?:EUR|USD|GBP|CAD|AUD|CHF)\b|[€$£]/i.test(txt)))return el}return null}
function candidateCards(){const set=new Set<HTMLElement>();document.querySelectorAll<HTMLImageElement>("img").forEach(img=>{const k=imageKey(img.currentSrc||img.src);if(!k||!verifiedImages.has(k))return;const card=cardForImage(img);if(card)set.add(card)});document.querySelectorAll<HTMLElement>("[data-product-id],[data-id]").forEach(card=>{if(!card.closest(".lv4-detail,.ynot-product-scan-layer")&&isVerifiedCard(card))set.add(card)});return [...set]}
function decorateVerified(){document.querySelectorAll(".ynot-verified-check").forEach(n=>n.remove());if(!verifiedTitles.size&&!verifiedImages.size&&!verifiedIds.size)return;for(const card of candidateCards()){if(getComputedStyle(card).position==="static")card.style.position="relative";card.dataset.channel3="true";const tick=document.createElement("span");tick.className="ynot-verified-check";tick.textContent="✓";tick.setAttribute("aria-label","Verified Channel3 product");const boxes=[...card.querySelectorAll<HTMLElement>("div,span,section,p")].filter(el=>{const r=el.getBoundingClientRect(),txt=el.textContent||"";return r.width>65&&r.height>24&&r.height<170&&(/\b(?:EUR|USD|GBP|CAD|AUD|CHF)\b|[€$£]/i.test(txt))}).sort((a,b)=>{const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();return br.bottom-ar.bottom||ar.height-br.height});const textBox=boxes[0];if(textBox&&getComputedStyle(textBox).position==="static")textBox.style.position="relative";(textBox||card).append(tick)}}
export default function CatalogSearchAccelerator(){useEffect(()=>{const originalFetch=window.fetch.bind(window);let decorateTimer=0;const scheduleDecorate=()=>{window.clearTimeout(decorateTimer);decorateTimer=window.setTimeout(decorateVerified,80)};const observer=new MutationObserver(scheduleDecorate);observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["src","class"]});window.addEventListener("ynot:verified-products-changed",scheduleDecorate);
 const acceleratedFetch:typeof window.fetch=async(input,init)=>{const raw=typeof input==="string"?input:input instanceof URL?input.toString():input.url;let url:URL;try{url=new URL(raw,window.location.origin)}catch{return originalFetch(input as RequestInfo|URL,init)}const isCatalog=url.origin===window.location.origin&&url.pathname==="/api/catalog",method=String(init?.method||(typeof input!=="string"&&!(input instanceof URL)?input.method:"GET")||"GET").toUpperCase(),source=url.searchParams.get("source")||"shopify",page=Number(url.searchParams.get("page")||"0"),shouldAccelerate=isCatalog&&method==="GET"&&url.searchParams.get("market")!=="ebay"&&(source==="shopify"||source==="all")&&page===0&&!url.searchParams.get("cursor")&&!url.searchParams.get("direction");if(!shouldAccelerate)return originalFetch(input as RequestInfo|URL,init);
  const cacheKey=`${url.pathname}?${[...url.searchParams.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("&")}`,cached=responseCache.get(cacheKey);if(cached&&Date.now()-cached.at<CACHE_MS){const c3=(cached.payload.products||[]).filter(p=>String(p.source||"").toLowerCase()==="channel3");rememberVerified(c3);prefetchImages(cached.payload.products||[]);scheduleDecorate();return jsonResponse({...cached.payload,accelerated:true,cached:true})}
  const mixedUrl=new URL(url.toString());mixedUrl.searchParams.set("source","all");const primaryPromise=originalFetch(mixedUrl.toString(),{...init,cache:"no-store"});
  const c3Url=new URL("/api/channel3",window.location.origin);c3Url.searchParams.set("q",url.searchParams.get("q")||"");c3Url.searchParams.set("country",url.searchParams.get("country")||"FR");c3Url.searchParams.set("limit","100");const channel3Promise=withTimeout(originalFetch(c3Url.toString(),{cache:"no-store"}).then(async r=>r.ok?await r.json() as CatalogPayload:null),8000);
  const primary=await primaryPromise;if(!primary.ok)return primary;let primaryData:CatalogPayload;try{primaryData=await primary.clone().json() as CatalogPayload}catch{return primary}const baseProducts=Array.isArray(primaryData.products)?primaryData.products:[],serverC3=baseProducts.filter(p=>String(p.source||"").toLowerCase()==="channel3").map(p=>({...p,verifiedMerchant:true})),channel3Data=await channel3Promise,extraC3=Array.isArray(channel3Data?.products)?channel3Data!.products!.map(p=>({...p,source:"channel3",verifiedMerchant:true})):[],channel3Products=mergeProducts([serverC3,extraC3]);rememberVerified(channel3Products);
  const nonC3=baseProducts.filter(p=>String(p.source||"").toLowerCase()!=="channel3"),liveProducts=interleave(nonC3,channel3Products),sources=[...new Set([...(primaryData.sources||[]),...(channel3Products.length?["channel3"]:[])])];prefetchImages(liveProducts);const livePayload={...primaryData,products:liveProducts,sources,channel3_count:channel3Products.length,accelerated:true,stream_first:true};responseCache.set(cacheKey,{at:Date.now(),payload:livePayload});scheduleDecorate();
  void Promise.all(EXPANSION_DIRECTIONS.map(async direction=>{const expansion=new URL(mixedUrl.toString());expansion.searchParams.set("direction",direction);expansion.searchParams.set("page","0");const payload=await withTimeout(originalFetch(expansion.toString(),{...init,cache:"no-store"}).then(async response=>response.ok?await response.json() as CatalogPayload:null),4000);if(payload?.products?.length)prefetchImages(payload.products);return payload})).then(extras=>{const expanded=mergeProducts([liveProducts,...extras.map(payload=>Array.isArray(payload?.products)?payload!.products!:[])]),expandedC3=expanded.filter(p=>String(p.source||"").toLowerCase()==="channel3");rememberVerified(expandedC3);const merged=interleave(expanded.filter(p=>String(p.source||"").toLowerCase()!=="channel3"),expandedC3);if(merged.length>liveProducts.length){const warmed={...livePayload,products:merged,initial_target:INITIAL_PRODUCT_TARGET};responseCache.set(cacheKey,{at:Date.now(),payload:warmed});window.dispatchEvent(new CustomEvent("ynot:catalog-warmed",{detail:{query:url.searchParams.get("q")||"",count:merged.length,channel3:expandedC3.length}}))}}).catch(()=>{});
  const headers=new Headers(primary.headers);headers.set("X-YNOT-Search-Accelerated","channel3-blend");headers.set("X-YNOT-Channel3-Count",String(channel3Products.length));return jsonResponse(livePayload,primary.status,headers)};
 window.fetch=acceleratedFetch;return()=>{observer.disconnect();window.removeEventListener("ynot:verified-products-changed",scheduleDecorate);window.clearTimeout(decorateTimer);if(window.fetch===acceleratedFetch)window.fetch=originalFetch}},[]);return <><ProductImageScanBridge/><style jsx global>{`.ynot-verified-check{position:absolute!important;right:7px!important;bottom:7px!important;z-index:50!important;width:14px!important;height:14px!important;border-radius:50%!important;display:flex!important;align-items:center!important;justify-content:center!important;background:#fff!important;color:#080808!important;font-size:9px!important;font-weight:900!important;line-height:1!important;box-shadow:0 1px 5px rgba(0,0,0,.28)!important;pointer-events:none!important}`}</style></>}
