"use client";
import {useEffect} from "react";
import ProductImageScanBridge from "./ProductImageScanBridge";
type Product={id?:string;title?:string;brand?:string;image?:string;images?:string[];price?:number|null;source?:string;verifiedMerchant?:boolean;[key:string]:unknown};type Payload={products?:Product[];sources?:string[];pagination?:Record<string,unknown>;[key:string]:unknown};
const MAX=180,verifiedTitles=new Set<string>(),verifiedImages=new Set<string>(),verifiedIds=new Set<string>();
const norm=(v:unknown)=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();
function imageKey(v:unknown){try{const u=new URL(String(v||""),location.origin);return`${u.hostname}${u.pathname}`.toLowerCase()}catch{return String(v||"").split("?")[0].toLowerCase()}}
function key(p:Product){return`${norm(p.title)}|${norm(p.brand)}`}
function unique(xs:Product[]){const seen=new Set<string>(),out:Product[]=[];for(const p of xs){const k=key(p)||String(p.id||"");if(!k||seen.has(k)||!p.image||p.price==null)continue;seen.add(k);out.push(p)}return out}
function interleave(base:Product[],c3:Product[]){const a=unique(base),b=unique(c3),out:Product[]=[];let i=0,j=0;while(out.length<MAX&&(i<a.length||j<b.length)){for(let n=0;n<2&&i<a.length;n++)out.push(a[i++]);if(j<b.length)out.push({...b[j++],source:"channel3",verifiedMerchant:true});if(i>=a.length&&j<b.length)out.push({...b[j++],source:"channel3",verifiedMerchant:true})}return unique(out).slice(0,MAX)}
function remember(xs:Product[]){for(const p of xs){const t=norm(p.title);if(t)verifiedTitles.add(t);if(p.id)verifiedIds.add(String(p.id));for(const im of [p.image,...(p.images||[])]){const k=imageKey(im);if(k)verifiedImages.add(k)}}}
function cardFor(img:HTMLImageElement){let el:HTMLElement|null=img.parentElement;for(let n=0;el&&n<8;n++,el=el.parentElement){if(el.closest(".lv4-detail,.ynot-product-scan-layer"))return null;const r=el.getBoundingClientRect(),txt=el.textContent||"";if(r.width>=80&&r.width<=520&&r.height>=100&&r.height<=950&&(/\b(?:EUR|USD|GBP|CAD|AUD|CHF)\b|[€$£]/i.test(txt)))return el}return null}
function verified(card:HTMLElement){const id=card.dataset.productId||card.getAttribute("data-id")||"";if(id&&verifiedIds.has(id))return true;for(const img of card.querySelectorAll<HTMLImageElement>("img"))if(verifiedImages.has(imageKey(img.currentSrc||img.src)))return true;const txt=norm(card.textContent);for(const t of verifiedTitles)if(t&&txt.includes(t))return true;return false}
function decorate(){document.querySelectorAll(".ynot-verified-check").forEach(n=>n.remove());const cards=new Set<HTMLElement>();document.querySelectorAll<HTMLImageElement>("img").forEach(img=>{if(verifiedImages.has(imageKey(img.currentSrc||img.src))){const c=cardFor(img);if(c)cards.add(c)}});document.querySelectorAll<HTMLElement>("[data-product-id],[data-id]").forEach(c=>{if(!c.closest(".lv4-detail")&&verified(c))cards.add(c)});for(const card of cards){if(!verified(card))continue;card.dataset.channel3="true";const boxes=[...card.querySelectorAll<HTMLElement>("div,span,section,p")].filter(el=>{const r=el.getBoundingClientRect(),t=el.textContent||"";return r.width>60&&r.height>22&&r.height<180&&(/\b(?:EUR|USD|GBP|CAD|AUD|CHF)\b|[€$£]/i.test(t))}).sort((a,b)=>b.getBoundingClientRect().bottom-a.getBoundingClientRect().bottom);const host=boxes[0]||card;if(getComputedStyle(host).position==="static")host.style.position="relative";const tick=document.createElement("span");tick.className="ynot-verified-check";tick.textContent="✓";tick.setAttribute("aria-label","Verified product");host.append(tick)}}
async function read(r:Response){try{return await r.json() as Payload}catch{return null}}
export default function CatalogSearchAccelerator(){useEffect(()=>{const original=window.fetch.bind(window);let timer=0;const schedule=()=>{clearTimeout(timer);timer=window.setTimeout(decorate,70)};const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["src","class"]});
 const patched:typeof window.fetch=async(input,init)=>{const raw=typeof input==="string"?input:input instanceof URL?input.toString():input.url;let u:URL;try{u=new URL(raw,location.origin)}catch{return original(input as RequestInfo|URL,init)}const method=String(init?.method||(typeof input!=="string"&&!(input instanceof URL)?input.method:"GET")||"GET").toUpperCase();if(u.origin!==location.origin||u.pathname!=="/api/catalog"||method!=="GET"||u.searchParams.get("yn-c3-direct")==="1"||u.searchParams.get("market")==="ebay")return original(input as RequestInfo|URL,init);
  // Every first-page YNOT masonry search is multi-source. Never silently revert to Shopify-only.
  const page=Number(u.searchParams.get("page")||"0");if(page!==0||u.searchParams.get("cursor"))return original(input as RequestInfo|URL,init);const mixed=new URL(u);mixed.searchParams.set("source","all");const c3=new URL("/api/catalog",location.origin);c3.searchParams.set("q",u.searchParams.get("q")||"");c3.searchParams.set("country",u.searchParams.get("country")||"FR");c3.searchParams.set("source","channel3");c3.searchParams.set("yn-c3-direct","1");
  const [mr,cr]=await Promise.allSettled([original(mixed.toString(),{...init,cache:"no-store"}),original(c3.toString(),{cache:"no-store"})]);if(mr.status!=="fulfilled")throw mr.reason;const primary=mr.value;if(!primary.ok)return primary;const data=await read(primary.clone());if(!data)return primary;const direct=cr.status==="fulfilled"&&cr.value.ok?await read(cr.value):null;const incoming=Array.isArray(data.products)?data.products:[],serverC3=incoming.filter(p=>String(p.source||"").toLowerCase().includes("channel3")),directC3=Array.isArray(direct?.products)?direct!.products!:[],channel3=unique([...serverC3,...directC3]).map(p=>({...p,source:"channel3",verifiedMerchant:true})),shopify=incoming.filter(p=>!String(p.source||"").toLowerCase().includes("channel3"));remember(channel3);const products=interleave(shopify,channel3),payload={...data,source:"ynot-multi-source",sources:["shopify-global-catalog",...(channel3.length?["channel3"]:[])],products,channel3_count:channel3.length,pagination:{...(data.pagination||{}),channel3_count:channel3.length}};schedule();setTimeout(decorate,250);const h=new Headers(primary.headers);h.set("Content-Type","application/json");h.set("X-YNOT-Channel3-Count",String(channel3.length));return new Response(JSON.stringify(payload),{status:primary.status,headers:h})};
 window.fetch=patched;return()=>{observer.disconnect();clearTimeout(timer);if(window.fetch===patched)window.fetch=original}},[]);return <><ProductImageScanBridge/><style jsx global>{`.ynot-verified-check{position:absolute!important;right:7px!important;bottom:7px!important;z-index:50!important;width:14px!important;height:14px!important;border-radius:50%!important;display:flex!important;align-items:center!important;justify-content:center!important;background:#fff!important;color:#080808!important;font-size:9px!important;font-weight:900!important;line-height:1!important;box-shadow:0 1px 5px rgba(0,0,0,.28)!important;pointer-events:none!important}`}</style></>}
