"use client";

import {useEffect} from "react";

function visible(el:HTMLElement){const s=getComputedStyle(el),r=el.getBoundingClientRect();return el.isConnected&&s.display!=="none"&&s.visibility!=="hidden"&&r.width>0&&r.height>0}
function dealCards(){const grid=document.querySelector<HTMLElement>('.ynot-grid');if(!grid)return[];return [...grid.children].filter((el):el is HTMLElement=>el instanceof HTMLElement&&visible(el))}
function activate(el:HTMLElement){const clickable=(el.matches('button,[role="button"]')?el:el.querySelector<HTMLElement>('button,[role="button"],a'))||el;clickable.scrollIntoView({block:'nearest',inline:'nearest'});clickable.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true,pointerType:'mouse',isPrimary:true}));clickable.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,cancelable:true,pointerType:'mouse',isPrimary:true}));clickable.click()}
function dealMove(direction:number){const cards=dealCards();if(cards.length<2)return false;const selected=document.querySelector<HTMLElement>('.ynot-selected');if(!selected)return false;const title=(selected.querySelector('h3,h2')?.textContent||'').trim().toLowerCase();let index=cards.findIndex(card=>(card.textContent||'').toLowerCase().includes(title));if(index<0)index=cards.findIndex(card=>card.classList.contains('active')||card.getAttribute('aria-current')==='true');if(index<0)index=0;activate(cards[(index+direction+cards.length)%cards.length]);return true}
function productCards(){return [...document.querySelectorAll<HTMLElement>('.lv4-product')].filter(visible)}
function productMove(direction:number){const cards=productCards();if(cards.length<2)return false;const detail=document.querySelector<HTMLElement>('.lv4-detail');if(!detail)return false;const title=(detail.querySelector('h2')?.textContent||'').trim().toLowerCase();let index=cards.findIndex(card=>(card.textContent||'').toLowerCase().includes(title));if(index<0)index=cards.findIndex(card=>card.classList.contains('active')||card.getAttribute('aria-current')==='true');if(index<0)index=0;activate(cards[(index+direction+cards.length)%cards.length]);return true}
function pan(direction:number){const world=document.querySelector<HTMLElement>('.lv4-world');if(!world)return;window.dispatchEvent(new CustomEvent('ynot:world-focus',{detail:{direction:direction>0?'right':'left',prefetch:true}}))}

export default function DesktopGlassSideControls({active=true}:{active?:boolean}){
 useEffect(()=>{const keep=()=>document.querySelectorAll<HTMLVideoElement>('.lv4-world video,.ynot-entry-ambient video,.ynot-world-background video,[data-ynot-background-video]').forEach(v=>{if(v.closest('.lv4-detail,.ynot-complete-image-viewer'))return;v.muted=true;v.loop=true;v.playsInline=true;if(v.paused)void v.play().catch(()=>{})});keep();const o=new MutationObserver(keep);o.observe(document.body,{subtree:true,childList:true});document.addEventListener('visibilitychange',keep);window.addEventListener('pageshow',keep);return()=>{o.disconnect();document.removeEventListener('visibilitychange',keep);window.removeEventListener('pageshow',keep)}},[]);
 if(!active)return null;
 const move=(d:number)=>{if(document.querySelector('.ynot-selected')&&dealMove(d))return;if(document.querySelector('.lv4-detail')&&productMove(d))return;pan(d)};
 return <><style>{`
 .ynot-glass-side-control{position:fixed;top:52%;z-index:2147483500;width:58px;height:58px;display:grid;place-items:center;border-radius:999px;border:1px solid rgba(255,255,255,.24);background:rgba(12,12,12,.42);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);transform:translateY(-50%);cursor:pointer;pointer-events:auto!important;touch-action:manipulation}.ynot-glass-side-control.left{left:14px}.ynot-glass-side-control.right{right:14px}.ynot-glass-side-control i{width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,.9)}
 /* Keep the YNOT Deals category rail above the lower fade/shadow. */
 .ynot-drawer .ynot-workspace,.ynot-drawer .ynot-dock{overflow:visible!important}.ynot-drawer .ynot-dock{position:relative!important;z-index:2147482000!important;isolation:isolate!important;filter:none!important;opacity:1!important}.ynot-drawer .ynot-dock:before,.ynot-drawer .ynot-dock:after{display:none!important}.ynot-drawer .ynot-dock button{position:relative!important;z-index:2!important;opacity:1!important;visibility:visible!important;filter:none!important;box-shadow:none!important}.ynot-drawer .ynot-dock button span{position:relative!important;z-index:3!important;opacity:1!important;visibility:visible!important}
 @media(max-width:899px){.ynot-glass-side-control{display:none!important}}
 `}</style><button type="button" className="ynot-glass-side-control left" aria-label="Previous product" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.preventDefault();e.stopPropagation();move(-1)}}><i/></button><button type="button" className="ynot-glass-side-control right" aria-label="Next product" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.preventDefault();e.stopPropagation();move(1)}}><i/></button></>;
}
