"use client";

import {useEffect} from "react";

function norm(value:string){return String(value||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function currentTitle(){return norm(document.querySelector(".lv4-detail .lv4-detailcopy h2")?.textContent||"")}
function cardTitle(card:HTMLElement){return norm(card.querySelector(".lv4-product-tooltip b,.lv4-orbmeta b")?.textContent||card.getAttribute("aria-label")||"")}
function cycleProduct(direction:number){const cards=[...document.querySelectorAll<HTMLElement>(".lv4-stage > .lv4-product")];if(cards.length<2)return false;const title=currentTitle();let index=cards.findIndex(card=>cardTitle(card)===title);if(index<0)index=0;const target=cards[(index+direction+cards.length)%cards.length];const image=target?.querySelector<HTMLImageElement>("img");if(image){image.loading="eager";image.setAttribute("fetchpriority","high");void image.decode?.().catch(()=>{})}target?.click();return Boolean(target)}
function cycleDealProduct(direction:number){const cards=[...document.querySelectorAll<HTMLElement>(".ynot-drawer.open .ynot-grid .ynot-orb")];if(cards.length<2)return false;const current=norm(document.querySelector(".ynot-selected .ynot-selected-copy h3")?.textContent||"");let index=cards.findIndex(card=>norm(card.querySelector(".ynot-orb-copy b")?.textContent||card.getAttribute("aria-label")||"")===current);if(index<0)index=0;const target=cards[(index+direction+cards.length)%cards.length];target?.click();return Boolean(target)}
function panWorld(direction:number){const world=document.querySelector<HTMLElement>(".lv4-world");if(!world)return;const rect=world.getBoundingClientRect(),startX=rect.left+rect.width/2,startY=rect.top+rect.height/2,distance=Math.max(420,Math.min(760,rect.width*.42)),endX=startX-(direction*distance),common={bubbles:true,cancelable:true,pointerId:91,pointerType:"mouse",isPrimary:true,buttons:1,clientY:startY};try{world.dispatchEvent(new PointerEvent("pointerdown",{...common,clientX:startX}));world.dispatchEvent(new PointerEvent("pointermove",{...common,clientX:endX}));world.dispatchEvent(new PointerEvent("pointerup",{...common,clientX:endX,buttons:0}))}catch{window.dispatchEvent(new CustomEvent("ynot:world-focus",{detail:{direction:direction>0?"right":"left",prefetch:true}}))}}
function mediaFromCard(){const gallery=document.querySelector<HTMLElement>(".lv4-detail .ynot-loaded-gallery");return [...new Set((gallery?.dataset.ynotFullMediaSignature||gallery?.dataset.mediaSignature||"").split("|").map(x=>x.trim()).filter(Boolean))]}
function openDesktopViewer(media:string[],start=0){if(!media.length)return;document.querySelector(".ynot-complete-image-viewer")?.remove();let index=Math.max(0,Math.min(start,media.length-1));const viewer=document.createElement("section");viewer.className="ynot-complete-image-viewer";viewer.tabIndex=0;const frame=document.createElement("div");frame.className="ynot-complete-image-frame";const stage=document.createElement("div");stage.className="ynot-complete-media-stage";const close=document.createElement("button");close.className="ynot-complete-image-close";close.type="button";close.textContent="×";close.setAttribute("aria-label","Close media");const prev=document.createElement("button"),next=document.createElement("button");prev.type=next.type="button";prev.className="ynot-viewer-nav prev";next.className="ynot-viewer-nav next";prev.textContent="‹";next.textContent="›";prev.setAttribute("aria-label","Previous image");next.setAttribute("aria-label","Next image");const render=()=>{stage.replaceChildren();const url=media[index];if(/\.(mp4|webm|mov|m4v)(?:\?|$)/i.test(url)){const v=document.createElement("video");v.src=url;v.controls=true;v.autoplay=true;v.playsInline=true;v.className="ynot-complete-media";stage.appendChild(v)}else{const img=document.createElement("img");img.src=url;img.alt="Product view";img.draggable=false;img.className="ynot-complete-media";img.addEventListener("click",()=>move(1));stage.appendChild(img)}};const move=(d:number)=>{index=(index+d+media.length)%media.length;render()};close.onclick=e=>{e.stopPropagation();viewer.remove()};prev.onclick=e=>{e.stopPropagation();move(-1)};next.onclick=e=>{e.stopPropagation();move(1)};viewer.onclick=e=>{if(e.target===viewer)viewer.remove()};viewer.onkeydown=e=>{if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1);if(e.key==="Escape")viewer.remove()};frame.append(stage,close,prev,next);viewer.appendChild(frame);document.body.appendChild(viewer);render();requestAnimationFrame(()=>viewer.focus())}

export default function DesktopGlassSideControls({active=true}:{active?:boolean}){
 useEffect(()=>{document.documentElement.classList.add("ynot-glass-side-controls-ready");return()=>document.documentElement.classList.remove("ynot-glass-side-controls-ready")},[]);
 useEffect(()=>{const click=(e:MouseEvent)=>{if(window.innerWidth<900||!(e.target instanceof HTMLImageElement))return;const main=e.target.closest(".lv4-detail")&&e.target.matches(".lv4-detail>img,.lv4-detail .lv4-detail-media")?e.target:null;if(!main)return;const media=mediaFromCard();if(!media.length)return;e.preventDefault();e.stopPropagation();const current=(main as HTMLImageElement).currentSrc||(main as HTMLImageElement).src;const start=Math.max(0,media.findIndex(x=>x===current));openDesktopViewer(media,start)};document.addEventListener("click",click,true);return()=>document.removeEventListener("click",click,true)},[]);
 if(!active)return null;const move=(direction:number)=>{if(document.querySelector(".ynot-drawer.open .ynot-selected")&&cycleDealProduct(direction))return;if(document.querySelector(".lv4-detail")&&cycleProduct(direction))return;if(document.querySelector(".ynot-drawer.open"))return;panWorld(direction)};
 return <><style>{`
 .ynot-glass-side-control{position:fixed;top:52%;z-index:2147482200;width:58px;height:58px;display:grid;place-items:center;border-radius:999px;border:1px solid rgba(255,255,255,.24);background:linear-gradient(145deg,rgba(255,255,255,.12),rgba(255,255,255,.035) 42%,rgba(8,8,8,.24));box-shadow:inset 0 1px 0 rgba(255,255,255,.16),inset 0 -12px 24px rgba(0,0,0,.12),0 12px 34px rgba(0,0,0,.18);backdrop-filter:blur(28px) saturate(138%);-webkit-backdrop-filter:blur(28px) saturate(138%);transform:translateY(-50%);cursor:pointer;touch-action:manipulation}.ynot-glass-side-control.left{left:14px}.ynot-glass-side-control.right{right:14px}.ynot-glass-side-control i{width:10px;height:10px;border-radius:50%;display:block;background:rgba(250,250,250,.86)}
 .lv4-detail>.lv4-close{position:absolute!important;top:12px!important;right:12px!important;left:auto!important;width:36px!important;height:36px!important;border-radius:999px!important;z-index:2147483646!important;display:grid!important;place-items:center!important;background:rgba(15,15,15,.34)!important;border:1px solid rgba(255,255,255,.16)!important;color:#fff!important}
 .ynot-complete-image-viewer{position:fixed!important;inset:0!important;z-index:2147483647!important;display:grid!important;place-items:center!important;background:rgba(0,0,0,.28)!important;backdrop-filter:blur(11px)!important;padding:28px!important;outline:none!important}.ynot-complete-image-frame{position:relative!important;width:min(76vw,860px)!important;height:min(68vh,680px)!important;display:grid!important;place-items:center!important;overflow:hidden!important;border:1px solid rgba(255,255,255,.24)!important;border-radius:28px!important;background:rgba(18,18,18,.76)!important;padding:18px!important}.ynot-complete-media-stage{width:100%!important;height:100%!important;display:grid!important;place-items:center!important;overflow:hidden!important}.ynot-complete-media{display:block!important;max-width:100%!important;max-height:100%!important;width:auto!important;height:auto!important;object-fit:contain!important;border-radius:18px!important}.ynot-complete-image-close{position:absolute!important;top:12px!important;right:12px!important;width:40px!important;height:40px!important;border-radius:999px!important;display:grid!important;place-items:center!important;border:1px solid rgba(255,255,255,.22)!important;background:rgba(20,20,20,.48)!important;color:#fff!important;font-size:25px!important;z-index:5!important;cursor:pointer!important}.ynot-viewer-nav{position:absolute!important;top:50%!important;transform:translateY(-50%)!important;width:48px!important;height:48px!important;border-radius:999px!important;border:1px solid rgba(255,255,255,.24)!important;background:rgba(20,20,20,.38)!important;color:white!important;font-size:34px!important;line-height:1!important;display:grid!important;place-items:center!important;z-index:5!important;cursor:pointer!important;backdrop-filter:blur(16px)!important}.ynot-viewer-nav.prev{left:14px!important}.ynot-viewer-nav.next{right:14px!important}
 @media(max-width:899px){.ynot-glass-side-control{display:none!important}.ynot-viewer-nav{display:none!important}}
 `}</style><button type="button" className="ynot-glass-side-control left" aria-label="Move left / previous product" onClick={()=>move(-1)}><i/></button><button type="button" className="ynot-glass-side-control right" aria-label="Move right / next product" onClick={()=>move(1)}><i/></button></>
}
