"use client";

import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {etsyProductPrice,klarnaPreview} from "@/lib/commerce/etsy-pricing";

type Review={rating:number;text:string;createdAt?:number};
type Variant={id:string;label:string;price:number|null;currency?:string;available:boolean};
type Product={id:string;listingId:number;shopId?:number;title:string;brand:string;description?:string;price:number|null;currency?:string;image:string;images?:string[];url?:string;variants?:Variant[];rating?:number|null;reviewCount?:number;reviews?:Review[]};
type BubbleStyle=CSSProperties&{"--etsy-x":string;"--etsy-y":string;"--etsy-size":string;"--etsy-delay":string};
function money(value:number|null,currency="EUR"){if(value==null)return"";try{return new Intl.NumberFormat(undefined,{style:"currency",currency,maximumFractionDigits:2}).format(value)}catch{return`${value.toFixed(2)} ${currency}`}}
function stars(value:number|null|undefined){const n=Math.max(0,Math.min(5,Number(value||0)));return`${"★".repeat(Math.round(n))}${"☆".repeat(5-Math.round(n))}`}
function bubbleStyle(index:number):BubbleStyle{const ring=Math.floor(index/10),slot=index%10,angle=(slot/10)*Math.PI*2+(ring%2)*.31;const radius=18+ring*14+(slot%3)*2.4;const x=50+Math.cos(angle)*radius,y=50+Math.sin(angle)*radius*.68;const size=116+((index*37)%58);return{"--etsy-x":`${Math.max(7,Math.min(93,x))}%`,"--etsy-y":`${Math.max(9,Math.min(91,y))}%`,"--etsy-size":`${size}px`,"--etsy-delay":`${-(index%9)*.42}s`}}
function regionCountry(){try{return String(JSON.parse(localStorage.getItem("ynot-region")||"null")?.country||"FR").toUpperCase()}catch{return"FR"}}

export default function EtsySourceController(){
 const [active,setActive]=useState(false);const [products,setProducts]=useState<Product[]>([]);const [loading,setLoading]=useState(false);const [buying,setBuying]=useState(false);const [error,setError]=useState("");const [selected,setSelected]=useState<Product|null>(null);const [showReviews,setShowReviews]=useState(false);const [variant,setVariant]=useState<Variant|null>(null);const [page,setPage]=useState(0);const [country,setCountry]=useState("FR");
 const query=useMemo(()=>{if(typeof document==="undefined")return"gifts";return document.querySelector<HTMLInputElement>(".lv4-search input")?.value?.trim()||"gifts"},[active,page]);
 async function load(nextPage=0,append=false){setLoading(true);setError("");try{const region=regionCountry();setCountry(region);const r=await fetch(`/api/etsy?q=${encodeURIComponent(query||"gifts")}&page=${nextPage}&country=${encodeURIComponent(region)}&currency=EUR`,{cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.error||"Etsy unavailable");const list=Array.isArray(data.products)?data.products:[];setProducts(prev=>append?[...prev,...list]:list);setPage(nextPage)}catch(e){setError(e instanceof Error?e.message:"Etsy unavailable")}finally{setLoading(false)}}
 async function checkout(){if(!selected?.url)return;setBuying(true);setError("");try{const supplierPrice=variant?.price??selected.price;if(supplierPrice==null)throw new Error("Price unavailable");const currency=variant?.currency||selected.currency||"EUR",quoteRes=await fetch("/api/checkout/quote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,variantId:variant?.id,title:selected.title,brand:selected.brand,price:supplierPrice,currency,image:selected.image,url:selected.url,source:"etsy",category:"default",quantity:1,region:{country}})}),quote=await quoteRes.json();if(!quoteRes.ok)throw new Error(quote.error||"Unable to price this Etsy item");const sessionRes=await fetch("/api/checkout/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:quote.token})}),session=await sessionRes.json();if(!sessionRes.ok||!session.url)throw new Error(session.error||"Unable to start checkout");window.location.assign(session.url)}catch(e){setError(e instanceof Error?e.message:"Unable to start checkout")}finally{setBuying(false)}}
 useEffect(()=>{if(!active)return;document.body.classList.add("ynot-etsy-mode");void load(0,false);return()=>document.body.classList.remove("ynot-etsy-mode")},[active]);
 useEffect(()=>{const host=document.querySelector(".lv4-market-toggle");if(!host)return;let button=host.querySelector<HTMLButtonElement>(".ynot-etsy-tab");if(!button){button=document.createElement("button");button.className="ynot-etsy-tab";button.innerHTML="<b>Etsy</b><span>Marketplace</span>";host.appendChild(button)}const click=(e:Event)=>{e.preventDefault();e.stopPropagation();setActive(true);setSelected(null);setShowReviews(false)};button.addEventListener("click",click,true);const leave=(e:Event)=>{const target=e.target as HTMLElement|null;if(target?.closest(".ynot-etsy-tab"))return;if(target?.closest(".lv4-market-toggle button")){setActive(false);setSelected(null);setShowReviews(false)}};document.addEventListener("click",leave,true);return()=>{button?.removeEventListener("click",click,true);document.removeEventListener("click",leave,true)}},[]);
 useEffect(()=>{if(!active)return;const submit=(e:Event)=>{const target=e.target as HTMLElement|null;if(target?.matches(".lv4-search button")||((e as KeyboardEvent).key==="Enter"&&target?.matches(".lv4-search input"))){e.preventDefault();e.stopImmediatePropagation();void load(0,false)}};document.addEventListener("click",submit,true);document.addEventListener("keydown",submit,true);return()=>{document.removeEventListener("click",submit,true);document.removeEventListener("keydown",submit,true)}},[active,query]);
 if(!active)return null;
 const supplierPrice=variant?.price??selected?.price??null,displayCurrency=variant?.currency||selected?.currency||"EUR",displayPrice=supplierPrice==null?null:etsyProductPrice(supplierPrice).ynotProductPrice,klarna=displayPrice==null?null:klarnaPreview(displayPrice,country,displayCurrency);
 return <>
  <section className="ynot-etsy-layer" aria-label="Etsy products only">
   <div className="ynot-etsy-head"><div><small>ETSY · YNOT WORLD</small><h2>Etsy</h2></div><button onClick={()=>void load(0,false)} disabled={loading}>{loading?"Loading…":"Refresh"}</button></div>
   {error&&<div className="ynot-etsy-error">{error}</div>}
   <div className="ynot-etsy-world">{products.map((product,index)=>{const ynot=product.price==null?null:etsyProductPrice(product.price).ynotProductPrice,kp=ynot==null?null:klarnaPreview(ynot,country,product.currency||"EUR");return <button key={product.id} style={bubbleStyle(index)} className="ynot-etsy-product" onClick={()=>{setSelected(product);setVariant(null);setShowReviews(false)}}><span className="ynot-etsy-image"><img src={product.image} alt=""/></span><span className="ynot-etsy-copy"><b>{product.title}</b><span className="ynot-etsy-rating">{product.rating?`★ ${product.rating.toFixed(1)} · ${product.reviewCount||0}`:"Etsy"}</span><strong>{money(ynot,product.currency||"EUR")}</strong>{kp?.eligible&&<small>{kp.parts} × {money(kp.amount,product.currency||"EUR")} with Klarna</small>}</span></button>})}</div>
   {products.length>0&&<button className="ynot-etsy-more" onClick={()=>void load(page+1,true)} disabled={loading}>{loading?"Loading…":"Explore more"}</button>}
  </section>
  {selected&&<article className={`lv4-detail ynot-etsy-detail ${showReviews?"ynot-etsy-reviews-open":""}`}>
   {!showReviews?<><button className="ynot-etsy-close" onClick={()=>setSelected(null)}>×</button><img src={selected.image} alt=""/><div className="lv4-detailcopy"><small>ETSY · {selected.brand}</small><h2>{selected.title}</h2>{selected.rating?<button className="ynot-etsy-review-trigger" onClick={()=>setShowReviews(true)}>{stars(selected.rating)} <b>{selected.rating.toFixed(1)}</b> · {selected.reviewCount||0} reviews</button>:null}<strong>{money(displayPrice,displayCurrency)}</strong>{klarna?.eligible?<div className="ynot-etsy-klarna"><b>{klarna.parts} × {money(klarna.amount,displayCurrency)}</b> with Klarna <small>Subject to Klarna approval. Final plan confirmed at checkout.</small></div>:<div className="ynot-etsy-klarna muted">{klarna?.label}</div>}<small>Shipping is checked for your country before payment and added to the final order total.</small>{(selected.variants||[]).length>0&&<div className="ynot-etsy-variants">{selected.variants?.map(v=><button key={v.id} className={variant?.id===v.id?"active":""} disabled={!v.available} onClick={()=>setVariant(v)}>{v.label}{v.price!=null?` · ${money(etsyProductPrice(v.price).ynotProductPrice,v.currency||selected.currency||"EUR")}`:""}</button>)}</div>}<button className="ynot-etsy-buy" disabled={buying||supplierPrice==null} onClick={()=>void checkout()}>{buying?"Preparing secure checkout…":"Buy with YNOT"}</button><p>{selected.description}</p>{selected.url&&<a href={selected.url} target="_blank" rel="noreferrer">View on Etsy</a>}</div></>:<section className="ynot-etsy-review-back"><button className="ynot-etsy-back" onClick={()=>setShowReviews(false)}>←</button><small>ETSY REVIEWS</small><h3>{selected.title}</h3><div className="ynot-etsy-review-list">{(selected.reviews||[]).slice(0,5).map((r,i)=><article key={i}><b>{stars(r.rating)} {r.rating.toFixed(1)}</b><p>{r.text||"Rated on Etsy"}</p></article>)}</div></section>}
  </article>}
 </>
}
