"use client";
import {useEffect} from "react";

type Detection={id:string;label:string;category?:string;searchQuery:string;alternateQueries?:string[];confidence?:number;box_2d:number[]};
type Analysis={sceneTitle?:string;sceneDescription?:string;styleDescription?:string;objects?:Detection[]};
type Product={id:string;title:string;brand?:string;image?:string;price?:number|null;currency?:string};
let active=false,root:HTMLElement|null=null,detections:Detection[]=[],analysis:Analysis={},lockedImageUrl="",heroGuard:MutationObserver|null=null,choiceToken=0,scanPage=0,scanLoading=false,scanTerms:string[]=[],scanSeen=new Set<string>(),scanTarget:HTMLElement|null=null,scanObserver:IntersectionObserver|null=null;
const q=<T extends Element>(s:string,r:ParentNode=document)=>r.querySelector<T>(s);
function stopHeroGuard(){heroGuard?.disconnect();heroGuard=null}function stopScanObserver(){scanObserver?.disconnect();scanObserver=null}
function ensureFrozen(card:HTMLElement){if(!active||!lockedImageUrl)return;const hero=q<HTMLElement>(".hero",card);if(!hero)return;let frozen=q<HTMLImageElement>(".masonry-scan-frozen-image",hero);if(!frozen){frozen=document.createElement("img");frozen.className="masonry-scan-frozen-image";frozen.alt="Product image being scanned";frozen.draggable=false;hero.prepend(frozen)}if(frozen.src!==lockedImageUrl)frozen.src=lockedImageUrl}
function startHeroGuard(card:HTMLElement){stopHeroGuard();const hero=q<HTMLElement>(".hero",card);if(!hero)return;heroGuard=new MutationObserver(()=>ensureFrozen(card));heroGuard.observe(hero,{childList:true,subtree:true,attributes:true,attributeFilter:["src"]})}
function restoreGrid(card:HTMLElement){const more=q<HTMLElement>(".more",card);if(more){more.classList.remove("masonry-scan-more-active");more.querySelector(".masonry-scan-inline")?.remove()}const related=q<HTMLElement>(".related",card);if(related){related.classList.remove("masonry-scan-grid-active");related.querySelectorAll<HTMLElement>("[data-masonry-scan-original]").forEach(n=>{n.style.removeProperty("display");n.removeAttribute("data-masonry-scan-original")});related.querySelectorAll(".masonry-scan-grid-item,.masonry-scan-empty,.masonry-scan-sentinel").forEach(n=>n.remove())}}
function clean(){choiceToken++;stopHeroGuard();stopScanObserver();if(root){root.classList.remove("masonry-scan-active");root.querySelectorAll(".masonry-scan-overlay,.masonry-scan-status,.masonry-scan-frozen-image").forEach(n=>n.remove());restoreGrid(root)}active=false;root=null;lockedImageUrl="";detections=[];analysis={};scanPage=0;scanTerms=[];scanSeen.clear();scanTarget=null}
function image(card:HTMLElement){return q<HTMLImageElement>(".hero img:not(.masonry-scan-frozen-image)",card)}function freezeImage(card:HTMLElement,img:HTMLImageElement){lockedImageUrl=img.currentSrc||img.src;ensureFrozen(card);startHeroGuard(card)}function money(p:Product){return p.price==null?"":`${p.currency||"EUR"} ${Number(p.price).toFixed(2)}`}
function setMoreLabel(card:HTMLElement,label:string,loading=false,whole=false){const more=q<HTMLElement>(".more",card);if(!more)return;more.classList.add("masonry-scan-more-active");let inline=q<HTMLElement>(".masonry-scan-inline",more);if(!inline){inline=document.createElement("div");inline.className="masonry-scan-inline";more.append(inline)}inline.innerHTML=`<small>${loading?"SEARCHING":whole?"SHOP THE LOOK":"SCAN MATCHES"}</small><h2></h2>`;(inline.querySelector("h2") as HTMLElement).textContent=loading?`Finding ${label}…`:label}
function searchTerms(d:Detection){const raw=[d.searchQuery,d.label,...(d.alternateQueries||[])].map(x=>String(x||"").trim()).filter(Boolean);const out:string[]=[];for(const term of raw){const c=term.replace(/\s+/g," ");if(c&&!out.some(x=>x.toLowerCase()===c.toLowerCase()))out.push(c)}return out}
function score(p:Product,d:Detection){const hay=`${p.title||""} ${p.brand||""}`.toLowerCase(),primary=`${d.label} ${d.searchQuery}`.toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2),alt=(d.alternateQueries||[]).join(" ").toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2);let s=0;for(const w of primary)if(hay.includes(w))s+=4;for(const w of alt)if(hay.includes(w))s+=1;if(d.category&&hay.includes(d.category.toLowerCase()))s+=2;return s}
function makeGridItem(p:Product,label:string){const b=document.createElement("button");b.type="button";b.className="masonry-scan-grid-item";const img=document.createElement("img");img.src=p.image!;img.alt=p.title||label;img.loading="lazy";const title=document.createElement("b");title.textContent=p.title||label;const price=document.createElement("em");price.textContent=money(p);b.append(img,title,price);b.dataset.ynotProduct=JSON.stringify(p);let opened=0;const open=(e:Event)=>{e.preventDefault();e.stopPropagation();const now=Date.now();if(now-opened<450)return;opened=now;window.dispatchEvent(new CustomEvent("ynot:open-product",{detail:p}))};b.addEventListener("pointerup",open);b.addEventListener("click",open);return b}
async function fetchBatch(card:HTMLElement,d:Detection,token:number){if(scanLoading||token!==choiceToken)return;const related=q<HTMLElement>(".related",card);if(!related)return;scanLoading=true;try{const wave=scanPage++;const terms=scanTerms.length?scanTerms:[d.searchQuery,d.label];const selected=terms.slice(wave%terms.length).concat(wave===0?terms.slice(1):[]);const groups=await Promise.all(selected.map(async(term)=>{try{const suffix=wave?` ${['popular','premium','best selling','new','recommended','trending'][wave%6]}`:"";const r=await fetch(`/api/catalog?q=${encodeURIComponent(term+suffix)}&source=all&limit=60`,{cache:"no-store"}),j=await r.json();return Array.isArray(j.products)?j.products as Product[]:[]}catch{return[]}}));if(token!==choiceToken)return;const items=groups.flat().filter(p=>p?.id&&p.image&&!scanSeen.has(String(p.id))).sort((a,b)=>score(b,d)-score(a,d));for(const p of items){scanSeen.add(String(p.id));related.insertBefore(makeGridItem(p,d.label),q(".masonry-scan-sentinel",related))}}finally{scanLoading=false}}
function infinite(card:HTMLElement,d:Detection,token:number){stopScanObserver();const related=q<HTMLElement>(".related",card);if(!related)return;let sentinel=q<HTMLElement>(".masonry-scan-sentinel",related);if(!sentinel){sentinel=document.createElement("div");sentinel.className="masonry-scan-sentinel";related.append(sentinel)}scanObserver=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)void fetchBatch(card,d,token)},{rootMargin:"1400px 0px"});scanObserver.observe(sentinel)}
async function choose(d:Detection,whole=false){if(!root)return;const card=root,token=++choiceToken;stopScanObserver();ensureFrozen(card);card.querySelectorAll<HTMLElement>(".masonry-scan-dot").forEach(n=>n.classList.toggle("on",n.dataset.id===d.id));const related=q<HTMLElement>(".related",card);if(!related)return;setMoreLabel(card,d.label,true,whole);related.classList.add("masonry-scan-grid-active");related.querySelectorAll<HTMLElement>(":scope > button:not(.masonry-scan-grid-item)").forEach(n=>{n.dataset.masonryScanOriginal="1";n.style.display="none"});related.querySelectorAll(".masonry-scan-grid-item,.masonry-scan-empty,.masonry-scan-sentinel").forEach(n=>n.remove());scanPage=0;scanSeen.clear();scanTerms=searchTerms(d);scanTarget=related;await fetchBatch(card,d,token);if(token!==choiceToken)return;setMoreLabel(card,d.label,false,whole);if(!related.querySelector(".masonry-scan-grid-item")){const e=document.createElement("div");e.className="masonry-scan-empty";e.textContent="No close matches yet.";related.append(e)}infinite(card,d,token)}
function wholeLook():Detection{const labels=detections.slice(0,8).map(d=>d.label);const style=String(analysis.styleDescription||analysis.sceneDescription||analysis.sceneTitle||"").trim();return{id:"whole-look",label:"Shop this look",category:"style",searchQuery:[style,...labels.slice(0,3)].filter(Boolean).join(" "),alternateQueries:[...labels,style].filter(Boolean),confidence:1,box_2d:[430,430,570,570]}}
function dotElement(d:Detection,whole=false){const dot=document.createElement("button");dot.type="button";dot.className=`masonry-scan-dot${whole?" whole":""}`;dot.dataset.id=d.id;const b=d.box_2d||[];dot.style.left=`${((b[1]+b[3])/2)/10}%`;dot.style.top=`${((b[0]+b[2])/2)/10}%`;dot.setAttribute("aria-label",d.label);dot.innerHTML=`<span>${d.label}</span>`;dot.onclick=e=>{e.preventDefault();e.stopPropagation();void choose(d,whole)};return dot}
function draw(card:HTMLElement,objects:Detection[]){ensureFrozen(card);const hero=q<HTMLElement>(".hero",card);if(!hero)return;hero.querySelector(".masonry-scan-overlay")?.remove();const overlay=document.createElement("div");overlay.className="masonry-scan-overlay";for(const d of objects)if((d.box_2d||[]).length===4)overlay.append(dotElement(d));if(objects.length>1)overlay.append(dotElement(wholeLook(),true));hero.append(overlay)}
async function scan(card:HTMLElement){if(active){clean();return}const img=image(card);if(!img?.src)return;const scanUrl=img.currentSrc||img.src;root=card;active=true;card.classList.add("masonry-scan-active");freezeImage(card,img);const status=document.createElement("div");status.className="masonry-scan-status";status.textContent="Scanning…";q<HTMLElement>(".hero",card)?.append(status);try{const r=await fetch("/api/room/quick/analyze-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({imageUrl:scanUrl})}),j=await r.json();if(!r.ok)throw new Error();analysis=j||{};detections=(Array.isArray(j.objects)?j.objects:[]).filter((d:Detection)=>Array.isArray(d.box_2d)&&d.box_2d.length===4&&String(d.label||d.searchQuery||"").trim()).sort((a:Detection,b:Detection)=>Number(b.confidence||0)-Number(a.confidence||0));status.remove();ensureFrozen(card);if(!detections.length){status.textContent="No products detected";q<HTMLElement>(".hero",card)?.append(status);setTimeout(()=>status.remove(),1600);return}draw(card,detections)}catch{status.textContent="Scan unavailable";setTimeout(()=>{status.remove();clean()},1500)}}
function heartOnly(save:HTMLButtonElement){if(save.dataset.heartOnly)return;save.dataset.heartOnly="1";for(const node of [...save.childNodes])if(node.nodeType===Node.TEXT_NODE)node.textContent="";save.querySelectorAll("span").forEach(n=>n.remove());save.setAttribute("aria-label","Save")}
function decorate(card:HTMLElement){const actions=q<HTMLElement>(".actions",card),hero=q<HTMLElement>(".hero",card);if(!actions||!hero)return;const buttons=actions.querySelectorAll<HTMLButtonElement>("button"),save=buttons[1];if(!save)return;heartOnly(save);if(actions.querySelector(".masonry-scan-trigger"))return;const btn=document.createElement("button");btn.type="button";btn.className="masonry-scan-trigger";btn.setAttribute("aria-label","Scan product image");btn.title="Scan";btn.innerHTML='<span></span>';btn.onclick=e=>{e.preventDefault();e.stopPropagation();void scan(card)};save.insertAdjacentElement("afterend",btn)}
export default function MasonryProductScan(){useEffect(()=>{const sync=()=>{document.querySelectorAll<HTMLElement>(".detail").forEach(decorate);document.querySelectorAll(".masonry-card-scan").forEach(n=>n.remove());if(active&&root)ensureFrozen(root)};sync();const o=new MutationObserver(sync);o.observe(document.body,{subtree:true,childList:true});return()=>{o.disconnect();clean()}},[]);return null}
