"use client";
import {useEffect} from "react";

type Detection={id:string;label:string;searchQuery:string;alternateQueries?:string[];box_2d:number[]};
type Product={id:string;title:string;image?:string;price?:number|null;currency?:string};
let active=false,root:HTMLElement|null=null,detections:Detection[]=[];
const q=<T extends Element>(s:string,r:ParentNode=document)=>r.querySelector<T>(s);
function clean(){root?.classList.remove("masonry-scan-active");root?.querySelectorAll(".masonry-scan-overlay,.masonry-scan-status").forEach(n=>n.remove());const scan=q<HTMLElement>(".masonry-scan-results",root||document);if(scan)scan.remove();const more=root&&q<HTMLElement>(".more",root);if(more){more.classList.remove("masonry-scan-more-active");more.querySelector(".masonry-scan-inline")?.remove();more.querySelectorAll<HTMLElement>("[data-masonry-scan-original]").forEach(n=>{n.style.removeProperty("display");n.removeAttribute("data-masonry-scan-original")})}active=false;detections=[]}
function image(root:HTMLElement){return q<HTMLImageElement>(".hero img",root)}
function money(p:Product){return p.price==null?"":`${p.currency||"EUR"} ${Number(p.price).toFixed(2)}`}
function scanHost(card:HTMLElement){const more=q<HTMLElement>(".more",card);if(!more)return null;more.classList.add("masonry-scan-more-active");for(const child of Array.from(more.children) as HTMLElement[]){if(child.classList.contains("masonry-scan-inline"))continue;child.dataset.masonryScanOriginal="1";child.style.display="none"}let host=q<HTMLElement>(".masonry-scan-inline",more);if(!host){host=document.createElement("div");host.className="masonry-scan-inline";more.append(host)}return host}
async function choose(d:Detection){if(!root)return;root.querySelectorAll<HTMLElement>(".masonry-scan-dot").forEach(n=>n.classList.toggle("on",n.dataset.id===d.id));const host=scanHost(root);if(!host)return;host.replaceChildren();const shell=document.createElement("section");shell.className="masonry-scan-results";shell.innerHTML=`<small>MORE LIKE THIS</small><h2></h2><div class="masonry-scan-row"><span>Finding products…</span></div>`;(shell.querySelector("h2") as HTMLElement).textContent=d.label;host.append(shell);const terms=[d.searchQuery,d.label,...(d.alternateQueries||[])].filter(Boolean);const groups=await Promise.all(terms.map(async term=>{try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(term)}&source=all`,{cache:"no-store"}),j=await r.json();return Array.isArray(j.products)?j.products as Product[]:[]}catch{return[]}}));const seen=new Set<string>(),items=groups.flat().filter(p=>{if(!p?.id||!p.image||seen.has(p.id))return false;seen.add(p.id);return true}),row=shell.querySelector(".masonry-scan-row")!;row.replaceChildren();if(!items.length){row.textContent="No close matches yet.";return}for(const p of items){const b=document.createElement("button");b.type="button";b.innerHTML=`<img alt=""><b></b><em></em>`;(b.querySelector("img") as HTMLImageElement).src=p.image!;(b.querySelector("b") as HTMLElement).textContent=p.title;(b.querySelector("em") as HTMLElement).textContent=money(p);b.onclick=()=>window.dispatchEvent(new CustomEvent("ynot:open-product",{detail:p}));row.append(b)}}
function draw(root:HTMLElement,img:HTMLImageElement,objects:Detection[]){const hero=q<HTMLElement>(".hero",root);if(!hero)return;const overlay=document.createElement("div");overlay.className="masonry-scan-overlay";for(const d of objects){const b=d.box_2d||[];if(b.length<4)continue;const dot=document.createElement("button");dot.type="button";dot.className="masonry-scan-dot";dot.dataset.id=d.id;dot.style.left=`${((b[1]+b[3])/2)/10}%`;dot.style.top=`${((b[0]+b[2])/2)/10}%`;dot.title=d.label;dot.onclick=e=>{e.preventDefault();e.stopPropagation();void choose(d)};overlay.append(dot)}hero.append(overlay)}
async function scan(card:HTMLElement){if(active){clean();return}const img=image(card);if(!img?.src)return;root=card;active=true;card.classList.add("masonry-scan-active");const status=document.createElement("div");status.className="masonry-scan-status";status.textContent="Scanning…";q<HTMLElement>(".hero",card)?.append(status);try{const r=await fetch("/api/room/quick/analyze-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({imageUrl:img.currentSrc||img.src})}),j=await r.json();if(!r.ok)throw new Error();detections=Array.isArray(j.objects)?j.objects:[];status.remove();draw(card,img,detections)}catch{status.textContent="Scan unavailable";setTimeout(()=>{status.remove();clean()},1500)}}
function heartOnly(save:HTMLButtonElement){if(save.dataset.heartOnly)return;save.dataset.heartOnly="1";for(const node of [...save.childNodes])if(node.nodeType===Node.TEXT_NODE)node.textContent="";save.querySelectorAll("span").forEach(n=>n.remove());save.setAttribute("aria-label","Save")}
function decorate(card:HTMLElement){const actions=q<HTMLElement>(".actions",card),hero=q<HTMLElement>(".hero",card);if(!actions||!hero)return;const buttons=actions.querySelectorAll<HTMLButtonElement>("button");const save=buttons[1];if(!save)return;heartOnly(save);if(actions.querySelector(".masonry-scan-trigger"))return;const scanButton=document.createElement("button");scanButton.type="button";scanButton.className="masonry-scan-trigger";scanButton.setAttribute("aria-label","Scan product image");scanButton.title="Scan";scanButton.innerHTML='<span></span>';scanButton.onclick=e=>{e.preventDefault();e.stopPropagation();void scan(card)};save.insertAdjacentElement("afterend",scanButton)}
export default function MasonryProductScan(){useEffect(()=>{const sync=()=>document.querySelectorAll<HTMLElement>(".detail").forEach(decorate);sync();const o=new MutationObserver(sync);o.observe(document.body,{subtree:true,childList:true});return()=>{o.disconnect();clean()}},[]);return null}
