"use client";

import {useEffect,useRef} from "react";

const richMediaCache=new Map<string,Promise<string[]>>();
const norm=(v:string)=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const mediaUrl=(v:any):string=>typeof v==="string"?v:String(v?.url||v?.src||v?.video||v?.image?.url||v?.image||v?.previewImage?.url||v?.preview_image?.url||v?.originalSource?.url||"");
function collectMedia(product:any){return [...new Set<string>([mediaUrl(product?.image),...(product?.images||[]).map(mediaUrl),...(product?.variants||[]).map((v:any)=>mediaUrl(v?.image)),...(product?.videos||[]).map(mediaUrl),mediaUrl(product?.video),mediaUrl(product?.videoUrl),mediaUrl(product?.video_url),...(product?.media||[]).map(mediaUrl)].filter(Boolean))]}
function mediaList(value:string){return [...new Set(value.split("|").map(x=>x.trim()).filter(Boolean))]}
function isVideo(url:string){return /\.(mp4|webm|mov|m4v)(?:\?|$)/i.test(url)||/[?&](?:format|fm)=(?:mp4|webm)/i.test(url)}

export default function MobileProductSwipeController(){
 const activeIndex=useRef(-1);
 const gesture=useRef<{x:number;y:number;target:EventTarget|null}|null>(null);
 useEffect(()=>{
  const productNodes=()=>[...document.querySelectorAll<HTMLElement>(".lv4-product")].filter(node=>node.isConnected&&node.getBoundingClientRect().width>4&&node.getBoundingClientRect().height>4);
  const syncIndex=()=>{const list=productNodes();if(!list.length)return;const title=norm(document.querySelector<HTMLElement>(".lv4-detail h2")?.textContent||"");const index=list.findIndex(node=>norm(node.dataset.productTitle||node.getAttribute("aria-label")||node.textContent||"")===title);if(index>=0)activeIndex.current=index};
  const nextProduct=(direction:number)=>{const list=productNodes();if(list.length<2)return;syncIndex();let index=activeIndex.current;if(index<0||index>=list.length)index=0;const next=(index+direction+list.length)%list.length;activeIndex.current=next;list[next].dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true,view:window}))};
  const interactive=(target:EventTarget|null)=>target instanceof Element&&Boolean(target.closest("a,input,textarea,select,.lv4-mobile-floating-close,.ynot-complete-image-viewer,.ynot-description-back,.ynot-shopify-description,.lv4-actions,.ynot-loaded-variants,.lv4-similar-block,.lv4-direction-row"));
  const onTouchStart=(e:TouchEvent)=>{if(window.innerWidth>=900||e.touches.length!==1||!(e.target instanceof Element)||!e.target.closest(".lv4-detail")||interactive(e.target))return;const t=e.touches[0];gesture.current={x:t.clientX,y:t.clientY,target:e.target}};
  const onTouchMove=(e:TouchEvent)=>{if(window.innerWidth>=900||!gesture.current||e.touches.length!==1)return;const t=e.touches[0],dx=t.clientX-gesture.current.x,dy=t.clientY-gesture.current.y;if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy)*.75)e.preventDefault()};
  const onTouchEnd=(e:TouchEvent)=>{const g=gesture.current;gesture.current=null;if(window.innerWidth>=900||!g||!e.changedTouches.length||interactive(g.target))return;const t=e.changedTouches[0],dx=t.clientX-g.x,dy=t.clientY-g.y;if(Math.abs(dx)<28||Math.abs(dx)<Math.abs(dy)*.72)return;e.preventDefault();e.stopImmediatePropagation();nextProduct(dx<0?1:-1)};
  const onProductClick=(e:Event)=>{const node=(e.target as Element|null)?.closest<HTMLElement>(".lv4-product");if(!node)return;const index=productNodes().indexOf(node);if(index>=0)activeIndex.current=index};

  const authoritativeMedia=(gallery:HTMLElement)=>{const locked=mediaList(gallery.dataset.ynotFullMediaSignature||"");const current=mediaList(gallery.dataset.mediaSignature||"");return [...new Set([...locked,...current])]};
  const onMainImageTap=(e:MouseEvent)=>{if(window.innerWidth>=900||!(e.target instanceof HTMLImageElement))return;const shell=e.target.closest<HTMLElement>(".lv4-detail");if(!shell||!e.target.classList.contains("lv4-detail-media"))return;const gallery=shell.querySelector<HTMLElement>(".ynot-loaded-gallery");if(!gallery)return;const all=authoritativeMedia(gallery),media=all.filter(url=>!isVideo(url));if(media.length<2)return;e.preventDefault();e.stopImmediatePropagation();let index=Number(gallery.dataset.ynotTapIndex||gallery.dataset.activeMediaIndex||e.target.dataset.ynotImageIndex||0);if(!Number.isFinite(index)||index<0||index>=media.length){const current=e.target.currentSrc||e.target.src;index=Math.max(0,media.findIndex(url=>url===current))}const next=(index+1)%media.length;gallery.dataset.ynotTapIndex=String(next);gallery.dataset.activeMediaIndex=String(next);gallery.dataset.ynotFullMediaSignature=all.join("|");gallery.dataset.mediaSignature=all.join("|");e.target.src=media[next];e.target.dataset.ynotImageIndex=String(next)};

  const removeDuplicateClose=()=>{if(window.innerWidth>=900)return;document.querySelectorAll<HTMLElement>(".lv4-detail").forEach(shell=>{shell.querySelectorAll<HTMLButtonElement>("button").forEach(button=>{if(button.closest(".ynot-description-back"))return;const text=(button.textContent||"").trim(),label=(button.getAttribute("aria-label")||"").toLowerCase(),cls=String(button.className||"").toLowerCase();if(cls.includes("lv4-close")||label.includes("close product")||label.includes("close image")||label.includes("close gallery")||label.includes("close media")||/^[×✕✖x]$/i.test(text))button.remove()})})};

  const hydrateFullGallery=()=>{if(window.innerWidth>=900)return;document.querySelectorAll<HTMLElement>(".lv4-detail").forEach(shell=>{const gallery=shell.querySelector<HTMLElement>(".ynot-loaded-gallery"),title=shell.querySelector<HTMLElement>(".lv4-detailcopy h2")?.textContent?.trim()||"";if(!gallery||!title)return;const all=authoritativeMedia(gallery);if(all.length){gallery.dataset.ynotFullMediaSignature=all.join("|");gallery.dataset.mediaSignature=all.join("|")}if(gallery.dataset.ynotFullMediaRequested==="1")return;gallery.dataset.ynotFullMediaRequested="1";const cacheKey=norm(title);let job=richMediaCache.get(cacheKey);if(!job){job=(async()=>{try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(title)}&market=lumina&source=all&page=0`,{cache:"no-store"}),d=await r.json(),list=Array.isArray(d?.products)?d.products:[];const product=list.find((p:any)=>norm(p?.title)===cacheKey)||list.find((p:any)=>norm(p?.title).includes(cacheKey)||cacheKey.includes(norm(p?.title)))||list[0];if(!product)return[];let media=collectMedia(product);try{const rr=await fetch("/api/commerce/product-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(product)}),rich=await rr.json();if(rr.ok&&rich?.product)media=[...new Set([...media,...collectMedia(rich.product)])]}catch{}return media}catch{return[]}})();richMediaCache.set(cacheKey,job)}void job.then(media=>{if(!document.body.contains(gallery)||!media.length)return;const merged=[...new Set([...authoritativeMedia(gallery),...media])];gallery.dataset.ynotFullMediaSignature=merged.join("|");gallery.dataset.mediaSignature=merged.join("|");gallery.dataset.ynotTapIndex=gallery.dataset.activeMediaIndex||"0";delete gallery.dataset.ynotCompleteMarker;delete gallery.dataset.ynotMediaHydrated})})};

  let frame=0;const scan=()=>{frame=0;removeDuplicateClose();hydrateFullGallery()};const schedule=()=>{if(!frame)frame=requestAnimationFrame(scan)};
  document.addEventListener("click",onProductClick,true);document.addEventListener("click",onMainImageTap,true);document.addEventListener("touchstart",onTouchStart,{passive:true,capture:true});document.addEventListener("touchmove",onTouchMove,{passive:false,capture:true});document.addEventListener("touchend",onTouchEnd,{passive:false,capture:true});
  const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class","data-media-signature"]});schedule();
  return()=>{observer.disconnect();if(frame)cancelAnimationFrame(frame);document.removeEventListener("click",onProductClick,true);document.removeEventListener("click",onMainImageTap,true);document.removeEventListener("touchstart",onTouchStart,true);document.removeEventListener("touchmove",onTouchMove,true);document.removeEventListener("touchend",onTouchEnd,true)};
 },[]);
 return <style>{`@media(max-width:899px){.lv4-scene{visibility:visible!important;opacity:.72!important;background-image:linear-gradient(rgba(8,8,8,.08),rgba(8,8,8,.18)),var(--scene)!important;background-size:cover!important;background-position:center!important}.lv4-shell:has(.lv4-detail) .lv4-scene{opacity:.62!important}.lv4-detail .lv4-close,.lv4-detail button[aria-label="Close product"],.lv4-detail button[aria-label="Close image"],.lv4-detail button[aria-label="Close gallery"],.lv4-detail button[aria-label="Close media"]{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}.lv4-mobile-floating-close{display:grid!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important}.lv4-detail,.lv4-detail-media,.lv4-detail>.ynot-shared-media{touch-action:pan-y!important}}`}</style>;
}
