"use client";

import {useEffect,useRef} from "react";

const norm=(v:string)=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const urlOf=(v:any):string=>typeof v==="string"?v:String(v?.url||v?.src||v?.image?.url||v?.image||v?.previewImage?.url||v?.preview_image?.url||v?.originalSource?.url||"");
const uniq=(values:any[])=>[...new Set(values.map(urlOf).filter(Boolean))];
const mediaCache=new Map<string,Promise<string[]>>();
async function fullMedia(title:string){const key=norm(title);let cached=mediaCache.get(key);if(cached)return cached;const job=(async()=>{try{const params=new URLSearchParams({q:title,market:"lumina",source:"all",page:"0"});const response=await fetch(`/api/catalog?${params}`,{cache:"no-store"});const data=await response.json();const list=Array.isArray(data?.products)?data.products:[];let product=list.find((p:any)=>norm(p?.title)===key)||list.find((p:any)=>norm(p?.title).includes(key)||key.includes(norm(p?.title)))||list[0];if(!product)return[];if(String(product?.source||"").toLowerCase().includes("shopify"))try{const richResponse=await fetch("/api/commerce/product-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(product)});const rich=await richResponse.json();if(richResponse.ok&&rich?.product)product={...product,...rich.product}}catch{}return uniq([product?.image,...(product?.images||[]),...(product?.variants||[]).map((v:any)=>v?.image),...(product?.media||[])]).filter(u=>!(/\.(mp4|webm|mov|m4v)(?:\?|$)/i.test(u)))}catch{return[]}})();mediaCache.set(key,job);return job}
export default function MobileProductSwipeController(){
 const activeIndex=useRef(-1),touch=useRef<{x:number;y:number}|null>(null),swipedAt=useRef(0);
 useEffect(()=>{
  const products=()=>[...document.querySelectorAll<HTMLButtonElement>("button.lv4-product[data-product-id]")].filter(n=>n.isConnected);
  const remember=(node:HTMLButtonElement|null)=>{if(!node)return;const i=products().indexOf(node);if(i>=0)activeIndex.current=i};
  const syncFromDetail=()=>{const list=products(),detail=document.querySelector<HTMLElement>(".lv4-detail"),title=norm(detail?.querySelector<HTMLElement>("h2")?.textContent||"");if(!list.length)return;let i=list.findIndex(n=>norm(n.dataset.productTitle||"")===title);if(i<0){const fallback=detail?.querySelector<HTMLImageElement>(".lv4-detail-media")?.dataset.productFallback||"";i=list.findIndex(n=>n.dataset.productImage===fallback)}if(i>=0)activeIndex.current=i};
  const switchProduct=(direction:number)=>{const list=products();if(list.length<2)return;syncFromDetail();let i=activeIndex.current;if(i<0||i>=list.length)i=0;const next=(i+direction+list.length)%list.length;activeIndex.current=next;list[next]?.click()};
  const blocked=(target:EventTarget|null)=>target instanceof Element&&Boolean(target.closest("input,textarea,select,a,.lv4-close,.lv4-mobile-floating-close,.ynot-description-toggle,.ynot-description-back,.ynot-shopify-description,.lv4-actions,.ynot-loaded-variants,.lv4-similar-block,.lv4-direction-row,.ynot-loaded-gallery,.lv4-gallery,.ynot-complete-image-viewer,.ynot-mobile-full-gallery"));
  const onTouchStart=(event:TouchEvent)=>{if(window.innerWidth>=900||event.touches.length!==1||!(event.target instanceof Element)||!event.target.closest(".lv4-detail")||blocked(event.target)){touch.current=null;return}const t=event.touches[0];touch.current={x:t.clientX,y:t.clientY}};
  const onTouchEnd=(event:TouchEvent)=>{const start=touch.current;touch.current=null;if(window.innerWidth>=900||!start||!event.changedTouches.length)return;const t=event.changedTouches[0],dx=t.clientX-start.x,dy=t.clientY-start.y;if(Math.abs(dx)<42||Math.abs(dx)<Math.abs(dy)*1.02)return;event.preventDefault();event.stopPropagation();swipedAt.current=Date.now();switchProduct(dx<0?1:-1)};
  const onProductClick=(event:Event)=>remember((event.target as Element|null)?.closest<HTMLButtonElement>("button.lv4-product[data-product-id]")||null);
  const suppressGhostClick=(event:MouseEvent)=>{if(Date.now()-swipedAt.current>650)return;if(event.target instanceof Element&&event.target.closest(".lv4-detail")){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation()}};
  const hydrate=async(shell:HTMLElement)=>{const title=shell.querySelector<HTMLElement>("h2")?.textContent?.trim()||"";if(!title)return;const token=norm(title);if(shell.dataset.ynotFullGalleryTitle===token)return;shell.dataset.ynotFullGalleryTitle=token;const existing=uniq((shell.querySelector<HTMLElement>(".ynot-loaded-gallery")?.dataset.mediaSignature||"").split("|"));const rich=await fullMedia(title);if(!shell.isConnected||norm(shell.querySelector<HTMLElement>("h2")?.textContent||"")!==token)return;const media=uniq([...existing,...rich]);if(!media.length)return;let gallery=shell.querySelector<HTMLElement>(".ynot-loaded-gallery");if(!gallery){gallery=document.createElement("div");gallery.className="ynot-loaded-gallery";shell.querySelector(".lv4-detail-media")?.insertAdjacentElement("afterend",gallery)}if(!gallery)return;gallery.dataset.mediaSignature=media.join("|");gallery.dataset.ynotFullMediaSignature=media.join("|");gallery.replaceChildren();const main=shell.querySelector<HTMLImageElement>("img.lv4-detail-media");if(main)main.onclick=ev=>{ev.preventDefault();ev.stopPropagation();const current=main.currentSrc||main.src;const start=Math.max(0,media.findIndex(src=>src===current));window.dispatchEvent(new CustomEvent("ynot:open-full-product-gallery",{detail:{title,media,start}}))};media.slice(0,4).forEach((src,index)=>{const b=document.createElement("button");b.type="button";b.className="ynot-complete-thumb";const img=document.createElement("img");img.src=src;img.alt=`${title} view ${index+1}`;img.draggable=false;b.appendChild(img);b.onclick=ev=>{ev.preventDefault();ev.stopPropagation();if(main){main.src=src;main.dataset.ynotImageIndex=String(index)}};gallery!.appendChild(b)});if(media.length>4){const more=document.createElement("button");more.type="button";more.className="ynot-complete-thumb ynot-gallery-more";more.dataset.more=`+${media.length-4}`;const img=document.createElement("img");img.src=media[4];img.alt="More product images";more.appendChild(img);more.onclick=ev=>{ev.preventDefault();ev.stopPropagation();window.dispatchEvent(new CustomEvent("ynot:open-full-product-gallery",{detail:{title,media,start:4}}))};gallery.appendChild(more)}};
  const scan=()=>{if(window.innerWidth<900)document.querySelectorAll<HTMLElement>(".lv4-detail").forEach(shell=>void hydrate(shell))};
  const openFull=(e:Event)=>{const detail=(e as CustomEvent<{media?:string[];start?:number}>).detail||{},media=Array.isArray(detail.media)?detail.media:[];if(!media.length)return;let index=Math.min(Math.max(Number(detail.start||0),0),media.length-1);document.querySelector(".ynot-mobile-full-gallery")?.remove();const viewer=document.createElement("div");viewer.className="ynot-mobile-full-gallery";const img=document.createElement("img");const close=document.createElement("button");close.type="button";close.textContent="×";const render=()=>img.src=media[index];let x=0,y=0;viewer.ontouchstart=ev=>{if(ev.touches.length===1){x=ev.touches[0].clientX;y=ev.touches[0].clientY}};viewer.ontouchend=ev=>{if(!ev.changedTouches.length)return;const dx=ev.changedTouches[0].clientX-x,dy=ev.changedTouches[0].clientY-y;if(Math.abs(dx)>30&&Math.abs(dx)>Math.abs(dy)){index=(index+(dx<0?1:-1)+media.length)%media.length;render()}};img.onclick=()=>{index=(index+1)%media.length;render()};close.onclick=()=>viewer.remove();viewer.append(img,close);document.body.appendChild(viewer);render()};
  document.addEventListener("click",onProductClick,true);document.addEventListener("click",suppressGhostClick,true);document.addEventListener("touchstart",onTouchStart,{capture:true,passive:true});document.addEventListener("touchend",onTouchEnd,{capture:true,passive:false});window.addEventListener("ynot:open-full-product-gallery",openFull as EventListener);const observer=new MutationObserver(scan);observer.observe(document.body,{subtree:true,childList:true});scan();return()=>{observer.disconnect();document.removeEventListener("click",onProductClick,true);document.removeEventListener("click",suppressGhostClick,true);document.removeEventListener("touchstart",onTouchStart,true);document.removeEventListener("touchend",onTouchEnd,true);window.removeEventListener("ynot:open-full-product-gallery",openFull as EventListener);document.querySelector(".ynot-mobile-full-gallery")?.remove()}
 },[]);
 return <style>{`@media(max-width:899px){.lv4-detail{touch-action:pan-y!important;-webkit-user-select:none!important;user-select:none!important}.lv4-detail-media{touch-action:pan-y!important;-webkit-user-select:none!important;user-select:none!important;cursor:pointer!important;pointer-events:auto!important}.ynot-loaded-gallery{display:flex!important;justify-content:center!important;gap:7px!important;margin:8px auto!important;max-width:calc(100% - 24px)!important;overflow:hidden!important}.ynot-loaded-gallery>.ynot-complete-thumb{position:relative!important;width:58px!important;height:54px!important;flex:0 0 58px!important;padding:0!important;border-radius:13px!important;overflow:hidden!important;border:1px solid rgba(255,255,255,.24)!important;background:rgba(255,255,255,.07)!important}.ynot-loaded-gallery>.ynot-complete-thumb img{width:100%!important;height:100%!important;object-fit:cover!important}.ynot-gallery-more:after{content:attr(data-more);position:absolute;inset:0;display:grid;place-items:center;background:rgba(0,0,0,.42);color:white;font-weight:800}.ynot-mobile-full-gallery{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;background:rgba(0,0,0,.82);backdrop-filter:blur(12px);touch-action:none}.ynot-mobile-full-gallery>img{max-width:94vw;max-height:84vh;object-fit:contain;border-radius:18px}.ynot-mobile-full-gallery>button{position:absolute;top:18px;right:18px;width:32px;height:32px;border-radius:50%;border:1px solid rgba(255,255,255,.3);background:rgba(20,20,20,.55);color:white;font-size:19px}}`}</style>
}
