"use client";

import {useEffect,useRef} from "react";

const norm=(v:string)=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const urlOf=(v:any):string=>typeof v==="string"?v:String(v?.url||v?.src||v?.image?.url||v?.image||v?.previewImage?.url||v?.preview_image?.url||v?.originalSource?.url||"");
const uniq=(values:any[])=>[...new Set(values.map(urlOf).filter(Boolean))];
const mediaCache=new Map<string,Promise<string[]>>();

async function fullMedia(title:string){
 const key=norm(title);let cached=mediaCache.get(key);if(cached)return cached;
 const job=(async()=>{try{
  const params=new URLSearchParams({q:title,market:"lumina",source:"all",page:"0"});
  const response=await fetch(`/api/catalog?${params}`,{cache:"no-store"});const data=await response.json();const list=Array.isArray(data?.products)?data.products:[];
  let product=list.find((p:any)=>norm(p?.title)===key)||list.find((p:any)=>norm(p?.title).includes(key)||key.includes(norm(p?.title)))||list[0];if(!product)return[];
  if(String(product?.source||"").toLowerCase().includes("shopify"))try{const richResponse=await fetch("/api/commerce/product-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(product)});const rich=await richResponse.json();if(richResponse.ok&&rich?.product)product={...product,...rich.product}}catch{}
  return uniq([product?.image,...(product?.images||[]),...(product?.variants||[]).map((v:any)=>v?.image),...(product?.media||[])]).filter(u=>!(/\.(mp4|webm|mov|m4v)(?:\?|$)/i.test(u)));
 }catch{return[]}})();mediaCache.set(key,job);return job;
}

export default function MobileProductSwipeController(){
 const activeIndex=useRef(-1);
 useEffect(()=>{
  const products=()=>[...document.querySelectorAll<HTMLButtonElement>("button.lv4-product[data-product-id]")].filter(n=>n.isConnected);
  const remember=(node:HTMLButtonElement|null)=>{if(!node)return;const i=products().indexOf(node);if(i>=0)activeIndex.current=i};
  const syncFromDetail=()=>{const list=products(),title=norm(document.querySelector<HTMLElement>(".lv4-detail h2")?.textContent||"");if(!list.length||!title)return;const i=list.findIndex(n=>norm(n.dataset.productTitle||"")===title);if(i>=0)activeIndex.current=i};
  const switchProduct=(direction:number)=>{const list=products();if(list.length<2)return;syncFromDetail();let i=activeIndex.current;if(i<0||i>=list.length)i=0;i=(i+direction+list.length)%list.length;activeIndex.current=i;const node=list[i];node.focus({preventScroll:true});node.click()};
  const isControl=(target:EventTarget|null)=>{if(!(target instanceof Element))return true;const control=target.closest("a,input,textarea,select,.lv4-close,.lv4-mobile-floating-close,.ynot-description-toggle,.ynot-description-back,.lv4-actions,.ynot-loaded-variants,.lv4-similar-block,.lv4-direction-row,.ynot-loaded-gallery,.ynot-complete-image-viewer");return Boolean(control)};

  let sx=0,sy=0,lx=0,ly=0,tracking=false,fired=false,suppressUntil=0;
  const begin=(x:number,y:number,target:EventTarget|null)=>{if(window.innerWidth>=900||!(target instanceof Element)||!target.closest(".lv4-detail")||isControl(target))return;sx=lx=x;sy=ly=y;tracking=true;fired=false};
  const finish=(x:number,y:number,event?:Event)=>{if(!tracking||fired)return false;const dx=x-sx,dy=y-sy;if(Math.abs(dx)<24||Math.abs(dx)<=Math.abs(dy)*.65)return false;fired=true;suppressUntil=Date.now()+650;event?.preventDefault();event?.stopPropagation();switchProduct(dx<0?1:-1);return true};
  const touchStart=(e:TouchEvent)=>{if(e.touches.length===1)begin(e.touches[0].clientX,e.touches[0].clientY,e.target)};
  const touchMove=(e:TouchEvent)=>{if(!tracking||e.touches.length!==1)return;lx=e.touches[0].clientX;ly=e.touches[0].clientY;if(finish(lx,ly,e))tracking=false};
  const touchEnd=(e:TouchEvent)=>{if(tracking&&e.changedTouches.length){lx=e.changedTouches[0].clientX;ly=e.changedTouches[0].clientY;finish(lx,ly,e)}tracking=false;fired=false};
  const touchCancel=()=>{if(tracking)finish(lx,ly);tracking=false;fired=false};
  const pointerDown=(e:PointerEvent)=>{if(e.pointerType==="touch"&&!tracking)begin(e.clientX,e.clientY,e.target)};
  const pointerMove=(e:PointerEvent)=>{if(e.pointerType!=="touch"||!tracking)return;lx=e.clientX;ly=e.clientY;if(finish(lx,ly,e))tracking=false};
  const pointerUp=(e:PointerEvent)=>{if(e.pointerType==="touch"&&tracking)finish(e.clientX,e.clientY,e);tracking=false;fired=false};
  const click=(e:MouseEvent)=>{const bubble=(e.target as Element|null)?.closest<HTMLButtonElement>("button.lv4-product[data-product-id]");if(bubble){remember(bubble);return}if(Date.now()<suppressUntil&&e.target instanceof Element&&e.target.closest(".lv4-detail")){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}};

  const hydrate=async(shell:HTMLElement)=>{const title=shell.querySelector<HTMLElement>("h2")?.textContent?.trim()||"";if(!title)return;const token=norm(title);if(shell.dataset.ynotFullGalleryTitle===token)return;shell.dataset.ynotFullGalleryTitle=token;
   const existing=uniq((shell.querySelector<HTMLElement>(".ynot-loaded-gallery")?.dataset.mediaSignature||"").split("|"));const rich=await fullMedia(title);if(!shell.isConnected||norm(shell.querySelector<HTMLElement>("h2")?.textContent||"")!==token)return;const media=uniq([...existing,...rich]);if(!media.length)return;
   let gallery=shell.querySelector<HTMLElement>(".ynot-loaded-gallery");if(!gallery){gallery=document.createElement("div");gallery.className="ynot-loaded-gallery";const main=shell.querySelector(".lv4-detail-media");main?.insertAdjacentElement("afterend",gallery)}if(!gallery)return;gallery.dataset.mediaSignature=media.join("|");gallery.dataset.ynotFullMediaSignature=media.join("|");gallery.replaceChildren();
   const main=shell.querySelector<HTMLImageElement>("img.lv4-detail-media");media.slice(0,4).forEach((src,index)=>{const b=document.createElement("button");b.type="button";b.className="ynot-complete-thumb";const img=document.createElement("img");img.src=src;img.alt=`${title} view ${index+1}`;img.draggable=false;b.appendChild(img);b.addEventListener("click",ev=>{ev.preventDefault();ev.stopPropagation();if(main){main.dataset.ynotGalleryOwned="1";main.src=src;main.dataset.ynotImageIndex=String(index)}gallery!.dataset.activeMediaIndex=String(index)});gallery!.appendChild(b)});
   if(media.length>4){const more=document.createElement("button");more.type="button";more.className="ynot-complete-thumb ynot-gallery-more";more.dataset.more=`+${media.length-4}`;const img=document.createElement("img");img.src=media[4];img.alt="More product images";more.appendChild(img);more.addEventListener("click",ev=>{ev.preventDefault();ev.stopPropagation();window.dispatchEvent(new CustomEvent("ynot:open-full-product-gallery",{detail:{title,media,start:4}}))});gallery.appendChild(more)}
  };
  const scan=()=>{if(window.innerWidth>=900)return;document.querySelectorAll<HTMLElement>(".lv4-detail").forEach(shell=>{shell.querySelectorAll<HTMLButtonElement>(":scope > button.lv4-close,:scope > button[aria-label='Close product']").forEach(b=>b.remove());void hydrate(shell)})};
  const openFull=(e:Event)=>{const detail=(e as CustomEvent<{media?:string[];start?:number}>).detail||{},media=Array.isArray(detail.media)?detail.media:[];if(!media.length)return;let index=Math.min(Math.max(Number(detail.start||0),0),media.length-1);document.querySelector(".ynot-mobile-full-gallery")?.remove();const viewer=document.createElement("div");viewer.className="ynot-mobile-full-gallery";const img=document.createElement("img");const close=document.createElement("button");close.type="button";close.textContent="×";const render=()=>img.src=media[index];let x=0,y=0;viewer.addEventListener("touchstart",ev=>{if(ev.touches.length===1){x=ev.touches[0].clientX;y=ev.touches[0].clientY}},{passive:true});viewer.addEventListener("touchend",ev=>{if(!ev.changedTouches.length)return;const dx=ev.changedTouches[0].clientX-x,dy=ev.changedTouches[0].clientY-y;if(Math.abs(dx)>30&&Math.abs(dx)>Math.abs(dy)){index=(index+(dx<0?1:-1)+media.length)%media.length;render()}},{passive:true});img.addEventListener("click",()=>{index=(index+1)%media.length;render()});close.addEventListener("click",()=>viewer.remove());viewer.append(img,close);document.body.appendChild(viewer);render()};

  window.addEventListener("touchstart",touchStart,{capture:true,passive:true});window.addEventListener("touchmove",touchMove,{capture:true,passive:false});window.addEventListener("touchend",touchEnd,{capture:true,passive:false});window.addEventListener("touchcancel",touchCancel,{capture:true,passive:true});window.addEventListener("pointerdown",pointerDown,true);window.addEventListener("pointermove",pointerMove,{capture:true,passive:false});window.addEventListener("pointerup",pointerUp,true);document.addEventListener("click",click,true);window.addEventListener("ynot:open-full-product-gallery",openFull as EventListener);const observer=new MutationObserver(scan);observer.observe(document.body,{subtree:true,childList:true});scan();
  return()=>{observer.disconnect();window.removeEventListener("touchstart",touchStart,true);window.removeEventListener("touchmove",touchMove,true);window.removeEventListener("touchend",touchEnd,true);window.removeEventListener("touchcancel",touchCancel,true);window.removeEventListener("pointerdown",pointerDown,true);window.removeEventListener("pointermove",pointerMove,true);window.removeEventListener("pointerup",pointerUp,true);document.removeEventListener("click",click,true);window.removeEventListener("ynot:open-full-product-gallery",openFull as EventListener);document.querySelector(".ynot-mobile-full-gallery")?.remove()}
 },[]);
 return <style>{`@media(max-width:899px){.lv4-detail>.lv4-close,.lv4-detail>button[aria-label="Close product"]{display:none!important}.lv4-mobile-floating-close{display:grid!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important}.lv4-detail{touch-action:pan-y!important}.lv4-detail-media{touch-action:none!important;-webkit-user-select:none!important;user-select:none!important}.ynot-loaded-gallery{display:flex!important;justify-content:center!important;gap:7px!important;margin:8px auto!important;max-width:calc(100% - 24px)!important;overflow:hidden!important}.ynot-loaded-gallery>.ynot-complete-thumb{position:relative!important;width:58px!important;height:54px!important;flex:0 0 58px!important;padding:0!important;border-radius:13px!important;overflow:hidden!important;border:1px solid rgba(255,255,255,.24)!important;background:rgba(255,255,255,.07)!important}.ynot-loaded-gallery>.ynot-complete-thumb img{width:100%!important;height:100%!important;object-fit:cover!important}.ynot-gallery-more:after{content:attr(data-more);position:absolute;inset:0;display:grid;place-items:center;background:rgba(0,0,0,.42);color:white;font-weight:800}.ynot-mobile-full-gallery{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;background:rgba(0,0,0,.82);backdrop-filter:blur(12px);touch-action:none}.ynot-mobile-full-gallery>img{max-width:94vw;max-height:84vh;object-fit:contain;border-radius:18px}.ynot-mobile-full-gallery>button{position:absolute;top:18px;right:18px;width:42px;height:42px;border-radius:50%;border:1px solid rgba(255,255,255,.3);background:rgba(20,20,20,.55);color:white;font-size:26px}}`}</style>
}
