"use client";
import {useEffect} from "react";
type P={id:string;title:string;brand?:string;image?:string;price?:number|null;currency?:string;source?:string};
const clean=(s:string)=>s.replace(/\s+/g," ").trim();
const STOP=new Set(["the","and","with","for","new","pro","max","plus","from","official","edition","model"]);
function symbol(c:string){const u=c.toUpperCase();return u==="EUR"||c==="€"?"€":u==="USD"||c==="$"?"$":u==="GBP"||c==="£"?"£":u==="CHF"?"CHF ":`${u} `}
function money(p:P){return p.price==null?"":`${symbol(p.currency||"EUR")}${Number(p.price).toFixed(2)}`}
function current(){const d=document.querySelector<HTMLElement>(".detail");if(!d)return null;const title=clean(d.querySelector<HTMLElement>(".info h1")?.textContent||"");const priceText=clean(d.querySelector<HTMLElement>(".info strong")?.textContent||"");const raw=priceText.match(/[\d.,]+/)?.[0]||"";const n=Number(raw.includes(",")&&!raw.includes(".")?raw.replace(",","."):raw.replace(/,/g,""));const currency=priceText.match(/EUR|USD|GBP|CAD|AUD|CHF|€|\$|£/i)?.[0]||"EUR";return title&&Number.isFinite(n)&&n>0?{d,title,price:n,currency}:null}
function words(title:string){return title.toLowerCase().split(/[^a-z0-9]+/i).filter(x=>x.length>2&&!STOP.has(x)).slice(0,10)}
function normalized(title:string){return words(title).join(" ")}
function score(p:P,title:string,target:number){const hay=normalized(p.title||""),base=normalized(title),ws=words(title);let s=0;if(hay===base)s+=100;else if(hay.includes(base)||base.includes(hay))s+=45;for(const w of ws)if(hay.includes(w))s+=8;if(p.brand&&title.toLowerCase().includes(p.brand.toLowerCase()))s+=10;if(p.price!=null){const delta=Math.abs(Number(p.price)-target)/target;s+=Math.max(0,30-delta*180)}return s}
async function queryCatalog(query:string){try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(query)}&source=all&limit=100`,{cache:"no-store"}),j=await r.json();return Array.isArray(j.products)?j.products as P[]:[]}catch{return[]}}
async function build(){const c=current();document.querySelectorAll(".yn-price-world").forEach(n=>n.remove());if(!c)return;const related=c.d.querySelector(".related");if(!related)return;const section=document.createElement("section");section.className="yn-price-world";section.innerHTML=`<div class="yn-price-head"><small>SAME TYPE · SAME SPEND</small><h2></h2></div><div class="yn-price-scroll"><div class="yn-price-masonry"></div><div class="yn-price-sentinel"></div></div>`;(section.querySelector("h2") as HTMLElement).textContent=`What else can ${symbol(c.currency)}${Math.round(c.price)} get you?`;related.insertAdjacentElement("afterend",section);const grid=section.querySelector<HTMLElement>(".yn-price-masonry")!,sentinel=section.querySelector<HTMLElement>(".yn-price-sentinel")!;const ws=words(c.title),queries=[c.title,ws.slice(0,6).join(" "),ws.slice(0,4).join(" "),ws.slice(-4).join(" ")].filter((v,i,a)=>v.length>2&&a.indexOf(v)===i);const groups=await Promise.all(queries.map(queryCatalog));if(!section.isConnected)return;const seen=new Set<string>(),all=groups.flat().filter(p=>p?.id&&p.image&&p.price!=null&&Number(p.price)>0&&!seen.has(String(p.id))&&!!seen.add(String(p.id)));const strictLo=c.price*.90,strictHi=c.price*1.10,wideLo=c.price*.82,wideHi=c.price*1.18;const strict=all.filter(p=>Number(p.price)>=strictLo&&Number(p.price)<=strictHi).sort((a,b)=>score(b,c.title,c.price)-score(a,c.title,c.price));const wide=all.filter(p=>!strict.includes(p)&&Number(p.price)>=wideLo&&Number(p.price)<=wideHi).sort((a,b)=>score(b,c.title,c.price)-score(a,c.title,c.price));const rest=all.filter(p=>!strict.includes(p)&&!wide.includes(p)).sort((a,b)=>score(b,c.title,c.price)-score(a,c.title,c.price));const items=[...strict,...wide,...rest];let shown=0;const add=()=>{const end=Math.min(items.length,shown+16);for(;shown<end;shown++){const p=items[shown],b=document.createElement("button");b.type="button";b.className="yn-price-card";b.dataset.source=String(p.source||"");const im=document.createElement("img");im.src=p.image!;im.alt=p.title||c.title;im.loading="lazy";const t=document.createElement("b");t.textContent=p.title||c.title;const e=document.createElement("em");e.textContent=money(p);b.append(im,t,e);b.onclick=()=>window.dispatchEvent(new CustomEvent("ynot:open-product",{detail:p}));grid.append(b)}if(shown>=items.length)sentinel.style.display="none"};add();const io=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)add()},{root:section.querySelector(".yn-price-scroll"),rootMargin:"0px 900px 0px 900px"});io.observe(sentinel);(section as any)._ynPriceObserver=io}
export default function PriceMasonrySlider(){useEffect(()=>{let timer=0,key="";const sync=()=>{clearTimeout(timer);timer=window.setTimeout(()=>{const c=current(),k=c?`${c.title}|${c.price}`:"";if(k!==key){document.querySelectorAll<any>(".yn-price-world").forEach(n=>n._ynPriceObserver?.disconnect?.());key=k;void build()}},180)};sync();const mo=new MutationObserver(sync);mo.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>{clearTimeout(timer);mo.disconnect();document.querySelectorAll<any>(".yn-price-world").forEach(n=>{n._ynPriceObserver?.disconnect?.();n.remove()})}},[]);return <style jsx global>{`.yn-price-world{padding:42px 0 28px;overflow:hidden;background:#080808;color:#fff}.yn-price-head{padding:0 16px 14px}.yn-price-head small{font-size:8px;letter-spacing:.2em;opacity:.48}.yn-price-head h2{margin:5px 0 0;font-size:22px;line-height:1.05}.yn-price-scroll{position:relative;overflow-x:auto;overflow-y:hidden;overscroll-behavior-x:contain;-webkit-overflow-scrolling:touch;scrollbar-width:none;padding:0 12px 12px}.yn-price-scroll::-webkit-scrollbar{display:none}.yn-price-masonry{height:520px;display:grid;grid-auto-flow:column;grid-template-rows:repeat(2,1fr);grid-auto-columns:minmax(155px,22vw);gap:4px;width:max-content}.yn-price-card{position:relative;width:100%;height:100%;border:0;padding:0;background:#141414;color:#fff;overflow:hidden;text-align:left;border-radius:2px}.yn-price-card:nth-child(4n+2),.yn-price-card:nth-child(4n+3){height:88%;align-self:end}.yn-price-card img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.yn-price-card:after{content:"";position:absolute;inset:auto 0 0;height:38%;background:linear-gradient(transparent,rgba(0,0,0,.82))}.yn-price-card b,.yn-price-card em{position:absolute;z-index:2;left:9px;right:8px;text-shadow:0 1px 7px #000}.yn-price-card b{bottom:30px;font-size:10px;line-height:1.15;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.yn-price-card em{bottom:10px;font-size:10px;font-style:normal}.yn-price-sentinel{position:absolute;right:1px;top:0;width:2px;height:100%;pointer-events:none}@media(max-width:700px){.yn-price-world{padding-top:34px}.yn-price-head h2{font-size:18px}.yn-price-masonry{height:410px;grid-auto-columns:42vw}}`}</style>}
