"use client";
import {useEffect} from "react";
type P={id:string;title:string;brand?:string;image?:string;price?:number|null;currency?:string;source?:string};
const clean=(s:string)=>s.replace(/\s+/g," ").trim();const STOP=new Set(["the","and","with","for","new","pro","max","plus","from","official","edition","model"]);
function symbol(c:string){const u=c.toUpperCase();return u==="EUR"||c==="€"?"€":u==="USD"||c==="$"?"$":u==="GBP"||c==="£"?"£":u==="CHF"?"CHF ":`${u} `}function money(p:P){return p.price==null?"":`${symbol(p.currency||"EUR")}${Number(p.price).toFixed(2)}`}
function priceFrom(text:string){const hits=[...text.matchAll(/(?:EUR|USD|GBP|CAD|AUD|CHF|€|\$|£)\s*([\d.,]+)|([\d.,]+)\s*(?:EUR|USD|GBP|CAD|AUD|CHF|€|\$|£)/gi)];for(const m of hits){const raw=m[1]||m[2]||"",n=Number(raw.includes(",")&&!raw.includes(".")?raw.replace(",","."):raw.replace(/,/g,""));if(Number.isFinite(n)&&n>0)return n}return null}
function current(){const d=document.querySelector<HTMLElement>(".lv4-detail,.detail");if(!d)return null;const title=clean(d.querySelector<HTMLElement>(".lv4-detailcopy h1,.lv4-detail h1,.info h1,h1")?.textContent||"");const text=clean(d.innerText||"");const price=priceFrom(text);const currency=text.match(/EUR|USD|GBP|CAD|AUD|CHF|€|\$|£/i)?.[0]||"EUR";return title&&price?{d,title,price,currency}:null}
function words(title:string){return title.toLowerCase().split(/[^a-z0-9]+/i).filter(x=>x.length>2&&!STOP.has(x)).slice(0,10)}function normalized(title:string){return words(title).join(" ")}function score(p:P,title:string,target:number){const hay=normalized(p.title||""),base=normalized(title),ws=words(title);let s=0;if(hay===base)s+=100;else if(hay.includes(base)||base.includes(hay))s+=45;for(const w of ws)if(hay.includes(w))s+=8;if(p.brand&&title.toLowerCase().includes(p.brand.toLowerCase()))s+=10;if(p.price!=null)s+=Math.max(0,30-Math.abs(Number(p.price)-target)/target*180);return s}
async function queryCatalog(query:string){try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(query)}&source=all&limit=100`,{cache:"no-store"}),j=await r.json();return Array.isArray(j.products)?j.products as P[]:[]}catch{return[]}}
async function build(c:NonNullable<ReturnType<typeof current>>){document.querySelectorAll(".yn-price-world").forEach(n=>n.remove());const section=document.createElement("section");section.className="yn-price-world";section.innerHTML='<div class="yn-price-head"><small>SAME TYPE · SAME SPEND</small><h2></h2></div><div class="yn-price-scroll"><div class="yn-price-masonry"></div></div>';(section.querySelector("h2") as HTMLElement).textContent=`What else can ${symbol(c.currency)}${Math.round(c.price)} get you?`;
 const similar=c.d.querySelector<HTMLElement>(".lv4-similar-slider,.related,.lv4-related");const more=Array.from(c.d.querySelectorAll<HTMLElement>("h1,h2,h3,div,section")).find(n=>/^more like this$/i.test(clean(n.textContent||"")));
 const anchor=(similar?.parentElement||more?.parentElement||c.d.querySelector<HTMLElement>(".lv4-detailcopy")||c.d);anchor.append(section);
 const grid=section.querySelector<HTMLElement>(".yn-price-masonry")!,ws=words(c.title),queries=[c.title,ws.slice(0,6).join(" "),ws.slice(0,4).join(" ")].filter((v,i,a)=>v.length>2&&a.indexOf(v)===i),groups=await Promise.all(queries.map(queryCatalog));if(!section.isConnected)return;const seen=new Set<string>(),all=groups.flat().filter(p=>p?.id&&p.image&&p.price!=null&&Number(p.price)>0&&!seen.has(String(p.id))&&!!seen.add(String(p.id)));const lo=c.price*.82,hi=c.price*1.18,items=all.filter(p=>Number(p.price)>=lo&&Number(p.price)<=hi).sort((a,b)=>score(b,c.title,c.price)-score(a,c.title,c.price));for(const p of items.slice(0,60)){const b=document.createElement("button");b.type="button";b.className="yn-price-card";const im=document.createElement("img");im.src=p.image!;im.alt=p.title||c.title;im.loading="lazy";const t=document.createElement("b");t.textContent=p.title||c.title;const e=document.createElement("em");e.textContent=money(p);b.append(im,t,e);b.onclick=()=>window.dispatchEvent(new CustomEvent("ynot:open-product",{detail:p}));grid.append(b)}if(!items.length){const empty=document.createElement("div");empty.className="yn-price-empty";empty.textContent="Finding products around this price…";grid.append(empty)}}
export default function PriceMasonrySlider(){useEffect(()=>{let timer=0,key="",building="";const sync=()=>{clearTimeout(timer);timer=window.setTimeout(()=>{const c=current();if(!c){key="";building="";document.querySelectorAll(".yn-price-world").forEach(n=>n.remove());return}const k=`${c.title}|${c.price}`;if(k===key||k===building)return;building=k;void build(c).finally(()=>{key=k;building=""})},120)};sync();const mo=new MutationObserver(sync);mo.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["class"]});const interval=window.setInterval(sync,700);return()=>{clearTimeout(timer);clearInterval(interval);mo.disconnect();document.querySelectorAll(".yn-price-world").forEach(n=>n.remove())}},[]);return <style jsx global>{`.yn-price-world{display:block!important;width:100%!important;min-height:180px!important;padding:34px 0 30px!important;background:#080808!important;color:#fff!important;overflow:hidden!important;clear:both!important}.yn-price-head{display:block!important;padding:0 16px 14px!important}.yn-price-head small{display:block!important;font-size:8px!important;letter-spacing:.2em!important;opacity:.48!important}.yn-price-head h2{display:block!important;margin:5px 0 0!important;font-size:20px!important;line-height:1.08!important;color:#fff!important}.yn-price-scroll{display:block!important;overflow-x:auto!important;overflow-y:hidden!important;-webkit-overflow-scrolling:touch;scrollbar-width:none;padding:0 12px 12px!important}.yn-price-scroll::-webkit-scrollbar{display:none}.yn-price-masonry{display:grid!important;height:410px!important;grid-auto-flow:column!important;grid-template-rows:repeat(2,1fr)!important;grid-auto-columns:42vw!important;gap:4px!important;width:max-content!important;min-width:100%!important}.yn-price-card{position:relative!important;display:block!important;width:100%!important;height:100%!important;border:0!important;padding:0!important;background:#141414!important;color:#fff!important;overflow:hidden!important;text-align:left!important}.yn-price-card img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;object-fit:cover!important}.yn-price-card:after{content:"";position:absolute;left:0;right:0;bottom:0;height:38%;background:linear-gradient(transparent,rgba(0,0,0,.84))}.yn-price-card b,.yn-price-card em{position:absolute;z-index:2;left:9px;right:8px;color:#fff;text-shadow:0 1px 7px #000}.yn-price-card b{bottom:30px;font-size:10px;line-height:1.15;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.yn-price-card em{bottom:10px;font-size:10px;font-style:normal}.yn-price-empty{width:80vw;padding:28px 16px;color:#888;font-size:11px}@media(min-width:701px){.yn-price-masonry{height:520px!important;grid-auto-columns:minmax(155px,22vw)!important}}`}</style>}
