"use client";
import {useEffect} from "react";
type P={id:string;title:string;brand?:string;image?:string;price?:number|null;currency?:string};
const clean=(s:string)=>s.replace(/\s+/g," ").trim();
function money(p:P){return p.price==null?"":`${p.currency||"EUR"} ${Number(p.price).toFixed(2)}`}
function current(){const d=document.querySelector<HTMLElement>(".detail");if(!d)return null;const title=clean(d.querySelector<HTMLElement>(".info h1")?.textContent||"");const priceText=clean(d.querySelector<HTMLElement>(".info strong")?.textContent||"");const n=Number((priceText.match(/[\d.,]+/)?.[0]||"").replace(/,/g,""));const currency=priceText.match(/EUR|USD|GBP|CAD|AUD|CHF|€|\$|£/i)?.[0]||"EUR";return title&&Number.isFinite(n)&&n>0?{d,title,price:n,currency}:null}
function words(title:string){return title.split(/[^a-z0-9]+/i).filter(x=>x.length>2&&!/^(the|and|with|for|new|pro|max|plus|from|official)$/i.test(x)).slice(0,7)}
function score(p:P,title:string,target:number){const hay=(p.title||"").toLowerCase(),ws=words(title.toLowerCase());let s=ws.reduce((n,w)=>n+(hay.includes(w)?5:0),0);if(p.price!=null)s+=Math.max(0,8-Math.abs(Number(p.price)-target)/Math.max(target*.03,1));return s}
async function build(){const c=current();document.querySelectorAll(".yn-price-world").forEach(n=>n.remove());if(!c)return;const related=c.d.querySelector(".related");if(!related)return;const section=document.createElement("section");section.className="yn-price-world";section.innerHTML=`<div class="yn-price-head"><small>DISCOVER BY PRICE</small><h2></h2></div><div class="yn-price-scroll"><div class="yn-price-masonry"></div></div>`;(section.querySelector("h2") as HTMLElement).textContent=`What else can ${c.currency} ${c.price.toFixed(2)} get you?`;related.insertAdjacentElement("afterend",section);const grid=section.querySelector<HTMLElement>(".yn-price-masonry")!;const queries=[c.title,words(c.title).slice(0,4).join(" "),words(c.title).slice(-3).join(" ")].filter(Boolean);const groups=await Promise.all(queries.map(async x=>{try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(x)}&source=all&limit=80`,{cache:"no-store"}),j=await r.json();return Array.isArray(j.products)?j.products as P[]:[]}catch{return[]}}));if(!section.isConnected)return;const seen=new Set<string>(),lo=c.price*.88,hi=c.price*1.12;let items=groups.flat().filter(p=>p?.id&&p.image&&p.price!=null&&Number(p.price)>=lo&&Number(p.price)<=hi&&!seen.has(String(p.id))&&!!seen.add(String(p.id))).sort((a,b)=>score(b,c.title,c.price)-score(a,c.title,c.price));if(items.length<10){const all=groups.flat().filter(p=>p?.id&&p.image&&p.price!=null&&!seen.has(String(p.id))&&!!seen.add(String(p.id))).sort((a,b)=>score(b,c.title,c.price)-score(a,c.title,c.price));items=items.concat(all.slice(0,30-items.length))}for(const p of items.slice(0,40)){const b=document.createElement("button");b.type="button";b.className="yn-price-card";const im=document.createElement("img");im.src=p.image!;im.alt=p.title;im.loading="lazy";const t=document.createElement("b");t.textContent=p.title;const e=document.createElement("em");e.textContent=money(p);b.append(im,t,e);b.onclick=()=>window.dispatchEvent(new CustomEvent("ynot:open-product",{detail:p}));grid.append(b)}}
export default function PriceMasonrySlider(){useEffect(()=>{let timer=0,key="";const sync=()=>{clearTimeout(timer);timer=window.setTimeout(()=>{const c=current(),k=c?`${c.title}|${c.price}`:"";if(k!==key){key=k;void build()}},180)};sync();const mo=new MutationObserver(sync);mo.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>{clearTimeout(timer);mo.disconnect();document.querySelectorAll(".yn-price-world").forEach(n=>n.remove())}},[]);return <style jsx global>{`.yn-price-world{padding:42px 0 28px;overflow:hidden;background:#080808;color:#fff}.yn-price-head{padding:0 16px 14px}.yn-price-head small{font-size:8px;letter-spacing:.2em;opacity:.48}.yn-price-head h2{margin:5px 0 0;font-size:22px;line-height:1.05}.yn-price-scroll{overflow-x:auto;overflow-y:hidden;overscroll-behavior-x:contain;-webkit-overflow-scrolling:touch;scrollbar-width:none;padding:0 12px 12px}.yn-price-scroll::-webkit-scrollbar{display:none}.yn-price-masonry{height:520px;display:grid;grid-auto-flow:column;grid-template-rows:repeat(2,1fr);grid-auto-columns:minmax(155px,22vw);gap:4px;width:max-content}.yn-price-card{position:relative;width:100%;height:100%;border:0;padding:0;background:#141414;color:#fff;overflow:hidden;text-align:left;border-radius:2px}.yn-price-card:nth-child(4n+2),.yn-price-card:nth-child(4n+3){height:88%;align-self:end}.yn-price-card img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.yn-price-card:after{content:"";position:absolute;inset:auto 0 0;height:38%;background:linear-gradient(transparent,rgba(0,0,0,.82))}.yn-price-card b,.yn-price-card em{position:absolute;z-index:2;left:9px;right:8px;text-shadow:0 1px 7px #000}.yn-price-card b{bottom:30px;font-size:10px;line-height:1.15;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.yn-price-card em{bottom:10px;font-size:10px;font-style:normal}@media(max-width:700px){.yn-price-world{padding-top:34px}.yn-price-head h2{font-size:18px}.yn-price-masonry{height:410px;grid-auto-columns:42vw}}`}</style>}
