"use client";
import {useEffect} from "react";
import PriceMasonrySlider from "./PriceMasonrySlider";
import ProductPackageDetails from "./ProductPackageDetails";

type Detection={id:string;label:string;searchQuery:string;alternateQueries?:string[];box_2d:number[]};
type Product={id:string;title:string;brand?:string;image?:string;price?:number|null;currency?:string};
const state={active:false,card:null as HTMLElement|null,selected:"",detections:[] as Detection[],results:[] as Product[]};
function mainImage(card:HTMLElement){return card.querySelector<HTMLImageElement>(".lv4-media img,.ynot-product-media img,img.lv4-main-image,img.ynot-shared-media,.lv4-detail-media img,.lv4-detail-image img,.lv4-detail-gallery img,.lv4-detailcopy img,img")}
function resultHost(card:HTMLElement){return card.querySelector<HTMLElement>(".lv4-similar-slider")?.parentElement||card.querySelector<HTMLElement>(".lv4-detailcopy")||card}
function clear(card?:HTMLElement|null){const c=card||state.card;c?.classList.remove("ynot-scan-active");c?.querySelectorAll(".ynot-scan-overlay,.ynot-scan-results,.ynot-scan-status").forEach(x=>x.remove());state.active=false;state.card=null;state.selected="";state.detections=[];state.results=[]}
async function imageFile(url:string){const r=await fetch(url,{cache:"force-cache"});if(!r.ok)throw new Error("image");const b=await r.blob();return new File([b],"product-image",{type:b.type||"image/jpeg"})}
function dots(card:HTMLElement,image:HTMLImageElement,detections:Detection[]){card.querySelector(".ynot-scan-overlay")?.remove();const wrap=document.createElement("div");wrap.className="ynot-scan-overlay";const ir=image.getBoundingClientRect(),cr=card.getBoundingClientRect();wrap.style.left=`${ir.left-cr.left}px`;wrap.style.top=`${ir.top-cr.top}px`;wrap.style.width=`${ir.width}px`;wrap.style.height=`${ir.height}px`;for(const d of detections){const b=d.box_2d||[];if(b.length<4)continue;const button=document.createElement("button");button.type="button";button.className="ynot-scan-dot";button.title=d.label;button.style.left=`${((b[1]+b[3])/2)/10}%`;button.style.top=`${((b[0]+b[2])/2)/10}%`;button.onclick=e=>{e.preventDefault();e.stopPropagation();void choose(card,d)};wrap.append(button)}card.append(wrap)}
function renderResults(card:HTMLElement,label:string,products:Product[],loading=false){card.querySelector(".ynot-scan-results")?.remove();const host=resultHost(card),box=document.createElement("section");box.className="ynot-scan-results";const head=document.createElement("div");head.className="ynot-scan-results-head";head.textContent=loading?`Finding ${label}…`:`${label} · ${products.length} matches`;box.append(head);const row=document.createElement("div");row.className="ynot-scan-result-row";for(const p of products.slice(0,12)){if(!p.image)continue;const button=document.createElement("button");button.type="button";button.className="ynot-scan-result";const img=document.createElement("img");img.src=p.image;img.alt=p.title||label;img.loading="lazy";const text=document.createElement("span");text.textContent=p.title||label;button.append(img,text);button.dataset.ynotProduct=JSON.stringify(p);let opened=0;const open=(e:Event)=>{e.preventDefault();e.stopPropagation();const now=Date.now();if(now-opened<450)return;opened=now;window.dispatchEvent(new CustomEvent("ynot:open-product",{detail:p}))};button.addEventListener("pointerup",open);button.addEventListener("click",open);row.append(button)}box.append(row);host.append(box)}
async function choose(card:HTMLElement,d:Detection){state.selected=d.id;card.querySelectorAll<HTMLElement>(".ynot-scan-dot").forEach(x=>x.classList.toggle("selected",x.title===d.label));renderResults(card,d.label,[],true);const terms=[d.searchQuery,d.label,...(d.alternateQueries||[])].filter(Boolean).slice(0,4);const groups=await Promise.all(terms.map(async q=>{try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(q)}&source=all`,{cache:"no-store"});const x=await r.json();return Array.isArray(x.products)?x.products:[]}catch{return[]}}));const seen=new Set<string>(),products=groups.flat().filter((p:Product)=>{if(!p?.id||!p.image||seen.has(p.id))return false;seen.add(p.id);return true});state.results=products;renderResults(card,d.label,products)}
async function scan(card:HTMLElement){if(state.active&&state.card===card){clear(card);return}clear(state.card);const image=mainImage(card);if(!image?.src)return;state.active=true;state.card=card;card.classList.add("ynot-scan-active");const status=document.createElement("div");status.className="ynot-scan-status";status.textContent="Scanning…";card.append(status);try{const file=await imageFile(image.currentSrc||image.src),fd=new FormData();fd.append("image",file);const r=await fetch("/api/room/quick/analyze",{method:"POST",body:fd}),data=await r.json();if(!r.ok)throw new Error(data?.error||"scan");state.detections=Array.isArray(data.objects)?data.objects:[];status.remove();dots(card,image,state.detections)}catch{status.textContent="Scan unavailable";setTimeout(()=>status.remove(),1800);clear(card)}}
function decorate(card:HTMLElement){const actions=card.querySelector<HTMLElement>(".lv4-actions");const save=actions?.querySelector<HTMLElement>(".lv4-save-action,.lv4-save-next-to-bag,[aria-label*='save' i]");if(!actions||!save)return;let button=actions.querySelector<HTMLButtonElement>(".ynot-product-scan");if(!button){button=document.createElement("button");button.type="button";button.className="ynot-product-scan";button.setAttribute("aria-label","Scan product image");button.title="Scan";button.innerHTML='<i aria-hidden="true"></i><span>Scan</span>';button.onclick=e=>{e.preventDefault();e.stopPropagation();void scan(card)}}if(button.parentElement!==actions||button.previousElementSibling!==save)save.insertAdjacentElement("afterend",button)}
function decorateMasonryAbout(card:HTMLElement){if(card.querySelector(".masonry-about-product"))return;const actions=card.querySelector<HTMLElement>(".actions");const more=card.querySelector<HTMLElement>(".more");if(!actions||!more)return;const title=(card.querySelector<HTMLElement>(".info h1,.info h2,h1,h2")?.textContent||"Product").trim();const description=(card.querySelector<HTMLElement>(".info p,.description")?.textContent||"").trim();const urls=[...card.querySelectorAll<HTMLImageElement>(".hero img,.gallery img")].map(img=>img.currentSrc||img.src).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).slice(1,4);const section=document.createElement("section");section.className="masonry-about-product";const images=document.createElement("div");images.className="masonry-about-images";urls.forEach((src,index)=>{const figure=document.createElement("figure");const img=document.createElement("img");img.src=src;img.alt=`${title} detail ${index+1}`;const caption=document.createElement("figcaption");caption.textContent=`${title} detail`;figure.append(img,caption);images.append(figure)});const head=document.createElement("div");head.className="masonry-about-head";head.innerHTML="<small>DETAILS</small><h2>About this product</h2>";const copy=document.createElement("p");copy.textContent=description||`More details about ${title}.`;section.append(images,head,copy);more.parentElement?.insertBefore(section,more)}
export default function ProductImageScan(){useEffect(()=>{let raf=0;const sync=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{document.querySelectorAll<HTMLElement>(".lv4-detail").forEach(decorate);document.querySelectorAll<HTMLElement>(".detail").forEach(decorateMasonryAbout)})};const observer=new MutationObserver(sync);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});sync();const interval=window.setInterval(sync,500);const close=(e:KeyboardEvent)=>{if(e.key==="Escape"&&state.active)clear()};document.addEventListener("keydown",close);return()=>{observer.disconnect();window.clearInterval(interval);cancelAnimationFrame(raf);document.removeEventListener("keydown",close);clear()}},[]);return <><PriceMasonrySlider/><ProductPackageDetails/></>}
