"use client";

import {useEffect} from "react";

type SavedItem={id:string;title:string;brand?:string;price?:number|null;currency?:string;image?:string;images?:string[];url?:string;source?:string;section?:string;sections?:string[];badge?:string;note?:string;description?:string;variants?:unknown[]};
const SAVED_KEY="ynot-saved-items";
function cleanTitle(s:string){return String(s||"").trim().toLowerCase()}
function parseMoney(text:string){const n=Number(String(text||"").replace(/[^0-9,.-]/g,"").replace(",","."));return Number.isFinite(n)?n:null}
function readSaved():SavedItem[]{try{const v=JSON.parse(localStorage.getItem(SAVED_KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function saveItem(item:SavedItem){const list=readSaved();const exists=list.some(x=>x.id===item.id||cleanTitle(x.title)===cleanTitle(item.title));const next=exists?list.filter(x=>x.id!==item.id&&cleanTitle(x.title)!==cleanTitle(item.title)):[{...item,section:item.section||"Saved",sections:item.sections||["Saved"],badge:item.badge||"Saved",note:item.note||"Saved from World"},...list];localStorage.setItem(SAVED_KEY,JSON.stringify(next));localStorage.setItem("ynot-saved-products",JSON.stringify(next.map(x=>x.id)));window.dispatchEvent(new Event("ynot:saves-changed"));return !exists}
function clearInjected(root:Element){root.querySelectorAll(".ynot-loaded-gallery,.ynot-loaded-variants,.ynot-rich-gallery,.ynot-rich-variants,.ynot-description-back").forEach(x=>x.remove());root.querySelectorAll<HTMLElement>("[data-ynot-hydrated]").forEach(x=>delete x.dataset.ynotHydrated)}
function worldSaveButton(root:HTMLElement){if(root.querySelector(".ynot-world-save"))return;const detail=root.closest(".lv4-detail") as HTMLElement|null;if(!detail)return;const title=root.querySelector("h2")?.textContent?.trim()||"";if(!title)return;const b=document.createElement("button");b.type="button";b.className="ynot-world-save";b.setAttribute("aria-label","Save product");b.textContent="♡";b.onclick=e=>{e.preventDefault();e.stopPropagation();const img=detail.querySelector<HTMLImageElement>(":scope > img")?.src||"";const price=parseMoney(root.querySelector("strong")?.textContent||"");const brand=root.querySelector(".lv4-product-brand")?.textContent?.trim()||undefined;const source=root.querySelector(".lv4-product-source")?.textContent?.trim()||"World";const link=detail.querySelector<HTMLAnchorElement>(".lv4-actions a")?.href||undefined;const active=saveItem({id:`world:${cleanTitle(title)}`,title,brand,price,image:img,url:link,source});b.textContent=active?"♥":"♡";b.classList.toggle("active",active)};root.appendChild(b)}
function sync(){document.querySelectorAll<HTMLElement>(".lv4-detailcopy").forEach(worldSaveButton);const ynot=document.querySelector<HTMLElement>(".ynot-selected");if(ynot){const title=ynot.querySelector("h3")?.textContent?.trim()||"";if(title&&ynot.dataset.productTitle!==title){clearInjected(ynot);delete ynot.dataset.ynotVariantId;ynot.dataset.productTitle=title}}
 const story=document.querySelector<HTMLElement>(".ynot-story");if(story){const title=story.querySelector("h2")?.textContent?.trim()||"";if(title&&story.dataset.productTitle!==title){clearInjected(story);delete story.dataset.ynotVariantId;story.dataset.productTitle=title}}}
export default function ProductCardSync():null{useEffect(()=>{let raf=0;const run=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(sync)};const observer=new MutationObserver(run);observer.observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener("click",run,true);run();return()=>{observer.disconnect();cancelAnimationFrame(raf);document.removeEventListener("click",run,true)}},[]);return null}
