"use client";

import {useEffect} from "react";

const mediaCache=new Map<string,Promise<string[]>>();
const isVideo=(url:string)=>/\.(mp4|webm|mov|m4v)(?:\?|$)/i.test(url)||/[?&](?:format|fm)=(?:mp4|webm)/i.test(url);
const normalize=(value:string)=>String(value||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const mediaUrl=(value:any):string=>typeof value==="string"?value:String(value?.url||value?.src||value?.video||value?.image?.url||value?.image||value?.previewImage?.url||value?.preview_image?.url||value?.originalSource?.url||"");
function uniqueMedia(signature:string){return [...new Set(signature.split("|").map(x=>x.trim()).filter(Boolean))]}
function collectProductMedia(product:any,current:string[]){return [...new Set<string>([
 ...current,
 mediaUrl(product?.image),
 ...(product?.images||[]).map(mediaUrl),
 ...(product?.variants||[]).map((v:any)=>mediaUrl(v?.image)),
 ...(product?.videos||[]).map(mediaUrl),
 mediaUrl(product?.video),mediaUrl(product?.videoUrl),mediaUrl(product?.video_url),
 ...(product?.media||[]).map(mediaUrl)
].filter(Boolean))]}
async function enrichMedia(gallery:HTMLElement,current:string[]){
 const shell=gallery.closest<HTMLElement>(".lv4-detail"),title=shell?.querySelector<HTMLElement>(".lv4-detailcopy h2")?.textContent?.trim()||"";
 if(!title||gallery.dataset.ynotMediaHydrated==="1")return current;
 gallery.dataset.ynotMediaHydrated="1";const key=normalize(title);
 let job=mediaCache.get(key);if(!job){job=(async()=>{try{
  const params=new URLSearchParams({q:title,market:"lumina",source:"all",page:"0"}),response=await fetch(`/api/catalog?${params}`,{cache:"no-store"}),data=await response.json(),list=Array.isArray(data?.products)?data.products:[];
  const product=list.find((p:any)=>normalize(p?.title)===key)||list.find((p:any)=>normalize(p?.title).includes(key)||key.includes(normalize(p?.title)))||list[0];
  return product?collectProductMedia(product,[]):[];
 }catch{return[]}})();mediaCache.set(key,job)}
 const rich=await job,merged=[...new Set([...current,...rich])];
 if(document.body.contains(gallery)&&merged.length>current.length){gallery.dataset.mediaSignature=merged.join("|");delete gallery.dataset.ynotCompleteMarker}
 return merged
}
function thumb(media:string){
 if(isVideo(media)){const video=document.createElement("video");video.src=media;video.muted=true;video.playsInline=true;video.preload="metadata";video.className="ynot-media-thumb-video";return video}
 const image=document.createElement("img");image.src=media;image.alt="";image.draggable=false;return image
}
function setMainMedia(gallery:HTMLElement,media:string[],index:number){
 const shell=gallery.closest<HTMLElement>(".lv4-detail"),main=shell?.querySelector<HTMLImageElement>(":scope > img");if(!shell||!main||!media.length)return;
 const next=Math.max(0,Math.min(index,media.length-1)),url=media[next];let video=shell.querySelector<HTMLVideoElement>(":scope > .ynot-main-product-video");
 if(isVideo(url)){
  if(!video){video=document.createElement("video");video.className="ynot-main-product-video";video.controls=true;video.playsInline=true;main.insertAdjacentElement("afterend",video)}
  if(video.src!==url)video.src=url;video.style.display="block";main.style.visibility="hidden";shell.classList.add("ynot-main-is-video");video.play().catch(()=>{video!.muted=true;void video!.play().catch(()=>{})})
 }else{
  if(video){video.pause();video.style.display="none"}shell.classList.remove("ynot-main-is-video");main.style.visibility="visible";main.src=url
 }
 main.dataset.ynotImageIndex=String(next);gallery.dataset.activeMediaIndex=String(next);
 gallery.querySelectorAll<HTMLElement>(".ynot-complete-thumb").forEach(node=>node.classList.toggle("active",Number(node.dataset.mediaIndex)===next&&!node.classList.contains("ynot-gallery-more")))
}
function openViewer(media:string[],startIndex:number){
 document.querySelector(".ynot-complete-image-viewer")?.remove();if(!media.length)return;
 let index=Math.max(0,Math.min(startIndex,media.length-1)),startX:number|null=null,startY:number|null=null,dragged=false;
 const viewer=document.createElement("section");viewer.className="ynot-complete-image-viewer";viewer.tabIndex=0;viewer.setAttribute("aria-label","Product media popup");
 const frame=document.createElement("div");frame.className="ynot-complete-image-frame";
 const stage=document.createElement("div");stage.className="ynot-complete-media-stage";
 const close=document.createElement("button");close.type="button";close.className="ynot-complete-image-close";close.textContent="×";close.setAttribute("aria-label","Close media");
 const render=()=>{stage.replaceChildren();const url=media[index];if(isVideo(url)){const video=document.createElement("video");video.src=url;video.controls=true;video.playsInline=true;video.autoplay=true;video.className="ynot-complete-media";stage.appendChild(video);void video.play().catch(()=>{})}else{const image=document.createElement("img");image.src=url;image.alt="Product view";image.draggable=false;image.className="ynot-complete-media";image.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();if(dragged){dragged=false;return}move(1)});stage.appendChild(image)}};
 const move=(delta:number)=>{index=(index+delta+media.length)%media.length;render()};
 close.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();viewer.remove()});viewer.addEventListener("click",e=>{if(e.target===viewer)viewer.remove()});frame.addEventListener("click",e=>e.stopPropagation());
 frame.addEventListener("pointerdown",e=>{if((e.target as Element).closest("button,video"))return;startX=e.clientX;startY=e.clientY;dragged=false;frame.setPointerCapture?.(e.pointerId)});
 frame.addEventListener("pointermove",e=>{if(startX===null||startY===null)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy)){dragged=true;e.preventDefault()}});
 frame.addEventListener("pointerup",e=>{if(startX===null||startY===null)return;const dx=e.clientX-startX,dy=e.clientY-startY;startX=null;startY=null;if(Math.abs(dx)>38&&Math.abs(dx)>Math.abs(dy)){dragged=true;move(dx<0?1:-1)}else dragged=false});frame.addEventListener("pointercancel",()=>{startX=null;startY=null;dragged=false});
 viewer.addEventListener("keydown",e=>{if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1);if(e.key==="Escape")viewer.remove()});frame.append(stage,close);viewer.appendChild(frame);document.body.appendChild(viewer);render();requestAnimationFrame(()=>viewer.focus())
}
function bindMainTap(gallery:HTMLElement){
 const shell=gallery.closest<HTMLElement>(".lv4-detail"),main=shell?.querySelector<HTMLImageElement>(":scope > img");if(!main||main.dataset.ynotTapThroughBound==="1")return;main.dataset.ynotTapThroughBound="1";
 main.addEventListener("click",event=>{if(window.innerWidth>=900)return;const current=shell?.querySelector<HTMLElement>(".ynot-loaded-gallery"),media=uniqueMedia(current?.dataset.mediaSignature||"");if(!current||media.length<2)return;event.preventDefault();event.stopPropagation();const stored=Number(current.dataset.activeMediaIndex||main.dataset.ynotImageIndex||0);setMainMedia(current,media,(stored+1)%media.length)})
}
function rebuildGallery(gallery:HTMLElement){
 const signature=gallery.dataset.mediaSignature||"";if(!signature)return;const media=uniqueMedia(signature);if(!media.length)return;const marker=`${signature}:media-v8`;if(gallery.dataset.ynotCompleteMarker===marker){bindMainTap(gallery);return}gallery.dataset.ynotCompleteMarker=marker;gallery.replaceChildren();
 const hasMore=media.length>4,normalCount=hasMore?3:Math.min(media.length,4);
 for(let index=0;index<normalCount;index++){const button=document.createElement("button");button.type="button";button.className="ynot-complete-thumb";button.dataset.mediaIndex=String(index);button.setAttribute("aria-label",`Show product media ${index+1}`);button.appendChild(thumb(media[index]));button.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();setMainMedia(gallery,media,index)});gallery.appendChild(button)}
 if(hasMore){const index=3,button=document.createElement("button");button.type="button";button.className="ynot-complete-thumb ynot-gallery-more";button.dataset.mediaIndex=String(index);button.dataset.more=`+${media.length-normalCount}`;button.setAttribute("aria-label",`Open all ${media.length} product media`);button.appendChild(thumb(media[index]));button.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();openViewer(media,index)});gallery.appendChild(button)}
 const shell=gallery.closest<HTMLElement>(".lv4-detail"),main=shell?.querySelector<HTMLImageElement>(":scope > img");if(main){const matched=media.findIndex(src=>src===main.currentSrc||src===main.src),active=matched>=0?matched:0;main.dataset.ynotImageIndex=String(active);gallery.dataset.activeMediaIndex=String(active)}bindMainTap(gallery);void enrichMedia(gallery,media).then(rich=>{if(rich.length!==media.length&&document.body.contains(gallery))rebuildGallery(gallery)})
}
function removeMobileSliderChrome(){if(window.innerWidth>=900)return;document.querySelectorAll<HTMLElement>(".lv4-detail").forEach(shell=>{shell.querySelectorAll<HTMLElement>(".lv4-gallery,.lv4-gallery-nav,.lv4-gallery-controls,.lv4-gallery-count,.lv4-gallery-prev,.lv4-gallery-next,.lv4-image-count,.lv4-media-count,.lv4-slide-count,.lv4-gallery-dots,.lv4-gallery-pagination,.ynot-full-slider,[class*='gallery-prev'],[class*='gallery-next'],[class*='slider-prev'],[class*='slider-next'],[class*='carousel-prev'],[class*='carousel-next'],[class*='swiper-button'],[class*='slick-arrow']").forEach(el=>{el.style.setProperty("display","none","important");el.style.setProperty("pointer-events","none","important")});shell.querySelectorAll<HTMLButtonElement>("button").forEach(button=>{const label=(button.getAttribute("aria-label")||"").toLowerCase(),cls=String(button.className||"").toLowerCase(),text=(button.textContent||"").trim();if(((/\b(previous|next)\b/.test(label)&&/(image|photo|slide|media|product)/.test(label))||/(gallery|slider|carousel|swiper).*(prev|next)|(prev|next).*(gallery|slider|carousel|swiper)/.test(cls)||/^[‹›«»]$/.test(text))&&!button.classList.contains("lv4-close")){button.style.setProperty("display","none","important");button.style.setProperty("pointer-events","none","important")}})})}
export default function ProductGalleryStability(){
 useEffect(()=>{let frame=0;const scan=()=>{frame=0;document.querySelectorAll<HTMLElement>(".ynot-loaded-gallery").forEach(rebuildGallery);removeMobileSliderChrome()};const schedule=()=>{if(!frame)frame=requestAnimationFrame(scan)};schedule();const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["data-media-signature","class"]});window.addEventListener("resize",schedule,{passive:true});return()=>{observer.disconnect();window.removeEventListener("resize",schedule);if(frame)cancelAnimationFrame(frame);document.querySelector(".ynot-complete-image-viewer")?.remove()}},[]);
 return <style>{`
 .lv4-detail .ynot-loaded-gallery{position:relative!important;left:auto!important;right:auto!important;transform:none!important;margin:8px auto 4px!important;width:max-content!important;max-width:calc(100% - 24px)!important;height:62px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:7px!important;padding:4px 7px!important;overflow:hidden!important;box-sizing:border-box!important}
 .lv4-detail .ynot-loaded-gallery>.ynot-complete-thumb{position:relative!important;flex:0 0 58px!important;width:58px!important;height:54px!important;min-width:58px!important;min-height:54px!important;margin:0!important;padding:0!important;border-radius:13px!important;overflow:hidden!important;box-sizing:border-box!important;border:1px solid rgba(255,255,255,.24)!important;background:rgba(255,255,255,.07)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.18),0 5px 16px rgba(0,0,0,.14)!important;cursor:pointer!important}.lv4-detail .ynot-loaded-gallery>.ynot-complete-thumb.active{border-color:rgba(255,255,255,.72)!important;background:rgba(255,255,255,.13)!important}.lv4-detail .ynot-loaded-gallery>.ynot-complete-thumb img,.lv4-detail .ynot-loaded-gallery>.ynot-complete-thumb video{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important;border-radius:11px!important}.lv4-detail .ynot-loaded-gallery>.ynot-complete-thumb:has(video):not(.ynot-gallery-more):after{content:"▶";position:absolute;inset:0;display:grid;place-items:center;color:#fff;font-size:12px;text-shadow:0 2px 8px #000;pointer-events:none}
 .lv4-detail .ynot-loaded-gallery>.ynot-gallery-more img,.lv4-detail .ynot-loaded-gallery>.ynot-gallery-more video{filter:blur(5px) brightness(.62)!important;transform:scale(1.12)!important}.lv4-detail .ynot-loaded-gallery>.ynot-gallery-more:before{content:""!important;position:absolute!important;inset:0!important;z-index:2!important;background:rgba(8,8,8,.18)!important}.lv4-detail .ynot-loaded-gallery>.ynot-gallery-more:after{content:attr(data-more)!important;position:absolute!important;inset:0!important;z-index:3!important;display:grid!important;place-items:center!important;color:#fff!important;font:800 11px/1 system-ui,sans-serif!important;text-shadow:0 1px 7px rgba(0,0,0,.65)!important}
 .ynot-main-product-video{position:absolute!important;z-index:3!important;left:50%!important;top:0!important;transform:translateX(-50%)!important;width:100%!important;height:var(--ynot-main-media-height,55%)!important;object-fit:contain!important;background:transparent!important;border:0!important}
 .ynot-complete-image-viewer{position:fixed!important;inset:0!important;z-index:2147483647!important;display:grid!important;place-items:center!important;background:rgba(0,0,0,.28)!important;backdrop-filter:blur(11px)!important;-webkit-backdrop-filter:blur(11px)!important;padding:28px!important;overflow:hidden!important;outline:none!important}.ynot-complete-image-frame{position:relative!important;width:min(76vw,860px)!important;height:min(68vh,680px)!important;display:grid!important;place-items:center!important;overflow:hidden!important;border:1px solid rgba(255,255,255,.24)!important;border-radius:28px!important;background:rgba(18,18,18,.76)!important;box-shadow:0 28px 90px rgba(0,0,0,.44),inset 0 1px 0 rgba(255,255,255,.15)!important;backdrop-filter:blur(28px) saturate(1.08)!important;-webkit-backdrop-filter:blur(28px) saturate(1.08)!important;padding:18px!important;touch-action:pan-y!important}.ynot-complete-media-stage{width:100%!important;height:100%!important;display:grid!important;place-items:center!important;overflow:hidden!important}.ynot-complete-media{display:block!important;max-width:100%!important;max-height:100%!important;width:auto!important;height:auto!important;object-fit:contain!important;border-radius:18px!important;background:transparent!important}.ynot-complete-image-close{position:absolute!important;top:12px!important;right:12px!important;width:40px!important;height:40px!important;border-radius:999px!important;display:grid!important;place-items:center!important;border:1px solid rgba(255,255,255,.22)!important;background:rgba(20,20,20,.48)!important;color:#fff!important;font-size:25px!important;line-height:1!important;backdrop-filter:blur(18px)!important;-webkit-backdrop-filter:blur(18px)!important;z-index:4!important}.ynot-full-slider{display:none!important}
 @media(max-width:899px){.lv4-detail>.lv4-gallery,.lv4-detail .lv4-gallery,.lv4-detail .lv4-gallery-nav,.lv4-detail .lv4-gallery-controls,.lv4-detail .lv4-gallery-prev,.lv4-detail .lv4-gallery-next,.lv4-detail .lv4-gallery-count,.lv4-detail .lv4-image-count,.lv4-detail .lv4-media-count,.lv4-detail .lv4-slide-count,.lv4-detail .lv4-gallery-dots,.lv4-detail .lv4-gallery-pagination,.lv4-detail [class*='gallery-prev'],.lv4-detail [class*='gallery-next'],.lv4-detail [class*='slider-prev'],.lv4-detail [class*='slider-next'],.lv4-detail [class*='carousel-prev'],.lv4-detail [class*='carousel-next'],.lv4-detail [class*='swiper-button'],.lv4-detail [class*='slick-arrow'],.lv4-detail button[aria-label*='Previous image' i],.lv4-detail button[aria-label*='Next image' i],.lv4-detail button[aria-label*='Previous photo' i],.lv4-detail button[aria-label*='Next photo' i],.lv4-detail button[aria-label*='Previous slide' i],.lv4-detail button[aria-label*='Next slide' i],.lv4-detail button[aria-label*='Previous product' i],.lv4-detail button[aria-label*='Next product' i]{display:none!important;visibility:hidden!important;pointer-events:none!important;width:0!important;height:0!important;min-width:0!important;min-height:0!important;padding:0!important;margin:0!important;border:0!important}.lv4-detail .ynot-loaded-gallery{width:max-content!important;max-width:calc(100% - 20px)!important;height:54px!important;gap:5px!important;padding:4px 7px!important;margin-left:auto!important;margin-right:auto!important}.lv4-detail .ynot-loaded-gallery>.ynot-complete-thumb{flex:0 0 48px!important;width:48px!important;height:46px!important;min-width:48px!important;min-height:46px!important;border-radius:11px!important}.ynot-complete-image-viewer{padding:18px 12px!important}.ynot-complete-image-frame{width:min(88vw,520px)!important;height:min(58dvh,520px)!important;border-radius:22px!important;padding:12px!important}.ynot-complete-media{border-radius:15px!important}.ynot-complete-image-close{top:9px!important;right:9px!important;width:36px!important;height:36px!important}}
 `}</style>
}
