type Detection={id:string;label:string;searchQuery:string;alternateQueries?:string[];box_2d:number[]};
type ScanData={objects?:Detection[];error?:string};
type CatalogProduct={id:string;title:string;brand?:string;price?:number|null;currency?:string;image?:string;url?:string};

type ScannerState={active:boolean;busy:boolean;image:string;objects:Detection[];selected:string;overlay?:HTMLDivElement;results?:HTMLDivElement};
const states=new WeakMap<HTMLElement,ScannerState>();
function clean(v:string){return String(v||"").trim()}
function money(p:CatalogProduct){if(typeof p.price!=="number")return"";try{return new Intl.NumberFormat(undefined,{style:"currency",currency:p.currency||"EUR",maximumFractionDigits:0}).format(p.price)}catch{return String(p.price)}}
function mainImage(shell:HTMLElement){const media=shell.querySelector<HTMLImageElement>(":scope > img.lv4-detail-media, :scope > img.ynot-shared-media, img.lv4-detail-media");return clean(media?.currentSrc||media?.src||media?.dataset.productFallback||"")}
function setNativeSimilar(shell:HTMLElement,hidden:boolean){shell.querySelectorAll<HTMLElement>(".lv4-similar-block,.lv4-direction-row").forEach(el=>el.style.setProperty("display",hidden?"none":"",hidden?"important":""))}
function clearOverlay(state:ScannerState){state.overlay?.remove();state.overlay=undefined}
function clearResults(shell:HTMLElement,state:ScannerState){state.results?.remove();state.results=undefined;state.selected="";setNativeSimilar(shell,false)}
function close(shell:HTMLElement,state:ScannerState,button:HTMLButtonElement){state.active=false;state.busy=false;state.objects=[];button.classList.remove("active","loading");button.title="Scan image";clearOverlay(state);clearResults(shell,state)}
function imageContentRect(img:HTMLImageElement,shell:HTMLElement){const ir=img.getBoundingClientRect(),sr=shell.getBoundingClientRect();let left=ir.left-sr.left,top=ir.top-sr.top,width=ir.width,height=ir.height;if(img.naturalWidth&&img.naturalHeight){const scale=Math.min(ir.width/img.naturalWidth,ir.height/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;left+=(ir.width-w)/2;top+=(ir.height-h)/2;width=w;height=h}return{left,top,width,height}}
function renderDots(shell:HTMLElement,state:ScannerState){clearOverlay(state);const img=shell.querySelector<HTMLImageElement>(":scope > img.lv4-detail-media, :scope > img.ynot-shared-media, img.lv4-detail-media");if(!img||!state.active||!state.objects.length)return;const rect=imageContentRect(img,shell),overlay=document.createElement("div");overlay.className="ynot-product-scan-overlay";Object.assign(overlay.style,{position:"absolute",left:`${rect.left}px`,top:`${rect.top}px`,width:`${rect.width}px`,height:`${rect.height}px`,zIndex:"19",pointerEvents:"none"});for(const object of state.objects){const b=object.box_2d||[];if(b.length<4)continue;const dot=document.createElement("button");dot.type="button";dot.className="ynot-product-scan-dot";dot.title=object.label;dot.setAttribute("aria-label",`Find ${object.label}`);dot.style.left=`${((b[1]+b[3])/2)/10}%`;dot.style.top=`${((b[0]+b[2])/2)/10}%`;dot.style.pointerEvents="auto";dot.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();void chooseObject(shell,state,object)});overlay.appendChild(dot)}shell.appendChild(overlay);state.overlay=overlay}
async function catalog(q:string){try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(q)}&source=all`,{cache:"no-store"});const d=await r.json().catch(()=>({}));return Array.isArray(d.products)?d.products as CatalogProduct[]:[]}catch{return[]}}
function dedupe(groups:CatalogProduct[][]){const seen=new Set<string>();return groups.flat().filter(p=>{const k=clean(p.id||`${p.title}|${p.brand}`);if(!p.image||!p.title||!k||seen.has(k))return false;seen.add(k);return true})}
async function chooseObject(shell:HTMLElement,state:ScannerState,object:Detection){state.selected=object.id;state.overlay?.querySelectorAll("button").forEach(dot=>dot.classList.toggle("active",dot.title===object.label));setNativeSimilar(shell,true);state.results?.remove();const block=document.createElement("div");block.className="ynot-scan-results";block.innerHTML=`<div class="ynot-scan-results-head"><span><i></i> ${object.label}</span><small>Finding exact matches…</small></div><div class="ynot-scan-results-row"></div>`;const anchor=shell.querySelector(".lv4-similar-block")||shell.querySelector(".lv4-direction-row");anchor?.parentElement?.insertBefore(block,anchor);state.results=block;const queries=[object.searchQuery,object.label,...(object.alternateQueries||[])].map(clean).filter(Boolean).slice(0,4);const groups=await Promise.all(queries.map(catalog));if(state.selected!==object.id)return;const products=dedupe(groups).slice(0,18),head=block.querySelector("small"),row=block.querySelector<HTMLElement>(".ynot-scan-results-row");if(head)head.textContent=products.length?`${products.length} matches for this object`:"No close matches found";if(!row)return;for(const p of products){const card=document.createElement("button");card.type="button";card.className="ynot-scan-product";card.innerHTML=`<img src="${p.image}" alt=""><span><b></b><small></small><em></em></span>`;const b=card.querySelector("b"),small=card.querySelector("small"),em=card.querySelector("em");if(b)b.textContent=p.brand||"Independent store";if(small)small.textContent=p.title;if(em)em.textContent=money(p);card.addEventListener("click",()=>{if(p.url)window.open(p.url,"_blank","noopener,noreferrer")});row.appendChild(card)}}
async function scan(shell:HTMLElement,state:ScannerState,button:HTMLButtonElement){const image=mainImage(shell);if(!image)return;if(state.active){close(shell,state,button);return}state.active=true;state.busy=true;state.image=image;button.classList.add("active","loading");button.title="Close scan";clearResults(shell,state);try{const r=await fetch("/api/room/quick/analyze-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({imageUrl:image}),cache:"no-store"});const data=await r.json() as ScanData;if(!r.ok)throw new Error(data.error||"Scan failed");if(!state.active||state.image!==image)return;state.objects=Array.isArray(data.objects)?data.objects:[];renderDots(shell,state)}catch{close(shell,state,button)}finally{state.busy=false;button.classList.remove("loading")}}
function styles(){if(document.getElementById("ynot-product-scanner-style"))return;const style=document.createElement("style");style.id="ynot-product-scanner-style";style.textContent=`.lv4-detail{position:relative}.ynot-product-scan-trigger{position:absolute;right:54px;top:18px;z-index:31;width:22px;height:22px;padding:0;border:0;background:transparent;display:grid;place-items:center;cursor:pointer}.ynot-product-scan-trigger:before{content:"";width:9px;height:9px;border-radius:50%;background:#ef2b2d;box-shadow:0 0 0 3px rgba(255,255,255,.94),0 2px 8px rgba(0,0,0,.22)}.ynot-product-scan-trigger.active:before{box-shadow:0 0 0 3px #fff,0 0 0 5px rgba(239,43,45,.35),0 2px 8px rgba(0,0,0,.22)}.ynot-product-scan-trigger.loading:after{content:"";position:absolute;width:18px;height:18px;border:1px solid rgba(239,43,45,.25);border-top-color:#ef2b2d;border-radius:50%;animation:ynotScanSpin .7s linear infinite}@keyframes ynotScanSpin{to{transform:rotate(360deg)}}.ynot-product-scan-dot{position:absolute;transform:translate(-50%,-50%);width:25px;height:25px;border-radius:50%;border:2px solid #fff;background:rgba(20,20,20,.28);box-shadow:0 2px 12px rgba(0,0,0,.28);cursor:pointer}.ynot-product-scan-dot:after{content:"";position:absolute;inset:7px;border-radius:50%;background:#fff}.ynot-product-scan-dot.active{background:#fff;box-shadow:0 0 0 4px rgba(255,255,255,.28),0 2px 12px rgba(0,0,0,.28)}.ynot-product-scan-dot.active:after{background:#ef2b2d}.ynot-scan-results{margin-top:18px}.ynot-scan-results-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:9px}.ynot-scan-results-head span{font-size:12px;font-weight:700;display:flex;align-items:center;gap:7px}.ynot-scan-results-head span i{width:7px;height:7px;border-radius:50%;background:#ef2b2d}.ynot-scan-results-head small{font-size:10px;opacity:.55}.ynot-scan-results-row{display:flex;gap:10px;overflow-x:auto;scrollbar-width:none;padding-bottom:4px}.ynot-scan-results-row::-webkit-scrollbar{display:none}.ynot-scan-product{flex:0 0 116px;border:0;background:transparent;text-align:left;padding:0;color:inherit}.ynot-scan-product img{width:116px;height:116px;object-fit:contain;border-radius:16px;background:rgba(127,127,127,.07)}.ynot-scan-product span{display:block;padding-top:6px}.ynot-scan-product b,.ynot-scan-product small,.ynot-scan-product em{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ynot-scan-product b{font-size:9px}.ynot-scan-product small{font-size:9px;opacity:.62}.ynot-scan-product em{font-size:10px;font-style:normal;margin-top:2px}@media(max-width:700px){.ynot-product-scan-trigger{right:50px;top:14px}.ynot-product-scan-dot{width:27px;height:27px}.ynot-scan-product{flex-basis:104px}.ynot-scan-product img{width:104px;height:104px}}`;document.head.appendChild(style)}
export function installProductImageScanner(shell:HTMLElement){styles();let state=states.get(shell);if(!state){state={active:false,busy:false,image:"",objects:[],selected:""};states.set(shell,state)}let button=shell.querySelector<HTMLButtonElement>(".ynot-product-scan-trigger");if(!button){button=document.createElement("button");button.type="button";button.className="ynot-product-scan-trigger";button.title="Scan image";button.setAttribute("aria-label","Scan product image");button.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();void scan(shell,state!,button!)});shell.appendChild(button)}if(state.active&&state.image!==mainImage(shell))close(shell,state,button);if(state.active&&state.objects.length&&!state.overlay)renderDots(shell,state)}
