"use client";
import {useEffect} from "react";

type Product={id:string;title:string;brand?:string;image?:string;price?:number|null;currency?:string};
const q=<T extends Element>(s:string,r:ParentNode=document)=>r.querySelector<T>(s);
const clean=(s:string)=>s.replace(/\s+/g," ").trim();
const generic=new Set(["all","option","default title","ynot","shopify","commerce","product","products","new","sale"]);
let observer:IntersectionObserver|null=null,active="",token=0;
function context(){const detail=q<HTMLElement>(".detail");if(!detail)return null;const title=clean(q<HTMLElement>(".info h1",detail)?.textContent||"");const brand=clean(q<HTMLElement>(".info>small",detail)?.textContent||"");return{detail,title,brand}}
function attributes(detail:HTMLElement){const raw:string[]=[];detail.querySelectorAll<HTMLElement>(".variantButtons button,.productTags span,.variant option").forEach(n=>raw.push(clean(n.textContent||"")));const seen=new Set<string>();return raw.filter(v=>{const k=v.toLowerCase().replace(/—.*$/," ").trim();if(!k||k.length>24||generic.has(k)||seen.has(k))return false;seen.add(k);return true}).slice(0,5)}
function money(p:Product){return p.price==null?"":`${p.currency||"EUR"} ${Number(p.price).toFixed(2)}`}
function restore(detail:HTMLElement){active="";detail.querySelectorAll(".yn-attribute-satellite").forEach(n=>n.classList.remove("on"));detail.querySelectorAll<HTMLElement>(".related>[data-yn-attribute-original]").forEach(n=>{n.style.removeProperty("display");n.removeAttribute("data-yn-attribute-original")});detail.querySelectorAll(".yn-attribute-result,.yn-attribute-empty").forEach(n=>n.remove());const more=q<HTMLElement>(".more h2",detail);if(more)more.textContent="More like this"}
async function apply(value:string){const c=context();if(!c)return;if(active===value){restore(c.detail);return}active=value;const my=++token;c.detail.querySelectorAll<HTMLElement>(".yn-attribute-satellite").forEach(n=>n.classList.toggle("on",n.dataset.value===value));const related=q<HTMLElement>(".related",c.detail),more=q<HTMLElement>(".more h2",c.detail);if(!related)return;related.querySelectorAll<HTMLElement>(":scope>button:not(.yn-attribute-result)").forEach(n=>{n.dataset.ynAttributeOriginal="1";n.style.display="none"});related.querySelectorAll(".yn-attribute-result,.yn-attribute-empty").forEach(n=>n.remove());if(more)more.textContent=`More like this · ${value}`;const query=clean([c.brand,c.title,value].filter(Boolean).join(" "));try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(query)}&source=all&limit=100`,{cache:"no-store"}),j=await r.json();if(my!==token)return;const seen=new Set<string>(),items=(Array.isArray(j.products)?j.products:[]).filter((p:Product)=>p?.id&&p.image&&!seen.has(String(p.id))&&!!seen.add(String(p.id)));if(!items.length){const e=document.createElement("div");e.className="yn-attribute-empty";e.textContent=`No ${value} matches yet`;related.append(e);return}for(const p of items){const b=document.createElement("button");b.type="button";b.className="yn-attribute-result";const img=document.createElement("img");img.src=p.image!;img.alt=p.title||value;img.loading="lazy";const title=document.createElement("b");title.textContent=p.title||value;const price=document.createElement("em");price.textContent=money(p);b.append(img,title,price);b.onclick=()=>window.dispatchEvent(new CustomEvent("ynot:open-product",{detail:p}));related.append(b)}}catch{restore(c.detail)}}
function mount(){const c=context();if(!c)return;const orb=q<HTMLElement>(".ynOrbWrap")||q<HTMLElement>(".orb");const more=q<HTMLElement>(".more",c.detail);if(!orb||!more)return;let tray=q<HTMLElement>(".yn-attribute-satellites",orb.parentElement||document);if(!tray){tray=document.createElement("div");tray.className="yn-attribute-satellites";orb.parentElement?.append(tray)}const vals=attributes(c.detail),key=vals.join("|");if(tray.dataset.key!==key){tray.dataset.key=key;tray.innerHTML="";for(const value of vals){const b=document.createElement("button");b.type="button";b.className="yn-attribute-satellite";b.dataset.value=value;b.textContent=value;b.onclick=e=>{e.preventDefault();e.stopPropagation();void apply(value)};tray.append(b)}}observer?.disconnect();observer=new IntersectionObserver(entries=>tray?.classList.toggle("show",!!entries[0]?.isIntersecting),{threshold:.02,rootMargin:"0px 0px -8% 0px"});observer.observe(more)}
export default function ProductAttributeSatellites(){useEffect(()=>{const sync=()=>mount();sync();const mo=new MutationObserver(sync);mo.observe(document.body,{childList:true,subtree:true});return()=>{mo.disconnect();observer?.disconnect();document.querySelectorAll(".yn-attribute-satellites").forEach(n=>n.remove())}},[]);return <style jsx global>{`.yn-attribute-satellites{position:fixed;z-index:89;left:50%;bottom:calc(102px + env(safe-area-inset-bottom));width:min(330px,88vw);height:76px;transform:translateX(-50%);pointer-events:none;opacity:0;transition:opacity .24s ease}.yn-attribute-satellites.show{opacity:1}.yn-attribute-satellite{position:absolute;left:50%;bottom:0;transform:translate(-50%,30px) scale(.55);opacity:0;pointer-events:none;max-width:105px;padding:7px 11px;border-radius:999px;border:1px solid rgba(255,255,255,.28);background:rgba(18,20,24,.48);color:#fff;font-size:10px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;box-shadow:inset 0 1px rgba(255,255,255,.16),0 8px 22px rgba(0,0,0,.22);backdrop-filter:blur(12px) saturate(145%);-webkit-backdrop-filter:blur(12px) saturate(145%);transition:.42s cubic-bezier(.16,.9,.2,1)}.show .yn-attribute-satellite{opacity:1;pointer-events:auto}.show .yn-attribute-satellite:nth-child(1){transform:translate(-155%,-6px) scale(1)}.show .yn-attribute-satellite:nth-child(2){transform:translate(-98%,-42px) scale(1)}.show .yn-attribute-satellite:nth-child(3){transform:translate(-50%,-58px) scale(1)}.show .yn-attribute-satellite:nth-child(4){transform:translate(-2%,-42px) scale(1)}.show .yn-attribute-satellite:nth-child(5){transform:translate(55%,-6px) scale(1)}.yn-attribute-satellite.on{background:rgba(255,255,255,.9);color:#111;border-color:#fff}.related>.yn-attribute-result{display:inline-block!important;width:100%!important;break-inside:avoid;margin:0 0 3px!important}.yn-attribute-empty{padding:28px 18px;color:#888;font-size:12px}@media(max-width:600px){.yn-attribute-satellites{bottom:calc(96px + env(safe-area-inset-bottom));width:92vw}.yn-attribute-satellite{font-size:9px;padding:6px 9px;max-width:92px}}@media(prefers-reduced-motion:reduce){.yn-attribute-satellite,.yn-attribute-satellites{transition:none}}`}</style>}
