"use client";

import {useEffect,useLayoutEffect,useRef,useState} from "react";
import {dynamicLuminaPrice} from "@/lib/commerce/engine";

const STOP=new Set(["the","and","for","with","from","this","that","your","live","product","products","store","shopify","amazon","ebay","ynot","best","value","view","available","option","options"]);
type Variant={id?:string;label?:string;price?:number|null;currency?:string;image?:string;url?:string;available?:boolean};
type Product={id:string;variantId?:string;title:string;brand?:string;price:number|null;currency?:string;image?:string;images?:string[];url?:string;source?:string;category?:string;variants?:Variant[];checkout?:{mode:string;reason?:string};supplierPrice?:number;retailPrice?:number;pricingMode?:string;[key:string]:unknown};
type Verified={product:Product&{supplierPrice?:number;retailPrice?:number;sellableByLumina?:boolean};shipping?:{amount:number;currency:string;country:string};marginPct?:number;verified:boolean;state?:string};
type LinkResponse={url?:string;variantId?:string;product?:Product;error?:string};
type CircleMember={id:string;display_name?:string|null};
const COUNTRIES=[['FR','France'],['BE','Belgium'],['DE','Germany'],['ES','Spain'],['IT','Italy'],['NL','Netherlands'],['GB','United Kingdom'],['US','United States']] as const;
const cache=new Map<string,Verified>();const pending=new Set<string>();const catalogProducts=new Map<string,Product>();const enrichmentPending=new Map<string,Promise<Product>>();let circleMembers:CircleMember[]=[];let circleProofTick=0;
function key(s:string){return String(s||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function words(text:string){return String(text||"").toLowerCase().replace(/[^a-z0-9€$£\- ]/g," ").split(/\s+/).filter(w=>w.length>2&&!STOP.has(w))}
function money(value:number,currency='EUR'){try{return new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:2}).format(value)}catch{return`${value.toFixed(2)} ${currency}`}}
function region(){try{return JSON.parse(localStorage.getItem('ynot-region')||'null') as {country:string}|null}catch{return null}}
function setText(el:HTMLElement|null|undefined,value:string){if(el&&el.textContent!==value)el.textContent=value}
function isShopify(p?:Product){return Boolean(p?.source?.toLowerCase().includes('shopify'))}
function inferCategory(p:Product){const text=`${p.category||''} ${p.title||''}`.toLowerCase();if(/dress|fashion|shirt|shoe|bag|jewel|accessor|apparel|clothing/.test(text))return'fashion';if(/fitness|gym|training|running|recovery|sport/.test(text))return'fitness';if(/skin|beauty|serum|cream|spf|cleanser/.test(text))return'skin';if(/hair|scalp|shampoo|conditioner/.test(text))return'hair';if(/home|decor|furniture|lamp|kitchen|bedding/.test(text))return'home';if(/tech|phone|audio|headphone|charger|gaming|smart/.test(text))return'tech';return'default'}
function provisionalRetail(p:Product){const supplier=Number(p.supplierPrice??p.price);if(!Number.isFinite(supplier)||supplier<=0)return null;return dynamicLuminaPrice({sourceId:p.source||'discovery',productId:p.variantId||p.id,title:p.title,category:inferCategory(p),price:supplier,currency:p.currency||'EUR',shipping:0,stockConfidence:.75,returnPolicyScore:.7,regionMatch:.75})}
function titleTags(root:Element){const title=(root.querySelector("h2,h3")?.textContent||"").trim();const body=(root.textContent||"").toLowerCase();const titleWords=words(title);const candidates:string[]=[];const existing=[...root.querySelectorAll<HTMLButtonElement>(".lv4-tagrow button")].map(b=>(b.textContent||"").trim()).filter(Boolean);candidates.push(...existing);const patterns=["minimal","premium","black","white","blue","red","green","beige","brown","pink","silver","gold","leather","cotton","linen","silk","wireless","portable","waterproof","running","activewear","dress","dresses","shoes","bag","bags","jewelry","skincare","hair","home","tech","fitness","accessories","vintage","organic","recycled","lightweight","casual"];for(const p of patterns)if(body.includes(p))candidates.push(p.replace(/^./,c=>c.toUpperCase()));candidates.push(...titleWords.slice(0,6).map(w=>w.replace(/^./,c=>c.toUpperCase())));const seen=new Set<string>();return candidates.filter(tag=>{const k=tag.toLowerCase();if(k.length<3||seen.has(k)||STOP.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const al=title.toLowerCase().includes(a.toLowerCase())?1:0,bl=title.toLowerCase().includes(b.toLowerCase())?1:0;return bl-al||a.length-b.length}).slice(0,6)}
function buildRow(root:Element){let row=root.querySelector<HTMLElement>(".lv4-tagrow,.ynot-card-tags");if(!row){row=document.createElement("div");row.className="lv4-tagrow ynot-card-tags";const action=root.querySelector(".ynot-story-action,.lv4-direction-row");if(action?.parentElement)action.parentElement.insertBefore(row,action);else root.appendChild(row)}const tags=titleTags(root);if(!tags.length)return;const signature=tags.join('|').toLowerCase();if(row.dataset.tagsSignature===signature)return;row.dataset.tagsSignature=signature;row.replaceChildren(...tags.map(tag=>{const b=document.createElement("button");b.type="button";b.textContent=tag;b.addEventListener("click",()=>window.dispatchEvent(new CustomEvent("shop:quick-tag",{detail:tag})));return b}))}
function addTick(root:Element){if(root.querySelector('.ynot-verified-tick'))return;const tick=document.createElement('span');tick.className='ynot-verified-tick';tick.title='YNOT Verified';tick.setAttribute('aria-label','YNOT Verified');tick.textContent='✓';const target=root.querySelector('.lv4-product-tooltip small,.lv4-product-brand,.ynot-orb-copy em,.ynot-selected-copy small,.ynot-story-copy small');target?.appendChild(tick)}
async function enrichProduct(product:Product){const k=key(product.title);const existing=catalogProducts.get(k)||product;if(!isShopify(existing))return existing;const prior=enrichmentPending.get(k);if(prior)return prior;const job=(async()=>{const response=await fetch('/api/commerce/product-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(existing)});const data=await response.json() as LinkResponse;if(!response.ok||!data.url)throw new Error(data.error||'Exact product page unavailable');const enriched={...existing,...(data.product||{}),url:data.url,variantId:data.variantId||existing.variantId};catalogProducts.set(k,enriched);return enriched})().finally(()=>enrichmentPending.delete(k));enrichmentPending.set(k,job);return job}
function productForTitle(title:string){return catalogProducts.get(key(title))}
function selectedVariant(root:Element,product:Product){const id=(root.closest('.lv4-detail') as HTMLElement|null)?.dataset.ynotVariantId||root.closest('.ynot-selected,.ynot-story')?.getAttribute('data-ynot-variant-id')||product.variantId;const variant=id?product.variants?.find(v=>String(v.id||'')===String(id)):undefined;return variant?{...product,variantId:variant.id,price:variant.price??product.price,supplierPrice:variant.price??product.supplierPrice??product.price,currency:variant.currency||product.currency,image:variant.image||product.image,url:variant.url||product.url}:product}
function addOriginDot(root:Element,title:string){const shell=root.closest('.lv4-detail,.ynot-selected,.ynot-story')||root;if(shell.querySelector(':scope > .ynot-origin-dot'))return;const dot=document.createElement('button');dot.type='button';dot.className='ynot-origin-dot';dot.title='Original merchant product page';dot.setAttribute('aria-label','Open original merchant product page');dot.addEventListener('click',async event=>{event.preventDefault();event.stopPropagation();try{const base=productForTitle(title);if(!base)throw new Error('Product unavailable');const exact=await enrichProduct(selectedVariant(root,base));if(!exact.url)throw new Error('Exact product page unavailable');window.open(exact.url,'_blank','noopener,noreferrer')}catch(e){window.alert(e instanceof Error?e.message:'Exact product page unavailable')}});shell.appendChild(dot)}
function renderLazyDetails(root:Element,product:Product){const detail=root.closest('.lv4-detail') as HTMLElement|null;if(!detail)return;const main=detail.querySelector<HTMLImageElement>(':scope > img');const images=[...new Set([product.image,...(product.images||[]),...(product.variants||[]).map(v=>v.image).filter(Boolean)].filter(Boolean) as string[])];if(images.length>1&&!detail.querySelector('.ynot-loaded-gallery')){const gallery=document.createElement('div');gallery.className='ynot-loaded-gallery';for(const src of images.slice(0,10)){const b=document.createElement('button');b.type='button';const img=document.createElement('img');img.src=src;img.alt='';b.appendChild(img);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(main)main.src=src;gallery.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))});gallery.appendChild(b)}main?.insertAdjacentElement('afterend',gallery)}
 if((product.variants||[]).length&&!root.querySelector('.ynot-loaded-variants')){root.querySelector('.lv4-variants')?.classList.add('ynot-native-hidden');const wrap=document.createElement('div');wrap.className='ynot-loaded-variants';for(const v of (product.variants||[]).slice(0,16)){const b=document.createElement('button');b.type='button';b.disabled=v.available===false;b.textContent=`${v.label||'Option'}${v.price!=null?` · ${money(Number(provisionalRetail({...product,price:v.price,supplierPrice:v.price,variantId:v.id})??v.price),v.currency||product.currency||'EUR')}`:''}`;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();wrap.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');detail.dataset.ynotVariantId=String(v.id||'');const updated={...product,variantId:v.id,price:v.price??product.price,supplierPrice:v.price??product.supplierPrice??product.price,currency:v.currency||product.currency,image:v.image||product.image,url:v.url||product.url};catalogProducts.set(key(product.title),updated);if(v.image&&main)main.src=v.image;const strong=root.querySelector<HTMLElement>('strong');const retail=provisionalRetail(updated);if(strong&&retail!=null)setText(strong,money(retail,updated.currency||'EUR'))});wrap.appendChild(b)}const actions=root.querySelector('.lv4-actions');actions?.parentElement?.insertBefore(wrap,actions)} }
function setActionLabels(){document.querySelectorAll<HTMLElement>('.ynot-shop span').forEach(x=>setText(x,'YNOT BAG'));document.querySelectorAll<HTMLElement>('.ynot-story-action').forEach(button=>{const texts=[...button.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE);if(texts.length)texts.forEach((n,i)=>{if(i===0&&n.textContent!=='YNOT BAG')n.textContent='YNOT BAG';else if(i>0)n.textContent=''})});document.querySelectorAll<HTMLElement>('.ynot-cart-checkout').forEach(x=>setText(x,'Checkout'))}
function memberName(member:CircleMember,index:number){const name=String(member.display_name||"").trim();return name||`Shopper ${String(member.id||index+1).replace(/-/g,"").slice(0,2).toUpperCase()}`}
function renderCircleProof(root:Element){let proof=root.querySelector<HTMLElement>(".ynot-product-proof");if(!proof){proof=document.createElement("div");proof.className="ynot-product-proof";const first=root.firstElementChild;first?root.insertBefore(proof,first):root.appendChild(proof)}const total=circleMembers.length;if(!total){proof.innerHTML='<span class="ynot-proof-empty">Join the first YNOT Circle</span>';return}const visible=Array.from({length:Math.min(3,total)},(_,offset)=>circleMembers[(circleProofTick+offset)%total]);const names=visible.slice(0,2).map(memberName);proof.replaceChildren();const faces=document.createElement("span");faces.className="ynot-proof-faces";visible.forEach((member,index)=>{const face=document.createElement("i");const name=memberName(member,index);face.textContent=name.slice(0,1).toUpperCase();face.title=name;face.style.setProperty("--face-i",String(index));faces.appendChild(face)});const copy=document.createElement("span");copy.className="ynot-proof-copy";const named=names.join(names.length>1?" & ":"");copy.textContent=total>2?`${named} and ${total-2} other${total-2===1?"":"s"} are in your Circle`:`${named} ${total===1?"is":"are"} in your Circle`;proof.append(faces,copy)}
function decorate(){
 document.querySelectorAll('.lv4-product').forEach(card=>{const title=card.querySelector('.lv4-product-tooltip b')?.textContent||'';const k=key(title);const known=catalogProducts.get(k);const v=cache.get(k);const price=card.querySelector<HTMLElement>('.lv4-price');if(v?.verified)addTick(card);if(price&&known){const shown=v?.verified&&v.product.retailPrice!=null?Number(v.product.retailPrice):provisionalRetail(known);if(shown!=null)setText(price,money(shown,String(known.currency||'EUR')))}card.classList.toggle('ynot-verified-product',Boolean(v?.verified))});
 document.querySelectorAll('.lv4-detailcopy,.ynot-selected-copy,.ynot-story-copy').forEach(root=>{renderCircleProof(root);const title=root.querySelector('h2,h3')?.textContent||'';const known=productForTitle(title);const v=cache.get(key(title));if(known)addOriginDot(root,title);if(v?.verified)addTick(root);const strong=root.querySelector<HTMLElement>('strong');const shown=v?.verified&&v.product.retailPrice!=null?Number(v.product.retailPrice):known?provisionalRetail(known):null;if(strong&&shown!=null)setText(strong,money(shown,String(known?.currency||v?.product.currency||'EUR')));if(v?.verified&&!root.querySelector('.ynot-shipping-hint')&&v.shipping){const s=document.createElement('small');s.className='ynot-shipping-hint';s.textContent=`Shipping to ${v.shipping.country}: ${money(v.shipping.amount,v.shipping.currency)} · rechecked before payment`;const action=root.querySelector('.lv4-actions,.ynot-shop,.ynot-story-action');action?.parentElement?.insertBefore(s,action)}});
 document.querySelectorAll('.ynot-orb').forEach(card=>{const title=card.querySelector('.ynot-orb-copy b')?.textContent||'';const known=productForTitle(title),v=cache.get(key(title));if(v?.verified)addTick(card);const strong=card.querySelector<HTMLElement>('.ynot-orb-copy strong');const shown=v?.verified&&v.product.retailPrice!=null?Number(v.product.retailPrice):known?provisionalRetail(known):null;if(strong&&shown!=null)setText(strong,money(shown,String(known?.currency||v?.product.currency||'EUR')))});setActionLabels();
}
async function verifyProduct(product:Product){const k=key(product.title);if(!k||pending.has(k)||cache.has(k)||!isShopify(product))return;const r=region();if(!r)return;pending.add(k);try{const response=await fetch('/api/commerce/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product,region:r})});const data=await response.json() as Verified;cache.set(k,data);decorate()}catch{cache.set(k,{product,verified:false,state:'unavailable'});decorate()}finally{pending.delete(k)}}
function ingest(data:unknown){const payload=data as {products?:Product[]};const list=Array.isArray(payload?.products)?payload.products:[];for(const p of list){if(!p?.title)continue;catalogProducts.set(key(p.title),p);if(isShopify(p))void verifyProduct(p)}decorate()}
function applyDisplayPricing(data:unknown){const payload=data as {products?:Product[]};if(!Array.isArray(payload?.products))return data;const products=payload.products.map(p=>{const supplier=Number(p.supplierPrice??p.price);if(!Number.isFinite(supplier)||supplier<=0)return p;const verified=cache.get(key(p.title));if(verified?.verified&&verified.product.retailPrice!=null)return{...p,supplierPrice:supplier,price:verified.product.retailPrice,retailPrice:verified.product.retailPrice,pricingMode:'verified',verified:true};const retail=provisionalRetail({...p,supplierPrice:supplier});return{...p,supplierPrice:supplier,price:retail??p.price,retailPrice:retail??p.price,pricingMode:'provisional'}});return{...(payload as object),products}}

export default function ProductCardEnhancer(){
 const [showRegion,setShowRegion]=useState(false),[bagItem,setBagItem]=useState<Product|null>(null),[bagError,setBagError]=useState(''),[bagBusy,setBagBusy]=useState(false),[creditCents,setCreditCents]=useState(0),[applyCredits,setApplyCredits]=useState(false);const patched=useRef(false);const frame=useRef<number|null>(null);
 useLayoutEffect(()=>{if(patched.current)return;patched.current=true;const native=window.fetch.bind(window);const wrapped=async(input:RequestInfo|URL,init?:RequestInit):Promise<Response>=>{const url=typeof input==='string'?input:input instanceof URL?input.toString():input.url;let nextInit=init;if(url.includes('/api/checkout/quote')&&init?.body&&region()){try{let body=JSON.parse(String(init.body)) as Product&Record<string,unknown>;if(isShopify(body))body=await enrichProduct(body) as typeof body;nextInit={...init,body:JSON.stringify({...body,region:region()})}}catch{}}let response=await native(input,nextInit);if(url.includes('/api/catalog')){try{const data=await response.clone().json();ingest(data);const priced=applyDisplayPricing(data);const headers=new Headers(response.headers);headers.set('content-type','application/json');response=new Response(JSON.stringify(priced),{status:response.status,statusText:response.statusText,headers})}catch{}}if(url.includes('/api/checkout/session')&&response.status===409){try{const data=await response.clone().json() as {error?:string;customerMayContinue?:boolean;repriceToken?:string;changePct?:number;freshPrice?:number;currency?:string};if(data.error==='PRICE_CHANGED_SIGNIFICANT'&&data.customerMayContinue&&data.repriceToken){const ok=window.confirm(`The supplier price increased ${data.changePct}%. The updated price is ${money(Number(data.freshPrice),String(data.currency||'EUR'))}. Continue?`);if(ok)response=await native(input,{...init,body:JSON.stringify({token:data.repriceToken,acceptPriceChange:true})})}}catch{}}return response};(window as typeof window&{fetch:typeof fetch}).fetch=wrapped as typeof fetch;return()=>{(window as typeof window&{fetch:typeof fetch}).fetch=native as typeof fetch}},[]);
 useEffect(()=>{let live=true;const sync=async()=>{try{const response=await fetch("/api/circle");const data=await response.json() as {members?:CircleMember[]};if(live&&Array.isArray(data.members)){circleMembers=data.members;decorate()}}catch{}};void sync();const rotate=window.setInterval(()=>{circleProofTick+=1;decorate()},4200),refresh=window.setInterval(()=>void sync(),30000);return()=>{live=false;window.clearInterval(rotate);window.clearInterval(refresh)}},[]);
 useEffect(()=>{setShowRegion(!region());decorate();const schedule=()=>{if(frame.current!=null)return;frame.current=requestAnimationFrame(()=>{frame.current=null;decorate()})};const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});const onRegion=()=>{cache.clear();for(const p of catalogProducts.values())if(isShopify(p))void verifyProduct(p)};
  const clicks=(event:MouseEvent)=>{const target=event.target as HTMLElement|null;const orb=target?.closest('.lv4-product') as HTMLElement|null;if(orb){const title=orb.querySelector('.lv4-product-tooltip b')?.textContent||'';const p=productForTitle(title);if(p)void enrichProduct(p).then(()=>setTimeout(decorate,0)).catch(()=>{});return}
   const action=target?.closest('.lv4-actions > a,.lv4-actions > button:first-child') as HTMLElement|null;if(action){const detail=action.closest('.lv4-detail');const root=detail?.querySelector('.lv4-detailcopy');const title=root?.querySelector('h2')?.textContent||'';const base=productForTitle(title);if(!base)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();const chosen=selectedVariant(root!,base);setBagError('');setBagItem(chosen);void enrichProduct(chosen).then(p=>setBagItem(selectedVariant(root!,p))).catch(()=>{});return}
  };
  window.addEventListener('ynot:region-changed',onRegion);document.addEventListener('click',clicks,true);return()=>{observer.disconnect();if(frame.current!=null)cancelAnimationFrame(frame.current);window.removeEventListener('ynot:region-changed',onRegion);document.removeEventListener('click',clicks,true)}},[]);
 useEffect(()=>{if(!bagItem){setCreditCents(0);setApplyCredits(false);return}let live=true;void fetch('/api/circle').then(r=>r.json()).then(data=>{if(live)setCreditCents(Number(data.balanceCents||0))}).catch(()=>{});return()=>{live=false}},[bagItem]);
 async function startCheckout(){if(!bagItem)return;setBagBusy(true);setBagError('');try{const exact=isShopify(bagItem)?await enrichProduct(bagItem):bagItem;const response=await fetch('/api/checkout/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...exact,price:exact.supplierPrice??exact.price,category:inferCategory(exact)})});const quote=await response.json();if(!response.ok)throw new Error(quote.error||quote.reason?.join?.(', ')||'This product cannot be verified for checkout yet');const sessionResponse=await fetch('/api/checkout/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:quote.token,applyCredits})});const session=await sessionResponse.json();if(!sessionResponse.ok||!session.url)throw new Error(session.error||'Checkout unavailable');window.location.assign(session.url)}catch(e){setBagError(e instanceof Error?e.message.replaceAll('_',' '):'Checkout unavailable')}finally{setBagBusy(false)}}
 function choose(country:string){localStorage.setItem('ynot-region',JSON.stringify({country}));setShowRegion(false);window.dispatchEvent(new Event('ynot:region-changed'))}
 const bagPrice=bagItem?provisionalRetail(bagItem):null;
 return <>{showRegion&&<div className="ynot-region-backdrop"><section className="ynot-region-card"><small>SHOPPING REGION</small><h2>Where are we delivering?</h2><p>YNOT uses this to verify supplier availability and shipping before products receive the verified tick.</p><div>{COUNTRIES.map(([code,label])=><button key={code} onClick={()=>choose(code)}><b>{label}</b><span>{code}</span></button>)}</div></section></div>}{bagItem&&<div className="ynot-checkout-backdrop" onClick={()=>!bagBusy&&setBagItem(null)}><section className="ynot-glass-checkout" onClick={e=>e.stopPropagation()}><button className="ynot-checkout-close" onClick={()=>setBagItem(null)} aria-label="Close">×</button><small>YOUR BAG</small><div className="ynot-checkout-product">{bagItem.image&&<img src={bagItem.image} alt=""/>}<div><b>{bagItem.title}</b><span>{bagItem.brand||'Independent store'}</span>{bagItem.variantId&&<em>Selected option · {bagItem.variants?.find(v=>String(v.id)===String(bagItem.variantId))?.label||'Variant'}</em>}</div><strong>{bagPrice!=null?money(bagPrice,bagItem.currency||'EUR'):'Checking…'}</strong></div><div className="ynot-checkout-line"><span>Shipping</span><b>Calculated from your delivery region</b></div><div className="ynot-checkout-line"><span>Price & availability</span><b>Rechecked before payment</b></div>{creditCents>0&&bagItem.currency?.toUpperCase()==='EUR'&&<label className="ynot-credit-toggle"><div><b>YNOT Credits · {money(creditCents/100,'EUR')} available</b><small>Apply up to 15% of this product</small></div><input type="checkbox" checked={applyCredits} onChange={e=>setApplyCredits(e.target.checked)}/></label>}{bagError&&<p className="ynot-checkout-error">{bagError}. You have not been charged.</p>}<button className="ynot-checkout-pay" onClick={()=>void startCheckout()} disabled={bagBusy}>{bagBusy?'Verifying product, option & delivery…':'Checkout'}</button></section></div>}</>;
}
