"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,ChevronLeft,LogIn,Save,UserRound,X} from "lucide-react";
type Saved={id:string;[key:string]:unknown};
type Profile={name:string;avatar:string;hasPin:boolean};
function localSaves(){try{const value=JSON.parse(localStorage.getItem("ynot-saved-items")||"[]");return Array.isArray(value)?value:[]}catch{return[]}}
function mergeSaves(remote:Saved[]){const all=[...remote,...localSaves()] as Saved[],seen=new Set<string>(),merged=all.filter(item=>{if(!item?.id||seen.has(item.id))return false;seen.add(item.id);return true});localStorage.setItem("ynot-saved-items",JSON.stringify(merged));localStorage.setItem("ynot-saved-products",JSON.stringify(merged.map(item=>item.id)));window.dispatchEvent(new Event("ynot:saves-changed"))}
async function imageData(file:File){if(!file.type.startsWith("image/")||file.size>6_000_000)throw new Error("Choose an image under 6 MB");const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement("canvas");canvas.width=256;canvas.height=256;const ctx=canvas.getContext("2d")!;const scale=Math.max(256/img.width,256/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(256-w)/2,(256-h)/2,w,h);return canvas.toDataURL("image/webp",.78)}finally{URL.revokeObjectURL(url)}}
export default function ProfilePanel(){
 const [open,setOpen]=useState(false),[restore,setRestore]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[name,setName]=useState(""),[pin,setPin]=useState(""),[avatar,setAvatar]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const syncTimer=useRef<number|null>(null);
 async function load(){try{const data=await fetch("/api/profile").then(r=>r.json());if(data.profile){setProfile(data.profile);setName(data.profile.name||"");setAvatar(data.profile.avatar||"");mergeSaves(data.saves||[])}}catch{}}
 useEffect(()=>{void load();const show=()=>setOpen(true),sync=()=>{if(!profile?.hasPin)return;if(syncTimer.current)clearTimeout(syncTimer.current);syncTimer.current=window.setTimeout(()=>void fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({saves:localSaves()})}),700)};window.addEventListener("ynot:open-profile",show);window.addEventListener("ynot:saves-changed",sync);return()=>{window.removeEventListener("ynot:open-profile",show);window.removeEventListener("ynot:saves-changed",sync);if(syncTimer.current)clearTimeout(syncTimer.current)}},[profile?.hasPin]);
 async function submit(){setBusy(true);setError("");try{const response=await fetch("/api/profile",{method:restore?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(restore?{name,pin}:{name,pin,avatar,saves:localSaves()})});const data=await response.json();if(!response.ok)throw new Error(String(data.error||"Unable to save profile").replaceAll("_"," "));setProfile(data.profile);setAvatar(data.profile?.avatar||avatar);mergeSaves(data.saves||[]);setRestore(false);setPin("");setOpen(false)}catch(e){setError(e instanceof Error?e.message:"Unable to save profile")}finally{setBusy(false)}}
 return <><button className="ynot-profile-orb" onClick={()=>setOpen(true)} aria-label="Open profile">{avatar?<img src={avatar} alt=""/>:<UserRound/>}</button>{open&&<div className="ynot-profile-shell"><button className="ynot-profile-backdrop" onClick={()=>setOpen(false)} aria-label="Close profile"/><aside className="ynot-profile-panel"><button className="ynot-profile-close" onClick={()=>setOpen(false)}><X/></button><small>YNOT PROFILE</small><h2>{restore?"Remember my account":"Your shopping world"}</h2><label className="ynot-profile-photo">{avatar?<img src={avatar} alt="Profile preview"/>:<UserRound/>}<span><Camera/> Add profile picture</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(file)try{setAvatar(await imageData(file))}catch(err){setError(err instanceof Error?err.message:"Invalid image")}}}/></label><label><span>Name</span><input value={name} maxLength={30} onChange={e=>setName(e.target.value)} placeholder="Your memorable name"/></label><label><span>4-digit PIN</span><input value={pin} inputMode="numeric" pattern="[0-9]*" maxLength={4} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} placeholder="••••" type="password"/></label>{error&&<p>{error}</p>}<button className="ynot-profile-submit" disabled={busy||name.trim().length<2||pin.length!==4} onClick={()=>void submit()}>{restore?<LogIn/>:<Save/>}{busy?"Please wait…":restore?"Restore profile & saves":"Save profile"}</button><button className="ynot-profile-mode" onClick={()=>{setRestore(v=>!v);setError("");setPin("")}}><ChevronLeft/>{restore?"Create or update profile":"Already have a name and PIN?"}</button><footer>Your PIN is encrypted. Five failed attempts temporarily lock restoration. Your Circle can see your name and profile image.</footer></aside></div>}</>
}
