"use client";
import {useEffect,useState} from "react";
import {Globe2,Pencil,Plus,Share2,Users,X} from "lucide-react";
import {authedFetch,readSession} from "../../lib/ynot/supabase-browser";

type SavedItem={id:string;title:string;brand?:string;price?:number;currency?:string;image:string;url?:string;source?:string;description?:string;images?:string[]};
type World={id:string;name:string;description?:string;role:"owner"|"contributor"|"viewer";updated_at?:string};
const STORAGE="ynot-saved-items",NAME_KEY="ynot-saves-name";
function loadSaved():SavedItem[]{try{const p=JSON.parse(localStorage.getItem(STORAGE)||"[]");return Array.isArray(p)?p:[]}catch{return[]}}
function loadName(){try{return localStorage.getItem(NAME_KEY)||"Your Saves"}catch{return"Your Saves"}}

export default function SavedNotebook(){
 const[open,setOpen]=useState(false),[items,setItems]=useState<SavedItem[]>([]),[worlds,setWorlds]=useState<World[]>([]),[creating,setCreating]=useState(false),[worldName,setWorldName]=useState(""),[savesName,setSavesName]=useState("Your Saves"),[renameOpen,setRenameOpen]=useState(false),[worldOpen,setWorldOpen]=useState(false),[share,setShare]=useState("");
 async function refreshWorlds(){if(!readSession()){setWorlds([]);return}const r=await authedFetch("/api/worlds"),d=await r.json().catch(()=>({}));if(r.ok)setWorlds(d.worlds||[])}
 useEffect(()=>{const refresh=()=>setItems(loadSaved()),show=()=>{refresh();setSavesName(loadName());void refreshWorlds();setOpen(true)};window.addEventListener("ynot:open-saves",show);window.addEventListener("ynot:saves-changed",refresh);return()=>{window.removeEventListener("ynot:open-saves",show);window.removeEventListener("ynot:saves-changed",refresh)}},[]);
 useEffect(()=>{document.documentElement.classList.toggle("ynot-saves-open",open);return()=>document.documentElement.classList.remove("ynot-saves-open")},[open]);
 useEffect(()=>{const token=new URLSearchParams(location.search).get("worldInvite");if(!token)return;if(!readSession()){window.dispatchEvent(new Event("ynot:open-auth"));return}authedFetch("/api/worlds/invite",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})}).then(r=>{if(r.ok){history.replaceState(null,"",location.pathname);void refreshWorlds();setOpen(true)}}).catch(()=>{})},[]);
 async function createWorld(){if(!readSession()){window.dispatchEvent(new Event("ynot:open-auth"));return}if(!items.length)return;const clean=worldName.trim()||"New World";setCreating(true);try{const r=await authedFetch("/api/worlds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:clean,products:items,tags:items.map(x=>x.brand).filter(Boolean)})});if(r.ok){setWorldName("");setWorldOpen(false);await refreshWorlds()}}finally{setCreating(false)}}
 async function invite(w:World){if(w.role!=="owner")return;const r=await authedFetch("/api/worlds/invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({worldId:w.id,role:"contributor"})}),d=await r.json().catch(()=>({}));if(r.ok)setShare(d.url||"")}
 function close(){setRenameOpen(false);setWorldOpen(false);setOpen(false)}
 function saveRename(){const clean=savesName.trim()||"Your Saves";setSavesName(clean);try{localStorage.setItem(NAME_KEY,clean)}catch{}setRenameOpen(false)}
 function openSavedProduct(item:SavedItem){setOpen(false);requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent("ynot:open-story",{detail:{...item,section:"Saved",sections:["Saved"],badge:"Saved",note:item.brand||item.source||"Saved product"}})))}
 if(!open)return null;
 return <div className="ynot-notebook-shell" role="dialog" aria-modal="true" aria-label="YNOT Saves"><div className="ynot-notebook-backdrop" onClick={close}/><section className="ynot-notebook ynot-world-library"><div className="ynot-saves-brand" aria-label="YNOT World"><span>YNOT</span><b>WORLD</b></div><div className="ynot-saves-tools"><button className="ynot-saves-edit" aria-label="Name your Saves" onClick={()=>setRenameOpen(true)}><Pencil/></button><button className="ynot-saves-add" aria-label="Create a World" onClick={()=>setWorldOpen(true)}><Plus/></button></div><button className="ynot-notebook-close" aria-label="Close Saves" onPointerDown={e=>{e.preventDefault();e.stopPropagation();close()}} onClick={close}><X/></button><header className="ynot-notebook-head"><small>YNOT LIBRARY</small><h2>{savesName}</h2><span>{items.length} saved</span></header>{worlds.length?<div className="ynot-world-list">{worlds.map(w=><article key={w.id} className="ynot-world-row"><span className="ynot-world-icon"><Globe2/></span><div><b>{w.name}</b><small><Users/> {w.role}</small></div>{w.role==="owner"?<button onClick={()=>void invite(w)}><Share2/> Invite</button>:<span className="ynot-world-role">Shared</span>}</article>)}</div>:null}{share?<div className="ynot-world-share"><b>Contributor link ready</b><input readOnly value={share}/></div>:null}<div className="ynot-notebook-grid">{items.map(item=><button key={item.id} className="ynot-save-orb" aria-label={`Open ${item.title}`} title={item.title} onClick={()=>openSavedProduct(item)}><span className="ynot-save-orb-gloss"/><img loading="lazy" src={item.image} alt=""/></button>)}{!items.length&&<p className="ynot-notebook-empty">Products you save will appear here.</p>}</div>{renameOpen&&<div className="ynot-saves-mini-backdrop" onClick={()=>setRenameOpen(false)}><div className="ynot-saves-mini" onClick={e=>e.stopPropagation()}><small>NAME YOUR SAVES</small><input autoFocus value={savesName} maxLength={48} onChange={e=>setSavesName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")saveRename()}}/><button onClick={saveRename}>Save name</button></div></div>}{worldOpen&&<div className="ynot-saves-mini-backdrop" onClick={()=>setWorldOpen(false)}><div className="ynot-saves-mini" onClick={e=>e.stopPropagation()}><small>CREATE A WORLD</small><input autoFocus value={worldName} maxLength={80} placeholder="World name" onChange={e=>setWorldName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void createWorld()}}/><p>Creates a World from your current saved products.</p><button disabled={creating||!items.length} onClick={()=>void createWorld()}>{creating?"Creating…":"Create World"}</button></div></div>}</section></div>}
