export type WorldRoot="fashion"|"fitness"|"skin"|"hair"|"home"|"tech"|"retail";
export type ShopCategory={id:string;label:string;root:WorldRoot;query:string;sub:string[]};

export const SHOP_TAXONOMY:ShopCategory[]=[
 {id:"fashion",label:"Fashion",root:"fashion",query:"fashion clothing style",sub:["Women","Men","Dresses","Tops","Bottoms","Denim","Knitwear","Outerwear","Activewear","Swimwear","Lingerie","Streetwear","Occasionwear","Vintage","Handmade Fashion"]},
 {id:"jewelry",label:"Jewelry & Accessories",root:"fashion",query:"jewelry accessories",sub:["Rings","Necklaces","Earrings","Bracelets","Charms","Fine Jewelry","Handmade Jewelry","Watches","Sunglasses","Hats","Scarves","Belts","Wallets"]},
 {id:"shoes",label:"Shoes",root:"fashion",query:"shoes footwear",sub:["Sneakers","Trainers","Heels","Boots","Sandals","Flats","Loafers","Running Shoes","Hiking Shoes","Slippers","Handmade Shoes"]},
 {id:"bags",label:"Bags & Travel",root:"fashion",query:"bags travel accessories",sub:["Handbags","Shoulder Bags","Crossbody","Tote Bags","Backpacks","Clutches","Travel Bags","Luggage","Laptop Bags","Pouches"]},
 {id:"beauty",label:"Beauty & Personal Care",root:"skin",query:"beauty personal care skincare",sub:["Skincare","Makeup","Hair Care","Hair Accessories","Fragrance","Bath & Body","Nails","Grooming","Beauty Tools","Natural Beauty","Self-Care Sets"]},
 {id:"hair",label:"Hair",root:"hair",query:"hair care styling",sub:["Shampoo","Conditioner","Repair","Scalp Care","Styling","Hair Tools","Volume","Curl Care","Hair Oils","Hair Accessories"]},
 {id:"home",label:"Home & Living",root:"home",query:"home living decor furniture",sub:["Furniture","Home Decor","Lighting","Kitchen","Dining","Bedding","Bathroom","Storage","Rugs","Wall Art","Mirrors","Candles","Garden","Outdoor Living","Handmade Home"]},
 {id:"fitness",label:"Fitness & Sports",root:"fitness",query:"fitness sports activewear",sub:["Activewear","Gym Clothing","Training Gear","Home Gym","Running","Yoga","Pilates","Cycling","Recovery","Outdoor Sports","Sports Accessories"]},
 {id:"tech",label:"Tech & Gadgets",root:"tech",query:"tech gadgets electronics",sub:["Phones","Phone Accessories","Computers","Computer Accessories","Audio","Headphones","Speakers","Gaming","Smart Home","Wearables","Cameras","Desk Tech","Charging","Gadgets"]},
 {id:"ai",label:"AI & Automation",root:"tech",query:"AI tools automation digital products",sub:["AI Tools","ChatGPT & Prompts","AI Agents","Automation","Content AI","Design AI","Business AI","Productivity AI","Developer AI","No-Code Tools","AI Templates","AI Workflows"]},
 {id:"learning",label:"Courses & Learning",root:"retail",query:"online course coaching training education digital",sub:["Online Courses","Coaching","AI Training","Business & Marketing","Fitness Coaching","Language Learning","Creative Skills","Career Skills","Coding & Tech","Finance Education","Personal Development","Teacher Resources","Exam Prep","Music Lessons","Photography Courses"]},
 {id:"digital",label:"Digital Products",root:"retail",query:"digital downloads templates ebooks printables",sub:["Ebooks","Guides","Printables","Digital Planners","Notion Templates","Canva Templates","Spreadsheets","Presets","Fonts","Icons","Mockups","Website Templates","Shopify Themes","App Templates","Stock Photos","Video Assets","Music & SFX","SVG & Cricut Files"]},
 {id:"business",label:"Business & Professional",root:"retail",query:"business professional templates marketing assets services",sub:["Business Templates","Marketing Templates","Social Media Kits","Branding Kits","Email Templates","Sales Scripts","SOPs","Business Plans","Resume & CV","Portfolio Templates","Client Forms","Invoice Templates","Presentation Templates","Consulting","Design Services","Marketing Services"]},
 {id:"memberships",label:"Memberships & Subscriptions",root:"retail",query:"membership subscription community digital access",sub:["Memberships","Communities","Paid Newsletters","Masterminds","Resource Libraries","Subscription Boxes","Clubs","VIP Access","Monthly Downloads","Creator Memberships"]},
 {id:"books",label:"Books & Media",root:"retail",query:"books media reading music entertainment",sub:["Books","Ebooks","Magazines","Journals","Comics","Audiobooks","Music","Vinyl","Digital Media","Educational Books"]},
 {id:"auto",label:"Auto & Mobility",root:"tech",query:"automotive car motorcycle accessories",sub:["Car Accessories","Car Care","Interior Accessories","Exterior Accessories","Motorcycle","Cycling Accessories","EV Accessories","Dash Cams","Car Tech","Travel Safety"]},
 {id:"tools",label:"Tools & DIY",root:"home",query:"tools diy hardware workshop home improvement",sub:["Hand Tools","Power Tools","DIY Kits","Hardware","Workshop","Painting","Home Improvement","Safety Gear","Organization","Craft Tools"]},
 {id:"outdoors",label:"Outdoor & Adventure",root:"fitness",query:"outdoor adventure camping hiking travel",sub:["Camping","Hiking","Travel Gear","Outdoor Clothing","Outdoor Cooking","Hydration","Backpacks","Survival Gear","Beach","Fishing","Adventure Accessories"]},
 {id:"spiritual",label:"Spirituality & Mindfulness",root:"retail",query:"spiritual mindfulness crystals tarot astrology",sub:["Crystals","Tarot","Oracle Cards","Astrology","Meditation","Incense","Candles","Ritual Tools","Journals","Affirmations","Energy Healing"]},
 {id:"gifts",label:"Gifts",root:"retail",query:"gifts handmade personalized",sub:["Gifts for Her","Gifts for Him","Couples","Birthday","Wedding","Anniversary","Baby","Housewarming","Personalized Gifts","Handmade Gifts","Gift Boxes","Stocking Fillers"]},
 {id:"art",label:"Art & Creative",root:"retail",query:"art creative handmade",sub:["Prints","Original Art","Photography","Posters","Sculptures","Ceramics","Handmade Art","Craft Supplies","Sewing","Knitting","Crochet","Stationery","Digital Downloads"]},
 {id:"kids",label:"Kids & Baby",root:"retail",query:"kids baby products",sub:["Baby Clothes","Kids Clothing","Toys","Nursery","Baby Accessories","Educational Toys","Personalized Kids Gifts","Kids Decor"]},
 {id:"pets",label:"Pets",root:"retail",query:"pet products accessories",sub:["Dog","Cat","Pet Clothing","Collars & Leads","Beds","Toys","Feeding","Pet Accessories","Personalized Pet Gifts"]},
 {id:"kitchen",label:"Food & Kitchen",root:"home",query:"food kitchen drinkware",sub:["Kitchen Tools","Drinkware","Coffee","Tea","Baking","Tableware","Food Storage","Barware","Specialty Food Gifts"]},
 {id:"wellness",label:"Wellness",root:"skin",query:"wellness self care",sub:["Self Care","Massage","Sleep","Meditation","Aromatherapy","Recovery","Wellness Accessories"]},
 {id:"office",label:"Office & Stationery",root:"home",query:"office stationery desk",sub:["Notebooks","Journals","Planners","Pens","Desk Accessories","Office Decor","Laptop Accessories","Personalized Stationery"]},
 {id:"weddings",label:"Weddings & Events",root:"retail",query:"wedding event party",sub:["Wedding Decor","Invitations","Bridal Accessories","Bridesmaid Gifts","Groom Gifts","Party Decor","Favors","Guest Books"]},
 {id:"seasonal",label:"Seasonal",root:"retail",query:"seasonal holiday products",sub:["Christmas","Halloween","Valentine's","Easter","Summer","Autumn","Holiday Decor","Seasonal Gifts"]},
 {id:"vintage",label:"Collectibles & Vintage",root:"retail",query:"vintage collectibles antiques",sub:["Vintage Clothing","Vintage Decor","Memorabilia","Collectibles","Antiques","Retro Tech","Rare Finds"]},
 {id:"discover",label:"Discover",root:"retail",query:"interesting trending products",sub:["Trending","New Arrivals","Handmade","Independent Brands","Personalized","Digital Products","Courses","AI Tools","Under €25","Under €50","Premium","Most Unique","YNOT Picks"]}
];

export const ALL_SUBCATEGORIES=[...new Set(SHOP_TAXONOMY.flatMap(category=>category.sub))];
export function taxonomyCategory(id:string){return SHOP_TAXONOMY.find(category=>category.id===id)||SHOP_TAXONOMY[0]}
