"use client";

import {useCallback,useMemo,useState} from "react";
import {ChevronLeft} from "lucide-react";
import {SHOP_TAXONOMY,taxonomyCategory,type ShopCategory} from "./shopTaxonomy";

type Stage="category"|"subcategory"|"attributes";

const ROOT_DEFAULT:Record<string,string>={fashion:"fashion",fitness:"fitness",skin:"beauty",hair:"hair",home:"home",tech:"tech",retail:"discover"};
const COMMON=["New Arrivals","Best Value","Premium","Popular","Under €25","Under €50"];
const STYLE=["Minimal","Statement","Vintage","Modern","Classic","Boho","Handmade","Personalized"];
const COLOR=["Black","White","Neutral","Brown","Blue","Green","Pink","Red"];
const MATERIAL=["Cotton","Linen","Leather","Silk","Wool","Silver","Gold","Wood"];

const EXACT:Record<string,string[]>={
 "Women":["Casual","Workwear","Occasion","Streetwear","Minimal","Plus Size","Petite","Premium"],"Men":["Casual","Smart Casual","Streetwear","Workwear","Minimal","Oversized","Premium","Under €100"],
 "Dresses":["Mini","Midi","Maxi","Bodycon","A-Line","Satin","Wedding Guest","Summer"],"Tops":["T-Shirts","Blouses","Shirts","Knitwear","Crop","Tank","Long Sleeve","Oversized"],"Bottoms":["Jeans","Trousers","Skirts","Shorts","Leggings","Cargo","Wide Leg","Tailored"],"Denim":["Straight","Wide Leg","Skinny","Bootcut","High Rise","Low Rise","Dark Wash","Light Wash"],"Knitwear":["Sweaters","Cardigans","Vests","Cashmere","Oversized","Cropped","Fine Knit","Chunky"],"Outerwear":["Coats","Jackets","Blazers","Trench","Puffer","Leather","Denim Jacket","Rainwear"],"Swimwear":["Bikinis","One Piece","High Waist","Triangle","Cover Ups","Plus Size","Minimal","Resort"],"Lingerie":["Bras","Briefs","Sets","Bodysuits","Lace","Seamless","Sleepwear","Shapewear"],"Streetwear":["Oversized","Graphic","Cargo","Hoodies","Sneakers","Unisex","Vintage","Limited"],"Occasionwear":["Wedding Guest","Party","Evening","Cocktail","Formal","Satin","Sequins","Premium"],
 "Rings":["Silver","Gold","Signet","Stacking","Gemstone","Minimal","Personalized","Vintage"],"Necklaces":["Pendant","Chain","Choker","Layered","Silver","Gold","Personalized","Gemstone"],"Earrings":["Studs","Hoops","Drop","Statement","Silver","Gold","Pearl","Handmade"],"Bracelets":["Chain","Cuff","Charm","Beaded","Silver","Gold","Personalized","Minimal"],"Charms":["Initial","Birthstone","Zodiac","Travel","Heart","Personalized","Silver","Gold"],"Fine Jewelry":["Diamond","Gold","White Gold","Gemstone","Luxury","Minimal","Gift","Heirloom"],"Handmade Jewelry":["Silver","Gold Filled","Clay","Beaded","Resin","Wire Wrapped","Personalized","Artisan"],"Watches":["Smart","Analog","Minimal","Leather Strap","Metal Bracelet","Sport","Luxury","Vintage"],"Sunglasses":["Round","Square","Aviator","Cat Eye","Oversized","Polarized","Black","Tortoiseshell"],
 "Sneakers":["Lifestyle","Running","Retro","Platform","Low Top","High Top","White","Limited"],"Trainers":["Gym","Running","Cross Training","Walking","Lightweight","Cushioned","Neutral","Performance"],"Heels":["Kitten","Block","Stiletto","Platform","Slingback","Black","Nude","Occasion"],"Boots":["Ankle","Knee High","Chelsea","Combat","Western","Leather","Black","Winter"],"Sandals":["Slides","Strappy","Platform","Flat","Leather","Beach","Minimal","Comfort"],"Loafers":["Leather","Suede","Chunky","Classic","Black","Brown","Office","Premium"],
 "Handbags":["Leather","Mini","Structured","Shoulder","Top Handle","Black","Neutral","Premium"],"Shoulder Bags":["Mini","Hobo","Leather","Chain Strap","Black","Brown","Statement","Everyday"],"Crossbody":["Mini","Leather","Camera Bag","Phone Bag","Travel","Black","Neutral","Lightweight"],"Tote Bags":["Canvas","Leather","Work","Beach","Large","Foldable","Personalized","Minimal"],"Backpacks":["Laptop","Travel","Leather","Waterproof","Minimal","School","Hiking","Lightweight"],"Clutches":["Evening","Satin","Beaded","Metallic","Black","Wedding","Minimal","Statement"],"Luggage":["Carry On","Hard Shell","Soft Shell","Cabin","Lightweight","Expandable","Sets","Premium"],
 "Skincare":["Dry Skin","Oily Skin","Sensitive","Acne","Glow","Barrier Repair","Anti-Aging","Fragrance Free"],"Makeup":["Foundation","Concealer","Blush","Bronzer","Eyes","Lips","Natural","Longwear"],"Fragrance":["Floral","Woody","Fresh","Gourmand","Citrus","Unisex","Travel Size","Luxury"],"Bath & Body":["Body Wash","Body Lotion","Scrub","Bath Salts","Body Oil","Natural","Gift Set","Sensitive"],"Nails":["Polish","Gel","Press Ons","Nail Art","Tools","Neutral","Bold","Sets"],"Grooming":["Beard","Shaving","Trimmers","Body Care","Hair Removal","Travel","Natural","Gift Sets"],"Beauty Tools":["LED","Gua Sha","Rollers","Brushes","Cleansing","Hair Removal","Travel","Professional"],
 "Shampoo":["Repair","Hydrating","Volume","Curly","Color Safe","Clarifying","Sensitive Scalp","Sulfate Free"],"Conditioner":["Repair","Hydrating","Leave In","Curly","Fine Hair","Color Safe","Deep Treatment","Silicone Free"],"Scalp Care":["Dry Scalp","Oily Scalp","Dandruff","Growth","Serums","Oils","Massagers","Clarifying"],"Styling":["Heat Protectant","Texture","Volume","Curl","Smoothing","Hold","Cream","Spray"],"Hair Tools":["Dryers","Straighteners","Curlers","Brushes","Hot Brushes","Diffusers","Cordless","Professional"],
 "Furniture":["Sofas","Chairs","Tables","Shelving","Bedroom","Office","Small Space","Statement"],"Home Decor":["Wall Decor","Vases","Objects","Cushions","Throws","Minimal","Vintage","Handmade"],"Lighting":["Table Lamps","Floor Lamps","Pendant","Wall Lights","Desk Lamps","Smart","Ambient","Minimal"],"Kitchen":["Cookware","Utensils","Storage","Appliances","Knives","Coffee","Baking","Minimal"],"Dining":["Dinnerware","Glassware","Cutlery","Table Linen","Serving","Ceramic","Handmade","Sets"],"Bedding":["Cotton","Linen","Duvets","Sheets","Throws","Neutral","Luxury","Organic"],"Bathroom":["Towels","Storage","Bath Mats","Dispensers","Mirrors","Natural","Minimal","Spa"],"Rugs":["Wool","Jute","Washable","Vintage","Modern","Neutral","Patterned","Large"],"Wall Art":["Prints","Photography","Abstract","Typography","Vintage","Framed","Original","Gallery Wall"],"Candles":["Soy","Scented","Unscented","Sculptural","Luxury","Personalized","Gift Set","Seasonal"],
 "Activewear":["Leggings","Sports Bras","Sets","Tops","Shorts","Seamless","Running","Yoga"],"Gym Clothing":["Tops","Shorts","Leggings","Hoodies","Sets","Oversized","Compression","Breathable"],"Training Gear":["Bands","Weights","Gloves","Belts","Mats","Bottles","Bags","Home Gym"],"Running":["Shoes","Tops","Shorts","Hydration","GPS","Reflective","Recovery","Race Day"],"Yoga":["Mats","Leggings","Blocks","Straps","Sets","Non Slip","Travel","Eco"],"Pilates":["Grip Socks","Rings","Bands","Mats","Sets","Studio","Home","Beginner"],"Cycling":["Jerseys","Shorts","Helmets","Lights","Bags","Indoor","Road","Accessories"],"Recovery":["Massage Guns","Foam Rollers","Compression","Mobility","Ice & Heat","Sleep","Stretching","Portable"],
 "Phones":["iPhone","Android","Unlocked","Budget","Premium","Compact","Large Screen","Refurbished"],"Phone Accessories":["Cases","Chargers","Power Banks","Stands","Cables","MagSafe","Screen Protectors","Car"],"Computers":["Laptops","Desktop","Mac","Windows","Gaming","Student","Creator","Refurbished"],"Computer Accessories":["Keyboards","Mice","Webcams","Hubs","Monitors","Laptop Stands","Storage","Desk"],"Audio":["Headphones","Earbuds","Speakers","Soundbars","Portable","Noise Cancelling","Wireless","Premium"],"Gaming":["Controllers","Headsets","Keyboards","Mice","Consoles","Desk Setup","RGB","Accessories"],"Smart Home":["Lighting","Security","Speakers","Plugs","Thermostats","Sensors","Voice","Automation"],"Wearables":["Smartwatches","Fitness Trackers","Smart Rings","Bands","Health","Running","Sleep","Premium"],"Cameras":["Mirrorless","Compact","Instant","Action","Lenses","Tripods","Creator","Vintage"],
 "Gifts for Her":["Personalized","Jewelry","Self Care","Home","Fashion","Under €25","Under €50","Luxury"],"Gifts for Him":["Personalized","Tech","Grooming","Fashion","Sports","Under €25","Under €50","Premium"],"Birthday":["Personalized","Funny","Milestone","Handmade","Under €25","Under €50","Luxury","Last Minute"],"Wedding":["Couple","Personalized","Home","Keepsake","Bridal","Groom","Under €50","Premium"],"Personalized Gifts":["Name","Initial","Photo","Date","Message","Birthstone","Custom Color","Made to Order"],"Handmade Gifts":["Ceramic","Jewelry","Textile","Art","Wood","Personalized","Small Business","One of a Kind"],"Gift Boxes":["Self Care","Food","Beauty","Couple","Birthday","Luxury","Personalized","Letterbox"],
 "Prints":["Abstract","Botanical","Typography","Photography","Vintage","Minimal","Colorful","Printable"],"Original Art":["Painting","Drawing","Mixed Media","Abstract","Landscape","Portrait","Small","Statement"],"Photography":["Travel","Nature","Architecture","Black & White","Portrait","Film","Framed","Limited"],"Ceramics":["Mugs","Vases","Bowls","Plates","Sculpture","Hand Thrown","Glazed","Minimal"],"Craft Supplies":["Beads","Fabric","Yarn","Paper","Paint","Tools","Kits","Bulk"],"Sewing":["Fabric","Patterns","Thread","Buttons","Kits","Tools","Embroidery","Beginner"],"Knitting":["Yarn","Patterns","Needles","Kits","Wool","Beginner","Chunky","Gifts"],"Crochet":["Yarn","Patterns","Hooks","Kits","Amigurumi","Beginner","Home","Wearables"],"Stationery":["Notebooks","Cards","Stickers","Pens","Planners","Personalized","Minimal","Cute"],
 "Baby Clothes":["Newborn","0-3 Months","3-6 Months","Organic","Unisex","Personalized","Sets","Gift"],"Kids Clothing":["Girls","Boys","Unisex","Sets","Outerwear","Organic","Personalized","Occasion"],"Toys":["Wooden","Educational","Sensory","STEM","Pretend Play","Outdoor","Personalized","Age 3+"],"Nursery":["Decor","Bedding","Storage","Lighting","Wall Art","Personalized","Neutral","Montessori"],
 "Dog":["Collars","Harnesses","Beds","Toys","Bowls","Clothing","Personalized","Travel"],"Cat":["Beds","Toys","Scratchers","Bowls","Collars","Furniture","Personalized","Indoor"],"Pet Clothing":["Sweaters","Raincoats","Costumes","Harnesses","Small Dog","Large Dog","Personalized","Seasonal"],"Beds":["Orthopedic","Washable","Cave","Raised","Small","Large","Neutral","Travel"],
 "Drinkware":["Mugs","Tumblers","Bottles","Glasses","Travel","Personalized","Ceramic","Insulated"],"Coffee":["Beans","Ground","Mugs","Brewers","Grinders","Accessories","Gift Sets","Specialty"],"Tea":["Loose Leaf","Tea Bags","Matcha","Herbal","Teapots","Infusers","Gift Sets","Organic"],"Baking":["Bakeware","Tools","Decorating","Mixes","Molds","Aprons","Kits","Gifts"],"Tableware":["Plates","Bowls","Cutlery","Glassware","Ceramic","Handmade","Sets","Minimal"],
 "Self Care":["Bath","Sleep","Aromatherapy","Journaling","Massage","Beauty","Gift Sets","Natural"],"Massage":["Massage Guns","Rollers","Oils","Neck","Foot","Heat","Portable","Recovery"],"Sleep":["Masks","Pillows","Bedding","Sound","Aromatherapy","Cooling","Travel","Wellness"],"Meditation":["Cushions","Mats","Candles","Incense","Sound","Journals","Beginners","Gifts"],"Aromatherapy":["Diffusers","Essential Oils","Candles","Roll Ons","Sleep","Relaxation","Gift Sets","Natural"],
 "Notebooks":["Lined","Dotted","Blank","Hardcover","Leather","Personalized","Minimal","A5"],"Journals":["Guided","Gratitude","Wellness","Travel","Leather","Personalized","Undated","Gift"],"Planners":["Daily","Weekly","Monthly","Academic","Undated","Minimal","Digital","Personalized"],"Pens":["Fountain","Gel","Ballpoint","Brush","Sets","Luxury","Personalized","Fine Tip"],"Desk Accessories":["Organizers","Stands","Mats","Lighting","Cable Management","Minimal","Wood","Personalized"],
 "Wedding Decor":["Signs","Table Decor","Candles","Flowers","Backdrop","Rustic","Minimal","Personalized"],"Invitations":["Minimal","Floral","Modern","Vintage","Digital","Printed","Personalized","Sets"],"Bridal Accessories":["Veils","Hair","Jewelry","Shoes","Bags","Garters","Pearls","Personalized"],"Bridesmaid Gifts":["Personalized","Jewelry","Robes","Bags","Drinkware","Self Care","Under €25","Gift Boxes"],"Favors":["Personalized","Candles","Edible","Drinkware","Mini Gifts","Rustic","Modern","Bulk"],
 "Christmas":["Decor","Ornaments","Stockings","Gifts","Cards","Personalized","Handmade","Under €25"],"Halloween":["Decor","Costumes","Party","Candles","Jewelry","Kids","Gifts","Handmade"],"Valentine's":["Jewelry","Personalized","Couple","Flowers","Self Care","Cards","Under €25","Romantic"],"Easter":["Baskets","Kids","Decor","Personalized","Chocolate","Crafts","Spring","Gifts"],
 "Vintage Clothing":["90s","80s","70s","Y2K","Designer","Denim","Leather","Rare"],"Vintage Decor":["Mid Century","Art Deco","Cottage","Ceramic","Glass","Brass","Wall Art","Rare"],"Memorabilia":["Sports","Music","Film","Gaming","Signed","Vintage","Limited","Rare"],"Collectibles":["Figures","Cards","Coins","Stamps","Toys","Art","Limited","Rare"],"Antiques":["Furniture","Jewelry","Silver","Ceramics","Art","Books","Decor","19th Century"],"Retro Tech":["Cameras","Audio","Gaming","Phones","Computers","Accessories","90s","80s"]
};

function attributesFor(label:string){
 const exact=EXACT[label];if(exact)return exact;
 const l=label.toLowerCase();
 if(/clothing|clothes|fashion|wear|tops|shorts|leggings|bras|sets/.test(l))return ["XS-S","M-L","XL+","Black","Neutral","Cotton","Relaxed Fit","Fitted"];
 if(/shoe|boots|sneaker|sandal|loafer|slipper/.test(l))return ["Black","White","Neutral","Leather","Suede","Comfort","Wide Fit","Premium"];
 if(/bag|wallet|pouch/.test(l))return ["Mini","Medium","Large","Leather","Canvas","Black","Neutral","Personalized"];
 if(/jewelry|ring|necklace|earring|bracelet|watch|accessor/.test(l))return ["Silver","Gold","Minimal","Statement","Personalized","Handmade","Vintage","Gift"];
 if(/home|decor|furniture|rug|mirror|garden|outdoor|office/.test(l))return ["Minimal","Modern","Vintage","Neutral","Natural Materials","Small Space","Handmade","Premium"];
 if(/beauty|skin|body|hair|nail|groom/.test(l))return ["Sensitive","Natural","Vegan","Fragrance Free","Travel Size","Professional","Gift Set","Premium"];
 if(/tech|phone|computer|audio|gaming|camera|charging|gadget/.test(l))return ["Wireless","Portable","Compact","Smart","USB-C","Budget","Premium","Top Rated"];
 if(/gift|wedding|birthday|anniversary|baby|housewarming/.test(l))return ["Personalized","Handmade","Under €25","Under €50","Premium","Fast Gift","For Her","For Him"];
 if(/art|print|photo|poster|sculpt|ceramic|craft|sewing|knitting|crochet/.test(l))return ["Handmade","Original","Personalized","Minimal","Colorful","Vintage","Digital","One of a Kind"];
 if(/kid|baby|toy|nursery/.test(l))return ["Newborn","Toddler","Age 3+","Educational","Organic","Unisex","Personalized","Gift"];
 if(/dog|cat|pet/.test(l))return ["Small","Medium","Large","Washable","Natural","Personalized","Travel","Gift"];
 if(/food|coffee|tea|baking|drink|tableware|kitchen/.test(l))return ["Organic","Artisan","Gift Set","Personalized","Reusable","Handmade","Premium","Under €25"];
 if(/season|christmas|halloween|easter|valentine|summer|autumn/.test(l))return ["Decor","Gift","Personalized","Handmade","Kids","Home","Under €25","Limited"];
 if(/vintage|collect|antique|retro|rare/.test(l))return ["Vintage","Rare","Limited","Original","Restored","Under €50","Premium","Collector"];
 return [...STYLE.slice(0,4),...COMMON.slice(0,4)];
}

function setInput(input:HTMLInputElement,value:string){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;setter?.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}))}
function searchNow(category:ShopCategory,subcategory?:string,attributes:string[]=[]){
 const terms=[category.query,subcategory,...attributes].filter(Boolean).join(" ");
 const tags=[subcategory,...attributes].filter(Boolean) as string[];
 window.dispatchEvent(new CustomEvent("shop:tags-changed",{detail:{tags,root:category.root,path:subcategory?[subcategory,...attributes]:[]}}));
 const input=document.querySelector<HTMLInputElement>(".lv4-search input");if(input){setInput(input,terms);requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>(".lv4-search button")?.click())}
}

export default function SubcategoryNavigator(){
 const[stage,setStage]=useState<Stage>("category");
 const[categoryId,setCategoryId]=useState("fashion");
 const[subcategory,setSubcategory]=useState("");
 const[selectedAttributes,setSelectedAttributes]=useState<string[]>([]);
 const category=useMemo(()=>taxonomyCategory(categoryId),[categoryId]);
 const options=useMemo(()=>stage==="category"?SHOP_TAXONOMY.map(x=>x.label):stage==="subcategory"?category.sub:attributesFor(subcategory),[stage,category,subcategory]);

 const chooseCategory=useCallback((next:ShopCategory)=>{setCategoryId(next.id);setSubcategory("");setSelectedAttributes([]);setStage("subcategory");searchNow(next)},[]);
 const chooseSubcategory=useCallback((label:string)=>{setSubcategory(label);setSelectedAttributes([]);setStage("attributes");searchNow(category,label)},[category]);
 function toggleAttribute(label:string){const exists=selectedAttributes.includes(label);const next=exists?selectedAttributes.filter(x=>x!==label):[...selectedAttributes,label].slice(-4);setSelectedAttributes(next);searchNow(category,subcategory,next)}
 function goBack(){if(stage==="attributes"){setStage("subcategory");setSelectedAttributes([]);searchNow(category,subcategory)}else if(stage==="subcategory"){setStage("category");setSubcategory("");setSelectedAttributes([]);window.dispatchEvent(new CustomEvent("shop:tags-changed",{detail:{tags:[],root:"retail",path:[]}}))}}
 function choose(label:string){if(stage==="category"){const next=SHOP_TAXONOMY.find(x=>x.label===label);if(next)chooseCategory(next);return}if(stage==="subcategory"){chooseSubcategory(label);return}toggleAttribute(label)}

 return <div className="ynot-subcat" aria-label="Shopping category navigator">
  {stage!=="category"&&<div className="ynot-subcat-head"><button className="ynot-subcat-back" onClick={goBack} aria-label="Back"><ChevronLeft/></button><div><small>{stage==="subcategory"?"CATEGORY":"REFINE"}</small><b>{stage==="subcategory"?category.label:subcategory}</b><span>{stage==="subcategory"?"Choose a subcategory":"Add up to four attributes for more accurate results"}</span></div></div>}
  {stage==="attributes"&&selectedAttributes.length>0&&<div className="ynot-subcat-head ynot-subcat-head-minimal"><span className="ynot-subcat-count active">{selectedAttributes.length}</span><b>{selectedAttributes.join(" + ")}</b></div>}
  <div className="ynot-subcat-bubbles">{options.map((label,index)=>{const active=stage==="attributes"&&selectedAttributes.includes(label);return <button key={`${stage}-${categoryId}-${subcategory}-${label}-${index}`} className={active?"selected":""} aria-pressed={active} onClick={()=>choose(label)} style={{"--i":index} as React.CSSProperties}>{label}</button>})}</div>
 </div>
}
