"use client";

import {useEffect,useLayoutEffect,useMemo,useRef,useState} from "react";
import {Check,Minus,Plus,ShoppingBag,Trash2,Users,X} from "lucide-react";

type Variant={id?:string;label?:string;price?:number|null;currency?:string;image?:string;url?:string;available?:boolean};
type Product={id:string;title:string;brand?:string;price:number|null;currency?:string;image?:string;url?:string;source?:string;category?:string;variants?:Variant[];supplierPrice?:number;retailPrice?:number;checkout?:{mode?:string;reason?:string}};
type CartItem={key:string;productId:string;variantId?:string;variantLabel?:string;title:string;brand?:string;image:string;quantity:number;price:number;currency:string;source:string;url?:string;supplierPrice?:number;category?:string;token?:string;expiresAt?:number};
type PaymentChoice="now"|"klarna";

const productsByTitle=new Map<string,Product>();
const productsById=new Map<string,Product>();
function norm(value:string){return String(value||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function money(value:number,currency="EUR"){try{return new Intl.NumberFormat("en-GB",{style:"currency",currency,maximumFractionDigits:2}).format(value)}catch{return`${value.toFixed(2)} ${currency}`}}
function loadCart():CartItem[]{try{const list=JSON.parse(localStorage.getItem("ynot-cart")||"[]");return Array.isArray(list)?list:[]}catch{return[]}}
function loadSavedProducts():Product[]{try{const list=JSON.parse(localStorage.getItem("ynot-saved-items")||"[]");return Array.isArray(list)?list.filter(p=>p&&p.title&&p.id):[]}catch{return[]}}
function loadCredit(){try{const raw=localStorage.getItem("ynot-loyalty-credit")||localStorage.getItem("ynot-credit")||"0";const value=Number(raw);return Number.isFinite(value)&&value>0?value:0}catch{return 0}}
function saveCart(list:CartItem[]){localStorage.setItem("ynot-cart",JSON.stringify(list));window.dispatchEvent(new CustomEvent("ynot:bag-changed",{detail:list}))}
function parseShownPrice(text:string,fallback:number){const match=String(text||"").replace(/\s/g,"").match(/-?[\d.,]+/);if(!match)return fallback;const raw=match[0],lastComma=raw.lastIndexOf(","),lastDot=raw.lastIndexOf(".");let normalized=raw;if(lastComma>lastDot)normalized=raw.replace(/\./g,"").replace(",",".");else normalized=raw.replace(/,/g,"");const number=Number(normalized);return Number.isFinite(number)?number:fallback}
function ingestProducts(list:Product[]){for(const product of list){if(!product?.title)continue;const titleKey=norm(product.title),prior=productsByTitle.get(titleKey),merged={...prior,...product};productsByTitle.set(titleKey,merged);if(merged.id)productsById.set(String(merged.id),merged)}}
function ingest(data:unknown){const list=(data as {products?:Product[]})?.products;if(Array.isArray(list))ingestProducts(list)}
function currentProduct(detail:HTMLElement){const title=detail.querySelector(".lv4-detailcopy h2")?.textContent?.trim()||"",titleKey=norm(title);let product=productsByTitle.get(titleKey);if(product)return product;const saved=loadSavedProducts().find(item=>norm(item.title)===titleKey);if(saved){ingestProducts([saved]);product=productsByTitle.get(titleKey)}return product}
function selectedProduct(detail:HTMLElement,product:Product){const variantId=detail.dataset.ynotVariantId||product.variants?.find(v=>v.id===product.id)?.id||undefined;const variant=variantId?product.variants?.find(v=>String(v.id||"")===String(variantId)):undefined;return{product,variantId,variant}}
function addWorldProduct(detail:HTMLElement){const product=currentProduct(detail);if(!product)return null;const {variantId,variant}=selectedProduct(detail,product),fallback=Number(product.retailPrice??product.price??0),shown=parseShownPrice(detail.querySelector(".lv4-detailcopy strong")?.textContent||"",fallback),currency=variant?.currency||product.currency||"EUR",supplier=Number(variant?.price??product.supplierPrice??product.price??shown),key=`${product.id}:${variantId||"default"}`,item:CartItem={key,productId:product.id,variantId,variantLabel:variant?.label,title:product.title,brand:product.brand,image:variant?.image||detail.querySelector<HTMLImageElement>(":scope > img")?.src||product.image||"",quantity:1,price:shown,currency,source:product.source||"shopify",url:variant?.url||product.url,supplierPrice:supplier,category:product.category};const cart=loadCart(),found=cart.find(x=>x.key===key),next=found?cart.map(x=>x.key===key?{...x,quantity:Math.min(10,x.quantity+1),image:item.image,variantLabel:item.variantLabel}:x):[...cart,item];saveCart(next);return next}

export default function UnifiedBag():null|JSX.Element{
 const [open,setOpen]=useState(false),[cart,setCart]=useState<CartItem[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[paymentChoice,setPaymentChoice]=useState<PaymentChoice>("now"),[credit,setCredit]=useState(0);
 const fetchPatched=useRef(false);
 useLayoutEffect(()=>{if(fetchPatched.current)return;fetchPatched.current=true;ingestProducts(loadSavedProducts());const previous=window.fetch.bind(window);const wrapped=async(input:RequestInfo|URL,init?:RequestInit)=>{const response=await previous(input,init);const url=typeof input==="string"?input:input instanceof URL?input.toString():input.url;if(url.includes("/api/catalog"))response.clone().json().then(ingest).catch(()=>{});return response};window.fetch=wrapped as typeof fetch;return()=>{window.fetch=previous}},[]);
 useEffect(()=>{setCart(loadCart());setCredit(loadCredit());const sync=(event?:Event)=>{const detail=(event as CustomEvent<CartItem[]>|undefined)?.detail;setCart(Array.isArray(detail)?detail:loadCart());setCredit(loadCredit())};const syncSaved=()=>ingestProducts(loadSavedProducts());window.addEventListener("ynot:bag-changed",sync as EventListener);window.addEventListener("ynot:saves-changed",syncSaved);window.addEventListener("ynot:credit-changed",sync);window.addEventListener("storage",sync);const onClick=(event:MouseEvent)=>{const target=event.target as HTMLElement|null;if(!target)return;const cartTrigger=target.closest(".ynot-cart-trigger");if(cartTrigger){event.preventDefault();event.stopPropagation();setCart(loadCart());setCredit(loadCredit());setOpen(true);return}const worldBag=target.closest(".ynot-unified-add");if(worldBag){event.preventDefault();event.stopPropagation();const detail=worldBag.closest<HTMLElement>(".lv4-detail");if(detail){const next=addWorldProduct(detail);if(next){setCart(next);setCredit(loadCredit());setOpen(true)}}return}if(target.closest(".ynot-shop,.ynot-story-action")){window.setTimeout(()=>{setCart(loadCart());setCredit(loadCredit());setOpen(true);document.querySelector<HTMLButtonElement>(".ynot-cart header button")?.click()},80)}};document.addEventListener("click",onClick,true);let frame=0;const decorate=()=>{frame=0;document.querySelectorAll<HTMLElement>(".lv4-detail").forEach(detail=>{const actions=detail.querySelector<HTMLElement>(".lv4-actions");if(!actions||actions.querySelector(".ynot-unified-add"))return;const button=document.createElement("button");button.type="button";button.className="ynot-unified-add";button.setAttribute("aria-label","Add selected option to YNOT bag");button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 8h12l-1 12H7L6 8Z" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M9 8V6a3 3 0 0 1 6 0v2" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg><span>Add to bag</span>';actions.appendChild(button)})};const schedule=()=>{if(frame)return;frame=requestAnimationFrame(decorate)};const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});schedule();return()=>{window.removeEventListener("ynot:bag-changed",sync as EventListener);window.removeEventListener("ynot:saves-changed",syncSaved);window.removeEventListener("ynot:credit-changed",sync);window.removeEventListener("storage",sync);document.removeEventListener("click",onClick,true);observer.disconnect();if(frame)cancelAnimationFrame(frame)}},[]);
 const enriched=useMemo(()=>cart.map(item=>{const product=productsById.get(String(item.productId))||productsByTitle.get(norm(item.title));const variant=item.variantId?product?.variants?.find(v=>String(v.id||"")===String(item.variantId)):undefined;return{...item,variantLabel:item.variantLabel||variant?.label,image:variant?.image||item.image}}),[cart]);
 const total=enriched.reduce((sum,item)=>sum+item.price*item.quantity,0),currency=enriched[0]?.currency||"EUR",count=enriched.reduce((sum,item)=>sum+item.quantity,0),installment=total/4;
 function update(key:string,delta:number){const next=cart.map(item=>item.key===key?{...item,quantity:Math.max(1,Math.min(10,item.quantity+delta)),token:undefined,expiresAt:undefined}:item);setCart(next);saveCart(next)}
 function remove(key:string){const next=cart.filter(item=>item.key!==key);setCart(next);saveCart(next)}
 function openInvites(){setOpen(false);window.dispatchEvent(new Event("ynot:open-circle"))}
 async function checkout(){if(!cart.length||busy)return;setBusy(true);setError("");try{const region=JSON.parse(localStorage.getItem("ynot-region")||"null");if(!region?.country){setError("Choose your delivery region before checkout.");return}const response=await fetch("/api/checkout/cart-session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart,region,paymentPreference:paymentChoice})}),data=await response.json();if(!response.ok||!data.url)throw new Error(data.error||"Checkout unavailable");window.location.assign(data.url)}catch(e){setError(e instanceof Error?e.message.replaceAll("_"," "):"Checkout unavailable")}finally{setBusy(false)}}
 if(!open)return null;
 return <div className="ynot-unified-bag-backdrop" onClick={()=>setOpen(false)}><section className="ynot-unified-bag" role="dialog" aria-modal="true" aria-label="Your YNOT bag" onClick={e=>e.stopPropagation()}><header><div><small>YOUR BAG</small><b>{count} item{count===1?"":"s"}</b></div><button onClick={()=>setOpen(false)} aria-label="Close bag"><X/></button></header><div className="ynot-unified-bag-list">{enriched.length?enriched.map(item=><article className="ynot-unified-bag-card" key={item.key}><img src={item.image} alt=""/><div className="ynot-unified-bag-copy"><b>{item.title}</b>{item.brand&&<span>{item.brand}</span>}<small>{item.variantLabel?`Selected option · ${item.variantLabel}`:"Selected option · Default"}</small><strong>{money(item.price,item.currency)}</strong></div><div className="ynot-unified-qty"><button onClick={()=>update(item.key,-1)}><Minus/></button><span>{item.quantity}</span><button onClick={()=>update(item.key,1)}><Plus/></button></div><button className="ynot-unified-remove" onClick={()=>remove(item.key)} aria-label="Remove item"><Trash2/></button></article>):<div className="ynot-unified-empty"><ShoppingBag/><p>Your YNOT bag is empty.</p></div>}</div>{enriched.length>0&&<footer><button className="ynot-bag-referral" onClick={openInvites}><span className="ynot-bag-perk-icon"><Users/></span><span><b>Invite 2 friends · get 10% off</b><small>Share YNOT with your circle</small></span><strong>Invite</strong></button><div className="ynot-bag-credit"><span><Check/> YNOT Loyalty Credit</span>{credit>0?<b>{money(credit,currency)} available</b>:<b>Earn credit when you shop</b>}</div><div className="ynot-bag-info"><span>Shipping</span><b>Calculated from your delivery region</b></div><div className="ynot-bag-info"><span>Price & availability</span><b>Rechecked before payment</b></div><div className="ynot-bag-total"><span>Total</span><strong>{money(total,currency)}</strong></div><div className="ynot-payment-choice" role="radiogroup" aria-label="Choose payment method"><button className={paymentChoice==="now"?"active":""} onClick={()=>setPaymentChoice("now")} role="radio" aria-checked={paymentChoice==="now"}><span className="ynot-pay-radio"/><span><b>Pay now</b><small>One payment</small></span><strong>{money(total,currency)}</strong></button><button className={paymentChoice==="klarna"?"active":""} onClick={()=>setPaymentChoice("klarna")} role="radio" aria-checked={paymentChoice==="klarna"}><span className="ynot-pay-radio"/><span><b>Klarna · Pay in 4</b><small>4 interest-free payments</small></span><strong>4 × {money(installment,currency)}</strong></button></div>{error&&<p className="ynot-unified-error">{error}</p>}<button className="ynot-unified-checkout" onClick={()=>void checkout()} disabled={busy}><ShoppingBag/>{busy?"Checking products…":paymentChoice==="klarna"?`Continue with Klarna · ${money(installment,currency)} today`:"Checkout"}</button></footer>}</section></div>;
}
