"use client";
import {useEffect,useRef,useState} from "react";
type VoiceState="idle"|"asking"|"listening"|"searching"|"error";type VoiceEvent={results:{[index:number]:{[index:number]:{transcript:string}}}};type VoiceError={error?:string};type Recognition={lang:string;interimResults:boolean;continuous:boolean;maxAlternatives:number;onresult:((event:VoiceEvent)=>void)|null;onerror:((event:VoiceError)=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};type Constructor=new()=>Recognition;
function setInput(input:HTMLInputElement,value:string){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;setter?.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}))}
function speak(text:string,onEnd?:()=>void){if(!("speechSynthesis" in window)){onEnd?.();return}window.speechSynthesis.cancel();const message=new SpeechSynthesisUtterance(text);message.rate=.96;message.pitch=.92;message.onend=()=>onEnd?.();message.onerror=()=>onEnd?.();window.speechSynthesis.speak(message)}
export default function VoiceSearchOrb({left,top}:{left:number;top:number}){const [state,setState]=useState<VoiceState>("idle"),[caption,setCaption]=useState("Tap to ask YNOT"),recognition=useRef<Recognition|null>(null),timer=useRef<number|null>(null),dictationCleanup=useRef<(()=>void)|null>(null);
function clear(){if(timer.current!=null)window.clearTimeout(timer.current);timer.current=null;dictationCleanup.current?.();dictationCleanup.current=null}
useEffect(()=>()=>{clear();recognition.current?.abort();window.speechSynthesis?.cancel()},[]);
function search(query:string){const clean=query.trim();if(clean.length<2){setState("error");setCaption("I didn’t catch that. Tap again.");return}setState("searching");setCaption(`Searching “${clean}”`);const input=document.querySelector<HTMLInputElement>(".lv4-search input"),button=document.querySelector<HTMLButtonElement>(".lv4-search button");if(!input||!button){setState("error");setCaption("Search is still loading. Tap again.");return}setInput(input,clean);requestAnimationFrame(()=>button.click());timer.current=window.setTimeout(()=>{setState("idle");setCaption("Tap to ask YNOT")},2200)}
function keyboardDictation(){clear();const input=document.querySelector<HTMLInputElement>(".ynot-bottom-search.shop input"),form=input?.closest("form");if(!input||!form){setState("error");setCaption("Use the search bar below");return}setState("listening");setCaption("Tap the keyboard microphone and speak");let submitTimer:number|null=null;const finish=()=>{if(submitTimer!=null)window.clearTimeout(submitTimer);input.removeEventListener("input",changed)};const changed=()=>{if(submitTimer!=null)window.clearTimeout(submitTimer);submitTimer=window.setTimeout(()=>{const query=input.value.trim();if(query.length>1){finish();form.requestSubmit();setCaption(`Searching “${query}”`);setState("searching")}},900)};input.addEventListener("input",changed);dictationCleanup.current=finish;timer.current=window.setTimeout(()=>{finish();setState("idle");setCaption("Tap to ask YNOT")},30000);input.focus();speak("Tap the microphone on your keyboard, then tell me what you would like to find.")}
function begin(){if(state==="asking"||state==="listening"||state==="searching")return;clear();const scope=window as unknown as {SpeechRecognition?:Constructor;webkitSpeechRecognition?:Constructor},VoiceRecognition=scope.SpeechRecognition||scope.webkitSpeechRecognition,isSafari=/Safari/i.test(navigator.userAgent)&&!/CriOS|FxiOS|EdgiOS/i.test(navigator.userAgent);if(!VoiceRecognition){keyboardDictation();return}const listener=new VoiceRecognition();recognition.current=listener;listener.lang=navigator.language||"en-US";listener.interimResults=false;listener.continuous=false;listener.maxAlternatives=1;listener.onresult=event=>{clear();const words=event.results[0]?.[0]?.transcript||"";recognition.current=null;speak(`Searching for ${words}`,()=>search(words))};listener.onerror=event=>{recognition.current=null;if(isSafari&&(event.error==="not-allowed"||event.error==="service-not-allowed"||event.error==="audio-capture")){keyboardDictation();return}clear();setState("error");setCaption(event.error==="network"?"Speech service needs internet":"I couldn’t hear that. Tap to retry.")};listener.onend=()=>{if(recognition.current){clear();recognition.current=null;setState("idle");setCaption("Tap to ask YNOT")}};const listen=()=>{try{setState("listening");setCaption("Listening…");listener.start();timer.current=window.setTimeout(()=>{try{listener.stop()}catch{}},12000)}catch{if(isSafari)keyboardDictation();else{setState("error");setCaption("Allow microphone access and tap again")}}};setState("asking");setCaption("YNOT is asking…");if(isSafari){speak("What would you like me to find?");listen()}else speak("What would you like me to find?",listen)}
return <button className={`ynot-voice-orb ${state}`} style={{left,top}} onClick={begin} aria-label="Ask YNOT to search by voice" aria-live="polite"><img src="/ynot-microphone.jpg" alt=""/><span className="ynot-voice-pulse"/><strong>{caption}</strong></button>}