"use client";

import {useEffect} from "react";

const KEY="ynot-saved-items";
function load(){try{const data=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(data)?data:[]}catch{return[]}}
function numberFrom(text:string){const match=text.replace(/\s/g,"").match(/([0-9]+(?:[.,][0-9]+)?)/);return match?Number(match[1].replace(",",".")):undefined}
function syncButton(shell:HTMLElement,button:HTMLButtonElement,id:string){const active=load().some((x:any)=>String(x.id)===id);button.classList.toggle("active",active);button.textContent=active?"♥":"♡"}
function install(shell:HTMLElement){const root=shell.querySelector<HTMLElement>(".lv4-detailcopy");if(!root)return;const title=root.querySelector("h2")?.textContent?.trim()||"";if(!title)return;const id=`world:${title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`;let button=shell.querySelector<HTMLButtonElement>(".ynot-world-save");if(button&&button.dataset.productId!==id){button.remove();button=null}if(!button){button=document.createElement("button");button.type="button";button.className="ynot-world-save";button.dataset.productId=id;button.setAttribute("aria-label","Save product");button.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();const list=load();const exists=list.some((x:any)=>String(x.id)===id);const image=shell.querySelector<HTMLImageElement>(":scope > img")?.src||shell.querySelector<HTMLImageElement>("img")?.src||"";const priceText=root.querySelector("strong,.lv4-price")?.textContent||"";const item={id,title,brand:root.querySelector("small,.lv4-product-brand")?.textContent?.trim()||"",price:numberFrom(priceText),currency:priceText.includes("€")?"EUR":priceText.includes("£")?"GBP":priceText.includes("$")?"USD":"EUR",image,images:[...shell.querySelectorAll<HTMLImageElement>(".ynot-rich-gallery img,.ynot-loaded-gallery img")].map(x=>x.src).filter(Boolean),source:"shopify",section:"World",sections:["World"],badge:"Saved from World",note:"Saved from the spatial World product card"};const next=exists?list.filter((x:any)=>String(x.id)!==id):[item,...list];localStorage.setItem(KEY,JSON.stringify(next));localStorage.setItem("ynot-saved-products",JSON.stringify(next.map((x:any)=>x.id)));window.dispatchEvent(new Event("ynot:saves-changed"));syncButton(shell,button!,id)});shell.appendChild(button)}syncButton(shell,button,id)}
export default function WorldSaveBridge():null{useEffect(()=>{let raf=0;const scan=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>document.querySelectorAll<HTMLElement>(".lv4-detail").forEach(install))};const observer=new MutationObserver(scan);observer.observe(document.body,{subtree:true,childList:true,characterData:true});window.addEventListener("ynot:saves-changed",scan);document.addEventListener("click",scan,true);scan();return()=>{observer.disconnect();cancelAnimationFrame(raf);window.removeEventListener("ynot:saves-changed",scan);document.removeEventListener("click",scan,true)}},[]);return null}
