"use client";

import {useEffect,useState} from "react";
import {Compass,Minus,X} from "lucide-react";
import CompassAIInputs from "./CompassAIInputs";

type WorldKey="fashion"|"fitness"|"skin"|"hair"|"home"|"tech"|"retail";
type WorldGroup={key:WorldKey;label:string;sub:string[]};
const GROUPS:WorldGroup[]=[{key:"fashion",label:"Fashion",sub:["Dresses","Tops","Bottoms","Shoes","Bags","Accessories","Activewear","Outerwear"]},{key:"fitness",label:"Fitness",sub:["Activewear","Strength","Running","Recovery","Gym Accessories","Training Shoes","Yoga","Mobility"]},{key:"skin",label:"Beauty",sub:["Skincare","Serums","Moisturizers","Cleansers","SPF","Sensitive Skin","Tools","Body Care"]},{key:"hair",label:"Hair",sub:["Shampoo","Conditioner","Repair","Scalp Care","Styling","Hair Tools","Volume","Curl Care"]},{key:"home",label:"Home",sub:["Furniture","Lighting","Decor","Storage","Kitchen","Bedding","Smart Home","Bathroom"]},{key:"tech",label:"Tech",sub:["Phones","Audio","Wearables","Gaming","Smart Home","Desk Setup","Accessories","Portable Tech"]},{key:"retail",label:"Discover",sub:["Trending","Best Value","New Arrivals","Popular","Premium","Under €50","Hidden Gems","Editor Picks"]}];
function setInput(input:HTMLInputElement,value:string){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;setter?.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}))}
function resetToWorlds(){[...document.querySelectorAll<HTMLButtonElement>(".lv4-rail button")].find(button=>button.textContent?.toLowerCase().includes("discover"))?.click()}
function clickCategory(key:WorldKey){const button=document.querySelector<HTMLButtonElement>(`.lv4-category-bubble.cat-${key}`);if(button){button.click();return true}return false}
function openCategory(key:WorldKey,after?:()=>void){document.querySelector<HTMLElement>(".lv4-shell")?.classList.remove("ynot-far-overview");resetToWorlds();let tries=0;const step=()=>{tries++;if(clickCategory(key)){setTimeout(()=>after?.(),90);return}if(tries<16)setTimeout(step,35)};setTimeout(step,20)}
function directSearch(group:WorldGroup,label:string){openCategory(group.key,()=>{window.dispatchEvent(new CustomEvent("shop:tags-changed",{detail:{tags:[label],root:group.key,path:[label]}}));const input=document.querySelector<HTMLInputElement>(".lv4-search input");if(!input)return;setInput(input,`${group.label} ${label}`);requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>(".lv4-search button")?.click())})}
export default function WorldCompass():React.ReactElement{
 const[open,setOpen]=useState(false),[far,setFar]=useState(false);
 useEffect(()=>{const shell=document.querySelector<HTMLElement>(".lv4-shell");if(!shell)return;shell.classList.toggle("ynot-far-overview",far);return()=>shell.classList.remove("ynot-far-overview")},[far]);
 useEffect(()=>{document.body.classList.toggle("ynot-compass-open",open);return()=>document.body.classList.remove("ynot-compass-open")},[open]);
 useEffect(()=>{const close=()=>{setOpen(false);setFar(false)};window.addEventListener("ynot:world-focus",close);return()=>window.removeEventListener("ynot:world-focus",close)},[]);
 function closeCompass(){setOpen(false);setFar(false)}
 function chooseWorld(group:WorldGroup){setOpen(false);setFar(false);openCategory(group.key)}
 function chooseSub(group:WorldGroup,label:string){setOpen(false);setFar(false);directSearch(group,label)}
 function toggleFar(){setOpen(false);setFar(value=>{const next=!value;window.dispatchEvent(new CustomEvent("ynot:set-world-overview",{detail:{far:next}}));return next})}
 return <><div className="ynot-compass-tools" aria-label="World navigation"><button className={`ynot-far-button ${far?"active":""}`} onClick={toggleFar}><Minus/><span>{far?"Near":"Far"}</span></button><button className={`ynot-compass-button ${open?"active":""}`} onClick={()=>setOpen(v=>!v)}><Compass/><span>Map</span></button></div>{open&&<div className="ynot-compass-backdrop" onClick={closeCompass}><section className="ynot-compass-map" onClick={e=>e.stopPropagation()}><header><div><small>WORLD COMPASS</small><h2>What are you looking for?</h2><p>Choose a niche first, then add inspiration, yourself, a room, or a voice search.</p></div><button className="ynot-compass-close" aria-label="Close compass" onPointerDown={e=>e.stopPropagation()} onPointerUp={e=>{e.preventDefault();e.stopPropagation();closeCompass()}} onClick={e=>{e.preventDefault();e.stopPropagation();closeCompass()}}><X/></button></header><div className="ynot-compass-grid">{GROUPS.map((group,index)=><article key={group.key} className={`ynot-map-world map-${group.key}`} style={{"--world-i":index} as React.CSSProperties}><button className="ynot-map-world-main" onClick={()=>chooseWorld(group)}><span className="ynot-map-node"/><b>{group.label}</b><small>Open world</small></button><div className="ynot-map-branches">{group.sub.map(label=><button key={label} onClick={()=>chooseSub(group,label)}>{label}</button>)}</div></article>)}</div><CompassAIInputs/></section></div>}</>}
