"use client";
import {useEffect,useState} from "react";
import {Check,Sparkles,X,Zap} from "lucide-react";

type OpenDetail={compact?:boolean}|undefined;
const plans=[
 {id:"single",name:"Quick Try",price:"$1",sub:"3 AI Tries",features:["Clothing Try On","Accessory Try On","View in My Room"],cta:"Get 3 Tries"},
 {id:"try",name:"YNOT Try",price:"$9.99",sub:"per month",features:["15 Tries every month","Inspiration + personal analysis","Complete the Look","Voice-to-world","Expanded AI saves"],cta:"Join YNOT Try",featured:true},
 {id:"pro",name:"YNOT Pro",price:"$19.99",sub:"per month",features:["50 Tries every month","Full AI personal shopper","Multi-product generations","Advanced preference profile","Priority AI features"],cta:"Go Pro"}
];
export default function YnotTryPricing(){const[open,setOpen]=useState(false),[compact,setCompact]=useState(false);useEffect(()=>{const show=(e:Event)=>{const d=(e as CustomEvent<OpenDetail>).detail;setCompact(Boolean(d?.compact));setOpen(true)};window.addEventListener("ynot:open-try-pricing",show);return()=>window.removeEventListener("ynot:open-try-pricing",show)},[]);async function checkout(plan:string){const r=await fetch("/api/checkout/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan})}).catch(()=>null);if(r?.ok){const d=await r.json();if(d?.url)location.href=d.url;return}window.dispatchEvent(new CustomEvent("ynot:try-checkout-pending",{detail:{plan}}))}if(!open)return null;return <div className="ynot-try-pricing-shell" role="dialog" aria-modal="true"><button className="ynot-try-pricing-backdrop" onClick={()=>setOpen(false)}/><section className={`ynot-try-pricing ${compact?"compact":""}`}><button className="ynot-try-x" onClick={()=>setOpen(false)}><X/></button><header><span><Sparkles/> YNOT TRY</span><h2>{compact?"Try it on before you buy it.":"See it. Try it. Make it yours."}</h2><p>AI Try On for clothing and accessories, Room Try for furniture, and personalized shopping worlds.</p></header><div className="ynot-try-plan-grid">{plans.map(p=><article key={p.id} className={p.featured?"featured":""}>{p.featured&&<em>MOST POPULAR</em>}<small>{p.name}</small><strong>{p.price}</strong><span>{p.sub}</span><div>{p.features.map(f=><p key={f}><Check/>{f}</p>)}</div><button onClick={()=>void checkout(p.id)}>{p.id==="single"?<Zap/>:<Sparkles/>}{p.cta}</button></article>)}</div><footer><b>Earn more Tries by inviting friends.</b> Each verified invite can add a Try to your balance. Your existing Circle purchase rewards stay separate.</footer></section></div>}
