"use client";

import { useEffect,useMemo,useRef,useState } from "react";
import { ChevronRight,Search,ShoppingBag,X,Minus,Plus,Trash2,Heart,ChevronUp } from "lucide-react";

type Variant={id:string;label:string;price:number|null;currency?:string;image?:string;url?:string;available?:boolean};
type CheckoutMode={mode:"ynot"|"merchant";reason:string};
type Deal={id:string;title:string;brand?:string;price:number;currency:string;image:string;images?:string[];url:string;section:string;sections:string[];badge:string;note:string;description?:string;installments?:number;score?:number;source?:string;variants?:Variant[];variantId?:string;checkout?:CheckoutMode;supplierPrice?:number;retailPrice?:number;pricingMode?:string;sellableByLumina?:boolean};
type FeedItem={source:string;source_product_id:string;title:string;brand?:string;price:number|null;currency?:string;image_url:string;product_url:string;primary_section:string;sections?:string[];badge?:string;offer_score?:number;installment_eligible?:boolean;free_delivery_evidence?:boolean};
type AmazonItem={id:string;title:string;brand?:string;price:number;currency:string;image:string;url:string;section:string;sections:string[];badge:string;score:number;rating?:number|null;reviews?:number;source:string};
type CatalogItem={id:string;title:string;brand?:string;price:number|null;currency?:string;image:string;images?:string[];url?:string;tags?:string[];source?:string;variants?:Variant[];checkout?:CheckoutMode;supplierPrice?:number;retailPrice?:number;pricingMode?:string;sellableByLumina?:boolean;description?:string};
type CartItem={key:string;productId:string;variantId?:string;title:string;image:string;quantity:number;price:number;currency:string;source:string;token?:string;expiresAt?:number};

const sections=["Best Value","Under €25","Selling Fast","Fast Delivery","Fashion","Jewelry","Accessories","Bags","Tech","Home","Beauty & Hair","Fitness","Pets","Car","Travel","Free Delivery","Amazon"];
const sectionQueries:Record<string,string>={"Best Value":"trending best value products","Under €25":"useful products under 25 euro","Selling Fast":"popular trending products","Fast Delivery":"popular products fast delivery",Fashion:"fashion clothing shoes accessories",Jewelry:"jewelry necklaces rings earrings",Accessories:"fashion accessories bags sunglasses",Bags:"bags handbags backpacks",Tech:"useful tech gadgets phone accessories",Home:"home decor storage kitchen","Beauty & Hair":"beauty skincare hair care",Fitness:"fitness activewear training recovery",Pets:"pet accessories",Car:"car accessories",Travel:"travel accessories luggage","Free Delivery":"popular products free delivery",Amazon:"popular products"};
const fallback:Deal[]=[{id:"preview-jewelry",title:"Minimal Chain Necklace",brand:"YNOT preview",price:19,currency:"EUR",image:"https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=700&q=82",url:"#",section:"Jewelry",sections:["Best Value","Jewelry","Under €25"],badge:"Preview",note:"Preview product while live offers load."},{id:"preview-watch",title:"Minimal Steel Watch",brand:"YNOT preview",price:39,currency:"EUR",image:"https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=700&q=82",url:"#",section:"Accessories",sections:["Best Value","Accessories"],badge:"Preview",note:"Preview product while live offers load."}];
const SAVED_KEY="ynot-saved-items";
function money(v:number,currency="EUR"){try{return new Intl.NumberFormat("en-IE",{style:"currency",currency,maximumFractionDigits:2}).format(v)}catch{return`${v.toFixed(2)} ${currency}`}}
function normalizeSections(item:FeedItem){return(item.sections||[]).map(s=>s==="Under 25"?"Under €25":s)}
function sourceLabel(source?:string){const value=(source||"").toLowerCase();if(value.includes("amazon"))return"Amazon";if(value.includes("shopify"))return"Shopify";if(value.includes("ebay"))return"eBay";return source||"Marketplace"}
function toDeal(item:FeedItem):Deal|null{if(item.price==null||!item.image_url||!item.product_url)return null;const ss=normalizeSections(item);if(item.source.toLowerCase().includes("amazon")&&!ss.includes("Amazon"))ss.push("Amazon");return{id:`${item.source}:${item.source_product_id}`,title:item.title,brand:item.brand,price:Number(item.price),currency:item.currency||"EUR",image:item.image_url,url:item.product_url,section:item.primary_section||"Best Value",sections:ss.length?ss:[item.primary_section||"Best Value"],badge:item.badge||"Worth a look",note:`${item.brand||"Independent store"} · ${item.offer_score||0}/100 offer score`,installments:item.installment_eligible?4:undefined,score:item.offer_score||0,source:item.source}}
function amazonToDeal(item:AmazonItem):Deal{return{id:item.id,title:item.title,brand:item.brand,price:item.price,currency:item.currency,image:item.image,url:item.url,section:item.section,sections:item.sections||[item.section,"Best Value"],badge:item.badge||"Amazon value",note:`Amazon · ${item.rating?`${item.rating}★ · `:""}${item.reviews?`${item.reviews.toLocaleString()} reviews · `:""}${item.score}/100 value score`,score:item.score,source:item.source}}
function catalogToDeal(item:CatalogItem,section="Best Value"):Deal|null{if(item.price==null||!item.image||!item.url||item.url==="#")return null;const tags=(item.tags||[]).filter(Boolean),under25=item.price<=25,source=sourceLabel(item.source),ss=["Best Value",...(under25?["Under €25"]:[]),section,...tags];if(source==="Amazon")ss.push("Amazon");return{id:item.id,title:item.title,brand:item.brand,price:item.retailPrice??item.price,currency:item.currency||"EUR",image:item.image,images:item.images,url:item.url,section,sections:[...new Set(ss)],badge:item.sellableByLumina?"YNOT price":under25?"Under €25":"Live result",note:`${source} · live YNOT catalogue`,description:item.description,source:item.source,variants:item.variants,checkout:item.checkout,supplierPrice:item.supplierPrice,retailPrice:item.retailPrice,pricingMode:item.pricingMode,sellableByLumina:item.sellableByLumina}}
function dedupe(list:Deal[]){const seen=new Set<string>();return list.filter(d=>{const k=d.id||`${d.title}|${d.brand}`;if(seen.has(k))return false;seen.add(k);return true})}
function loadCart():CartItem[]{try{const parsed=JSON.parse(localStorage.getItem("ynot-cart")||"[]");return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function loadSaved():Deal[]{try{const parsed=JSON.parse(localStorage.getItem(SAVED_KEY)||"[]");return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function persistSaved(list:Deal[]){try{localStorage.setItem(SAVED_KEY,JSON.stringify(list));localStorage.setItem("ynot-saved-products",JSON.stringify(list.map(x=>x.id)));window.dispatchEvent(new Event("ynot:saves-changed"))}catch{}}

export default function YnotDrawer(){
 const [open,setOpen]=useState(false),[active,setActive]=useState("Best Value"),[deals,setDeals]=useState<Deal[]>(fallback),[selected,setSelected]=useState<Deal|null>(null),[query,setQuery]=useState(""),[searchResults,setSearchResults]=useState<Deal[]>([]),[searching,setSearching]=useState(false),[loadingMore,setLoadingMore]=useState(false),[live,setLive]=useState(false),[cartOpen,setCartOpen]=useState(false),[cart,setCart]=useState<CartItem[]>([]),[cartBusy,setCartBusy]=useState(false),[cartError,setCartError]=useState(""),[saved,setSaved]=useState<Set<string>>(new Set()),[story,setStory]=useState<Deal|null>(null),[storyImage,setStoryImage]=useState(0);
 const bodyRef=useRef<HTMLDivElement>(null),loadingMoreRef=useRef(false),searchRequestRef=useRef(0),searchPageRef=useRef(0),searchCursorRef=useRef(""),searchLoadingRef=useRef(false),sectionCursorRef=useRef<Record<string,string>>({}),sectionPageRef=useRef<Record<string,number>>({}),miniStartY=useRef(0),storyStart=useRef({x:0,y:0});
 useEffect(()=>{setCart(loadCart());setSaved(new Set(loadSaved().map(x=>x.id)))} ,[]);
 useEffect(()=>{try{localStorage.setItem("ynot-cart",JSON.stringify(cart))}catch{}},[cart]);
 useEffect(()=>{const openStory=(event:Event)=>{const item=(event as CustomEvent<Deal>).detail;if(!item)return;setOpen(true);setStory({...item,section:item.section||"Saved",sections:item.sections||["Saved"],badge:item.badge||"Saved",note:item.note||`${sourceLabel(item.source)} product`});setStoryImage(0)};window.addEventListener("ynot:open-story",openStory);return()=>window.removeEventListener("ynot:open-story",openStory)},[]);
 useEffect(()=>{let alive=true;const shopify=new URLSearchParams({q:"trending fashion beauty home tech accessories",market:"lumina",source:"shopify",page:"0"});Promise.allSettled([fetch(`/api/catalog?${shopify}`).then(r=>r.json()),fetch("https://iycxkwoxbkanfyraohge.supabase.co/functions/v1/ynot-feed").then(r=>r.json()),fetch("/api/ynot-amazon?country=FR").then(r=>r.json())]).then(results=>{if(!alive)return;const shopifyDeals=results[0].status==="fulfilled"?((results[0].value?.products||[]).map((p:CatalogItem)=>catalogToDeal(p,"Best Value")).filter(Boolean) as Deal[]):[];const feed=results[1].status==="fulfilled"?((results[1].value?.items||[]).map(toDeal).filter(Boolean) as Deal[]):[];const amazon=results[2].status==="fulfilled"?(results[2].value?.items||[]).map(amazonToDeal):[];const merged=dedupe([...shopifyDeals,...feed,...amazon]).sort((a,b)=>(b.score||0)-(a.score||0));if(merged.length){setDeals(merged);setLive(true)}const next=results[0].status==="fulfilled"?results[0].value?.pagination?.next_cursor:"";if(typeof next==="string")sectionCursorRef.current["Best Value"]=next}).catch(()=>{});return()=>{alive=false}},[]);
 const activeDeals=useMemo(()=>deals.filter(d=>active==="Best Value"||d.sections.includes(active)||d.section===active).slice(0,1000),[deals,active]);
 const searched=useMemo(()=>query.trim()?dedupe([...searchResults,...deals.filter(d=>`${d.title} ${d.brand||""} ${d.section} ${d.badge} ${d.source||""}`.toLowerCase().includes(query.toLowerCase()))]):null,[query,deals,searchResults]);
 async function searchCatalogue(term:string,append=false){const clean=term.trim();if(clean.length<2||(append&&searchLoadingRef.current))return;const request=append?searchRequestRef.current:++searchRequestRef.current;if(!append){searchPageRef.current=0;searchCursorRef.current="";setSearchResults([])}searchLoadingRef.current=true;setSearching(true);try{const params=new URLSearchParams({q:clean,market:"lumina",source:"all",page:String(searchPageRef.current)});if(searchCursorRef.current)params.set("cursor",searchCursorRef.current);const response=await fetch(`/api/catalog?${params}`),data=await response.json();if(request!==searchRequestRef.current)return;const incoming=(data.products||[]).map((p:CatalogItem)=>catalogToDeal(p,"Search results")).filter(Boolean) as Deal[];setSearchResults(previous=>dedupe(append?[...previous,...incoming]:incoming));searchPageRef.current+=1;searchCursorRef.current=typeof data.pagination?.next_cursor==="string"?data.pagination.next_cursor:""}finally{if(request===searchRequestRef.current){searchLoadingRef.current=false;setSearching(false)}}}
 useEffect(()=>{const clean=query.trim();if(clean.length<2){searchRequestRef.current++;setSearchResults([]);setSearching(false);return}const timer=window.setTimeout(()=>void searchCatalogue(clean),300);return()=>window.clearTimeout(timer)},[query]);
 function chooseSection(section:string){setActive(section);setSelected(null);setCartOpen(false);bodyRef.current?.scrollTo({top:0,behavior:"smooth"})}
 async function loadMore(section=active){if(loadingMoreRef.current)return;loadingMoreRef.current=true;setLoadingMore(true);try{const page=(sectionPageRef.current[section]||0)+1,source=section==="Amazon"?"amazon":"shopify",params=new URLSearchParams({q:sectionQueries[section]||section,market:"lumina",source,page:String(page)}),cursor=sectionCursorRef.current[section];if(cursor&&source==="shopify")params.set("cursor",cursor);const response=await fetch(`/api/catalog?${params}`),data=await response.json();const catalog=(data.products||[]).map((p:CatalogItem)=>catalogToDeal(p,section)).filter(Boolean) as Deal[];const known=new Set(deals.map(d=>d.id)),fresh=dedupe(catalog).filter(d=>!known.has(d.id));sectionPageRef.current[section]=page;const next=data.pagination?.next_cursor;if(typeof next==="string")sectionCursorRef.current[section]=next;if(fresh.length)setDeals(previous=>dedupe([...previous,...fresh]))}finally{loadingMoreRef.current=false;setLoadingMore(false)}}
 useEffect(()=>{if(open&&!query.trim()&&activeDeals.length<24)void loadMore(active)},[open,active]);
 function toggleSave(deal:Deal){const list=loadSaved();const exists=list.some(x=>x.id===deal.id);const next=exists?list.filter(x=>x.id!==deal.id):[{...deal,savedAt:Date.now()} as Deal,...list];persistSaved(next);setSaved(new Set(next.map(x=>x.id)))}
 async function addSelectedToCart(product=selected){if(!product)return;if(product.checkout?.mode!=="ynot"){if(product.url&&product.url!=="#")window.open(product.url,"_blank","noopener,noreferrer");return}setCartBusy(true);setCartError("");try{const response=await fetch("/api/checkout/quote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:product.id,variantId:product.variantId,title:product.title,brand:product.brand,price:product.supplierPrice??product.price,currency:product.currency,image:product.image,url:product.url,source:product.source})}),quote=await response.json();if(!response.ok)throw new Error(quote.error||"Unable to verify YNOT price");const key=`${product.id}:${product.variantId||"default"}`,item:CartItem={key,productId:product.id,variantId:product.variantId,title:product.title,image:product.image,quantity:1,price:Number(quote.price),currency:quote.currency||product.currency,source:product.source||"ynot",token:quote.token,expiresAt:quote.expiresAt};setCart(current=>{const found=current.find(x=>x.key===key);return found?current.map(x=>x.key===key?{...x,quantity:x.quantity+1,price:item.price,token:item.token,expiresAt:item.expiresAt}:x):[...current,item]});setCartOpen(true)}catch(e){setCartError(e instanceof Error?e.message.replaceAll("_"," "):"Unable to add to cart")}finally{setCartBusy(false)}}
 function updateQty(key:string,delta:number){setCart(current=>current.map(item=>item.key===key?{...item,quantity:Math.max(1,item.quantity+delta)}:item))}
 function removeCart(key:string){setCart(current=>current.filter(item=>item.key!==key))}
 async function checkoutCartItem(item:CartItem){if(!item.token)return;setCartBusy(true);try{const response=await fetch("/api/checkout/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:item.token})}),session=await response.json();if(!response.ok||!session.url)throw new Error(session.error||"Checkout unavailable");window.location.assign(session.url)}catch(e){setCartError(e instanceof Error?e.message.replaceAll("_"," "):"Checkout unavailable")}finally{setCartBusy(false)}}
 const cartCount=cart.reduce((sum,item)=>sum+item.quantity,0),cartTotal=cart.reduce((sum,item)=>sum+item.price*item.quantity,0),cartCurrency=cart[0]?.currency||"EUR";
 const storyImages=story?[...new Set([story.image,...(story.images||[]),...(story.variants||[]).map(v=>v.image).filter(Boolean) as string[]])].filter(Boolean):[];
 return <>
  <button className="ynot-peek" onClick={()=>setOpen(true)} aria-label="Open YNOT deals"><span className="ynot-peek-mark">YNOT</span><span>{live?"Live offers":"Worth a look"}</span><ChevronRight/></button>
  <div className={`ynot-backdrop ${open?"open":""}`} onClick={()=>setOpen(false)}/>
  <aside className={`ynot-drawer ${open?"open":""}`} aria-hidden={!open}>
   <div className="ynot-head"><div><small>YNOT DEAL WORLD</small><h2>YNOT</h2><p>AI shopping across the same Shopify + Amazon catalogues used by the main world.</p></div><div className="ynot-head-actions"><button className="ynot-cart-trigger" onClick={()=>setCartOpen(v=>!v)}><ShoppingBag/><span>{cartCount}</span></button><button className="ynot-close" onClick={()=>setOpen(false)}><X/></button></div></div>
   <label className="ynot-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ‘black dress under €80’ or ‘gym gear under €30’"/></label>
   <div className="ynot-workspace"><nav className="ynot-dock" aria-label="YNOT sections">{sections.map(s=><button key={s} className={active===s?"active":""} onClick={()=>chooseSection(s)}><span>{s}</span></button>)}</nav><div className="ynot-body" ref={bodyRef} onScroll={event=>{const el=event.currentTarget;if(el.scrollHeight-el.scrollTop-el.clientHeight<480){if(query.trim().length>=2)void searchCatalogue(query,true);else void loadMore()}}}>{searched?<section className="ynot-section"><div className="ynot-section-title"><span>AI search results</span><small>{searching?"Understanding your request…":`${searched.length} finds`}</small></div><div className="ynot-grid">{searched.map(d=><DealOrb key={d.id} deal={d} active={selected?.id===d.id} saved={saved.has(d.id)} onSelect={setSelected} onSave={toggleSave}/>)}</div><button className="ynot-load-more" onClick={()=>void searchCatalogue(query,true)} disabled={searching}>{searching?"Searching Shopify + Amazon…":"Load more results"}</button></section>:<section className="ynot-section" key={active}><div className="ynot-section-title"><span>{active}</span><small>{activeDeals.length} finds</small></div><div className="ynot-grid">{activeDeals.map(d=><DealOrb key={`${active}-${d.id}`} deal={d} active={selected?.id===d.id} saved={saved.has(d.id)} onSelect={setSelected} onSave={toggleSave}/>)}</div><button className="ynot-load-more" onClick={()=>void loadMore()} disabled={loadingMore}>{loadingMore?"Loading more…":"Load more products"}</button></section>}</div></div>
   {selected&&<div className="ynot-selected" onPointerDown={e=>{miniStartY.current=e.clientY}} onPointerUp={e=>{if(miniStartY.current-e.clientY>55){setStory(selected);setStoryImage(0)}}}><button className="ynot-selected-close" onClick={()=>setSelected(null)} aria-label="Close product details"><X/></button><button className={`ynot-selected-heart ${saved.has(selected.id)?"active":""}`} onClick={e=>{e.stopPropagation();toggleSave(selected)}} aria-label="Save product"><Heart/></button><div className="ynot-swipe-cue"><ChevronUp/></div><img src={selected.image} alt=""/><div className="ynot-selected-copy"><small>{selected.badge}{selected.score?` · ${selected.score}/100`:""}</small><h3>{selected.title}</h3><strong>{money(selected.price,selected.currency)}</strong>{Boolean(selected.variants?.length)&&<div className="ynot-variants">{selected.variants!.slice(0,8).map(v=><button key={v.id} disabled={v.available===false} className={selected.variantId===v.id?"active":""} onClick={()=>setSelected(d=>d?{...d,variantId:v.id,price:v.price??d.price,currency:v.currency||d.currency,image:v.image||d.image,url:v.url||d.url}:d)}>{v.label}</button>)}</div>}<p>{selected.note}</p>{cartError&&<p className="ynot-error">{cartError}</p>}</div><button className={`ynot-shop ${selected.checkout?.mode==="ynot"?"ynot-own":""}`} onClick={()=>void addSelectedToCart()} disabled={selected.url==="#"||cartBusy}><ShoppingBag/><span>{selected.checkout?.mode==="ynot"?(cartBusy?"Verifying…":"Add to YNOT cart"):"View at store"}</span></button></div>}
   {cartOpen&&<div className="ynot-cart"><header><div><small>YNOT CART</small><b>{cartCount} item{cartCount===1?"":"s"}</b></div><button onClick={()=>setCartOpen(false)}><X/></button></header><div className="ynot-cart-list">{cart.length?cart.map(item=><div className="ynot-cart-line" key={item.key}><img src={item.image} alt=""/><div><b>{item.title}</b><span>{money(item.price,item.currency)}</span><small>{item.variantId?"Selected option":"Standard option"}</small></div><div className="ynot-qty"><button onClick={()=>updateQty(item.key,-1)}><Minus/></button><span>{item.quantity}</span><button onClick={()=>updateQty(item.key,1)}><Plus/></button></div><button className="ynot-cart-remove" onClick={()=>removeCart(item.key)}><Trash2/></button><button className="ynot-cart-checkout" onClick={()=>void checkoutCartItem(item)} disabled={cartBusy||!item.token}>Checkout</button></div>):<p className="ynot-empty">Your YNOT cart is empty.</p>}</div>{cart.length>0&&<footer><span>Subtotal</span><strong>{money(cartTotal,cartCurrency)}</strong><small>Verified YNOT items keep their retail price when quoted. External marketplace items stay at the merchant checkout.</small></footer>}</div>}
  </aside>
  {story&&<div className="ynot-story" role="dialog" aria-modal="true" onPointerDown={e=>{storyStart.current={x:e.clientX,y:e.clientY}}} onPointerUp={e=>{const dx=e.clientX-storyStart.current.x,dy=e.clientY-storyStart.current.y;if(dy>85&&Math.abs(dy)>Math.abs(dx)){setStory(null);return}if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)&&storyImages.length>1)setStoryImage(i=>dx<0?Math.min(storyImages.length-1,i+1):Math.max(0,i-1))}}><button className="ynot-story-close" onClick={()=>setStory(null)}><X/></button><button className={`ynot-story-heart ${saved.has(story.id)?"active":""}`} onClick={()=>toggleSave(story)}><Heart/></button><div className="ynot-story-progress">{storyImages.map((_,i)=><i key={i} className={i===storyImage?"active":""}/>)}</div><div className="ynot-story-media"><img src={storyImages[storyImage]||story.image} alt=""/></div><div className="ynot-story-copy"><small>{sourceLabel(story.source)}{story.brand?` · ${story.brand}`:""}</small><h2>{story.title}</h2><strong>{money(story.price,story.currency)}</strong><p>{story.description||story.note||`Live ${sourceLabel(story.source)} product with ${story.variants?.length||0} available options.`}</p>{Boolean(story.variants?.length)&&<div className="ynot-story-variants">{story.variants!.slice(0,12).map(v=><button key={v.id} disabled={v.available===false} className={story.variantId===v.id?"active":""} onClick={()=>{setStory(d=>d?{...d,variantId:v.id,price:v.price??d.price,currency:v.currency||d.currency,image:v.image||d.image,url:v.url||d.url}:d);if(v.image){const index=storyImages.indexOf(v.image);if(index>=0)setStoryImage(index)}}}>{v.label}</button>)}</div>}<button className="ynot-story-action" onClick={()=>void addSelectedToCart(story)}><ShoppingBag/>{story.checkout?.mode==="ynot"?"Add to YNOT cart":"View at store"}</button></div></div>}
 </>;
}

function DealOrb({deal,active,saved,onSelect,onSave}:{deal:Deal;active:boolean;saved:boolean;onSelect:(d:Deal)=>void;onSave:(d:Deal)=>void}){const variantImages=[...new Set([...(deal.images||[]),...(deal.variants||[]).map(v=>v.image).filter(Boolean) as string[]])].filter(Boolean).slice(0,4),lastTap=useRef(0);function tap(){const now=Date.now();if(now-lastTap.current<320){onSave(deal);lastTap.current=0}else{lastTap.current=now;onSelect(deal)}}return <button className={`ynot-orb ${active?"active":""}`} onClick={tap}><button className={`ynot-orb-heart ${saved?"active":""}`} onClick={e=>{e.stopPropagation();onSave(deal)}} aria-label="Save product"><Heart/></button><span className="ynot-orb-img"><img src={deal.image} alt=""/>{variantImages.length>1&&<span className="ynot-variant-strip">{variantImages.slice(0,3).map((img,i)=><img key={`${img}-${i}`} src={img} alt=""/>)}</span>}</span><span className="ynot-orb-copy"><b>{deal.title}</b><em>{sourceLabel(deal.source)} · {deal.badge}</em><strong>{money(deal.price,deal.currency)}</strong></span></button>}
