import {cookies} from "next/headers";
import {NextRequest,NextResponse} from "next/server";
import crypto from "node:crypto";
import {ensureProfile} from "@/lib/circle/server";

export const runtime="nodejs";
const COOKIE="ynot-circle-id",base=()=>String(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL||"").replace(/\/$/,""),key=()=>String(process.env.SUPABASE_SERVICE_ROLE_KEY||"");
async function db(path:string,init:RequestInit={}){const r=await fetch(`${base()}/rest/v1/${path}`,{...init,headers:{apikey:key(),Authorization:`Bearer ${key()}`,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})},cache:"no-store"});const t=await r.text();if(!r.ok)throw new Error(t||"PROFILE_DATABASE_ERROR");return t?JSON.parse(t):null}
function hashPin(pin:string,salt=crypto.randomBytes(16).toString("hex")){return`${salt}:${crypto.scryptSync(pin,salt,32).toString("hex")}`}
function verifyPin(pin:string,stored:string){const [salt,want]=stored.split(":");if(!salt||!want)return false;const got=crypto.scryptSync(pin,salt,32),expected=Buffer.from(want,"hex");return got.length===expected.length&&crypto.timingSafeEqual(got,expected)}
function cleanName(value:unknown){const name=String(value||"").trim().replace(/\s+/g," ");if(name.length<2||name.length>30)throw new Error("NAME_MUST_BE_2_TO_30_CHARACTERS");return name}
function cleanSaves(value:unknown){return Array.isArray(value)?value.slice(0,150):[]}
async function identity(){const jar=await cookies(),found=jar.get(COOKIE)?.value;if(found&&/^[0-9a-f-]{36}$/i.test(found))return{id:found,fresh:false};return{id:crypto.randomUUID(),fresh:true}}
function setIdentity(response:NextResponse,id:string){response.cookies.set(COOKIE,id,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:60*60*24*365*3});return response}
export async function GET(){try{const who=await identity();await ensureProfile(who.id);const rows=await db(`ynot_users?id=eq.${encodeURIComponent(who.id)}&select=id,display_name,account_name,avatar_data,saved_items`),p=rows?.[0];const response=NextResponse.json({profile:p?{name:p.display_name||p.account_name||"",avatar:p.avatar_data||"",hasPin:Boolean(p.account_name)}:null,saves:p?.saved_items||[]});return who.fresh?setIdentity(response,who.id):response}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"PROFILE_UNAVAILABLE"},{status:400})}}
export async function PUT(req:NextRequest){try{const who=await identity();await ensureProfile(who.id);const body=await req.json() as {name?:string;pin?:string;avatar?:string;saves?:unknown[]},patch:Record<string,unknown>={profile_updated_at:new Date().toISOString()};if(body.name!=null){const name=cleanName(body.name);patch.display_name=name;patch.account_name=name.toLowerCase()}if(body.pin!=null){if(!/^\d{4}$/.test(body.pin))throw new Error("PIN_MUST_BE_4_DIGITS");patch.pin_hash=hashPin(body.pin)}if(body.avatar!=null){if(body.avatar&&!/^data:image\/(?:webp|jpeg|png);base64,/.test(body.avatar))throw new Error("INVALID_PROFILE_IMAGE");if(body.avatar.length>350000)throw new Error("PROFILE_IMAGE_TOO_LARGE");patch.avatar_data=body.avatar}if(body.saves!=null)patch.saved_items=cleanSaves(body.saves);const rows=await db(`ynot_users?id=eq.${encodeURIComponent(who.id)}`,{method:"PATCH",body:JSON.stringify(patch)}),p=rows?.[0];const response=NextResponse.json({ok:true,profile:{name:p?.display_name||p?.account_name||"",avatar:p?.avatar_data||"",hasPin:Boolean(p?.account_name)},saves:p?.saved_items||[]});return who.fresh?setIdentity(response,who.id):response}catch(e){const message=e instanceof Error?e.message:"PROFILE_SAVE_FAILED";return NextResponse.json({error:/duplicate|unique/i.test(message)?"NAME_ALREADY_TAKEN":message},{status:400})}}
export async function POST(req:NextRequest){try{const body=await req.json() as {name?:string;pin?:string},name=cleanName(body.name),pin=String(body.pin||"");if(!/^\d{4}$/.test(pin))throw new Error("PIN_MUST_BE_4_DIGITS");const ip=(req.headers.get("x-forwarded-for")||"unknown").split(",")[0].trim().slice(0,80),account=name.toLowerCase();const recent=await db(`ynot_profile_attempts?account_name=eq.${encodeURIComponent(account)}&ip_key=eq.${encodeURIComponent(ip)}&created_at=gte.${encodeURIComponent(new Date(Date.now()-15*60_000).toISOString())}&select=id`);if((recent||[]).length>=5)return NextResponse.json({error:"TOO_MANY_ATTEMPTS_TRY_LATER"},{status:429});const rows=await db(`ynot_users?account_name=eq.${encodeURIComponent(account)}&select=id,display_name,account_name,pin_hash,avatar_data,saved_items&limit=1`),p=rows?.[0];if(!p||!verifyPin(pin,p.pin_hash||"")){await db("ynot_profile_attempts",{method:"POST",body:JSON.stringify({account_name:account,ip_key:ip})});return NextResponse.json({error:"NAME_OR_PIN_INCORRECT"},{status:401})}await db(`ynot_profile_attempts?account_name=eq.${encodeURIComponent(account)}&ip_key=eq.${encodeURIComponent(ip)}`,{method:"DELETE"});return setIdentity(NextResponse.json({ok:true,profile:{name:p.display_name||p.account_name,avatar:p.avatar_data||"",hasPin:true},saves:p.saved_items||[]}),p.id)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"PROFILE_RESTORE_FAILED"},{status:400})}}